// Static curriculum content for the Theory tab — 150 concept cards, grouped
// by category below and interleaved into a single day-by-day schedule by
// buildTheorySchedule(). This is pure content (no DB), so it's imported
// directly by both the server and the frontend, same as scheduling.ts.

export type Category =
  | "System Design"
  | "Data Structures & Algorithms"
  | "Distributed Systems"
  | "Databases"
  | "Networking & OS"
  | "Behavioral";

export interface ConceptSeed {
  question: string;
  answer: string;
}

export interface Concept extends ConceptSeed {
  day: number;
  category: Category;
}

export const SYSTEM_DESIGN: ConceptSeed[] = [
  { question: "What problem does a load balancer solve, and what are the main algorithms it can use to pick a backend?", answer: "It spreads incoming requests across multiple backend instances so no single one is overwhelmed, and gives you horizontal scalability and failover. Common algorithms: round robin, weighted round robin, least connections, and consistent hashing (for session/cache affinity)." },
  { question: "When do you scale horizontally vs vertically, and what does each cost you?", answer: "Vertical scaling (bigger machine) is simple but has a hard ceiling and a single point of failure. Horizontal scaling (more machines) scales further and improves availability, but forces you to deal with statelessness, data partitioning, and coordination between nodes." },
  { question: "Compare cache-aside, write-through, and write-behind caching strategies.", answer: "Cache-aside: app reads from cache, falls back to DB and populates cache on miss — simple, but first request is always slow. Write-through: writes go to cache and DB together — reads are always fresh but writes are slower. Write-behind: writes hit the cache and are flushed to DB asynchronously — fast writes, but risks data loss on crash." },
  { question: "What does a CDN actually do, and why does it help even for dynamic content?", answer: "A CDN caches content at edge servers geographically close to users, cutting latency and offloading origin servers. Even 'dynamic' pages often have static sub-resources (images, JS, CSS) that benefit, and some CDNs support edge compute for personalization without a full origin round-trip." },
  { question: "In system design interviews, what does 'picking two out of three' really mean for CAP?", answer: "Under a network partition (P, which is unavoidable in distributed systems), you must choose between Consistency (every read gets the latest write) and Availability (every request gets a response). In practice this becomes a spectrum — most real systems are AP with tunable consistency, not a strict binary choice." },
  { question: "What is consistent hashing and what problem does it solve over plain modulo hashing?", answer: "Plain hash(key) % N remaps almost every key when N changes, causing a cache/shard stampede. Consistent hashing places nodes and keys on a ring so adding/removing a node only remaps the keys between it and its neighbor — minimizing redistribution." },
  { question: "What are the main strategies for sharding a database, and what's the risk of each?", answer: "Range-based (ordered key ranges) — simple but risks hot ranges. Hash-based — even distribution but loses range-query locality. Directory-based (lookup service maps key to shard) — flexible rebalancing but adds a lookup hop and a new single point of failure to protect." },
  { question: "Why add read replicas, and what problem do they introduce?", answer: "Read replicas offload read traffic from the primary and improve read throughput and geographic latency. They introduce replication lag, so a read right after a write on a replica can return stale data unless you route that read to the primary or use read-your-writes tricks." },
  { question: "Why put a message queue between two services instead of calling directly?", answer: "It decouples producer and consumer in time and load: the producer doesn't block on the consumer being up or fast, and the queue absorbs bursts so consumers can process at their own pace. It also enables fan-out to multiple consumers and easy retry/dead-lettering of failed messages." },
  { question: "Explain token bucket and leaky bucket rate limiting and how they differ.", answer: "Token bucket: tokens refill at a fixed rate into a bucket of fixed capacity; a request consumes a token and is allowed only if one's available — permits bursts up to the bucket size. Leaky bucket: requests queue and drain at a fixed rate, smoothing bursts into a constant output rate rather than allowing them through." },
  { question: "What is the circuit breaker pattern and what are its three states?", answer: "It stops a service from repeatedly calling a downstream dependency that's already failing, giving it time to recover instead of piling on load. Closed (calls flow normally, failures counted), Open (calls fail fast without hitting the dependency), Half-Open (a trial request checks if it's healthy again before fully closing)." },
  { question: "What responsibilities does an API Gateway typically take on?", answer: "Routing to the right backend service, authentication/authorization, rate limiting, request/response transformation, and aggregating multiple backend calls into one client-facing response. It centralizes cross-cutting concerns so individual services don't each reimplement them." },
  { question: "Client-side vs server-side service discovery — what's the tradeoff?", answer: "Client-side: the client queries a registry (e.g. Consul, Eureka) and load-balances itself — no extra network hop, but every client needs discovery logic. Server-side: a load balancer/router queries the registry on the client's behalf — simpler clients, but an extra hop and another component to keep highly available." },
  { question: "Why do idempotency keys matter for APIs that might be retried?", answer: "Network failures mean a client can't always tell if a request succeeded, so it may retry. An idempotency key lets the server recognize a retried request (e.g. a duplicate payment) and return the original result instead of double-processing it." },
  { question: "What is back-pressure and why does a fast producer need to respect it?", answer: "Back-pressure is a signal from a slower consumer telling an upstream producer to slow down, instead of the producer overwhelming it and causing unbounded queueing, memory blowup, or dropped requests. It's implemented via bounded queues, reactive streams, or simply blocking/rejecting once a buffer is full." },
  { question: "Compare long polling, WebSockets, and Server-Sent Events for real-time updates.", answer: "Long polling: client repeatedly asks 'anything new?' and the server holds the request open until there is — simple, works everywhere, but overhead per cycle. WebSockets: full-duplex persistent connection — low latency both ways, but more infra complexity (sticky sessions, scaling connections). SSE: server pushes a one-way stream over plain HTTP — simpler than WebSockets when you only need server-to-client updates." },
  { question: "What's the difference between a forward proxy and a reverse proxy?", answer: "A forward proxy sits in front of clients and hides/represents them to the internet (e.g. a corporate proxy). A reverse proxy sits in front of servers and hides/represents them to clients (e.g. nginx routing to backend services) — clients don't know which backend actually served them." },
  { question: "How do bloom filters help at scale, and what's their key limitation?", answer: "A bloom filter answers 'definitely not present' or 'maybe present' in O(1) with tiny memory, so you can skip an expensive lookup (disk, cache, network) when it says 'definitely not.' The limitation: false positives are possible (never false negatives), and you can't delete items from a standard bloom filter." },
  { question: "What's the difference between active-passive and active-active multi-region deployment?", answer: "Active-passive: one region serves live traffic, the other stands by and takes over on failover — simple, but the standby capacity sits idle. Active-active: multiple regions serve traffic simultaneously — better resource use and lower latency globally, but requires solving cross-region data consistency and conflict resolution." },
  { question: "Walk through a rough back-of-envelope capacity estimate: how would you size servers for 10M daily active users?", answer: "Estimate requests/user/day (e.g. 20) → total daily requests (200M) → divide by seconds/day (~86,400) for average QPS (~2,300), then multiply by a peak factor (e.g. 3-5x) for peak QPS. Divide peak QPS by one server's sustainable QPS (load-tested) to get a rough server count, then pad for redundancy." },
  { question: "What's the difference between SLA, SLO, and SLI?", answer: "SLI (indicator) is the actual measured metric, e.g. request latency or error rate. SLO (objective) is your internal target for that metric, e.g. 'p99 latency < 300ms.' SLA (agreement) is the external, often contractual, promise to customers — usually looser than your SLO, with penalties if missed." },
  { question: "What is graceful degradation and how do feature flags support it under load?", answer: "Graceful degradation means shedding non-critical functionality to keep the core service up under stress (e.g. disabling recommendations to keep checkout working). Feature flags let you toggle those non-critical paths off instantly in production without a redeploy, often automated via load/error-rate triggers." },
  { question: "Compare blue-green and canary deployment strategies.", answer: "Blue-green: run two full identical environments, switch all traffic from old to new at once — instant rollback (switch back), but doubles infra cost temporarily. Canary: roll the new version out to a small traffic percentage first, watch metrics, then gradually increase — lower blast radius on a bad release, but slower and needs good monitoring to catch issues early." },
  { question: "What's the core difference between event-driven architecture and request/response, and when would you pick each?", answer: "Request/response is synchronous and simple to reason about, good when the caller needs an immediate result. Event-driven is asynchronous — services publish events and others react — good for decoupling, fan-out to many consumers, and workflows where the caller doesn't need to wait, at the cost of harder end-to-end tracing and eventual consistency." },
  { question: "Why does database indexing help system-scale design decisions, and what's the tradeoff of adding many indexes?", answer: "An index turns an O(n) table scan into an O(log n) lookup for queries that filter/sort on that column, which matters enormously at scale. Every index speeds reads but slows writes (each write must update every index) and costs storage, so you index based on actual query patterns, not defensively." },
  { question: "Design a URL shortener. What's the core approach and the main design decision?", answer: "Generate a short, unique key per long URL (base62-encode an auto-incrementing ID, or hash+collision-check) and store the mapping in a key-value store; redirect on GET via a 301/302. The main decision is key generation strategy (sequential counter vs random) — sequential is collision-free but reveals volume/order and needs a coordinated counter at scale; random needs a uniqueness check." },
  { question: "Design a rate limiter service usable by many downstream APIs. What would you clarify and what's the core component?", answer: "Clarify: per-user or per-IP or per-API-key limits, and whether it must be exact (strict distributed counting) or can tolerate slight overshoot. Core: a token-bucket or sliding-window counter kept in a fast shared store (e.g. Redis) with atomic increment-and-check, so all app servers share the same limit state instead of each enforcing it locally." },
  { question: "Design a distributed cache (like a Redis cluster). What are the key components?", answer: "Consistent hashing to map keys to shard nodes, replication per shard for failover, an eviction policy (LRU/LFU) under memory pressure, and a client library that knows the current shard map (often via a coordination service). The key design question is consistency vs latency: do writes wait for replica ack or return immediately?" },
  { question: "Design a unique ID generator for a distributed system (Snowflake-style). What goes into an ID?", answer: "Combine a timestamp (for rough time-ordering), a machine/worker ID (to avoid collisions across nodes), and a per-millisecond sequence number (to avoid collisions within one node) into a single 64-bit integer. This avoids a centralized counter bottleneck while keeping IDs roughly sortable by creation time." },
  { question: "Design a news feed / timeline system (like Twitter). What's the fan-out tradeoff?", answer: "Fan-out-on-write: when you post, push it into every follower's precomputed feed — fast reads, but expensive/wasteful for accounts with millions of followers. Fan-out-on-read: build the feed at read time by merging recent posts from everyone you follow — cheap writes, but slower reads. Most real systems hybridize: fan-out-on-write for normal users, fan-out-on-read for celebrity accounts." },
  { question: "Design a chat application (like WhatsApp). What are the core components?", answer: "Persistent connections (WebSocket) per online user held by a connection-gateway layer, a message store for history/offline delivery, and a presence service tracking who's online and which gateway node holds their connection (so messages can be routed to the right server). Delivery/read receipts need per-message state tracked separately from the message itself." },
  { question: "Design a notification system that fans out to push, email, and SMS. What's the core architecture?", answer: "An event (e.g. 'order shipped') is published to a queue; a notification service consumes it, checks user preferences/quiet-hours, and dispatches to the right channel-specific providers (APNs/FCM for push, an email provider, an SMS gateway) — each with its own retry/backoff since third-party providers fail independently." },
  { question: "Design a web crawler. What are the key components and the main failure mode to guard against?", answer: "A frontier (URL queue) prioritized by freshness/importance, a fetcher pool respecting per-domain rate limits and robots.txt, a dedup layer (seen-URL bloom filter or hash set) to avoid re-crawling, and a parser that extracts new links back into the frontier. The main failure mode is crawler traps (infinite link generation) and being politely rate-limited by target sites." },
  { question: "Design an autocomplete/typeahead search. What data structure and update strategy would you use?", answer: "A trie (or a precomputed top-K-per-prefix index) lets you return suggestions in O(prefix length) instead of scanning all terms. Since rebuilding a trie from live query logs on every keystroke is too slow, you typically batch-update the suggestion index periodically (e.g. hourly) from aggregated query frequency data." },
  { question: "Design a distributed file storage system (like Dropbox/S3). What are the core layers?", answer: "A metadata service (file names, versions, permissions, chunk locations) separate from a blob storage layer (the actual chunked file data, replicated across nodes/regions for durability). Large files are split into chunks for parallel upload/download and deduplication (identical chunks across files/users stored once)." },
  { question: "Design a video streaming service (like YouTube). What's the role of transcoding and adaptive bitrate?", answer: "Uploaded video is transcoded into multiple resolutions/bitrates and split into small segments; the player requests the segment size matching current network conditions (adaptive bitrate streaming, e.g. HLS/DASH), switching quality mid-stream without rebuffering. A CDN serves the segments close to the viewer." },
  { question: "Design a ride-sharing matching system (like Uber). What's the core matching approach?", answer: "Geo-index driver locations (e.g. a grid or geohash/quadtree) so you can cheaply query 'drivers near this rider,' then rank candidates by ETA and apply a matching algorithm (often greedy nearest-available, sometimes batched auction-style matching for fairness/efficiency). Location updates stream continuously and must be processed with low latency." },
  { question: "Design an e-commerce checkout and inventory system. What's the trickiest consistency problem?", answer: "The trickiest problem is preventing overselling: two concurrent checkouts shouldn't both succeed for the last item. Solutions include reserving stock atomically at add-to-cart or checkout-start (with a timeout to release abandoned reservations), or optimistic decrement-with-check at the DB layer using a conditional update." },
  { question: "Design a payment processing system. What design principle is non-negotiable and why?", answer: "Idempotency is non-negotiable: network retries must never double-charge a customer, so every payment request carries an idempotency key and the system must reliably detect and dedupe repeats, even across process crashes. Payments also typically use the saga pattern to coordinate multi-step flows (charge, then fulfill, then notify) with compensating actions on failure." },
  { question: "Design a leaderboard for a game with millions of players. What data structure powers real-time ranking?", answer: "A sorted set (like Redis's ZSET) keyed by score gives O(log n) insert/update and O(log n + k) range queries for 'top K' or 'rank of player X,' which a relational DB can't do efficiently at this scale without heavy indexing. Sharding by region/game-mode keeps individual leaderboards small enough to fit these structures." },
  { question: "Design a distributed job scheduler (like cron at scale). What problem does it solve beyond a single-node cron?", answer: "It must guarantee a scheduled job runs exactly once even with many worker nodes (avoiding double-execution and single-point-of-failure), typically via a leader-elected scheduler or a distributed lock per job, plus persistence so scheduled jobs survive a scheduler restart." },
  { question: "Design a distributed logging/monitoring pipeline. What's the general data flow?", answer: "Agents on each host ship logs/metrics to a durable buffer (e.g. a message queue or log-structured store), which is consumed by processors that index/aggregate the data into a queryable store (e.g. a time-series DB or search index), which dashboards and alerting query. The buffer decouples bursty log volume from downstream processing capacity." },
  { question: "At a high level, what are the main components behind a search engine's ranking backend?", answer: "A crawler/indexer builds an inverted index (term → documents containing it); at query time, candidate documents are retrieved from the index, then ranked by a scoring function combining relevance signals (term frequency, link popularity, freshness, personalization). Ranking is often split into a cheap first-pass retrieval and an expensive re-ranking of the top candidates." },
  { question: "Design an uptime/health-check monitoring system for thousands of URLs. What's the core loop?", answer: "Distribute the URL list across a pool of checker workers (often in multiple regions, to distinguish a real outage from a regional network issue), each pinging its assigned URLs on an interval and recording pass/fail with latency. An aggregator requires failures from multiple regions/checkers before alerting, to avoid false positives from one checker's own network blip." },
  { question: "Design a collaborative document editor (like Google Docs). What's the core technique for merging concurrent edits?", answer: "Operational Transformation or CRDTs (Conflict-free Replicated Data Types) let multiple users' concurrent edits be merged deterministically without locking the document, so everyone converges to the same final state regardless of the order operations arrive in. Each keystroke is broadcast as a small operation, not the whole document." },
  { question: "Design a ticket-booking system (like Ticketmaster) that must never oversell a seat. What's the concurrency approach?", answer: "Treat a seat reservation as an atomic conditional update (e.g. 'reserve seat WHERE status = available') so only one of many concurrent requests wins; the loser gets an immediate 'already taken' rather than being queued behind a lock. Reservations get a short TTL hold during checkout, releasing back to available if payment doesn't complete in time." },
  { question: "Design a key-value store from scratch. What are the core building blocks?", answer: "A partitioning scheme (consistent hashing) to distribute keys across nodes, replication (e.g. N=3 copies) for durability, a quorum read/write scheme (R+W>N) to balance consistency and availability, and a storage engine per node (often an LSM-tree for write-heavy workloads)." },
  { question: "Design a 'like' counter for posts that need to handle huge write volume. Why not just UPDATE a counter column directly?", answer: "Direct row updates under massive concurrent writes cause heavy lock contention on that single row. Instead, batch/aggregate likes in a fast in-memory store or write-behind buffer and periodically flush aggregated counts to the durable store, or shard the counter itself (multiple counter rows summed on read) to spread write load." },
  { question: "Design an ad click-tracking and analytics pipeline. What's the core tradeoff in how you process events?", answer: "Stream processing (e.g. Kafka + a stream processor) gives near-real-time aggregation but is more complex to build correctly (exactly-once semantics, late-arriving events). Batch processing is simpler and easier to reason about but only gives you hourly/daily freshness — many systems run both: a fast approximate real-time path and a slower exact batch reconciliation." },
  { question: "Design a public API platform with per-customer quotas and billing. What's the core architectural addition over a plain API?", answer: "A metering/gateway layer that authenticates each request to a customer account, enforces that customer's quota (via the same kind of distributed rate limiter used elsewhere), and durably logs usage events for billing — usage logging must be reliable even if the request itself later fails, since you often bill on request attempts, not just successes." },
];

export const DSA: ConceptSeed[] = [
  { question: "What does Big-O actually describe, and what's a common mistake people make when reasoning about it?", answer: "Big-O describes how an algorithm's time/space grows as input size grows, not its exact runtime — O(n) means 'roughly linear,' constants and lower-order terms are dropped. A common mistake is fixating on worst-case only when average-case or amortized behavior is what matters in practice (e.g. hash table lookups)." },
  { question: "What are the practical tradeoffs between arrays and linked lists?", answer: "Arrays give O(1) random access and better cache locality (contiguous memory) but O(n) insert/delete in the middle and costly resizing. Linked lists give O(1) insert/delete once you're at a node but O(n) access and worse cache performance due to scattered memory." },
  { question: "How does a hash table resolve collisions, and what are the two main strategies?", answer: "Chaining: each bucket holds a list (or tree) of all entries that hash there — simple, degrades gracefully, but extra memory per bucket. Open addressing: on collision, probe for the next open slot (linear/quadratic/double hashing) — better cache locality, but needs careful handling of deletions and can cluster under high load factor." },
  { question: "When would you reach for a stack vs a queue?", answer: "Stack (LIFO) fits problems needing 'undo the most recent thing first' — matching parentheses, DFS, call-stack simulation, expression evaluation. Queue (FIFO) fits 'process in arrival order' — BFS, task scheduling, buffering between producer and consumer." },
  { question: "What preconditions does binary search require, and what's the classic off-by-one bug?", answer: "The array must be sorted (or the search space must be monotonic) for binary search to be valid. The classic bug is an inconsistent loop invariant — e.g. mixing `mid = (lo+hi)/2` with `hi = mid` instead of `hi = mid - 1`, causing an infinite loop or skipping a valid answer at the boundary." },
  { question: "What is the two-pointer technique and what kind of problems does it solve efficiently?", answer: "Two pointers move through a sorted array or string from different positions (often start and end, or slow/fast) to avoid the O(n²) of checking every pair — e.g. finding a pair summing to a target in a sorted array in O(n), or detecting a cycle in a linked list (Floyd's algorithm)." },
  { question: "What is the sliding window technique and when does it apply?", answer: "It maintains a contiguous subrange (window) over an array/string, expanding and shrinking its bounds incrementally rather than recomputing from scratch, turning an O(n²) 'check every subarray' brute force into O(n). Applies to problems like longest substring without repeats, or max sum subarray of size k." },
  { question: "What distinguishes a binary search tree from a plain binary tree?", answer: "A BST enforces an ordering invariant: every left subtree's values are less than the node, every right subtree's values are greater — this ordering is what enables O(log n) search/insert/delete (on a balanced tree), which a plain binary tree with no ordering doesn't guarantee at all." },
  { question: "Why does an unbalanced BST hurt performance, and how do AVL/Red-Black trees fix it?", answer: "Inserting sorted data into a plain BST degenerates it into a linked list — O(n) operations instead of O(log n). AVL trees rebalance via rotations to keep subtree heights within 1 of each other; Red-Black trees use a looser coloring invariant that needs fewer rotations on average, trading a bit of balance strictness for cheaper maintenance." },
  { question: "What is a heap, and why is it the right structure for a priority queue?", answer: "A heap is a complete binary tree maintaining a heap property (parent always ≤ or ≥ children), giving O(1) peek at the min/max and O(log n) insert/extract — exactly what a priority queue needs, without paying for full sorted order like a balanced BST would." },
  { question: "What is a trie and what makes it well-suited to prefix-based lookups?", answer: "A trie stores strings character-by-character along tree paths, so all strings sharing a prefix share the same path from the root. This makes prefix search (autocomplete, spell-check) O(length of prefix) instead of scanning every string, at the cost of higher memory overhead per node." },
  { question: "Adjacency list vs adjacency matrix for representing a graph — when does each win?", answer: "Adjacency list: O(V+E) space, efficient for sparse graphs and iterating a node's neighbors. Adjacency matrix: O(V²) space but O(1) edge-existence checks — better for dense graphs or when you need frequent 'are these two nodes connected?' queries." },
  { question: "BFS vs DFS — how do you decide which to use?", answer: "BFS explores level by level (using a queue) and is the right choice for shortest path in an unweighted graph, or 'find the nearest X.' DFS explores as deep as possible before backtracking (using a stack/recursion) and fits cycle detection, topological sort, and exhaustive search/backtracking problems." },
  { question: "What does Dijkstra's algorithm compute, and what's its key limitation?", answer: "It computes shortest paths from a source to all other nodes in a weighted graph, using a priority queue to always expand the currently-closest unvisited node. Its key limitation: it doesn't work with negative edge weights (Bellman-Ford handles that case, at higher time complexity)." },
  { question: "What is topological sort and what precondition must the graph satisfy?", answer: "It orders nodes in a directed graph so every edge u→v places u before v — used for scheduling with dependencies (e.g. build order, course prerequisites). It only exists if the graph is a DAG (directed, acyclic); a cycle means no valid ordering exists." },
  { question: "What problem does Union-Find (Disjoint Set) solve efficiently, and what two optimizations make it fast?", answer: "It efficiently tracks which elements belong to the same group and merges groups, answering 'are these connected?' — used in Kruskal's MST algorithm and cycle detection. Union by rank/size and path compression together bring near-O(1) amortized operations." },
  { question: "How do you recognize that a problem should be solved with dynamic programming?", answer: "Look for optimal substructure (the optimal solution is built from optimal solutions to subproblems) and overlapping subproblems (the same subproblem recurs many times in a naive recursive solution) — if both hold, DP avoids exponential recomputation by caching subproblem results." },
  { question: "What's the difference between memoization and tabulation?", answer: "Memoization is top-down: write the natural recursive solution and cache (memoize) results as you compute them, so repeat calls are O(1). Tabulation is bottom-up: iteratively fill a table from the smallest subproblems up, avoiding recursion overhead and stack depth limits entirely." },
  { question: "When does a greedy algorithm give the correct (optimal) answer?", answer: "Greedy works when the problem has the greedy-choice property (a locally optimal choice at each step leads to a globally optimal solution) combined with optimal substructure — e.g. activity selection, Huffman coding. It fails on problems like 0/1 knapsack, where a locally best choice can block a better overall solution." },
  { question: "What is backtracking, and how does it differ from plain brute-force recursion?", answer: "Backtracking builds a solution incrementally and abandons ('backtracks' from) a partial solution as soon as it can't possibly lead to a valid answer, pruning large parts of the search space. Plain brute force would explore every possibility to completion before checking validity — backtracking is brute force with early exit." },
  { question: "What is the divide-and-conquer paradigm, and what's a classic example?", answer: "It splits a problem into independent subproblems of the same type, solves them recursively, then combines their results — e.g. merge sort splits the array, sorts each half, then merges. It works well when subproblems are truly independent and combining is cheap relative to the split-solve cost." },
  { question: "Compare merge sort and quicksort — when would you prefer one over the other?", answer: "Merge sort is O(n log n) worst-case guaranteed and stable, but needs O(n) extra space — good when worst-case guarantees or stability matter. Quicksort is typically faster in practice (better cache behavior, in-place) with O(n log n) average case, but O(n²) worst case on bad pivots (mitigated by randomized/median-of-three pivot selection)." },
  { question: "What's the practical tradeoff between recursion and iteration?", answer: "Recursion often expresses divide-and-conquer/tree/graph problems more naturally and readably, but each call adds stack frame overhead and risks stack overflow on deep recursion. Iteration avoids that overhead and stack limits but can require manually managing state (e.g. an explicit stack) that recursion gets for free." },
  { question: "Give an example of a bit-manipulation trick and what it's used for.", answer: "`n & (n-1)` clears the lowest set bit — used to count set bits (Brian Kernighan's algorithm) in O(number of set bits) instead of checking every bit, or to check if n is a power of two (`n & (n-1) == 0`)." },
  { question: "How would you design an LRU cache with O(1) get and put?", answer: "Combine a hash map (key → node) for O(1) lookup with a doubly linked list ordered by recency, so you can move a just-accessed node to the front in O(1) and evict the tail (least recently used) in O(1) when over capacity — the hash map gives direct access to the node to splice, avoiding an O(n) list search." },
  { question: "What problem do segment trees / Fenwick (BIT) trees solve that a plain array can't do efficiently?", answer: "They support both range queries (e.g. sum/min over a range) and point updates in O(log n), whereas a plain array gives O(1) point update but O(n) range query (or O(1) range query with O(n) update if precomputed) — segment trees/BITs balance both instead of forcing that tradeoff." },
  { question: "How does a bloom filter achieve O(1) 'possibly present' checks, and why can't it have false negatives?", answer: "It hashes an item with k independent hash functions and sets those k bit positions in a bit array; checking an item means checking all k positions are set. It can't false-negative because any item actually inserted will always have set all its bits — a 'not present' answer requires at least one unset bit, which only happens if it was truly never inserted." },
  { question: "What is a skip list and what does it offer over a balanced BST?", answer: "A skip list is a layered linked list where higher layers skip over more elements, giving O(log n) expected search/insert/delete via probabilistic balancing (coin flips decide node height) instead of tree rotations. It's simpler to implement correctly than a balanced BST, especially for concurrent access, at the cost of being probabilistic rather than worst-case guaranteed." },
  { question: "What is amortized analysis, and what's the classic example?", answer: "It analyzes the average cost per operation over a worst-case sequence of operations, rather than the worst-case cost of a single operation in isolation. Classic example: dynamic array (e.g. ArrayList) append is usually O(1), but occasionally O(n) when it resizes — amortized analysis shows the average over n appends is still O(1) because resizes become exponentially rarer." },
  { question: "What does 'NP-complete' mean in practical terms for an engineer?", answer: "It means no known algorithm solves the problem in polynomial time in the worst case, and if you found one, it would imply P=NP (solving every problem in NP quickly) — practically, it's a signal to stop searching for an exact efficient solution and instead use heuristics, approximations, or accept exponential time on small inputs." },
];

export const DISTRIBUTED: ConceptSeed[] = [
  { question: "What problem do consensus algorithms like Paxos and Raft solve?", answer: "They let a cluster of nodes agree on a single value (e.g. who's the leader, or the next entry in a replicated log) even when some nodes fail or messages are delayed/lost, without ever disagreeing — this is the foundation for consistent replicated state across a distributed system." },
  { question: "Compare two-phase commit and the saga pattern for distributed transactions.", answer: "2PC: a coordinator asks all participants to prepare, then commits only if all agree — strongly consistent, but blocks if the coordinator or a participant fails mid-protocol, and doesn't scale well. Saga: a sequence of local transactions, each with a compensating action to undo it — no blocking/locking across services, but only eventually consistent, and you must write the undo logic yourself." },
  { question: "What problem do vector clocks solve that a simple timestamp can't?", answer: "A single timestamp can't tell you whether two events on different nodes are causally related or truly concurrent (clocks drift and aren't synchronized). A vector clock (one counter per node) lets you compare two events' vectors to determine 'happened-before,' 'happened-after,' or 'concurrent, no causal relationship.'" },
  { question: "What is the gossip protocol and why is it useful for large clusters?", answer: "Nodes periodically exchange state with a few random peers, and information spreads epidemic-style across the whole cluster in O(log n) rounds. It's useful because it has no single coordinator (no bottleneck/SPOF), scales well, and tolerates node failures gracefully — used for membership/failure detection in systems like Cassandra." },
  { question: "What does the quorum condition R + W > N guarantee in a replicated data store?", answer: "With N replicas, requiring R replicas to agree on a read and W replicas to acknowledge a write, R + W > N guarantees any read quorum overlaps with any write quorum by at least one node — so a read is guaranteed to see the latest acknowledged write, giving strong consistency without needing all N replicas online." },
  { question: "How should a distributed system handle a network partition, and what's the core decision it forces?", answer: "During a partition, nodes on each side can't talk to nodes on the other side, forcing a choice per the CAP theorem: keep serving requests on both sides (favoring availability, risking inconsistent writes on each side) or refuse requests on the minority side until the partition heals (favoring consistency)." },
  { question: "What is split-brain and why is it dangerous?", answer: "Split-brain happens when a network partition causes two nodes to each believe they're the sole leader and both accept writes independently — when the partition heals, you have two divergent histories that must be reconciled, potentially losing data. Systems prevent it with quorum-based leader election (a leader needs majority agreement, so only one side of any partition can have a majority)." },
  { question: "Multi-leader vs single-leader replication — what's the core tradeoff?", answer: "Single-leader: all writes go through one node — simple conflict-free ordering, but that leader is a write bottleneck and a single point of failure until failover completes. Multi-leader: writes can go to any of several leaders (e.g. different regions) — better write availability and locality, but concurrent writes to the same data on different leaders can conflict and need resolution." },
  { question: "Explain 'read-your-writes' and 'monotonic reads' as eventual-consistency guarantees.", answer: "Read-your-writes guarantees a user always sees their own prior writes on subsequent reads (even if a replica hasn't caught up yet, e.g. by routing that user's reads to the primary briefly). Monotonic reads guarantees that once you've seen a value, you never see an older value on a later read — you don't 'go back in time' by hitting a lagging replica after hitting a fresher one." },
  { question: "What is distributed tracing and what problem does it solve in a microservices architecture?", answer: "It propagates a single trace ID through a request as it hops across many services, recording timing/spans at each hop, so you can reconstruct the full request path and pinpoint which service caused a slowdown or error. Without it, debugging a request that touched 10 services means correlating separate logs manually." },
  { question: "What is a service mesh and what does the sidecar pattern give you?", answer: "A service mesh handles cross-cutting network concerns (retries, mTLS, load balancing, observability) via a sidecar proxy deployed alongside each service instance, so the application code doesn't need to implement any of it — the mesh's control plane configures all sidecars centrally." },
  { question: "Explain the difference between at-least-once, at-most-once, and exactly-once delivery.", answer: "At-most-once: a message might be lost but is never duplicated (fire-and-forget). At-least-once: a message is never lost but might be delivered/processed multiple times (retries on unconfirmed delivery). Exactly-once is the hardest to achieve in practice — usually approximated by at-least-once delivery plus idempotent processing on the consumer side." },
  { question: "Why must event consumers in a distributed system be idempotent?", answer: "Because most messaging systems only guarantee at-least-once delivery, a consumer will sometimes receive the same message twice (e.g. after a redelivery following an ack timeout). If processing it twice isn't safe (e.g. double-charging), the consumer must detect and ignore duplicates itself, typically via a processed-message ID log." },
  { question: "Why can't distributed systems just rely on synchronized clocks, and what do they use instead?", answer: "Even NTP-synchronized clocks can drift by tens of milliseconds and briefly jump backward, which is dangerous for ordering events. Systems instead use logical clocks (Lamport timestamps, vector clocks) that capture causal ordering directly from message passing, independent of physical clock accuracy — or hybrid approaches like Google Spanner's TrueTime with bounded uncertainty." },
  { question: "What are the main approaches to leader election in a distributed system?", answer: "Bully algorithm (highest ID node declares itself leader and others defer), Raft's randomized-timeout voting (candidates request votes after an election timeout, majority wins), or delegating to an external coordination service (ZooKeeper/etcd) that provides leader election as a primitive via ephemeral nodes/leases." },
  { question: "Why are distributed locks hard to get right, and what's a common failure mode?", answer: "A common failure mode: a node holds a lock, then pauses (GC pause, network delay) long enough for the lock's lease to expire and be granted to another node — then the first node resumes, still believing it holds the lock, and both act concurrently. Fencing tokens (a monotonically increasing number issued with each lock grant) let the resource reject stale operations from a node that lost the lock." },
  { question: "What is PACELC and how does it extend CAP?", answer: "CAP only describes behavior during a Partition (choose Availability or Consistency). PACELC adds: Else (when there's no partition), you still must choose between Latency and Consistency — even with no failures, waiting for all replicas to confirm a write (consistency) costs latency versus returning as soon as one replica acks (lower latency, weaker consistency)." },
  { question: "What is chaos engineering and why deliberately break your own production system?", answer: "It's the practice of intentionally injecting failures (killing instances, adding network latency, partitioning services) into a system — often in production — to verify your resilience assumptions actually hold, rather than discovering they don't during a real, unplanned outage. Netflix's Chaos Monkey popularized randomly terminating instances during business hours." },
  { question: "What are the 'fallacies of distributed computing' and why do they matter?", answer: "A list of false assumptions engineers often make: the network is reliable, latency is zero, bandwidth is infinite, the network is secure, topology doesn't change, there's one administrator, transport cost is zero, and the network is homogeneous. They matter because designs built on any of these assumptions break in real distributed deployments — every one of them is false in practice." },
  { question: "How do you implement rate limiting that's correct across multiple servers, not just one?", answer: "Local (per-server) counters undercount because traffic is split across servers, letting a client exceed the real limit. You need a shared, atomic counter (e.g. Redis with `INCR` + expiry, or a sliding-window log in a shared store) that every server checks against, so the limit is enforced against total traffic, not per-server traffic." },
];

export const DATABASES: ConceptSeed[] = [
  { question: "What do the four ACID properties guarantee?", answer: "Atomicity: a transaction fully completes or fully rolls back, no partial effects. Consistency: a transaction moves the DB from one valid state to another, respecting all constraints. Isolation: concurrent transactions don't see each other's uncommitted intermediate state. Durability: once committed, data survives a crash." },
  { question: "Name the standard SQL transaction isolation levels and the anomaly each one prevents that the level below allows.", answer: "Read Uncommitted (allows dirty reads) → Read Committed (prevents dirty reads, allows non-repeatable reads) → Repeatable Read (prevents non-repeatable reads, allows phantom reads in some DBs) → Serializable (prevents all of the above, transactions behave as if run one at a time)." },
  { question: "What is MVCC and what problem does it solve for concurrent reads and writes?", answer: "Multi-Version Concurrency Control keeps multiple versions of a row so readers see a consistent snapshot as of when their transaction started, without blocking on or being blocked by concurrent writers. This is how Postgres/MySQL (InnoDB) give you 'readers don't block writers, writers don't block readers' without full locking." },
  { question: "Optimistic vs pessimistic locking — when do you use each?", answer: "Pessimistic: lock the row before reading, blocking other transactions until you're done — safe under high contention where conflicts are likely. Optimistic: read without locking, then check a version number on write to detect if someone else changed it in between, retrying if so — better throughput when conflicts are rare, since you avoid holding locks." },
  { question: "What is a write-ahead log (WAL) and why does it enable both durability and crash recovery?", answer: "Every change is written to an append-only log on disk before it's applied to the actual data pages. If the DB crashes mid-write, on restart it can replay the WAL to reconstruct any change that was logged but not yet flushed to the data files, guaranteeing no committed transaction is lost." },
  { question: "How does a B-tree index actually speed up a lookup?", answer: "It's a balanced, sorted tree structure where each node holds multiple keys and pointers to children (fan-out much wider than a binary tree, matching disk/page size), so finding a row takes O(log n) page reads instead of scanning every row — and because it's sorted, range queries and ORDER BY can use it too." },
  { question: "Hash index vs B-tree index — what's the tradeoff?", answer: "A hash index gives O(1) equality lookups but no ordering, so it can't support range queries, sorting, or prefix matches. A B-tree index is slightly slower for pure equality (O(log n)) but supports range queries, sorting, and is the default for most general-purpose indexing needs." },
  { question: "What's the tradeoff between a normalized and a denormalized schema?", answer: "Normalized: data lives in one place (no duplication), so updates are cheap and consistent — but reads often need multiple joins. Denormalized: data is duplicated to avoid joins, making reads faster — but every write must update all the duplicated copies, risking inconsistency if one is missed." },
  { question: "What's the difference between OLTP and OLAP workloads, and why does each need a different storage layout?", answer: "OLTP (transactional): many small reads/writes of individual rows (e.g. 'update this order') — row-oriented storage is efficient since a whole row is fetched/written together. OLAP (analytical): few queries scanning huge amounts of data but only a few columns (e.g. 'average order value last quarter') — column-oriented storage is efficient since you only read the columns you need, skipping the rest." },
  { question: "Explain the difference between INNER, LEFT, RIGHT, and FULL OUTER joins.", answer: "INNER: only rows with matches in both tables. LEFT: all rows from the left table, with NULLs for unmatched right-side columns. RIGHT: the mirror of LEFT. FULL OUTER: all rows from both tables, NULLs on whichever side has no match." },
  { question: "What is the N+1 query problem and how do you fix it?", answer: "It happens when you fetch N parent records, then loop over them issuing one additional query per record to fetch related data (N+1 total queries) instead of one batched query. Fix it with a JOIN, or a single `WHERE id IN (...)` query for all related rows at once, or a data loader that batches lookups." },
  { question: "What does a query optimizer do, and how do you use EXPLAIN to work with it?", answer: "The optimizer picks an execution plan (which indexes to use, join order, join algorithm) estimated to be cheapest, based on table statistics. EXPLAIN (or EXPLAIN ANALYZE) shows you that chosen plan — letting you spot a missing index (sequential scan where an index scan was expected) or a bad join order before it becomes a production problem." },
  { question: "Why use a connection pool instead of opening a new DB connection per request?", answer: "Opening a DB connection is relatively expensive (TCP handshake, auth, resource allocation on the DB server), and a DB can only handle a limited number of concurrent connections. A pool keeps a set of connections open and reused across requests, avoiding that per-request cost and protecting the DB from being overwhelmed by connection count." },
  { question: "What causes replication lag and what problem can it cause for an application?", answer: "A replica applies writes from the primary's log asynchronously, so if the replica is slower (network delay, heavy load, or a large transaction) it falls behind — an application reading from that replica can see stale data, including 'my own write from a second ago isn't there yet,' which surprises users." },
  { question: "Compare the four main NoSQL data models: document, key-value, column, and graph.", answer: "Key-value: simplest, O(1) lookup by key, no query flexibility — great for caching/sessions. Document: JSON-like nested structures, flexible schema — good for varied/evolving records. Column(-family): optimized for huge sparse tables and range scans over a row key — good for time-series/write-heavy analytics. Graph: nodes and edges as first-class citizens — good for relationship-heavy queries like social networks or fraud detection." },
  { question: "What's the difference between database sharding and partitioning?", answer: "Partitioning splits a table's data within a single database instance (e.g. by date range), still queryable as one logical table. Sharding splits data across multiple separate database instances/machines entirely, requiring the application (or a routing layer) to know which shard holds a given piece of data." },
  { question: "How do you make a schema migration safe on a large table with zero downtime?", answer: "Avoid a single blocking ALTER TABLE on a huge table; instead, add the new column as nullable (fast, metadata-only in most DBs), backfill data in small batches in the background, then add constraints (NOT NULL, etc.) only after the backfill completes — and always deploy application code that tolerates both old and new schema during the rollout window." },
  { question: "What is a covering index and why can it make a query much faster?", answer: "A covering index includes every column the query needs (in the WHERE, SELECT, and ORDER BY), so the database can answer the query entirely from the index itself without a second lookup ('bookmark lookup') into the actual table row — cutting I/O roughly in half for that query." },
  { question: "How does a full-text search index differ from a normal B-tree index, and why can't a B-tree do full-text search well?", answer: "A B-tree indexes exact/prefix values, so it can't efficiently answer 'does this text contain this word anywhere' — that requires an inverted index mapping each word to every document containing it (with position/relevance data), which is what full-text search engines (or a DB's built-in FTS) build and maintain separately." },
  { question: "Compare full, incremental, and point-in-time-recovery backup strategies.", answer: "Full backup: a complete copy of the DB — simple to restore, but slow and storage-heavy to take often. Incremental: only changes since the last backup — fast and cheap, but restoring means replaying a chain of backups. Point-in-time recovery: continuous WAL archiving lets you restore to any specific moment (e.g. right before a bad migration), not just a backup's exact timestamp." },
];

export const NETWORKING_OS: ConceptSeed[] = [
  { question: "TCP vs UDP — what's the core tradeoff and when do you pick UDP?", answer: "TCP guarantees ordered, reliable delivery via acknowledgments and retransmission, at the cost of connection setup and latency overhead. UDP is fire-and-forget with no ordering/delivery guarantees, but lower latency and overhead — pick it for real-time use cases (video calls, gaming) where a late retransmitted packet is worse than a dropped one." },
  { question: "Walk through the TCP three-way handshake.", answer: "Client sends SYN (synchronize, proposing an initial sequence number) → server responds SYN-ACK (acknowledging the client's SYN and sending its own) → client sends ACK (acknowledging the server's SYN). After this, both sides have agreed on sequence numbers and the connection is established." },
  { question: "At a high level, what happens during a TLS handshake before HTTPS data flows?", answer: "The client and server agree on a TLS version and cipher suite, the server presents its certificate (proving its identity, verified against a trusted CA), and they establish a shared symmetric session key (via key exchange, e.g. Diffie-Hellman) — after which all data is encrypted with that fast symmetric key rather than the slower asymmetric keys used just for the handshake." },
  { question: "Walk through the steps of DNS resolution for a URL you've never visited.", answer: "Your resolver checks its cache, then queries a root nameserver (which points to the TLD nameserver, e.g. for .com), then the TLD nameserver points to the domain's authoritative nameserver, which finally returns the IP address. Each hop's answer is cached (per its TTL) so most real-world lookups skip several of these steps." },
  { question: "What is the OSI model and why does it still matter practically, even though real systems don't cleanly map to it?", answer: "It's a 7-layer conceptual model (Physical, Data Link, Network, Transport, Session, Presentation, Application) describing where different networking concerns live. It matters practically as shared vocabulary — e.g. saying a load balancer works at 'L4' (transport, routing by IP/port) vs 'L7' (application, routing by HTTP headers/path) communicates a precise capability difference." },
  { question: "What's the fundamental difference between a process and a thread?", answer: "A process has its own isolated memory space and resources — communicating with another process requires explicit IPC. Threads within the same process share that memory space (heap, globals) but each has its own stack and registers, making inter-thread communication cheap but requiring synchronization to avoid data races." },
  { question: "Why is a context switch expensive, and what does it actually involve?", answer: "It involves saving the current thread/process's CPU register state and memory mappings, then loading the next one's — plus indirect costs like CPU cache and TLB invalidation, since the new context's working set isn't 'warm' in cache anymore. This is why excessive threading/switching (thousands of threads fighting for a few cores) can hurt throughput despite seeming more parallel." },
  { question: "What are the four necessary conditions for deadlock, and how does breaking just one prevent it?", answer: "Mutual exclusion (resource can't be shared), hold-and-wait (holding one resource while waiting for another), no preemption (can't forcibly take a resource back), and circular wait (a cycle of processes each waiting on the next). Deadlock requires all four simultaneously, so e.g. enforcing a global lock-acquisition ordering (breaking circular wait) alone prevents it." },
  { question: "What is virtual memory and what does paging give you over directly addressing physical RAM?", answer: "Virtual memory gives each process its own private address space, isolated from other processes and larger than physically available RAM (backed by disk swap). Paging divides memory into fixed-size pages, letting the OS map virtual pages to physical frames flexibly — non-contiguous physical allocation, on-demand loading, and swapping out unused pages." },
  { question: "What's the difference between a mutex and a semaphore?", answer: "A mutex allows only one thread to hold it at a time and typically must be released by the same thread that acquired it — it's about mutual exclusion of a critical section. A semaphore holds a count and allows up to N holders, and can be signaled by a different thread than the one that waited — it's more general, useful for limiting concurrent access to a pool of N resources." },
  { question: "Why use a thread pool instead of spawning a new thread per task?", answer: "Creating a thread has real overhead (stack allocation, OS scheduling registration) and unbounded thread creation under load can exhaust memory or overwhelm the scheduler. A thread pool reuses a fixed set of worker threads, queueing excess tasks, bounding resource use and giving predictable behavior under load." },
  { question: "Name a few CPU scheduling algorithms and what each optimizes for.", answer: "First-Come-First-Served: simple, but a long task blocks everything behind it. Shortest-Job-First: minimizes average wait time, but needs to know job length in advance and can starve long jobs. Round-robin: gives every task a time slice in turn — fair and responsive for interactive systems, at some throughput cost from frequent switching." },
  { question: "What is a socket, concretely?", answer: "A socket is an OS-provided endpoint for network communication, identified by an IP address + port (plus protocol), that an application reads/writes like a file descriptor. The OS's networking stack handles the actual packet framing/transmission underneath — the socket API is the abstraction the application code interacts with." },
  { question: "What does HTTP/2 improve over HTTP/1.1, and why does that matter for web performance?", answer: "HTTP/1.1 typically needs a separate connection (or head-of-line-blocked pipeline) per concurrent request. HTTP/2 multiplexes many requests over a single TCP connection with interleaved binary frames, plus header compression — eliminating the need for workarounds like domain sharding or spriting that HTTP/1.1 sites used to reduce connection overhead." },
  { question: "What's the practical difference between load balancing at L4 vs L7?", answer: "L4 (transport layer) routes based on IP/port only, without inspecting the actual request content — faster and protocol-agnostic, but can't route based on e.g. URL path or headers. L7 (application layer) terminates and inspects the actual HTTP request, enabling routing by path/header/cookie (e.g. sending /api/* to one service and /static/* to another) at the cost of more processing per request." },
];

export const BEHAVIORAL: ConceptSeed[] = [
  { question: "What is the STAR method and why do interviewers want answers structured that way?", answer: "Situation, Task, Action, Result — it forces a concrete story instead of a vague generalization, and specifically isolates your individual actions and the measurable outcome. Interviewers want it because 'I'm good at teamwork' is unverifiable, but a specific story with a specific result lets them actually assess it." },
  { question: "How should you structure an answer to 'tell me about a time you disagreed with a teammate'?", answer: "Pick a real disagreement about substance (not personality), show you understood their perspective before pushing back, describe how you resolved it (data, compromise, or escalation) professionally, and land on the outcome and what you'd do differently. Avoid stories where you were simply 'right' and they were 'wrong' — interviewers are listening for collaboration skill, not vindication." },
  { question: "What makes a strong answer to 'tell me about a time you failed'?", answer: "Choose a real failure with real stakes (not a humble-brag disguised as a failure), own your specific mistake without deflecting blame, and focus most of the answer on what you learned and changed afterward. A weak answer picks something trivial or spends all its time explaining why it wasn't really your fault." },
  { question: "How do you answer 'how do you prioritize when everything feels urgent'?", answer: "Describe a concrete framework you actually use (e.g. impact vs effort, or asking 'what breaks if this waits a day'), give a real example of applying it under pressure, and mention how you communicate the tradeoffs to stakeholders whose items get deprioritized — the communication part is often what separates a good answer from a great one." },
  { question: "What's a good structure for 'tell me about a time you persuaded others of a technical decision'?", answer: "Describe the disagreement and why your position wasn't obviously correct to others at first, how you built your case (data, prototype, or addressing their specific concerns rather than repeating your own point), and the actual outcome — including if you were only partially successful or had to compromise, which reads as more credible than a clean total win." },
  { question: "How should you talk about receiving critical feedback in an interview?", answer: "Give a specific example of feedback that actually stung a little (not a softball like 'be more confident'), show you took it seriously rather than getting defensive, and describe the concrete change you made afterward — interviewers are checking for coachability, so a story with zero discomfort in it usually doesn't land." },
  { question: "What should a good 'tell me about a time you mentored someone' answer emphasize?", answer: "Focus less on what you knew and more on how you adapted your approach to that specific person's learning style/gaps, and describe a measurable change in their skill or confidence over time — a generic 'I answered their questions' answer doesn't show mentoring skill, it shows being helpful, which is a different thing." },
  { question: "How do you handle a question about working with ambiguous or incomplete requirements?", answer: "Describe how you narrowed ambiguity through action — asking targeted clarifying questions, making a reasonable documented assumption and validating it early, or building a small prototype to surface hidden requirements — rather than either freezing or barreling ahead on guesses without checking in." },
  { question: "What's a productive way to answer 'tell me about a conflict with a manager or stakeholder'?", answer: "Keep it professional and specific (a real disagreement about approach, priority, or scope), show you raised it directly and respectfully rather than working around them or complaining to others, and be honest about the actual resolution — including if you ultimately deferred to their call after making your case." },
  { question: "How do you talk about working with an underperforming teammate without sounding like you're throwing them under the bus?", answer: "Focus on what you did — offered specific help, adjusted how you communicated, escalated appropriately if it affected the team — rather than cataloguing their shortcomings. The interviewer is assessing your judgment and empathy here, not auditing your teammate's performance review." },
  { question: "What's a strong way to answer 'tell me about a time you missed a deadline'?", answer: "Own it plainly (don't reflexively blame scope changes or other people), explain what you did once you realized it was at risk (early communication, renegotiating scope, asking for help), and describe the concrete process change you made afterward to catch it earlier next time." },
  { question: "How do you effectively communicate a technical tradeoff to a non-technical stakeholder?", answer: "Translate the tradeoff into terms they care about (cost, time, risk, user impact) instead of the technical mechanism itself, give them a small number of concrete options rather than an open-ended problem, and state your recommendation clearly rather than just listing pros/cons and leaving the decision entirely to them." },
  { question: "What makes a good answer to 'tell me about a time you took initiative without being asked'?", answer: "Pick an example where you identified a real problem others hadn't flagged, made the case for why it mattered (not just did something because you felt like it), and describe the actual impact — a strong initiative story shows judgment about what's worth doing, not just proactiveness for its own sake." },
  { question: "How should you answer a question about handling scope creep on a project?", answer: "Describe how you made the growing scope visible early (rather than silently absorbing it and burning out or quietly missing the original deadline), and how you renegotiated timeline/scope/resources explicitly with whoever requested the additions — showing you protect the project's health rather than just saying yes to everything." },
  { question: "How do you give a genuine, specific answer to 'why do you want to work here'?", answer: "Anchor it to something concrete and specific to that company (a product decision, engineering challenge, or technical direction you've actually researched) connected to something specific about your own background or goals — generic answers ('great culture,' 'exciting mission') that could apply to any company signal you didn't do the research." },
];

const CATEGORY_GROUPS: [Category, ConceptSeed[]][] = [
  ["System Design", SYSTEM_DESIGN],
  ["Data Structures & Algorithms", DSA],
  ["Distributed Systems", DISTRIBUTED],
  ["Databases", DATABASES],
  ["Networking & OS", NETWORKING_OS],
  ["Behavioral", BEHAVIORAL],
];

// Interleaves the category groups proportionally to their size (a group with
// 50 items appears roughly 3.3x as often as one with 15) while preserving
// each group's internal order — a fractional round-robin (Bresenham-style):
// every group accumulates its own share (size/total) each step, and the
// group with the largest accumulated share is picked next and decremented by
// 1, so error never builds up in one direction the way naive rounding would.
export function buildTheorySchedule(): Concept[] {
  const total = CATEGORY_GROUPS.reduce((sum, [, items]) => sum + items.length, 0);
  const indices = CATEGORY_GROUPS.map(() => 0);
  const share = CATEGORY_GROUPS.map(([, items]) => items.length / total);
  const acc = CATEGORY_GROUPS.map(() => 0);
  const result: Concept[] = [];

  for (let day = 1; day <= total; day++) {
    let best = -1;
    for (let g = 0; g < CATEGORY_GROUPS.length; g++) {
      acc[g]! += share[g]!;
      if (indices[g]! < CATEGORY_GROUPS[g]![1].length && (best === -1 || acc[g]! > acc[best]!)) {
        best = g;
      }
    }
    const [category, items] = CATEGORY_GROUPS[best]!;
    const seed = items[indices[best]!]!;
    result.push({ day, category, question: seed.question, answer: seed.answer });
    indices[best]! += 1;
    acc[best]! -= 1;
  }

  return result;
}
