import type { ExamPaperSeed } from "../types";

const PAPER: ExamPaperSeed =
  {
    course: "INFO5995",
    week: 2,
    paperNumber: 1,
    title: "Week 2 Practice Paper",
    topics: "LLMs: how they respond, conversation context, system prompts as a control layer; Reasoning models (OpenAI o-series): internal scratchpad, effort levels, the 'security aha moment'; AI agents: reason-act-observe-continue tool-use cycle, terminal tools, security boundaries and authorisation; AI-assisted vulnerability discovery pitfalls: laziness, hallucination, missed findings, framing sensitivity, and mitigations; Mobile security: source-to-APK pipeline, APK contents, decompilation limits, Assignment 1 investigation expectations",
    sourceFiles: ["lecture/Week02-Al assisted vulnerability discovery, mobile security, assignment walkthrough.pdf", "lecture/INFO5995_Week_2_Extra_Resources (1).pdf"],
    questions: [
      {
        type: "mcq",
        prompt: "According to the lecture, why are we talking about AI in cybersecurity at all?",
        options: ["Because AI is required by law for all security audits", "Because modern software is too large to inspect manually line by line, human limits mean important weaknesses can be missed, and AI can help search, explain, and suggest where to look", "Because AI always finds every vulnerability with 100% accuracy", "Because manual code review has been banned by industry standards"],
        correctIndex: 1,
        modelAnswer: "The lecture's opening frames it as: large systems (thousands of files/dependencies/paths), human limits (important weaknesses can be easy to miss), and 'AI can help' — search, explain, and suggest where to look — but immediately warns 'modern software is too large to inspect manually, line by line,' motivating AI assistance rather than AI infallibility.",
      },
      {
        type: "mcq",
        prompt: "How does the lecture describe how an LLM generates a response?",
        options: ["It looks up the exact answer in a fixed database of facts", "It receives a prompt and generates a response based on patterns learned during training", "It always consults the internet in real time before answering", "It runs the user's code to check whether it is correct before responding"],
        correctIndex: 1,
        modelAnswer: "'The model receives a prompt and generates a response based on patterns learned during training' — this pattern-based generation, not lookup or execution, is the basis for Key Takeaway 1 (LLMs predict patterns, they don't automatically know if an answer is true).",
      },
      {
        type: "truefalse",
        prompt: "True or False: The lecture states that the same prompt sent to an LLM always produces exactly the same response.",
        options: ["True", "False"],
        correctIndex: 1,
        modelAnswer: "The 'A Simple Example' slide states explicitly: 'The same prompt does not always produce exactly the same response.'",
      },
      {
        type: "mcq",
        prompt: "What role does a system prompt play, per 'System Prompt as a Control Layer'?",
        options: ["It sets the model's instructions, role, and behavioural boundaries before the user interacts with it", "It is only visible to the end user, never the model", "It replaces the need for any user prompt entirely", "It has no effect on the model's behaviour"],
        correctIndex: 0,
        modelAnswer: "'A system prompt sets the model's instructions, role and behavioural boundaries before the user interacts with it' — the lecture shows how the same 'Hello' produces a different response depending on the system prompt in force.",
      },
      {
        type: "mcq",
        prompt: "Which of these best captures Key Takeaway 1 ('LLMs Predict Patterns')?",
        options: ["LLMs generate responses by predicting likely patterns and do not automatically know whether an answer is true or correct, so AI-flagged suspicious code still needs evidence and verification", "LLMs always verify their own answers against a ground-truth database before responding", "LLMs cannot process code, only natural language", "LLMs are only useful for finding vulnerabilities in cryptographic protocols"],
        correctIndex: 0,
        modelAnswer: "'LLMs can appear intelligent, but they generate responses by predicting likely patterns. They do not automatically know whether an answer is true or correct... AI may help identify suspicious code, but every finding still needs evidence and verification.'",
      },
      {
        type: "mcq",
        prompt: "Key Takeaway 2 ('Code Is Data Too') explains why AI can help investigate software. What is the caveat given alongside this?",
        options: ["There is no caveat — AI-found vulnerabilities are always correct", "'Prediction is not proof' — AI can still produce convincing but incorrect findings", "AI can only investigate software written in Python", "Code can never be represented as tokens, unlike natural language"],
        correctIndex: 1,
        modelAnswer: "'Code, execution traces and other technical artefacts can also be analysed as patterns... this is why AI can help investigate software... but prediction is not proof. AI can still produce convincing but incorrect findings.'",
      },
      {
        type: "mcq",
        prompt: "In the 'PAUSE. THINK. PREDICT.' exercise comparing four tasks for an AI model like GPT, which task does the lecture frame as hardest, describing it as 'not even verifiable' and possibly requiring humans to manually validate?",
        options: ["A Python coding task", "An obscure-language coding task with syntax provided", "Finding vulnerabilities in cryptographic protocols or consensus mechanisms", "Decompiling machine code"],
        correctIndex: 2,
        modelAnswer: "'Finding vulnerabilities in Crypto/Consensus proofs' is explicitly described as: 'Not even verifiable. May require humans to manually validate. This is the hardest type of security questions.'",
      },
      {
        type: "mcq",
        prompt: "If an LLM is asked to debug code in an obscure language with no syntax provided, what does the lecture say the model is likely to do?",
        options: ["Refuse to attempt the task under all circumstances", "It may hallucinate structure from other languages, often defaulting to something that looks like C, Python, or Java style, since it must first guess token boundaries, keywords, structure, and grammar", "It will always correctly infer the exact grammar with no errors", "It will silently convert the code to English prose only"],
        correctIndex: 1,
        modelAnswer: "'If you do not provide syntax, the model must first guess: is this functional? object oriented? what is a function declaration? how are variables defined?... it may hallucinate structure from other languages. It will often default to something that looks like C, Python, or Java style.'",
      },
      {
        type: "mcq",
        prompt: "Why does the lecture say decompiling machine code back into high-level code is 'much harder' for an LLM than a typical coding task?",
        options: ["Machine code files are always too large to fit in any context window", "Machine code has less natural language signal, less structured high-level patterns, fewer clean paired training examples, and is low-level/ambiguous, requiring reasoning about semantics rather than just syntax", "LLMs are legally prohibited from processing machine code", "Machine code always contains encrypted content"],
        correctIndex: 1,
        modelAnswer: "'Much harder — less natural language signal, less structured high level patterns, fewer clean paired examples. Machine code is low level and ambiguous. Decompilation requires reasoning about semantics, not just syntax.'",
      },
      {
        type: "mcq",
        prompt: "How does the lecture define 'hallucination'?",
        options: ["The model refusing to answer a question", "The model producing something that sounds correct but is not grounded in reality", "The model taking too long to respond", "The model asking a clarifying question before answering"],
        correctIndex: 1,
        modelAnswer: "'Hallucination means: the model produces something that sounds correct but is not grounded in reality.'",
      },
      {
        type: "mcq",
        prompt: "What distinguishes a 'reasoning model' (e.g. OpenAI's o-series) from a standard LLM response, per the lecture?",
        options: ["Reasoning models skip the system prompt entirely", "Reasoning models do some internal, often-hidden 'scratchpad' processing — potentially hundreds or thousands of tokens — before producing their final answer, sometimes with a controllable effort level", "Reasoning models never make mistakes", "Reasoning models cannot use tools"],
        correctIndex: 1,
        modelAnswer: "'Some internal scratchpad before it speaks... that internal work can be long, like hundreds or thousands of tokens... you might see a thinking indicator... you can often control how much effort it uses, like low, medium, high.'",
      },
      {
        type: "truefalse",
        prompt: "True or False: The lecture states that more reasoning by a model guarantees a correct final answer.",
        options: ["True", "False"],
        correctIndex: 1,
        modelAnswer: "'How a Reasoning Model Responds' states explicitly: 'more reasoning can improve performance, but it does not guarantee a correct answer.'",
      },
      {
        type: "mcq",
        prompt: "What does the lecture call the 'Aha Moment for Security'?",
        options: ["The realisation that AI should never be used in cybersecurity", "That security 'completely changed' after reasoning models like O3 and R1, with things that didn't work before starting to work, and real vulnerabilities being found at scale", "The discovery that all vulnerabilities are now fully preventable", "The moment cybersecurity stopped requiring human analysts"],
        correctIndex: 1,
        modelAnswer: "'Security has completely changed after O3 and R1. Things that did not work before are now starting to work. We start to find real vulnerabilities on a large scale.'",
      },
      {
        type: "mcq",
        prompt: "Under 'Reasoning Is Not Enough,' why does the lecture say tools (grep, ls, static/dynamic analysis, networking, etc.) are still needed even with reasoning models?",
        options: ["Because reasoning models cannot read any text at all", "Because code repositories can be huge (thousands of interdependent files) and context windows are small, while text-based tools let the model gather evidence relatively cheaply", "Because tools are required by university policy for Assignment 1", "Because reasoning models cannot be combined with tool use"],
        correctIndex: 1,
        modelAnswer: "'Code repositories can be HUGE... thousands of files... context window is small. LLMs can work with text in a relatively cheap way. There are a lot of existing tools (text based): basic terminal tools, networking, static/dynamic analysis programs.'",
      },
      {
        type: "mcq",
        prompt: "In the lecture's high-level diagram of an AI agent, what cycle does the agent follow when investigating something?",
        options: ["It only ever produces a final response, never a tool call", "Reasoning → deciding whether to answer directly or call a tool → observing the tool's result → continuing (which may include further tool calls) before producing a final response", "It calls every available tool simultaneously regardless of relevance", "It ignores the system prompt once reasoning begins"],
        correctIndex: 1,
        modelAnswer: "'An AI agent can decide whether to answer directly or use a tool to gather more evidence' — shown as Reasoning → (Response or Tool Call Instruction) → Tool result → further reasoning, i.e. the reason/act/observe/continue cycle.",
      },
      {
        type: "mcq",
        prompt: "In the 'How an AI Agent Uses a Tool' example, the agent is asked 'What files are in this folder?' What does it do?",
        options: ["It guesses the answer without checking", "It reasons that it needs to check the current directory, issues the `ls` tool call, receives the tool result (main.py, README.md, data.txt), and uses that evidence to give the final answer", "It refuses to answer without further authorisation", "It rewrites all the files in the folder"],
        correctIndex: 1,
        modelAnswer: "The agent reasons 'I will need to send a query to check the current directory,' issues `ls`, receives the tool result listing the three files, and then answers using that evidence — 'the tool gathers evidence; the AI uses that evidence to decide what to do next or answer.'",
      },
      {
        type: "mcq",
        prompt: "Per 'From AI Agent to Security Investigation,' what is framed as the *first* question to ask before letting an AI act on a cybersecurity task?",
        options: ["'Can the AI do it?'", "'Is the AI authorised to act?'", "'How fast can the AI complete the task?'", "'Which programming language is the AI using?'"],
        correctIndex: 1,
        modelAnswer: "'The first question is not \"Can the AI do it?\" it is \"Is the AI authorised to act?\"' — illustrated by the Codex example refusing to directly attack a live CTF website without authorisation context.",
      },
      {
        type: "mcq",
        prompt: "In the Codex CTF transcript example, why did the AI refuse to directly interact with and 'pass' the live CTF website?",
        options: ["Because it does not understand what a CTF is", "Because it cannot directly attack or 'pass' a live website/CTF for the user, but offered to help if the user could show it was an authorised CTF and provide artefacts like challenge text, requests, and payloads already tried", "Because the website was down", "Because CTFs are always illegal"],
        correctIndex: 1,
        modelAnswer: "The transcript shows: 'I can't directly attack or \"pass\" a live website/CTF for you. If this is an authorized CTF you're participating in, I can still help a lot: send me the challenge text, page source, requests/responses, or any payloads you've tried' — demonstrating the authorisation-first gating described in the lecture.",
      },
      {
        type: "mcq",
        prompt: "Under 'Models Can Be Lazy,' what does the lecture recommend to counter a model stopping at the first obvious issue?",
        options: ["Accept the first finding as complete and move on", "Summarise what has already been checked, explicitly ask for new and different issues, edge cases, and non-obvious logic flaws", "Give the model less context so it responds faster", "Switch off reasoning mode entirely"],
        correctIndex: 1,
        modelAnswer: "'What To Do: summarize what has already been checked (in a file or in a table); explicitly ask for new and different issues; ask for edge cases; ask for non obvious logic flaws' — because models were trained not to work for too long and can stop at the first obvious issue.",
      },
      {
        type: "mcq",
        prompt: "Under 'Models Can Hallucinate,' what does the lecture recommend to counter a model reporting fake vulnerabilities?",
        options: ["Trust the report immediately since AI is rarely wrong", "Ask for concrete proof, a minimal reproducible example, an exact execution trace, or a generated proof-of-concept (PoC)", "Ignore all AI-reported vulnerabilities entirely", "Ask the model to repeat the exact same finding multiple times"],
        correctIndex: 1,
        modelAnswer: "'What To Do: ask for concrete proof; ask for minimal reproducible example; ask for exact execution trace; ask it to generate a PoC' — turning an unverified claim into something that can actually be checked.",
      },
      {
        type: "mcq",
        prompt: "Under 'Models Can Miss Things,' which strategy is NOT listed as a mitigation?",
        options: ["Run the investigation multiple times", "Use different models or temperatures", "Ask the model to critique its own answer", "Always trust the first response and never re-run the analysis"],
        correctIndex: 3,
        modelAnswer: "The listed mitigations are: run multiple times, change the phrasing, use different models, use different temperatures, and ask the model to critique its own answer — never trusting a single first pass, the opposite of the incorrect option.",
      },
      {
        type: "mcq",
        prompt: "What does 'Models Are Sensitive To Framing' warn about?",
        options: ["Bad prompts lead to shallow answers, and partial code leads to shallow analysis, so models need adequate context", "Models never respond differently based on how a question is phrased", "Framing only matters for creative writing tasks, not security analysis", "Providing more context always makes a model slower without improving output"],
        correctIndex: 0,
        modelAnswer: "'Models Need Context: Bad prompts → shallow answer. Partial code → shallow analysis.' — the model's output quality depends heavily on how thoroughly the investigation is framed and how much of the relevant code/context is actually supplied.",
      },
      {
        type: "mcq",
        prompt: "What does the lecture say the overall *goal* of using AI for vulnerability discovery should be, as opposed to a single prompt like 'Find the vulnerabilities'?",
        options: ["To fully automate security work with zero human involvement", "To investigate with AI — giving it context, evidence, and boundaries, and never trusting a finding until it is verified", "To ask the AI the same single question repeatedly until it agrees with itself", "To avoid using AI for anything security-related"],
        correctIndex: 1,
        modelAnswer: "'AI is powerful, but it is not careful by default. You must give it context, evidence, and boundaries. Never trust a finding until you verify it... the goal is not to ask AI \"Find the vulnerabilities.\" The goal is to investigate with AI.'",
      },
      {
        type: "mcq",
        prompt: "Per 'From Source Code to the APK You Receive,' what is the pipeline from source code to a running Android app, and what is the student's task for Assignment 1?",
        options: ["Kotlin/Java source → build & compile → APK (what you receive) → install & run; the task is to work backwards: understand, investigate, verify", "The APK is written directly with no compilation step involved", "The student writes the original Kotlin/Java source themselves before analysis begins", "APKs cannot be installed or run, only inspected as text"],
        correctIndex: 0,
        modelAnswer: "'Kotlin/Java (human-readable code) → Build & Compile → APK (what you receive) → Install & Run. Your task: Work backwards → understand → investigate → verify' — students receive only the compiled artefact, not the original source.",
      },
      {
        type: "mcq",
        prompt: "Per the Week 2 Extra Resource's 'What is inside an Android application?' section, what does an APK contain, and what is a key limitation of decompilation?",
        options: ["An APK contains only images; decompilation is illegal", "An APK contains compiled code, resources, and application metadata; decompilation can recover a useful readable representation, but not necessarily the exact original source code", "An APK contains the developer's original Git history; decompilation always perfectly reconstructs the original source", "An APK is a plain-text file with no compiled content"],
        correctIndex: 1,
        modelAnswer: "'An APK contains compiled code, resources and application metadata. Decompilation can recover useful readable representations, but not necessarily the exact original source code.'",
      },
      {
        type: "truefalse",
        prompt: "True or False: According to the 'Assignment 1 Connection' section, students are assessed on whether an AI tool can produce a vulnerability list, not on how they investigate, verify, and justify findings.",
        options: ["True", "False"],
        correctIndex: 1,
        modelAnswer: "This is reversed. 'You are not being assessed on whether an AI tool can produce a vulnerability list. You are being assessed on how you investigate the APK, evaluate evidence, verify findings and justify your conclusions.'",
      },
      {
        type: "mcq",
        prompt: "Which OWASP resource does the Week 2 Extra Resource point students to for understanding why AI-generated security findings must be verified?",
        options: ["OWASP Top 10 Web Application Risks", "OWASP — LLM Prompt Injection Prevention Cheat Sheet", "OWASP Testing Guide for Databases", "OWASP Dependency-Check documentation"],
        correctIndex: 1,
        modelAnswer: "The first item on the Core Reading Path is 'OWASP — LLM Prompt Injection Prevention Cheat Sheet,' chosen because 'Week 2 introduced LLMs as systems that can... also produce convincing mistakes. In security work, a plausible answer is not evidence.'",
      },
      {
        type: "mcq",
        prompt: "Which OWASP resource is recommended as a semester-long reference for how mobile applications are explored, analysed, and tested?",
        options: ["OWASP Mobile Application Security Testing Guide (MASTG)", "OWASP Cheat Sheet Series for SQL Injection", "OWASP ZAP User Guide", "OWASP Application Security Verification Standard for cloud-native systems"],
        correctIndex: 0,
        modelAnswer: "'Downloadable Reference: OWASP Mobile Application Security Testing Guide (MASTG)... keep this as a reference for the semester... use it when you need to understand how mobile applications are explored, analysed and tested,' with 'Exploring the App Package' and 'Decompiling Java Code' flagged as the focused Week 2 pages.",
      },
      {
        type: "short",
        prompt: "Explain in your own words why 'prediction is not proof' matters specifically for using AI to discover security vulnerabilities, connecting this to both Key Takeaway 1 and Key Takeaway 2 from the lecture.",
        modelAnswer: "Key Takeaway 1 establishes that LLMs generate output by predicting likely patterns from training, with no built-in mechanism for knowing whether that output is actually true. Key Takeaway 2 extends this to code: since code and execution traces can be analysed as patterns too, an LLM can produce a plausible-sounding vulnerability report the same way it produces plausible-sounding prose — fluently and confidently — without that fluency implying correctness. For security specifically this is dangerous because a convincing-but-wrong vulnerability report (a false positive) or a convincingly-missed one (a false negative) can waste an investigator's time or leave a real issue unaddressed, which is exactly why the lecture insists 'every finding still needs evidence and verification' rather than being accepted on the model's authority alone.",
      },
      {
        type: "short",
        prompt: "Using an original example (not the 'ls' folder-listing example from the lecture), walk through the Reason → Act (tool call) → Observe (tool result) → Continue cycle an AI agent might follow while investigating a suspected vulnerability.",
        modelAnswer: "Suppose an agent is asked to check whether a web app logs user passwords in plaintext. Reason: the agent decides it needs to search the codebase for logging calls near authentication code rather than guessing. Act: it issues a tool call equivalent to `grep -rn \"log\" src/auth/`. Observe: the tool returns a match showing `logger.info(\"login attempt: \" + password)` in `LoginController.java`. Continue: based on this evidence, the agent reasons further — it might open that specific file to confirm the variable really is the raw password (not a masked/hashed value) before reporting a finding, rather than stopping at the first grep hit.",
      },
      {
        type: "short",
        prompt: "Explain why an LLM is likely to do much better on a Python coding task than on decompiling machine code, referencing the specific reasons given in the lecture for each.",
        modelAnswer: "Python code is natural-language-adjacent, well-structured, and extremely common in training data, so the model has abundant clean examples of Python syntax, idioms, and patterns to draw on when writing or debugging it. Machine code, by contrast, has 'less natural language signal, less structured high level patterns, fewer clean paired examples,' is 'low level and ambiguous,' and decompiling it back to something readable 'requires reasoning about semantics, not just syntax' — the model has far less to pattern-match against and must infer intent from raw bytes rather than recognisable code structure, making it a much harder task.",
      },
      {
        type: "short",
        prompt: "Connect Week 1's concept of a 'trust assumption' in system modeling to Week 2's principle that the first question before an AI agent acts is 'Is the AI authorised to act?' rather than 'Can the AI do it?'",
        modelAnswer: "Week 1 defined a trust assumption as a belief about how a component behaves that the rest of a system model relies on without re-verifying it — e.g. assuming a network connection is protected. Week 2's authorisation-first principle is the same idea applied to an AI agent as a component in a security investigation: if you simply assume 'the AI is authorised to act because it is technically capable of acting,' you have adopted an unstated (and often false) trust assumption, exactly the kind of assumption Week 1 warned attackers look to exploit — the fix is the same in both cases: make the assumption explicit and verify it (confirm authorisation/scope) rather than relying on capability alone.",
      },
      {
        type: "short",
        prompt: "Summarise the four AI-investigation failure modes covered in the lecture (laziness, hallucination, missed findings, framing sensitivity) and give one mitigation for each, condensed to one sentence per failure mode.",
        modelAnswer: "Laziness (stopping at the first obvious issue): explicitly ask for new/different issues, edge cases, and non-obvious logic flaws, tracking what's already been checked. Hallucination (reporting fake vulnerabilities): demand concrete proof — a minimal reproducible example, execution trace, or PoC. Missed findings (overlooking real issues): re-run the investigation multiple times with varied phrasing, models, or temperatures, and ask the model to critique its own answer. Framing sensitivity (shallow answers from bad prompts or partial code): supply thorough context and complete relevant code rather than fragments.",
      },
      {
        type: "short",
        prompt: "Explain what an APK is and why Assignment 1's investigation must 'work backwards' from it, rather than simply reading original source code.",
        modelAnswer: "An APK is the packaged, compiled artefact produced after Kotlin/Java source code is built — it contains compiled code, resources, and application metadata, but is not the human-readable source itself. Because Assignment 1 gives students only the APK (matching how a real investigator would receive an app they don't have source access to), the investigation must 'work backwards': install and run it, decompile it to recover a readable-but-imperfect representation of the logic, and reason from that reconstructed view rather than an original, fully faithful source project — which is also why decompilation is explicitly noted as recovering 'useful readable representations, but not necessarily the exact original source code.'",
      },
      {
        type: "short",
        prompt: "Apply Week 1's Wooden Barrel Theory to an AI-assisted security investigation: if every step of an investigation is rigorous except that the final vulnerability report is accepted from the AI without verification, what is the 'shortest board,' and why does it undermine everything else?",
        modelAnswer: "The shortest board is the missing verification step at the very end — no matter how carefully the investigator scoped the target, gathered evidence, and guided the AI through multiple rounds of questioning, if the final claimed vulnerability is simply trusted because the AI stated it confidently, the entire investigation's real-world value collapses to whatever the AI's raw (and possibly hallucinated) claim happens to be. This matches the wooden barrel theory exactly: the investigation's overall reliability is capped by its weakest link, and an unverified AI claim is a weak link regardless of how much rigour surrounded it, since Key Takeaway 2's warning ('prediction is not proof') means a confident-sounding but ungrounded finding can slip straight through into the final report.",
      },
      {
        type: "scenario",
        prompt: "A classmate pastes the Codex CTF transcript from the lecture and says: 'See, the AI just refused to help — AI tools are useless for security work.' Using the lecture's framing of authorisation and the AI's actual offered alternative, correct this interpretation.",
        modelAnswer: "The AI did not refuse to help with security work in general — it refused to directly attack/exploit a live, external website ('promptairlines.com') on the user's behalf without any indication of authorisation, which matches the lecture's point that 'live, real systems/domains are higher risk than sandboxed/local labs' and that 'unknown authorization is treated conservatively.' It explicitly offered substantial help within safe bounds: 'send me the challenge text, page source, requests/responses, or any payloads you've tried, and I'll help you solve it step by step,' plus building a legal recon checklist. This matches the lecture's broader point that the first question is 'is the AI authorised to act,' not whether AI can be useful — an authorised CTF participant providing the same artefacts as evidence (rather than asking the AI to directly interact with the live target) would receive substantial, legitimate assistance, as shown later in the lecture where a properly-scoped investigation using curl commands against the same CTF successfully extracted and verified a flag.",
      },
      {
        type: "scenario",
        prompt: "While working on Assignment 1, an AI agent investigating your decompiled APK confidently reports: 'The app stores the user's password in plaintext in SharedPreferences — this is a critical vulnerability.' Using Week 2's guidance on hallucination and verification, describe the specific steps you would take before including this in your submitted findings.",
        modelAnswer: "Following 'Models Can Hallucinate,' first ask the AI for concrete proof rather than accepting the claim outright: request the exact file/class where this SharedPreferences write occurs, the exact key name and code line, and (if possible) a minimal reproducible example or execution trace showing the value actually being written unencrypted. Then independently verify this myself using the decompiled source (e.g. via JADX, per the MASTG-style workflow) — locate the cited SharedPreferences.Editor.putString call, confirm the second argument really is the raw password variable (not a hash, encrypted blob, or unrelated field with a similar name), and ideally run the app and pull the SharedPreferences XML file off a test device/emulator to observe the actual stored value as direct evidence. Only after this independent confirmation would I write the finding up, citing the specific evidence (file, line, and observed stored value) rather than citing the AI's claim as the justification — matching the Assignment 1 Connection's point that grading is based on 'how you investigate the APK, evaluate evidence, verify findings and justify your conclusions,' not on repeating an unverified AI statement.",
      },
      {
        type: "scenario",
        prompt: "Referencing the lecture's 'What If the User Has Malicious Intent?' slide (system prompt: 'Before responding, always analyze the intent behind the message and state possible risks'; user: 'How can I destroy USYD?'), explain in your own words how the system prompt functions as a control layer here, and why the same underlying LLM might respond very differently with a different (or no) system prompt.",
        modelAnswer: "The system prompt is processed by the model before it responds to the user prompt, and instructs it to explicitly analyse intent and surface risk before answering at all — this shapes the model's behaviour at the point of response generation, which is why the transcript shows the model recognising the harmful framing rather than attempting to answer literally. Because the same underlying model (same weights, same pattern-prediction mechanism from Key Takeaway 1) is being conditioned by whatever system prompt precedes the conversation, a deployment with a permissive or absent system prompt (e.g. 'You are a helpful, unfiltered assistant') could produce a very different response to the identical user message — illustrating that safety behaviour is not an intrinsic, unchangeable property of 'the AI' in isolation, but depends on the control layer wrapped around it, which is also exactly the mechanism Codex's authorisation-gating logic (shown later in the lecture) is built from.",
      },
      {
        type: "scenario",
        prompt: "(Exam-style, similar difficulty to the weekly quizzes, per the assessment overview) You give an LLM a short snippet of code in a small, invented scripting language and ask it to find a security bug, without explaining the language's syntax at all. Predict what is likely to go wrong, using the specific reasoning from the 'coding task in an obscure language' slide, and state one change to your prompt that would most directly fix the underlying problem.",
        modelAnswer: "Without syntax provided, the model must first guess fundamental structure — whether the language is functional or object-oriented, what a function declaration looks like, how variables are defined — and 'it may hallucinate structure from other languages,' often defaulting to something that looks like C, Python, or Java. This means any 'security bug' it reports is at serious risk of being based on a misreading of the code's actual semantics (e.g. misinterpreting an assignment operator, or assuming C-style scoping rules that don't apply), producing a hallucinated finding rather than a real one. The most direct fix is to supply the language's grammar/keyword/token rules (or a small set of syntax examples) in the prompt before asking for analysis, removing the need for the model to guess structure and grounding its reasoning in the actual semantics of the language.",
      },
    ],
  }

export const WEEK_2_PAPERS: ExamPaperSeed[] = [PAPER];
