import type { ExamPaperSeed } from "../types";

const PAPER: ExamPaperSeed = {
  course: "INFO5995",
  week: 3,
  paperNumber: 1,
  title: "Week 3 Practice Paper",
  topics:
    "Mobile security in the age of AI; Android/iOS market share, AOSP vs proprietary Google Mobile Services; Android as gatekeeper (sandbox, intents, permissions); AOSP layered architecture (Apps/APIs, Framework/System Services, Android Runtime, HAL, Linux Kernel) and trust levels; threat classification (hardware, runtime, gray zone); APK structure (AndroidManifest.xml, classes.dex, res/assets, META-INF) and decompilation with JADX; never store secrets client-side; Activities, Services, Broadcast Receivers, Content Providers; explicit vs implicit Intents; AndroidManifest intent filters, MAIN/LAUNCHER/exported; deep links and untrusted input validation; mobile agents (Observe-Decide-Act-Repeat), UI tree; FitLife AI in-class case study; Assignment 1 (SafeCampus APK) investigation practice and authorisation scope; connections to Week 1 (trust assumptions, Bybit) and Week 2 (AI agent authorisation, verification)",
  sourceFiles: [
    "lecture/Week03-Mobile Security.pdf",
    "lecture/INFO5995_Week_3_Extra_Resources.pdf",
    "lecture/Week 03 - Introducti-s2-low.transcript.md",
  ],
  questions: [
    {
      type: "mcq",
      prompt: "Why does the lecture argue mobile security still matters in the age of AI?",
      options: [
        "AI does not replace mobile security — it creates new actors (like AI agents) that can interact with mobile systems, so the existing security model still matters",
        "AI eliminates the need for mobile security entirely, since fully autonomous threat detection now runs at the model layer instead of on the device itself",
        "AI security concerns are confined to desktop and server environments, so mobile-specific protections were never really relevant to begin with",
        "Mobile security became irrelevant once AI assistants were introduced, because assistants now mediate every sensitive interaction on the user's behalf",
      ],
      correctIndex: 0,
      modelAnswer: "\"AI does not replace mobile security, it creates new actors that can interact with mobile systems.\"",
    },
    {
      type: "mcq",
      prompt: "The lecture frames a shift in how we think about who or what accesses our phone data, in light of AI agents. What is that shift?",
      options: [
        "From \"what can access our data\" back to \"who is tapping our phone\" — a return to earlier physical-surveillance concerns",
        "From asking \"who can access our data\" to also asking \"what can access our data\" — AI agents are a new class of actor",
        "From caring about access at all to no longer caring about access, since encryption is now assumed to make the question moot",
        "From physical threats like device theft to purely legal and contractual threats around data ownership",
      ],
      correctIndex: 1,
      modelAnswer: "\"Earlier days, we used to think who can access our data or who is tapping our phone. But now we are also thinking like what can access our data, right? So the question is now from who to what.\" AI agents are a new class of actor that can access phone data alongside people.",
    },
    {
      type: "mcq",
      prompt: "Roughly what share of the global smartphone market does Android hold, and why does the lecture focus on it?",
      options: [
        "~30%; because it's the OS with the strongest built-in security track record among the two major platforms",
        "~99%; because iOS is treated as a negligible niche platform with almost no real installed base",
        "~70%; because that is the majority of mobile users, so the lecture focuses on where most people/data are",
        "~50%; split evenly with iOS, so the lecture treats both platforms as equally weighted case studies",
      ],
      correctIndex: 2,
      modelAnswer: "\"70% of the users or mobile use Android... we will try to focus on like, you know, the majority.\"",
    },
    {
      type: "mcq",
      prompt: "Google provides AOSP (the Android core) as free and open source. According to the lecture, why isn't all of Android open source?",
      options: [
        "Because Android has never actually been open source at all, and AOSP itself is a proprietary Google internal codebase",
        "Because each hardware vendor is legally required by their manufacturing contracts to keep their forked code closed",
        "Because open-sourcing code makes phones measurably slower, so vendors close parts of it purely for performance reasons",
        "Because Google Mobile Services (GMS) — the proprietary layer bundled on top of AOSP by Google — is not open source, even though the AOSP core is",
      ],
      correctIndex: 3,
      modelAnswer: "\"Google is giving AOSP as a core, but Google Mobile Service is not open source.\" AOSP itself is free (a strategy for wide adoption), but GMS is proprietary.",
    },
    {
      type: "mcq",
      prompt: "When Samsung builds its phones on top of AOSP, what does the lecture say Samsung adds?",
      options: [
        "An additional security layer (Knox) on top of AOSP's basic security foundation, plus its own UI (One UI)",
        "Nothing at all — Samsung ships AOSP completely unmodified, relying entirely on Google's default configuration",
        "A full replacement of the Linux kernel with an entirely Samsung-authored kernel built from scratch",
        "Removal of AOSP's sandboxing feature entirely, to allow noticeably faster switching between running apps",
      ],
      correctIndex: 0,
      modelAnswer: "\"When Samsung actually takes AOSP as foundation, it adds... added layer of security using Knox,\" on top of AOSP's basic permission/sandbox security, plus its own UI (One UI) for a personalised feel.",
    },
    {
      type: "mcq",
      prompt: "Android is described as \"the gatekeeper.\" Which three mechanisms does it use to control what crosses the boundary between an app and protected destinations (other apps / system resources)?",
      options: [
        "Firewalls (blocks network traffic), antivirus (scans for malware), and encryption (protects stored data)",
        "Sandbox (keeps apps separated), Intents (controls app-to-app messages), Permissions (controls access to resources)",
        "Passwords (unlocks the device), biometrics (verifies identity), and PINs (a fallback unlock method)",
        "VPN (routes traffic through a tunnel), proxy (relays requests), and DNS filtering (blocks known-bad domains)",
      ],
      correctIndex: 1,
      modelAnswer: "Matches the \"Android is the gatekeeper\" slide: 1. Sandbox — keeps apps separated; 2. Intents — controls app-to-app messages; 3. Permissions — controls access to resources.",
    },
    {
      type: "mcq",
      prompt: "The lecture gives a real-world analogy for the app sandbox. Which is it?",
      options: [
        "A hotel where every guest is issued the same master key, so any room can be opened by anyone staying there",
        "A single open-plan office where every desk is visible and reachable by every other employee at all times",
        "A 10-storey building where each app owns its own separate unit/space, and no other app can access another unit's data",
        "A locked safe that only the phone's manufacturer holds the combination to, with no other party ever granted access",
      ],
      correctIndex: 2,
      modelAnswer: "\"Think of the mobile app as a 10-story building, and each of these app owns one unit... All their data will be in their Sandbox, and no other app can access those data.\"",
    },
    {
      type: "mcq",
      prompt: "According to the lecture, can two apps (e.g. WhatsApp and Instagram) communicate directly with each other by default?",
      options: [
        "Only if both apps are made and signed by the same company, since shared authorship implies shared trust",
        "Only over Wi-Fi, never over mobile data, because Android treats mobile-data connections as inherently untrusted",
        "Yes, always, since being installed on the same physical device is treated as sufficient grounds for trust",
        "No — apps do not trust each other by default; Android mediates all communication through controlled mechanisms like intents",
      ],
      correctIndex: 3,
      modelAnswer: "\"Apps do NOT trust each other. Android is the mediator.\" Direct app-to-app access is blocked; a controlled mechanism such as an intent is required.",
    },
    {
      type: "mcq",
      prompt: "In the AOSP layered architecture (App/API to Framework/System Services to Android Runtime to HAL to Linux Kernel), what does the Hardware Abstraction Layer (HAL) do?",
      options: [
        "It acts as a translator/standard interface so Android doesn't need to know the specific hardware (e.g. camera, Bluetooth chip) each vendor uses",
        "It stores the user's saved passwords in an encrypted vault shared across every installed app",
        "It replaces the need for the permissions system entirely, granting hardware access automatically to any app",
        "It is where all app source code is stored, unminified, before the compilation step runs",
      ],
      correctIndex: 0,
      modelAnswer: "\"The HAL actually works kind of like a translator... a standard interface for hardware implementation,\" so Android doesn't need to bother about which specific camera/Bluetooth hardware different phones use.",
    },
    {
      type: "mcq",
      prompt: "Per the trust-level table (apps = lowest, framework services = medium, native services/HAL = high, kernel = highest), why does the lecture say \"more privilege means more risk\"?",
      options: [
        "Higher layers are statistically attacked first in practice, so the lecture argues they actually need the least added protection",
        "A component with more privilege can do more if compromised, so compromising it causes greater harm — e.g. a compromised kernel affects every app on the device, not just one",
        "Privilege level and security risk are treated as entirely unrelated variables in Android's overall design",
        "Only the kernel layer can ever realistically be attacked; individual apps are said to never be compromised",
      ],
      correctIndex: 1,
      modelAnswer: "\"If a Linux kernel is compromised... everything is gone\" — versus a compromised single gaming app, which is a much smaller impact; more privileged components cause more harm when broken.",
    },
    {
      type: "mcq",
      prompt: "A phone is plugged into a compromised public USB charging station (\"juice jacking\"). Per the lecture's threat classification, which category does this fall into?",
      options: [
        "Runtime attack — the malicious code executes inside an already-running app process on the phone",
        "Gray zone — a legitimately granted permission is simply being used more broadly than necessary",
        "Hardware attack — the device/connection itself is untrusted, and the attack begins at physical connection",
        "Denial of service — the charging station is deliberately overwhelming the phone's power circuitry",
      ],
      correctIndex: 2,
      modelAnswer: "\"Juice jacking: a compromised public USB charging station... the attack starts when the phone is physically connected\" — a hardware attack.",
    },
    {
      type: "mcq",
      prompt: "A crafted malicious input triggers a buffer overflow that corrupts memory in a running app. Per the lecture's threat classification, which category is this?",
      options: [
        "Hardware attack — the attack originates from the physical device or connection, not the running code",
        "Gray zone — the app has a legitimately granted permission that is simply being used too broadly",
        "Social engineering — the attacker is manipulating a person into taking an unsafe action voluntarily",
        "Runtime attack — software fails while it is executing, and the bug can break security boundaries",
      ],
      correctIndex: 3,
      modelAnswer: "\"Runtime attack: software fails while it is running... buffer overflow, use-after-free, type confusion... can corrupt memory and break security boundaries.\"",
    },
    {
      type: "mcq",
      prompt: "The lecturer describes their own phone's permissions being handled by their son, who just taps \"allow\" for everything instead of choosing \"only while using the app.\" Which Week 3 concept does this best illustrate?",
      options: [
        "The gray zone — an app can have a legitimately granted permission, but whether that access is necessary, proportionate, and used responsibly is a separate question from whether it was \"allowed\"",
        "A runtime attack — the son's phone is running compromised code that exploits a memory-corruption bug",
        "Juice jacking — the son is charging the phone from an untrusted public USB port while tapping allow",
        "HAL translation — the son's taps are being mistranslated by the hardware abstraction layer's interface",
      ],
      correctIndex: 0,
      modelAnswer: "Matches the \"gray zone\" slide: \"permitted does not always mean harmless... the security question is not only 'did the user allow it?' it is also 'was the access necessary, proportionate and used responsibly?'\"",
    },
    {
      type: "mcq",
      prompt: "What are the four main parts security analysts focus on inside an APK?",
      options: [
        "Login.java, Dashboard.java, Profile.java, Settings.java — the app's individual screen-controller source files",
        "AndroidManifest.xml, classes.dex, res/ + assets/, META-INF/ — the four parts the lecture names",
        "source.zip, build.gradle, README.md, LICENSE — the raw project files a developer works with before building",
        "kernel.img, boot.img, system.img, vendor.img — the OS-level image files flashed onto the device firmware",
      ],
      correctIndex: 1,
      modelAnswer: "Matches the SafeCampus.apk breakdown: AndroidManifest.xml (components/permissions), classes.dex (compiled code), res/ + assets/ (screens/images/packaged files), META-INF/ (signing/certificate info).",
    },
    {
      type: "mcq",
      prompt: "Why do analysts decompile classes.dex rather than reading it directly?",
      options: [
        "classes.dex is encrypted by default, so it cannot be opened in any form without a decryption key",
        "Decompiling is imposed as a legal requirement that every analyst must complete before installing any app",
        "classes.dex is compiled bytecode, not readable source; a decompiler (e.g. JADX) converts it into readable source-like code so the app's logic can be inspected — though this is not guaranteed to exactly match the original source",
        "classes.dex only contains packaged images and media assets, with no executable code inside it at all",
      ],
      correctIndex: 2,
      modelAnswer: "\"To understand classes.dex, we decompile it into readable source-like code. This helps us inspect the app's logic, but it does not recreate the exact original source code.\"",
    },
    {
      type: "mcq",
      prompt: "The lecture explains why a hardcoded password will always be recoverable by decompilation, even though the exact original source code can't be perfectly reconstructed. What is the reasoning?",
      options: [
        "JADX ships a special built-in password-detection AI feature that scans specifically for credential-shaped strings",
        "Passwords are always stored directly in the AndroidManifest.xml, where any analyst can read them in plain text",
        "Hardcoded passwords are automatically encrypted by the Android runtime the moment the app is compiled",
        "A hardcoded password is a static value stored at a fixed memory address, not an instruction — so a decompiler can always recognise and recover the literal value, unlike more complex control-flow logic",
      ],
      correctIndex: 3,
      modelAnswer: "\"This password is not an instruction, it's a static value... any decompiler will know that here this value is being saved... if you have hard coded in your code, 100% of the time you're going to recover it through decompilation.\"",
    },
    {
      type: "mcq",
      prompt: "Which of the four main Android app components is this lecture's primary focus, and what does it represent?",
      options: [
        "Activities — the screens the user interacts with, combining a layout (XML) with controlling code (Java/Kotlin)",
        "Broadcast receivers — components that listen for and respond to system-wide or app-wide background alerts",
        "Content providers — components that expose an app's structured data as a shared database to other apps",
        "Services — components that run background tasks such as music playback without a visible user interface",
      ],
      correctIndex: 0,
      modelAnswer: "\"FOCUS: ACTIVITIES\" — \"Screens the user interacts with,\" e.g. Login, home, settings; an activity combines a screen layout (XML) with the code that controls it.",
    },
    {
      type: "mcq",
      prompt: "What is an Intent, in the lecture's own mental model?",
      options: [
        "A permanent, hardcoded link between two specific apps that, once created, can never be changed or removed",
        "A message Android delivers to request an action or open a destination (app/screen) — \"the request, not the destination\"",
        "A type of malware payload that hides itself inside an APK's compiled bytecode file",
        "The Android platform's rough equivalent of a network firewall rule that blocks unwanted traffic",
      ],
      correctIndex: 1,
      modelAnswer: "\"An Intent is the message Android delivers to another screen or app... The request, not the destination.\" The transcript adds: \"if I say intent is the data carrier, it will not be wrong.\"",
    },
    {
      type: "mcq",
      prompt: "What is the key difference between an explicit and an implicit intent?",
      options: [
        "Explicit intents can only be issued by pre-installed system apps; implicit intents are restricted to third-party user apps",
        "Explicit intents are defined as never carrying any payload data; implicit intents always carry a data payload",
        "Your code names the exact destination Activity directly (explicit) vs. your code describes only the action, and Android offers the user a choice of matching apps (implicit)",
        "Implicit intents are always inherently safer, since Android automatically checks and vets every implicit intent's target",
      ],
      correctIndex: 2,
      modelAnswer: "\"EXPLICIT INTENT: One exact destination... your code names the Activity directly. IMPLICIT INTENT: Android offers choices... your code describes the action—not the app.\"",
    },
    {
      type: "mcq",
      prompt: "The lecturer is asked \"which is more dangerous, explicit or implicit intent?\" What is the actual answer given?",
      options: [
        "Explicit is always the more dangerous type, since naming the target directly hands an attacker the exact component to attack",
        "Implicit is always the more dangerous type, since letting Android choose the destination removes the developer's control entirely",
        "Both are equally dangerous in literally every situation, with no exceptions the lecture is willing to carve out",
        "Neither type is inherently more dangerous by itself — it depends on context, e.g. whether the intent stays within the same app or crosses to a third-party app where control is lost once data is sent",
      ],
      correctIndex: 3,
      modelAnswer: "\"It is taking data to a different app... third party, you have no control over that. Once it is gone, it's gone... it really depends... Neither intent type is dangerous by itself.\"",
    },
    {
      type: "mcq",
      prompt: "What ultimately determines whether a path through an Intent is safe, per \"the real danger is an Activity with no lock\"?",
      options: [
        "Whether the target Activity checks who is allowed to start it (e.g. login/session authentication) before granting access — not the intent type itself",
        "Whether the incoming intent that reached the Activity was declared explicit or implicit in the calling code",
        "Whether the app's launcher icon uses a colourful design rather than a plain monochrome one",
        "Whether the physical device the app is installed on has been rooted by its owner",
      ],
      correctIndex: 0,
      modelAnswer: "\"Security depends on who can start the Activity and whether the Activity checks authentication,\" not on whether the calling Intent was explicit or implicit.",
    },
    {
      type: "mcq",
      prompt: "In AndroidManifest.xml, what combination identifies an app's public starting point — the screen shown when the app icon is tapped?",
      options: [
        "The SERVICE action combined with the RECEIVER category declared on a background component",
        "The MAIN action + LAUNCHER category, together with exported=\"true\"",
        "The PERMISSION and CATEGORY tags alone, with no action attribute required",
        "The META-INF signing directory combined with the compiled classes.dex bytecode file",
      ],
      correctIndex: 1,
      modelAnswer: "\"MAIN — starting action, LAUNCHER — appears in app launcher, exported=\\\"true\\\" — PUBLIC APP ENTRY POINT... Look for MAIN + LAUNCHER first.\"",
    },
    {
      type: "mcq",
      prompt: "A component's manifest entry has exported=\"true\". Per both the slides and the in-class payment-activity case study, what can be concluded from that fact alone?",
      options: [
        "The activity is definitely vulnerable, and payment data is provably being leaked to any app that reaches it",
        "Authentication on this activity has definitely already been bypassed by an unspecified third party",
        "Only that other apps can potentially start/reach this activity — whether that is actually a problem depends on whether the activity itself performs proper checks (e.g. authentication), which cannot be determined from the manifest alone",
        "The activity has been fully disabled by this flag and can no longer run under any circumstances",
      ],
      correctIndex: 2,
      modelAnswer: "\"exported=\\\"true\\\"... only means other apps can call this activity... does that mean it's a vulnerability?... No... you really need to know the context.\"",
    },
    {
      type: "mcq",
      prompt: "In the FitLife AI case study, the app tracks the user's precise location continuously even though it only needs location while the user is looking for nearby activities. Which specific privacy/security principle does this violate?",
      options: [
        "Non-repudiation — the ability to prove an action was taken by a specific verified user",
        "Availability — ensuring the app's location feature keeps working reliably without interruption",
        "Authentication — verifying that the person requesting location data is really who they claim to be",
        "Data minimization — only collecting what's genuinely necessary for the feature to work",
      ],
      correctIndex: 3,
      modelAnswer: "\"At 10 AM, FitLife tracks precise location continuously, but only needs it for nearby activities... Data minimization. Not availability, not authentication.\"",
    },
    {
      type: "mcq",
      prompt: "Still in the FitLife AI case study: a 4.9-star app with 10 million downloads requests location, camera, contacts, and activity permissions, and the user taps \"Allow.\" Per the lecture's own resolution of this question, what actually determines whether this is a warning sign — not the raw number of permissions requested, and not whether a competitor app requests the same permissions?",
      options: [
        "Whether each individual permission is actually necessary for the app's stated functionality",
        "Whether the app's launcher icon visually looks polished and trustworthy at a glance",
        "Whether the app happened to be downloaded from an official, vetted app store",
        "Whether the user personally read through the full terms and conditions before installing",
      ],
      correctIndex: 0,
      modelAnswer: "The clicker vote showed \"of course not the first one [number of permissions] and last one [competitor parity]\" — the real question is whether each permission is necessary, echoing the gray-zone principle.",
    },
    {
      type: "mcq",
      prompt: "A student asks whether hardcoded credentials found in SafeCampus's decompiled code still count as a vulnerability, even though the assignment build doesn't reach the internet. What does \"never store sensitive secrets in the client app\" imply about this?",
      options: [
        "It's not a real vulnerability at all, since the app never actually reaches out to the internet in this build",
        "It is still a real weakness — anyone who can decompile the APK can recover a hardcoded secret regardless of whether that specific build happens to call out to a live server, since compiled code is not secret",
        "Only vulnerabilities that can be shown to cause an actual, live financial loss count as real vulnerabilities",
        "Hardcoded credentials are described as only ever being a genuine problem on iOS, never on Android",
      ],
      correctIndex: 1,
      modelAnswer: "\"Compiled code is not secret... Never store sensitive secrets in the client app.\" Any hardcoded secret is 100% recoverable via decompilation regardless of the app's current network configuration.",
    },
    {
      type: "mcq",
      prompt: "The lecturer mentions that a student last semester \"tried to send packets to Singapore Airlines\" while working on this same assignment. What point does this anecdote illustrate, and how does it connect to Week 2?",
      options: [
        "That external commercial airlines generally have weak security and therefore make good practice targets for students",
        "That mobile apps are architecturally incapable of ever reaching real, live network endpoints from a phone",
        "That investigation must stay strictly within the authorised assignment scope — echoing Week 2's point that the first question before any AI/security action is not \"can it be done?\" but \"is it authorised?\"",
        "That Singapore Airlines specifically sponsors this course and pre-approved this exact kind of testing",
      ],
      correctIndex: 2,
      modelAnswer: "The anecdote is a cautionary tale about scope: testing against a real, live, unauthorised external system crosses the exact authorisation boundary Week 2 raised — \"the first question is not 'Can the AI do it?' it is 'Is the AI authorised to act?'\"",
    },
    {
      type: "mcq",
      prompt: "To make an outgoing GSM phone call from within an app, what does the lecture say the developer actually needs to do?",
      options: [
        "Write custom low-level driver code that directly controls the phone's cellular modem chip",
        "Recompile the entire Android Runtime with modem-calling support enabled at the framework level",
        "Nothing at all — outgoing GSM calls are said to require no declared permission whatsoever",
        "Declare the relevant permission (e.g. for the phone/microphone hardware) in the manifest — the underlying hardware-access code already exists in the HAL/driver layer",
      ],
      correctIndex: 3,
      modelAnswer: "\"Permissions for microphone, permissions for... the GSM chip... you just need permission. The code is already there in the hall [HAL].\"",
    },
    {
      type: "mcq",
      prompt: "How important does the lecturer rate the UI tree (page-navigation layout) when searching for vulnerabilities, on a low/medium/high scale?",
      options: [
        "Medium — not where you should spend most of your time, but it can hint at which pages have meaningful transitions between them",
        "Low — the lecturer treats it as essentially irrelevant background noise for security analysis",
        "High — the lecturer says it should be the very first and primary focus of any investigation",
        "The lecturer explicitly declines to give it any rating at all when asked",
      ],
      correctIndex: 0,
      modelAnswer: "\"How important is UI tree when you are searching for vulnerabilities? From low, medium and high. I will also rate it as medium.\"",
    },
    {
      type: "mcq",
      prompt: "What is the key distinction the lecture draws between an \"AI model\" and an \"AI agent\" (mobile agent)?",
      options: [
        "There is no real difference between the two terms; the lecture treats them as fully interchangeable",
        "An agent acts — it can access system resources and work on the user's behalf (e.g. tap, type, open apps), not just generate text",
        "A model is described as always strictly more capable at every task than an agent built around it",
        "Agents are described as only able to run on desktop computers, never on a mobile device",
      ],
      correctIndex: 1,
      modelAnswer: "\"It works for you, right? It acts, it can access your systems resources. It can really work on your behalf... That's why we call it like an agent.\"",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's specific caution about mobile agents and app icons, what should developers avoid doing?",
      options: [
        "Using colourful, high-contrast icon designs anywhere within the app's user interface",
        "Allowing icons to be tapped or otherwise interacted with by the user at all",
        "Putting meaningful or sensitive information in the names/labels of icons and UI elements, since an AI agent reads the underlying UI tree/labels, not just the visual image the way a human does",
        "Placing more than roughly ten distinct icons on any single screen of the app",
      ],
      correctIndex: 2,
      modelAnswer: "\"For you, it's just an icon. But AI agent know its name as well, the name of the icon. So don't save any meaningful critical data in your names of the icons as well.\"",
    },
    {
      type: "mcq",
      prompt: "What does the UI tree structure expose to a mobile agent that a human eye would treat as \"just an image\"?",
      options: [
        "The exact GPS coordinates of the phone, refreshed continuously in real time regardless of screen content",
        "The user's raw biometric fingerprint data captured directly from the device's sensor",
        "The phone's IMEI hardware identifier, exposed automatically as part of every UI element",
        "Structured, machine-readable data per element — its text label, type (e.g. button/image), whether it's clickable, and its screen bounds",
      ],
      correctIndex: 3,
      modelAnswer: "Matches the \"Runtime UI Tree\" slide fields: TEXT, TYPE, CLICKABLE, BOUNDS — \"the agent now knows: what is visible, what is clickable, where to act.\"",
    },
    {
      type: "mcq",
      prompt: "Why does the lecture warn that inputs passed through a deep link/API are \"a playground for hackers\"?",
      options: [
        "Because an attacker can enter malicious commands instead of expected input, and if the backend doesn't sanitize/validate that input, it can result in command injection or SQL injection",
        "Because deep links can only ever be triggered manually by the app's own original developer, no one else",
        "Because deep links are always transmitted encrypted, and encryption itself is treated as inherently untrustworthy",
        "Because deep links are said to bypass the Android sandbox entirely, for every single app on the device",
      ],
      correctIndex: 0,
      modelAnswer: "\"If you have ever played with APIs, you can pass your inputs as well... this is a playground for hackers. They can really start doing command injection... SQL injection... because you didn't filter out unnecessary inputs.\"",
    },
    {
      type: "truefalse",
      prompt: "True or False: Decompiled code produced by a tool like JADX is guaranteed to exactly match the original developer's source code.",
      options: ["True", "False"],
      correctIndex: 1,
      modelAnswer: "\"Decompiled code may not exactly match the original.\"",
    },
    {
      type: "truefalse",
      prompt: "True or False: The lecture's security takeaway is that if code is delivered to a user's device, you should assume someone can inspect it — so mobile apps can be reverse engineered and compiled code should never be treated as secret.",
      options: ["True", "False"],
      correctIndex: 0,
      modelAnswer: "\"If code is delivered to a user's device, assume that someone can inspect it. 1. Mobile apps can be reverse engineered. 2. Compiled code is not secret.\"",
    },
    {
      type: "truefalse",
      prompt: "True or False: A \"gray zone\" issue means an app was given a permission it was never authorised to have.",
      options: ["True", "False"],
      correctIndex: 1,
      modelAnswer: "\"An app may receive legitimate permission, but the amount of data collected and how it is used still matter\" — gray zone is about the proportionality/necessity of permitted access, not about unauthorized access.",
    },
    {
      type: "truefalse",
      prompt: "True or False: A deep link should always be validated, checked against the user's authentication/session, and — for sensitive actions — confirmed with the user before it's allowed to execute.",
      options: ["True", "False"],
      correctIndex: 0,
      modelAnswer: "\"SECURITY RULE: Validate input + check session + confirm sensitive actions\" — e.g. a transfer link must not send money merely because the screen opened.",
    },
    {
      type: "truefalse",
      prompt: "True or False: The lecture states that more privileged Android components (e.g. the Linux kernel) pose a lower security risk than less privileged components (e.g. a single app), because privileged components are harder to reach.",
      options: ["True", "False"],
      correctIndex: 1,
      modelAnswer: "It's the opposite — \"more privilege means more risk.\" A compromised kernel affects the whole device (\"everything is gone\"), while a compromised low-privilege app has far smaller impact.",
    },
    {
      type: "short",
      prompt: "Explain what \"Android as the gatekeeper\" means, naming the three specific mechanisms Android uses to control what crosses the boundary from an app to other apps or system resources.",
      modelAnswer: "Apps start isolated from every other app by default (\"safe by default\"); Android acts as the gatekeeper/mediator between an app and protected destinations (other apps, system resources like camera/files/location) using three mechanisms: (1) Sandbox — keeps apps separated; (2) Intents — controls app-to-app messages; (3) Permissions — controls access to resources. Missing or misconfigured controls at any of these points is \"where things go wrong,\" and vulnerabilities begin.",
    },
    {
      type: "short",
      prompt: "Using the AOSP layered architecture (Apps+APIs, Framework+System Services, Android Runtime, HAL, Linux Kernel), trace what happens when an app requests to take a photo, and explain why this layering matters for security.",
      modelAnswer: "The app asks Android to perform an action rather than controlling the device directly: Camera app requests through the Camera API, Android Framework checks the permission, the HAL translates the request for the specific device's hardware, and the Camera hardware executes it. Each layer controls what the layer above it can do, so a request has to pass through multiple independent checkpoints (\"doors\") rather than a single one — to control the whole phone, malicious code must escape its sandbox and cross several of these boundaries, not just one.",
    },
    {
      type: "short",
      prompt: "Explain why the lecture says \"never store sensitive secrets in the client app,\" using the technical reasoning about how decompilers recover static values.",
      modelAnswer: "A hardcoded secret like a password is stored as a static value at a fixed memory address rather than as executable control-flow logic — a decompiler doesn't need to guess complex logic to recover it, it can simply read the static value directly from where it's saved. Because compiled code delivered to a user's device can always be inspected/decompiled, any secret embedded in the client APK is 100% recoverable, regardless of how the rest of the app's logic is obfuscated — so secrets must live only on a trusted server, never inside the client.",
    },
    {
      type: "short",
      prompt: "Explain the difference between an explicit and an implicit Intent, and describe why the lecture is \"reluctant\" to declare one type more dangerous than the other in general.",
      modelAnswer: "An explicit Intent names its exact destination Activity directly in code (e.g. tapping Login sends the user straight to LoginActivity); an implicit Intent only describes the action, letting Android offer the user a chooser among matching apps (e.g. Share to Gmail/Photos/WhatsApp). Neither is inherently more dangerous — it depends on context, particularly whether the data stays within the same app (still worth checking, but you retain some control) or crosses to a different, third-party app (once sent, you have no control over it and can't undo it). Real danger comes from whether the receiving Activity checks authorisation, not from the Intent type itself.",
    },
    {
      type: "short",
      prompt: "A manifest shows a payment Activity with exported=\"true\". Explain what this fact alone does and does not tell an analyst, using the in-class case study discussion.",
      modelAnswer: "exported=\"true\" only means the Activity can potentially be started/reached by other apps — it is about reachability, not automatically about vulnerability. It does not by itself mean payment data is exposed, that the activity is vulnerable, or that authentication has been bypassed; a banking app's own payment screen may legitimately need to be reachable so a user can open it to pay. The analyst must go further and check whether the Activity actually performs the necessary authentication/session checks before showing sensitive information — context determines whether exported access is a real problem.",
    },
    {
      type: "short",
      prompt: "Describe the Observe, Decide, Act, Repeat loop that defines a mobile agent, and explain the specific security concern the lecture raises about UI element names/icons in this context.",
      modelAnswer: "A mobile agent is AI that repeatedly observes the screen and its UI elements, decides the next action, acts (tap/type/swipe/open), then observes the result and continues, looping until its task is complete. Because the agent reads the underlying UI tree — structured data like each element's text label, type, clickability, and screen bounds — rather than just seeing a picture the way a human does, sensitive information hidden in an icon's or element's name/label is visible to the agent even though a human user would only see the icon image. Developers should therefore never store meaningful or critical data in UI element names/labels.",
    },
    {
      type: "short",
      prompt: "A student found hardcoded credentials in SafeCampus's decompiled code, and asked whether it counts as a real vulnerability since the assignment build doesn't reach the live internet. Using the lecture's \"compiled code is not secret\" takeaway, explain why it still counts.",
      modelAnswer: "Whether or not this particular build calls out to a live server, a hardcoded secret is still fully recoverable by anyone who decompiles the APK — compiled code delivered to a device is never truly secret. The risk isn't contingent on the current network configuration; if that same credential were ever reused against a real, live system (or the code were redeployed with network access enabled), it would be immediately compromised. So hardcoded credentials remain a genuine finding worth reporting, independent of whether the sandboxed assignment build happens to reach the internet.",
    },
    {
      type: "short",
      prompt: "Using the FitLife AI case study's \"exported=true payment activity\" question and Week 1's \"trust assumption\" idea, explain why security analysts should never conclude \"exported=true, therefore vulnerable\" without further investigation.",
      modelAnswer: "Concluding \"exported=true, therefore vulnerable\" treats an assumption (that any externally reachable component is automatically unsafe) as a fact without verifying it — exactly the kind of unchecked trust assumption Week 1 warned about. Just like a system model's trust assumptions must be tested rather than accepted at face value, exported=\"true\" only establishes reachability; the analyst must still check the actual behaviour of the Activity — e.g. whether it authenticates the caller/session before showing protected information — before concluding whether that reachability is actually exploitable.",
    },
    {
      type: "scenario",
      prompt: "In the lecture's warm-up video, a person blindly follows an AI assistant's suggestions (asking a stranger \"Fred\" for help, then almost handing an unverified home address to a caller claiming to be police) purely out of habit and convenience, without questioning what was actually being requested. The lecturer's point was \"we should not be just using it because of the habit.\" Using Week 1's Bybit case, explain the underlying failure pattern this video shares with Bybit, and describe one concrete Week 3 practice a mobile app developer or investigator should apply to avoid it.",
      modelAnswer: "In Bybit, staff trusted what the approval UI displayed and acted on it without independently verifying what was actually being signed. The video shows the same underlying failure: a user follows the AI agent's suggestions purely out of habit/convenience, without pausing to verify what information is actually being requested or why — trusting the assistant's framing instead of checking the actual request. A Week 3-aligned defence: for any Android app, sensitive actions and screens (e.g. a payment or data-sharing screen reached via a deep link or Intent) must independently validate input, authenticate the user/session, and confirm sensitive actions explicitly, rather than trusting that the request reaching the screen is automatically legitimate — the same \"don't trust the display, verify independently\" principle Bybit lacked.",
    },
    {
      type: "scenario",
      prompt: "A fitness app requests camera, contacts, and continuous precise-location permissions, which the user grants. Its manifest also shows a \"FriendFinder\" Activity with exported=\"true\" that displays a user's live location to any caller that starts it, with no login/session check in the Activity's code. a) Name the specific privacy principle violated by using continuous precise location when the feature only needs location during active use. b) Explain, using the lecture's manifest/exported reasoning, why exported=\"true\" alone doesn't prove FriendFinder is vulnerable — but explain what specifically about this Activity's code does make it a real vulnerability here.",
      modelAnswer: "a) Data minimization — the app should only collect precise location while genuinely needed for the nearby-activity/friend-finding feature, not track it continuously. b) exported=\"true\" only means other apps can call/reach the FriendFinder Activity — that fact alone is not proof of a vulnerability, since a legitimately-reachable screen isn't automatically unsafe (e.g. a banking app's own payment screen may need to be reachable). What makes this a real vulnerability is the missing authentication/session check: because any caller can start FriendFinder and it never verifies who is asking or whether they're authorised to see this specific user's live location, any other app on the device can call it and read sensitive location data — exactly the \"Activity with no lock\" danger the lecture describes, where the risk comes from the missing check, not from exported access itself.",
    },
    {
      type: "scenario",
      prompt: "SafeCampus has a deep link, safecampus://transfer?amount=X&to=Y, that opens the transfer-confirmation screen and passes the amount and recipient straight into a backend query without any filtering. Using the lecture's deep-link security rule and its discussion of API/deep-link inputs being \"a playground for hackers,\" identify two distinct things that could go wrong here, and describe the three checks that should have been applied before this screen executed anything.",
      modelAnswer: "Two things that could go wrong: (1) an attacker could pass a malicious value instead of a plain amount/recipient (e.g. injection-style characters) which, if unsanitised, becomes a command run against the backend — SQL injection or command injection; (2) even with a well-formed amount/recipient, the link could trigger the transfer to actually execute the moment the screen opens, with no check that the requester is logged in/authorised, or without asking the user to confirm a sensitive money-moving action. The three checks the lecture requires before any deep link executes: (1) Validate — is the URL and its input the expected shape/type (e.g. sanitise special characters, validate the amount is a real number in range)? (2) Authenticate — is the user actually logged in and authorised for this account? (3) Confirm — for a sensitive action like a transfer, explicitly ask the user before executing it; a transfer link must not send money merely because the screen opened.",
    },
    {
      type: "scenario",
      prompt: "You are using an AI coding agent with terminal access to help decompile and investigate the SafeCampus APK for Assignment 1. Recall the lecturer's anecdote about a student who, last semester, tried to send network packets to Singapore Airlines while working on this same assignment. Using Week 2's authorisation-gating idea and Week 3's material, explain what went wrong in that anecdote and describe one concrete safeguard you'd put in place before letting your AI agent act.",
      modelAnswer: "What went wrong: the investigation crossed from the authorised, sandboxed assignment scope (the local SafeCampus APK) into an unauthorised, live, real-world target (an actual airline's systems) — exactly the boundary Week 2 warns about: \"the first question is not 'Can the AI do it?' it is 'Is the AI authorised to act?'\" Real/live systems are higher risk than sandboxed/local labs, and unauthorised action against them is not covered by coursework permission just because it happened while doing an assignment. Safeguard: before giving an AI agent terminal/network access during the investigation, explicitly scope and confirm what targets are in-bounds (the local decompiled APK and any files/servers the assignment explicitly provides) and treat any address, hostname, or endpoint the agent discovers in the code as something to inspect statically, never something to actually contact over the live network, unless it's confirmed as part of the sandboxed assignment environment.",
    },
    {
      type: "scenario",
      prompt: "Week 2 described an AI agent's Reason, Act, Observe, Continue loop when using a text-based tool like ls. Week 3 describes a mobile agent's Observe, Decide, Act, Repeat loop when interacting with a phone's UI. Compare these two loops: what is functionally the same between them, and what is the mobile-specific security concern Week 3 adds that Week 2's ls example doesn't raise?",
      modelAnswer: "Functionally the same: both are a closed loop where the agent gathers evidence from its environment (an ls result / the current screen's UI elements), decides what to do next based on that evidence, performs an action (a tool call / a tap-type-swipe), and then observes the outcome before continuing — evidence drives the next decision either way. Week 3's mobile-specific addition: a mobile agent doesn't just see a picture of the screen the way a person does — it reads the underlying UI tree, structured data including each element's text label, type, clickability, and bounds. This means UI metadata itself (e.g. sensitive information placed in an icon's or button's internal name/label) becomes part of the app's attack surface, exposed to automated inspection at scale in a way that a purely text-based tool loop like ls over a file listing does not raise.",
    },
  ],
};

export const WEEK_3_PAPERS: ExamPaperSeed[] = [PAPER];
