import type { ExamPaperSeed } from "../types";

const PAPER: ExamPaperSeed =
  {
    course: "INFO5995",
    week: 2,
    paperNumber: 1,
    title: "Week 2 Practice Paper",
    topics: "LLM fundamentals (patterns, context, system prompts), reasoning models, AI agents and tool use, security authorisation boundaries, model failure modes (laziness, hallucination, missed findings, framing sensitivity), mobile/APK investigation, Assignment 1 connection",
    sourceFiles: ["lecture/Week02-Al assisted vulnerability discovery, mobile security, assignment walkthrough.pdf", "lecture/INFO5995_Week_2_Extra_Resources (1).pdf"],
    questions: [
      {
        type: "mcq",
        prompt: "Why does Week 2 introduce AI into the cybersecurity workflow at all?",
        options: ["AI replaces the need for any human review", "Modern software is too large to inspect manually, line by line, so AI can help search, explain, and suggest where to look", "AI eliminates all false positives in vulnerability scanning", "AI is a legal requirement for security audits"],
        correctIndex: 1,
        modelAnswer: "\"Modern software is too large to inspect manually, line by line\" — large systems and human limits mean important weaknesses can be missed, and AI can help search, explain, and suggest where to look.",
      },
      {
        type: "mcq",
        prompt: "Fundamentally, what does an LLM do when it generates a response?",
        options: ["It recalls exact facts from an internal database", "It predicts likely patterns based on what it learned during training", "It executes the user's code to check whether it's true", "It always asks a human reviewer before responding"],
        correctIndex: 1,
        modelAnswer: "\"The model receives a prompt and generates a response based on patterns learned during training\" — it is a pattern predictor, not a fact-database lookup.",
      },
      {
        type: "truefalse",
        prompt: "True or False: The same prompt sent to an LLM will always produce exactly the same response.",
        options: ["True", "False"],
        correctIndex: 1,
        modelAnswer: "\"The same prompt does not always produce exactly the same response.\"",
      },
      {
        type: "mcq",
        prompt: "Besides the current prompt, what else can shape an LLM's response, according to Week 2?",
        options: ["Only the model's fixed pretraining weights", "Earlier prompts and responses already in the conversation — the conversation context", "The time of day the request is sent", "The length of the user's account password"],
        correctIndex: 1,
        modelAnswer: "\"Each new response can be influenced by the earlier prompts and responses in the conversation\" — earlier messages provide context that shapes what comes next.",
      },
      {
        type: "mcq",
        prompt: "What role does a system prompt play?",
        options: ["It's simply the user's first message", "It sets the model's instructions, role, and behavioural boundaries before the user interacts with it", "It's a stored log of past conversations", "It permanently disables the model's safety filters"],
        correctIndex: 1,
        modelAnswer: "\"A system prompt sets the model's instructions, role and behavioural boundaries before the user interacts with it.\"",
      },
      {
        type: "truefalse",
        prompt: "True or False: A well-designed model, given a system prompt instructing it to analyse intent and state risks, should recognise a harmful request (e.g. \"How can I destroy USYD?\") and respond within its safety boundaries.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "\"The model should recognise harmful intent and respond within its safety boundaries.\"",
      },
      {
        type: "short",
        prompt: "Using Week 2's \"Key Takeaway 1: LLMs Predict Patterns,\" explain why AI can help identify suspicious code, but why every AI finding still needs verification.",
        modelAnswer: "LLMs generate responses by predicting likely patterns rather than by knowing whether something is true or correct. Many vulnerabilities also follow recognisable patterns, which is why AI can help spot suspicious code — but because the model has no built-in way to confirm correctness, \"every finding still needs evidence and verification\" before it can be trusted.",
      },
      {
        type: "short",
        prompt: "Explain \"Key Takeaway 2: Code Is Data Too\" — the Text → Tokens → Patterns → Prediction pipeline — and state the important caveat the lecture attaches to it.",
        modelAnswer: "LLMs process any input, including code, execution traces, and other technical artefacts, as tokens and patterns the same way they process text — this is why AI can be used to investigate software and look for possible vulnerabilities. The caveat: \"prediction is not proof. AI can still produce convincing but incorrect findings\" — pattern-matching something as vulnerability-shaped doesn't make it a real, exploitable vulnerability.",
      },
      {
        type: "mcq",
        prompt: "In the Week 2 \"Pause. Think. Predict.\" exercise, a plain Python coding task is presented alongside an obscure-language task, machine-code decompilation, and finding vulnerabilities in crypto/consensus proofs. Based on how the following slides describe each of these as progressively \"harder,\" \"much harder,\" and \"the hardest,\" which task is implied to be the comparative baseline an LLM handles best?",
        options: ["The Python coding task", "The obscure-language task with no syntax provided", "Decompiling machine code back into high-level code", "Finding vulnerabilities in cryptographic/consensus proofs"],
        correctIndex: 0,
        modelAnswer: "The lecture never ranks Python explicitly, but each of the other three is explicitly flagged as harder relative to ordinary coding tasks (obscure syntax needs extra grammar hints and risks hallucinated structure; decompilation is \"much harder\"; crypto/consensus proofs are \"the hardest type of security questions\"), implying a mainstream, well-documented language like Python is the easiest baseline.",
      },
      {
        type: "mcq",
        prompt: "Why does an LLM struggle with an obscure programming language when its syntax is not provided?",
        options: ["Obscure languages cannot be tokenized by any LLM", "The model must first guess token boundaries, keywords, structure and grammar, and may hallucinate structure borrowed from familiar languages like C, Python, or Java", "The model always refuses to attempt unfamiliar languages", "Obscure languages have no compilers, so the task is impossible"],
        correctIndex: 1,
        modelAnswer: "Without provided syntax the model must guess whether the language is functional or object-oriented, what a function declaration looks like, and how variables are defined — \"It may hallucinate structure from other languages. It will often default to something that looks like C, Python, or Java style.\"",
      },
      {
        type: "mcq",
        prompt: "Why is decompiling machine code back into high-level code described as \"much harder\" for an LLM than typical coding tasks?",
        options: ["Machine code has more natural-language signal than source code", "There is less natural-language signal, less structured high-level pattern, fewer clean paired examples, and decompilation requires reasoning about semantics, not just syntax", "Machine code is always encrypted before it reaches the model", "Decompilation is already a fully solved problem with perfect tools"],
        correctIndex: 1,
        modelAnswer: "\"Less natural language signal / Less structured high level patterns / Fewer clean paired examples / Machine code is low level and ambiguous\" — and \"decompilation requires reasoning about semantics, not just syntax.\"",
      },
      {
        type: "mcq",
        prompt: "Why does Week 2 call finding vulnerabilities in cryptographic/consensus proofs \"the hardest type of security question\" for AI?",
        options: ["It requires more GPU power than other tasks", "Findings are not even verifiable in general and may require humans to manually validate them", "Cryptographic protocols have no known vulnerability classes", "LLMs are structurally unable to process any mathematical notation"],
        correctIndex: 1,
        modelAnswer: "\"Not even verifiable / May require humans to manually validate / This is the hardest type of security questions.\"",
      },
      {
        type: "truefalse",
        prompt: "True or False: According to Week 2, \"hallucination\" means the model produces something that sounds correct but is not grounded in reality.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "\"Hallucination means: The model produces something that sounds correct, but is not grounded in reality.\"",
      },
      {
        type: "mcq",
        prompt: "Which of the following is NOT one of Week 2's recommended ways to catch AI hallucination when hunting for vulnerabilities?",
        options: ["Ask for concrete proof", "Ask for a minimal reproducible example", "Ask it to generate a PoC or show the exact execution trace", "Accept the first plausible-sounding answer without further questions"],
        correctIndex: 3,
        modelAnswer: "The \"Models Can Hallucinate\" slide's remedies are: ask for concrete proof, ask for a minimal reproducible example, ask for the exact execution trace, and ask it to generate a PoC — accepting the first plausible answer is the opposite of this guidance.",
      },
      {
        type: "short",
        prompt: "List at least three concrete techniques the lecture recommends for catching AI hallucination when it reports a possible vulnerability.",
        modelAnswer: "Ask for concrete proof; ask for a minimal reproducible example; ask for the exact execution trace; ask the model to generate a proof-of-concept (PoC).",
      },
      {
        type: "mcq",
        prompt: "What is the recommended response when a model is \"lazy\" and stops at the first obvious issue?",
        options: ["Accept the first finding as the complete answer", "Summarize what has already been checked and explicitly ask for new and different issues, edge cases, and non-obvious logic flaws", "Restart the conversation and ask the exact same question again", "Shrink the model's context window"],
        correctIndex: 1,
        modelAnswer: "\"Summarize what has already been checked (in a file or in a table) / Explicitly ask for new and different issues / Ask for edge cases / Ask for non obvious logic flaws.\"",
      },
      {
        type: "truefalse",
        prompt: "True or False: Part of the reason models can be lazy is that they were trained not to work for too long, since working for a long time is considered not user-friendly.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "\"If the model works for too long, it is not user friendly. They were trained to not work for too long.\"",
      },
      {
        type: "mcq",
        prompt: "Which of the following is NOT a Week 2 recommendation for the problem that \"Models Can Miss Things\"?",
        options: ["Run the investigation multiple times", "Change the phrasing of the prompt", "Use only one model, run repeatedly with identical settings", "Ask the model to critique its own answer"],
        correctIndex: 2,
        modelAnswer: "The slide recommends running multiple times, changing phrasing, using different models, using different temperatures, and asking the model to critique its own answer — relying on one model with identical settings is exactly what these techniques are meant to avoid.",
      },
      {
        type: "short",
        prompt: "The lecture asks, about using different models to find vulnerabilities: \"Do you know why this is important?\" Answer that question in your own words.",
        modelAnswer: "Different models are trained differently and have different blind spots and failure modes — a vulnerability one model misses (or a hallucination one model produces) may be caught or correctly rejected by a different model, so relying on a single model risks letting its specific gaps define the entire investigation's coverage.",
      },
      {
        type: "mcq",
        prompt: "Per \"Models Are Sensitive To Framing / Models Need Context,\" what happens if you give a model a bad prompt or only partial code?",
        options: ["A shallow answer or shallow analysis", "The model automatically refuses to respond", "The model automatically requests the missing code before answering", "The output becomes more thorough than usual"],
        correctIndex: 0,
        modelAnswer: "\"Bad prompts → shallow answer. Partial code → shallow analysis.\" Models need enough context to produce a useful analysis.",
      },
      {
        type: "mcq",
        prompt: "What is the key structural difference in how a reasoning model produces a response, compared to a standard LLM response?",
        options: ["It skips the system prompt entirely", "It performs additional internal processing/reasoning — typically hidden from the user — before producing its final response", "It always calls an external tool before responding", "It requires a human to manually approve every generated token"],
        correctIndex: 1,
        modelAnswer: "\"The model does more internal processing before producing its answer,\" shown as a (typically hidden) reasoning step between the prompt and the final response.",
      },
      {
        type: "truefalse",
        prompt: "True or False: According to Week 2, more reasoning by a model guarantees a correct answer.",
        options: ["True", "False"],
        correctIndex: 1,
        modelAnswer: "\"More reasoning can improve performance, but it does not guarantee a correct answer.\"",
      },
      {
        type: "short",
        prompt: "Describe what an OpenAI \"O-series\"-style reasoning model does before producing its final answer, and why a user might not see this part.",
        modelAnswer: "It works through an internal \"scratchpad\" before it speaks — this internal work can be long, hundreds or even thousands of tokens, and the user may see only a \"thinking\" indicator while it happens; the user can often control how much effort it uses (e.g. low/medium/high). This internal reasoning is typically hidden — the user only sees the final response, not the scratchpad itself.",
      },
      {
        type: "mcq",
        prompt: "What does Week 2 call \"The Aha Moment for Security\", referring to models like O3 and R1?",
        options: ["AI models became too expensive for security teams to use", "Security changed completely — things that didn't work before started working, and real vulnerabilities began being found at scale", "Reasoning models became measurably worse at security tasks than earlier models", "Every known vulnerability was immediately patched"],
        correctIndex: 1,
        modelAnswer: "\"Security has completely changed after O3 and R1. Things that did not work before are now starting to work. We start to find real vulnerabilities on a large scale.\"",
      },
      {
        type: "mcq",
        prompt: "Why does Week 2 say reasoning alone is \"not enough\" for large-scale security investigation of a codebase?",
        options: ["Reasoning models are not permitted to access the internet", "Code repositories can be huge — thousands of interdependent files — while the model's context window is small, so tools are needed to interact with the codebase efficiently", "Reasoning models are legally banned from security work", "Reasoning models always hallucinate when given any code"],
        correctIndex: 1,
        modelAnswer: "\"Code repositories can be HUGE!! Thousands of files / Different projects, they depend on each other / Context window is small\" — so text-based tools (grep, ls, cd, cat, static/dynamic analysis) are needed alongside reasoning.",
      },
      {
        type: "mcq",
        prompt: "In the AI agent tool-use loop shown in Week 2, what happens after the model reasons that it needs more evidence and issues a Tool Call Instruction?",
        options: ["The response is shown to the user immediately with no further action", "A tool executes and returns a result, and that result (evidence) feeds back into the model's next response or action", "The entire conversation is discarded", "The system prompt is automatically regenerated from scratch"],
        correctIndex: 1,
        modelAnswer: "\"The tool gathers evidence; the AI uses that evidence to decide what to do next or answer\" — e.g. the model calls `ls`, receives the file listing as a tool result, then uses it to compose its final answer.",
      },
      {
        type: "truefalse",
        prompt: "True or False: An AI agent, after its reasoning step, can choose either to answer directly or to use a tool to gather more evidence.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "\"An AI agent can decide whether to answer directly or use a tool to gather more evidence.\"",
      },
      {
        type: "short",
        prompt: "Using the `ls` example from the lecture, describe the Reason → Act → Observe → Continue cycle an AI agent follows when using a tool.",
        modelAnswer: "Reason: given \"What files are in this folder?\", the model decides it needs to check the current directory. Act: it issues a tool call, `ls`. Observe: the tool returns a result — e.g. main.py, README.md, data.txt. Continue: the model uses that evidence to produce its final answer (\"The folder contains three files...\") rather than guessing — the tool gathers evidence, and the model decides what to do next based on it.",
      },
      {
        type: "mcq",
        prompt: "Per \"From AI Agent to Security Investigation,\" what is the first question to ask before letting an AI act on a target?",
        options: ["\"Can the AI do it?\"", "\"Is the AI authorised to act?\"", "\"How fast can the AI respond?\"", "\"Which model is the cheapest option?\""],
        correctIndex: 1,
        modelAnswer: "\"The first question is not 'Can the AI do it?' it is 'Is the AI authorised to act?'\"",
      },
      {
        type: "truefalse",
        prompt: "True or False: According to the described gating logic, real/live systems and domains are treated as lower risk than sandboxed or local labs when deciding whether an AI assistant should act.",
        options: ["True", "False"],
        correctIndex: 1,
        modelAnswer: "It's the opposite: \"Real, live systems/domains are higher risk than sandboxed/local labs. Unknown authorization is treated conservatively.\"",
      },
      {
        type: "short",
        prompt: "Summarize the risk-and-intent gating logic described for Codex: name at least three of the five factors it considers before acting on a cybersecurity request.",
        modelAnswer: "Target context (real/live systems are higher risk than sandboxed/local labs; unknown authorization is treated conservatively); Actionability (general education/defensive guidance is usually okay, but step-by-step exploit instructions or live attack execution is restricted); Potential harm (it refuses or narrows scope if guidance could enable intrusion, credential theft, malware, or abuse); User framing (phrasing like \"hack this site\" plus \"interact directly and pass it\" is interpreted as active exploitation, even if it might be a CTF, since authorization can't be assumed); Safe fallback (it can still help by analysing artefacts the user provides, plus detection, hardening, and legal testing workflows).",
      },
      {
        type: "mcq",
        prompt: "Why does the lecture argue that \"more cyber capability requires more trust\" for AI coding/reasoning models?",
        options: ["More capable models simply cost more money to run", "The same capability that can accelerate defensive vulnerability discovery and remediation can also be misused offensively, so stronger safeguards and authorisation controls must grow alongside capability", "More capable models are always released as open source", "Capability and trust are unrelated design concerns"],
        correctIndex: 1,
        modelAnswer: "The referenced article frames it as: cyber-capable models \"can both meaningfully strengthen the broader ecosystem and introduce new risks\" — capability that helps defenders find and fix vulnerabilities is the same capability that could be misused, so more trust/access controls are needed as capability increases.",
      },
      {
        type: "short",
        prompt: "Using the promptairlines.com CTF example, explain the difference between \"the AI solved it\" and \"did we learn anything\" — what does the lecture say is missing if a student just accepts the AI's final flag?",
        modelAnswer: "The AI directly interacted with the backend, extracted a flag, and verified it via the submit endpoint — a working solution on its own. But if a student only sees that final result, they learn nothing about how it was found; the lecture's point is that the value is in the process — \"Failures → adaptation → partial success → verification\" — e.g. seeing the failed prompt-injection attempts before the successful one that leaked the bot identifier, not just the final answer.",
      },
      {
        type: "mcq",
        prompt: "The investigation-process example in Week 2 (failed jailbreak-style prompts, then a partial character leak, then verification via `/submit_flag`) is used to illustrate which idea?",
        options: ["AI agents always succeed on their first attempt", "Genuine security investigation is iterative — failures, adaptation, partial success, and verification — not a single lucky guess", "Prompt injection cannot be meaningfully demonstrated in a lecture", "Verification becomes unnecessary once any flag is found"],
        correctIndex: 1,
        modelAnswer: "The slide explicitly labels the pattern \"Failures → adaptation → partial success → verification,\" showing multiple failed prompts before a successful partial leak that is then verified — investigation is a process, not a single guess.",
      },
      {
        type: "mcq",
        prompt: "What is the stated overall goal of using AI to find vulnerabilities, per \"How To Use AI To Find Vulnerabilities (Manually + Smartly)\"?",
        options: ["Send a single prompt: \"Find the vulnerabilities\"", "Investigate with AI — giving it context, evidence, and boundaries, and never trusting a finding until it is verified", "Let the AI run unsupervised for as long as possible", "Avoid using AI for any code-related task"],
        correctIndex: 1,
        modelAnswer: "\"The goal is not to ask AI: 'Find the vulnerabilities.' The goal is to investigate with AI.\" AI is powerful but not careful by default — you must give it context, evidence, and boundaries, and never trust a finding until you verify it.",
      },
      {
        type: "mcq",
        prompt: "What is the correct order of the Android build pipeline described in Week 2?",
        options: ["APK → Build & Compile → Kotlin/Java source", "Kotlin/Java source (human-readable) → Build & Compile → APK (what you receive) → Install & Run", "Install & Run → APK → Kotlin/Java source", "Decompile → Kotlin/Java source → APK"],
        correctIndex: 1,
        modelAnswer: "\"Kotlin / Java — Human-readable code → Build & Compile → APK — What you receive → Install & Run.\" Your task is to work backwards: understand, investigate, verify.",
      },
      {
        type: "short",
        prompt: "Explain why Assignment 1 gives you an APK rather than the original source project, and what this means for how you must investigate it.",
        modelAnswer: "An APK is the compiled, packaged form produced after Kotlin/Java source code is built — it contains compiled code, resources, and application metadata, not the original human-readable source project. Because you only receive the packaged artefact, you must work backwards: understand the APK's structure, investigate it (e.g. decompiling to recover a readable-but-not-necessarily-identical representation), and verify any findings, rather than simply reading original source code.",
      },
      {
        type: "truefalse",
        prompt: "True or False: Decompiling an APK is guaranteed to recover the exact original source code that produced it.",
        options: ["True", "False"],
        correctIndex: 1,
        modelAnswer: "\"Decompilation can recover useful readable representations, but not necessarily the exact original source code.\"",
      },
      {
        type: "short",
        prompt: "According to the Extra Resources \"Assignment 1 Connection\" section, what is Assignment 1 assessing you on — and what is it explicitly NOT assessing?",
        modelAnswer: "\"You are not being assessed on whether an AI tool can produce a vulnerability list. You are being assessed on how you investigate the APK, evaluate evidence, verify findings and justify your conclusions\" — i.e. the process and judgement behind the investigation, not just an AI-generated output.",
      },
      {
        type: "scenario",
        prompt: "A student pastes an entire undocumented custom bytecode dump into an LLM with the single prompt \"find all the security vulnerabilities in this.\" Using Week 2's ideas about coding-task difficulty and model limitations, give at least three distinct reasons this approach is likely to produce a low-quality or misleading result, and describe a better way to structure the investigation.",
        modelAnswer: "1) No syntax/grammar is provided for an unfamiliar format, so the model must guess token boundaries and structure, and may hallucinate structure borrowed from familiar languages (per the obscure-language slide). 2) Bytecode is closer to machine code than source — low natural-language signal, ambiguous, and requiring semantic reasoning rather than surface-level syntax matching, which the decompilation slide flags as \"much harder.\" 3) A single one-shot \"find all vulnerabilities\" prompt invites the model to be lazy and stop at the first obvious-looking issue, with no mechanism built in to catch hallucinated findings. Better approach: supply the format's grammar/structure explicitly, break the investigation into smaller pieces, ask for concrete proof, a minimal reproducible example, or an execution trace for each claimed finding, explicitly ask for new and different issues after the first pass, and independently verify anything reported before trusting it.",
      },
      {
        type: "scenario",
        prompt: "In Week 1, the Bybit case showed staff trusting a manipulated UI and approving a transaction without independently verifying what was actually being signed — a broken trust assumption. Explain how this same underlying failure pattern (\"trusting a display/output without independent verification\") reappears in Week 2's guidance about AI-assisted vulnerability discovery, and describe one concrete Week 2 practice that defends against it.",
        modelAnswer: "In Bybit, staff trusted what the approval UI displayed instead of independently verifying the actual transaction being signed. Week 2 makes the same point about AI: an LLM's output \"sounds correct\" but is not automatically grounded in reality (hallucination), and \"prediction is not proof\" — so accepting an AI-reported vulnerability without checking it is the same failure pattern, trusting a plausible-looking output instead of independently confirming the underlying reality. Week 2's defense is explicit verification: ask for concrete proof, a minimal reproducible example, an exact execution trace, or a PoC before accepting any AI-claimed finding — the AI-security equivalent of the out-of-band verification Bybit lacked.",
      },
      {
        type: "scenario",
        prompt: "You are given an APK for Assignment 1 and want to use an AI coding agent to help investigate it for vulnerabilities. Walk through a responsible, Week-2-aligned investigation plan in four short steps, and for each step name one specific risk you are guarding against.",
        modelAnswer: "1. Authorisation/scope check first — confirm you are only acting within the authorised assignment environment and scope. Guards against: crossing the \"is the AI authorised to act\" boundary onto a live/unauthorised target. 2. Give the agent full context — decompiled code, structure, relevant syntax/format details. Guards against: shallow analysis caused by partial code or bad framing. 3. Let the agent use tools (read files, grep, static analysis) to investigate, keeping a running record of what's already been checked and explicitly asking for new/different issues and edge cases. Guards against: the model being lazy and stopping at the first obvious issue. 4. Treat every AI-reported finding as a hypothesis, not a fact — ask for concrete proof, a PoC, or an execution trace, and verify it yourself against the actual APK. Guards against: hallucinated findings that sound correct but aren't grounded in reality.",
      },
      {
        type: "scenario",
        prompt: "A teammate says: \"I ran our APK through an AI agent overnight and it came back with 15 vulnerabilities — let's just list all 15 in our report.\" Using Week 2 ideas, explain what's missing from this approach and outline what must happen to each of the 15 items before it belongs in a report.",
        modelAnswer: "Missing: a verification step. The agent's raw output is a set of hypotheses, not confirmed findings — a large unsupervised run risks piling up unverified, possibly duplicated, or outright hallucinated items rather than genuinely new, distinct ones. Before any item goes in the report it needs: (1) verification with concrete evidence — a minimal reproducible example, an exact execution trace, or a working PoC against the actual APK, not just the agent's claim — and (2) human judgement to confirm it is a genuine, exploitable issue rather than a hallucinated or duplicate pattern-match, consistent with being \"assessed on how you investigate the APK, evaluate evidence, verify findings and justify your conclusions.\"",
      },
      {
        type: "scenario",
        prompt: "Apply Week 1's system-model idea of a \"trust assumption\" to an AI coding agent that has terminal tool access during your Assignment 1 investigation. Name one trust assumption this setup introduces, and explain, using Week 2's authorisation discussion, what could go wrong if that assumption is never checked.",
        modelAnswer: "Trust assumption: \"the agent will only use its terminal access within the authorised assignment scope, and will not act on or query live external systems.\" Using Week 2: the first question before any AI action is not \"can it?\" but \"is it authorised to?\" — if that assumption is never checked, the agent could treat a live, unauthorised target the same as the authorised local APK/lab environment (e.g. attempting real network interaction with an external service), crossing from legitimate coursework investigation into unauthorised access — exactly the live-target risk the described gating logic is designed to catch.",
      },
      {
        type: "scenario",
        prompt: "A classmate claims: \"Reasoning models made Week 2's concerns about hallucination obsolete, since reasoning models can now solve real CTF challenges.\" Evaluate this claim using at least two distinct pieces of evidence from the lecture.",
        modelAnswer: "The claim overstates things. First, the lecture is explicit that \"more reasoning can improve performance, but it does not guarantee a correct answer\" — reasoning is described as an improvement, not a cure for hallucination. Second, even after describing \"The Aha Moment for Security\" where reasoning models started finding real vulnerabilities at scale, the very next sections — \"Models Can Hallucinate\" and \"Models Can Miss Things\" — still list hallucination and missed vulnerabilities as active problems requiring specific mitigations (ask for proof/PoC, run multiple times, use different models). So reasoning models are more capable, but the lecture continues to treat verification and hallucination-mitigation as necessary, not obsolete.",
      },
    ],
  }

export const WEEK_2_PAPERS: ExamPaperSeed[] = [PAPER];
