// Starting data for the Jobs tab, imported once on first boot (see seedJobsOnce).
// Built from the 2026-09-23 internship tracker: Gmail history (Mar–Sep 2026) +
// open Sydney roles + startup outreach targets researched that day.
import type { JobInput } from "./db";

export const JOB_SEED: JobInput[] = [
  {
    "kind": "role",
    "company": "Open (Open Home Loans)",
    "role": "Software Engineer Intern (AU)",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": "Gmail – denise@openloans.com.au · Passed AI interview 4 Jun. You replied 7 Jun about placement timing. No reply since.",
    "status": "Interview",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-05-18",
    "last_update": "2026-06-07",
    "next_action": "FOLLOW UP with Denise: ask about take-home project",
    "next_action_due": "2026-09-24",
    "about": null
  },
  {
    "kind": "role",
    "company": "Amazon",
    "role": "2027 Applied Science Intern (ML, Recommender Systems)",
    "job_type": "Intern",
    "cycle": "2027",
    "link": "https://www.amazon.jobs",
    "notes": "Invited to online assessment 12 May.",
    "status": "OA",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-05-12",
    "last_update": "2026-05-12",
    "next_action": "Check amazon.jobs portal for status",
    "next_action_due": "2026-09-24",
    "about": null
  },
  {
    "kind": "role",
    "company": "Amazon",
    "role": "2026 Software Dev Engineer Intern (Sydney)",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": "https://www.amazon.jobs",
    "notes": "Also invited to Amazon Sydney intern event 24 Apr.",
    "status": "Applied",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-04-06",
    "last_update": "2026-04-06",
    "next_action": "Check portal",
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "TikTok",
    "role": "Backend Engineer Intern (TikTok LIVE) – 2027 Start",
    "job_type": "Intern",
    "cycle": "2027",
    "link": "https://lifeattiktok.com",
    "notes": null,
    "status": "Applied",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-03-01",
    "last_update": "2026-03-01",
    "next_action": "Check lifeattiktok.com status",
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "TikTok",
    "role": "Backend SWE Intern (Data Trust & Safety) – 2026 Start",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": "https://lifeattiktok.com",
    "notes": null,
    "status": "Applied",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-03-01",
    "last_update": "2026-03-01",
    "next_action": "Check status",
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "TikTok",
    "role": "Backend Engineer Intern (TikTok LIVE – Sydney) – 2026 Start",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": "https://lifeattiktok.com",
    "notes": null,
    "status": "Applied",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-05-18",
    "last_update": "2026-05-18",
    "next_action": "Check status",
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "TikTok",
    "role": "Backend SWE Intern (Data Trust & Safety) – 2027 Start",
    "job_type": "Intern",
    "cycle": "2027",
    "link": "https://lifeattiktok.com",
    "notes": null,
    "status": "Applied",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-06-06",
    "last_update": "2026-06-06",
    "next_action": "Check status",
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "TikTok",
    "role": "SWE Intern (Multimedia Arch-Live) – 2027 Start",
    "job_type": "Intern",
    "cycle": "2027",
    "link": null,
    "notes": null,
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-09-09",
    "last_update": "2026-09-11",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Atlassian",
    "role": "Software Engineer Intern, 2026 Summer Australia",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": "Gmail (iCIMS)",
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-03-08",
    "last_update": "2026-03-10",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Atlassian",
    "role": "Data Engineer Intern, 2026 Summer Australia",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": "Gmail (iCIMS)",
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-03-09",
    "last_update": "2026-03-10",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Airwallex",
    "role": "2026/27 Software Engineering Intern Program",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": "Gmail (Ashby)",
    "status": "Applied",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-03-08",
    "last_update": "2026-03-08",
    "next_action": "Likely closed – mark Rejected if no reply",
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Google",
    "role": "Internship applications (2)",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": null,
    "status": "Applied",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-03-30",
    "last_update": "2026-03-30",
    "next_action": "Check Google careers portal",
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Dolby Australia",
    "role": "Software Engineer Internship 2026–27",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": null,
    "status": "Applied",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-03-30",
    "last_update": "2026-03-31",
    "next_action": "Did you complete the MS Form they asked for?",
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Jump Trading",
    "role": "Internship",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": null,
    "status": "Applied",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-04-08",
    "last_update": "2026-04-08",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "SLB",
    "role": "Early Careers – IT & Digital Internships",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": null,
    "status": "Applied",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-04-08",
    "last_update": "2026-04-08",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "WTW",
    "role": "Intern – Risk Engineering",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": null,
    "status": "Applied",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-05-11",
    "last_update": "2026-05-11",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "NiCE",
    "role": "Forward Deployed Engineer",
    "job_type": "Job",
    "cycle": null,
    "link": null,
    "notes": "Gmail (Greenhouse)",
    "status": "Applied",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-05-11",
    "last_update": "2026-05-11",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "HappyRobot",
    "role": "Founding Forward Deployed Engineer",
    "job_type": "Job",
    "cycle": null,
    "link": null,
    "notes": "Gmail (Ashby)",
    "status": "Applied",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-05-19",
    "last_update": "2026-05-19",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Employment Hero",
    "role": "AI Activation Intern (Remote)",
    "job_type": "Intern",
    "cycle": "2026",
    "link": null,
    "notes": null,
    "status": "Applied",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-06-05",
    "last_update": "2026-06-05",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Displayr",
    "role": "Internship – Software Engineer",
    "job_type": "Intern",
    "cycle": "2025/26",
    "link": null,
    "notes": "Gmail (Workable)",
    "status": "Applied",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-05-10",
    "last_update": "2026-05-10",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "University of Sydney",
    "role": "Casual Academic – Computer Science (EOI)",
    "job_type": "Part-time",
    "cycle": "Ongoing",
    "link": null,
    "notes": "Gmail (Workday)",
    "status": "Applied",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-06-29",
    "last_update": "2026-06-29",
    "next_action": "Good part-time option – email unit coordinators",
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "CBA",
    "role": "Software Engineer (Career Comeback Program)",
    "job_type": "Job",
    "cycle": null,
    "link": null,
    "notes": "Gmail (Workday) · Outcome email 3 Jun – open it to confirm.",
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-05-14",
    "last_update": "2026-06-03",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Bank of America",
    "role": "Global Tech Summer Analyst (Core Tech Infra) 2026/27 Sydney",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": null,
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-04-09",
    "last_update": "2026-09-04",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Microsoft",
    "role": "SWE Intern – Clipchamp",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": null,
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-08-25",
    "last_update": "2026-08-31",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Suncorp",
    "role": "Technology Intern (Grad Stream)",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": "Did online assessment.",
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-08-12",
    "last_update": "2026-08-14",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Jane Street",
    "role": "Internship",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": null,
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-08-06",
    "last_update": "2026-08-17",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "OpenAI",
    "role": "AI Deployment Engineer, Startups",
    "job_type": "Job",
    "cycle": null,
    "link": null,
    "notes": null,
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-06-14",
    "last_update": "2026-07-21",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Optiver",
    "role": "FutureFocus Sydney – Technology",
    "job_type": "Program",
    "cycle": "2026",
    "link": null,
    "notes": "Did online assessment.",
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-07-06",
    "last_update": "2026-07-12",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Optiver",
    "role": "Software Developer Internship 2026-27",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": null,
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-04-15",
    "last_update": "2026-04-18",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Stripe",
    "role": "Software Engineer, Intern",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": null,
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-04-05",
    "last_update": "2026-07-10",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "MongoDB",
    "role": "Software Engineering Internship 2026/27",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": null,
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-05-17",
    "last_update": "2026-06-25",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Siemens",
    "role": "Systems Engineering Intern",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": null,
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-05-04",
    "last_update": "2026-06-05",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Bolttech",
    "role": "Intern – AI and Data Science",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": null,
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-04-08",
    "last_update": "2026-06-22",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Resonate Solutions",
    "role": "Software Engineer – Intern",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": null,
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-03-30",
    "last_update": "2026-05-14",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "BAE Systems",
    "role": "2026/27 Technology Summer Internship",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": "Needs defence clearance eligibility.",
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-05-12",
    "last_update": "2026-05-12",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "EY",
    "role": "2026/27 Vacationer Program",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": "Not eligible (citizen/PR only).",
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-04-27",
    "last_update": "2026-04-29",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Susquehanna (SIG)",
    "role": "Software Development Internship: Nov 2026",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": "Did CodeSignal OA.",
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-04-07",
    "last_update": "2026-04-15",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "P&G",
    "role": "Summer Internship Program",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": null,
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-04-15",
    "last_update": "2026-04-16",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Canva",
    "role": "Backend SWE – Product & Features (Java)",
    "job_type": "Job",
    "cycle": null,
    "link": null,
    "notes": null,
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-04-20",
    "last_update": "2026-04-22",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Canva",
    "role": "SWE Intern Frontend/Backend 2026/27 (Launchpad)",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": null,
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-04-05",
    "last_update": "2026-04-07",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Amazon",
    "role": "Network Dev Engineer Intern, Core Networking",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": null,
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-03-11",
    "last_update": "2026-03-30",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "The Trade Desk",
    "role": "2026 Australia SWE Internship",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": null,
    "status": "Rejected",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": "2026-03-01",
    "last_update": "2026-03-16",
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "NAB",
    "role": "2026 Summer Intern Program",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": null,
    "notes": "Started but never submitted.",
    "status": "Not submitted",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": null,
    "last_update": "2026-08-09",
    "next_action": "Closed 9 Aug",
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Citadel Securities",
    "role": "2026-27 Software Engineering Internship",
    "job_type": "Full-time (11 wks)",
    "cycle": "2026/27",
    "link": "https://au.gradconnection.com/employers/citadel-citadel-securities/jobs/citadel-securities-2026-2027-software-engineering-internship-44/",
    "notes": "Closes 28 Sep 12:59pm. Masters OK. Apply TODAY.",
    "status": "To apply",
    "priority": "High",
    "intl_ok": "Yes",
    "closes_on": "2026-09-28",
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "TikTok",
    "role": "Backend SWE Intern (Platform Engineering) – 2027 Start",
    "job_type": "Full-time",
    "cycle": "2026/27",
    "link": "https://au.gradconnection.com/employers/tiktok/jobs/tiktok-backend-software-engineer-intern-platform-engineering-2027-start-bsms/",
    "notes": "Close date approx – check listing.",
    "status": "To apply",
    "priority": "High",
    "intl_ok": "Yes",
    "closes_on": "2026-09-30",
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "TikTok",
    "role": "Software Engineer Intern (TikTok Live) – 2027 Start",
    "job_type": "Full-time",
    "cycle": "2026/27",
    "link": "https://au.gradconnection.com/employers/tiktok/jobs/tiktok-software-engineer-intern-tiktok-live-2027-start-bsms/",
    "notes": "Close date approx – check listing.",
    "status": "To apply",
    "priority": "High",
    "intl_ok": "Yes",
    "closes_on": "2026-09-30",
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "TikTok",
    "role": "Agent Development Engineer Intern (Media Network) – 2027",
    "job_type": "Full-time",
    "cycle": "2026/27",
    "link": "https://au.gradconnection.com/employers/tiktok/jobs/tiktok-agent-development-engineer-intern-media-network-2027-start-bsms/",
    "notes": "AI agents – good fit. LinkedIn recommended this to you.",
    "status": "To apply",
    "priority": "High",
    "intl_ok": "Yes",
    "closes_on": "2026-09-30",
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "University of Sydney",
    "role": "Engineering Vacation Research Internship",
    "job_type": "Full-time (Dec 1 – Feb 5)",
    "cycle": "2026/27",
    "link": "https://www.sydney.edu.au/engineering/study/scholarships/engineering-vacation-research-internship-program.html",
    "notes": "$500/week. Masters students OK. Min WAM 75. Pick a supervisor first.",
    "status": "To apply",
    "priority": "High",
    "intl_ok": "Yes (USYD students)",
    "closes_on": "2026-10-04",
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "TikTok",
    "role": "Backend SWE Intern (TikTok Foundation) – 2027 Start",
    "job_type": "Full-time",
    "cycle": "2026/27",
    "link": "https://au.gradconnection.com/employers/tiktok/jobs/tiktok-backend-software-engineer-intern-tiktok-foundation-2027-start/",
    "notes": "Close date from listing; other TikTok roles may close ~30 Sep.",
    "status": "To apply",
    "priority": "High",
    "intl_ok": "Yes",
    "closes_on": "2026-10-19",
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Apple",
    "role": "2027 Apple Internship – Information Systems & Technology (AUS)",
    "job_type": "Full-time",
    "cycle": "2026/27",
    "link": "https://jobs.apple.com/en-au/details/200676288-3957/2027-apple-internship-information-systems-and-technology-aus",
    "notes": "On your LinkedIn saved jobs. No close date shown – apply soon.",
    "status": "To apply",
    "priority": "High",
    "intl_ok": "Check",
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Apple",
    "role": "Secure Kernel Engineering Intern, Sydney",
    "job_type": "Full-time",
    "cycle": "2026/27",
    "link": "https://au.linkedin.com/jobs/view/secure-kernel-engineering-intern-sydney-at-apple-4458943511",
    "notes": "Posted 28 Aug (from your Bubblelab internship emails). Needs C/C++, OS knowledge.",
    "status": "To apply",
    "priority": "High",
    "intl_ok": "Check",
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Deloitte",
    "role": "Full Stack SWE / Product Developer – Student",
    "job_type": "Part-time (15 h/wk, $33.71/h)",
    "cycle": "2026/27",
    "link": "https://hatch.team/job/full-stack-software-engineer-product-developer-student-or-graduate-job_3InSNRGpOiKFjKUWQue0Pq48ko2",
    "notes": "Hybrid Sydney. Starts Sep/Oct. Fits study load.",
    "status": "To apply",
    "priority": "High",
    "intl_ok": "Check",
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Deloitte",
    "role": "Applied AI Engineer – Student",
    "job_type": "Part-time",
    "cycle": "2026/27",
    "link": "https://hatch.team/job/applied-ai-engineer-student-or-graduate-job_3InP3QKT9HnVkzFtA8c3OE82rxc",
    "notes": "Via Hatch.",
    "status": "To apply",
    "priority": "High",
    "intl_ok": "Check",
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Citadel Securities",
    "role": "2026-27 FPGA Engineer Internship",
    "job_type": "Full-time",
    "cycle": "2026/27",
    "link": "https://au.gradconnection.com/employers/citadel-citadel-securities/jobs/citadel-securities-2026-2027-fpga-engineer-internship-48/",
    "notes": "Only if you have hardware/Verilog skills.",
    "status": "To apply",
    "priority": "Medium",
    "intl_ok": "Yes",
    "closes_on": "2026-09-28",
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "TikTok",
    "role": "Site Reliability Engineer Intern (Technical Infrastructure) – 2027",
    "job_type": "Full-time",
    "cycle": "2026/27",
    "link": "https://au.gradconnection.com/employers/tiktok/jobs/tiktok-site-reliability-engineer-intern-technical-infrastructure-2027-start-bsms/",
    "notes": "Close date approx.",
    "status": "To apply",
    "priority": "Medium",
    "intl_ok": "Yes",
    "closes_on": "2026-09-30",
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "TikTok",
    "role": "SWE Intern (Multimedia Framework, C++) – 2027",
    "job_type": "Full-time",
    "cycle": "2026/27",
    "link": "https://au.gradconnection.com/employers/tiktok/jobs/tiktok-software-engineer-intern-multimedia-framework-c-2027-start-bsms/",
    "notes": "Needs C++.",
    "status": "To apply",
    "priority": "Medium",
    "intl_ok": "Yes",
    "closes_on": "2026-09-30",
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "TikTok",
    "role": "Frontend SWE Intern (TikTok Foundation) – 2027",
    "job_type": "Full-time",
    "cycle": "2026/27",
    "link": "https://au.gradconnection.com/employers/tiktok/jobs/tiktok-frontend-software-engineer-intern-tiktok-foundation-2027-start-bsms/",
    "notes": "Close date approx.",
    "status": "To apply",
    "priority": "Medium",
    "intl_ok": "Yes",
    "closes_on": "2026-09-30",
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "TikTok",
    "role": "SDET Intern (TikTok LIVE) – 2027",
    "job_type": "Full-time",
    "cycle": "2026/27",
    "link": "https://au.gradconnection.com/employers/tiktok/jobs/tiktok-software-development-engineer-in-test-intern-tiktok-live-2027-start-bsms-5/",
    "notes": "Testing role – less competitive.",
    "status": "To apply",
    "priority": "Medium",
    "intl_ok": "Yes",
    "closes_on": "2026-09-30",
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "TikTok",
    "role": "Hyper-Edge Tech Dev Engineer Intern (Data Application) – 2027",
    "job_type": "Full-time",
    "cycle": "2026/27",
    "link": "https://au.gradconnection.com/employers/tiktok/jobs/tiktok-hyper-edge-technology-development-engineer-intern-data-application-2027-start-bsms/",
    "notes": "Close date approx.",
    "status": "To apply",
    "priority": "Medium",
    "intl_ok": "Yes",
    "closes_on": "2026-09-30",
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Deloitte",
    "role": "Quality & Test Automation Engineer – Student",
    "job_type": "Part-time",
    "cycle": "2026/27",
    "link": "https://hatch.team/job/quality-test-automation-engineer-student-or-graduate-job_3InqLjwaM19g04p0S91X8Z6l0sL",
    "notes": "Via Hatch.",
    "status": "To apply",
    "priority": "Medium",
    "intl_ok": "Check",
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Signify",
    "role": "Dynalite R&D Intern",
    "job_type": "Part-time",
    "cycle": "2026/27",
    "link": "https://hatch.team/jobs/software-engineering/intern/sydney",
    "notes": "Search on Hatch page.",
    "status": "To apply",
    "priority": "Medium",
    "intl_ok": "Check",
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "SG Fleet",
    "role": "Internship Program 2027 – Software Engineering",
    "job_type": "Full-time",
    "cycle": "2026/27",
    "link": "https://au.gradconnection.com/employers/sg-fleet-group/jobs/",
    "notes": "LinkedIn recommended it.",
    "status": "To apply",
    "priority": "Medium",
    "intl_ok": "Check",
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Antares Solutions",
    "role": "Product Innovation & Technology Intern",
    "job_type": "Intern",
    "cycle": "2026/27",
    "link": "https://au.indeed.com/q-software-development-internship-l-sydney-nsw-jobs.html",
    "notes": "Find on Indeed search page.",
    "status": "To apply",
    "priority": "Medium",
    "intl_ok": "Check",
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "BHP",
    "role": "2027 Technology Internship (10–12 wk Summer)",
    "job_type": "Full-time",
    "cycle": "2026/27",
    "link": "https://au.prosple.com",
    "notes": "You pre-registered 31 Aug – apply the day it opens.",
    "status": "To apply",
    "priority": "Medium",
    "intl_ok": "Check",
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "Binance",
    "role": "Accelerator Program – Applied AI Agent Engineer",
    "job_type": "Remote",
    "cycle": "2026/27",
    "link": "https://au.indeed.com/q-software-development-internship-l-sydney-nsw-jobs.html",
    "notes": "Fully remote.",
    "status": "To apply",
    "priority": "Low",
    "intl_ok": "Check",
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "role",
    "company": "EY",
    "role": "2026/27 Vacationer Program – Computer Science",
    "job_type": "Full-time",
    "cycle": "2026/27",
    "link": "https://au.gradconnection.com/employers/ey/jobs/ey-202627-ey-vacationer-program-computer-science-2-2/",
    "notes": "You were rejected on eligibility in April – skip unless you have PR.",
    "status": "Skipped",
    "priority": "Low",
    "intl_ok": "No (citizen/PR)",
    "closes_on": "2026-10-16",
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": null
  },
  {
    "kind": "startup",
    "company": "Lorikeet",
    "role": "'Pitch us a role' – pitch a summer SWE intern",
    "job_type": "Open pitch",
    "cycle": null,
    "link": "https://jobs.ashbyhq.com/lorikeet/7c5d5246-4d18-41c4-a972-b87fdebccf06",
    "notes": "Hot Sydney AI startup. They invite pitches – send a 1-page 'what I'd build in 10 weeks'.",
    "status": "Not started",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": "Live posting · AI customer support agents (raised $75m)"
  },
  {
    "kind": "startup",
    "company": "Alignerr",
    "role": "Software Engineer (AI Training) – remote contract",
    "job_type": "Part-time / flexible",
    "cycle": null,
    "link": "https://au.linkedin.com/jobs/view/software-engineer-ai-training-%E2%80%94-remote-contract-at-alignerr-4461025894",
    "notes": "Paid, flexible hours. They already emailed you: your 15-min coding interview is still open.",
    "status": "Not started",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": "Live posting · AI training data (remote contract)"
  },
  {
    "kind": "startup",
    "company": "Sundrive Solar",
    "role": "Graduate / Intern Engineer – Expression of Interest",
    "job_type": "EOI",
    "cycle": null,
    "link": "https://jobs.blackbird.vc/companies/sundrive-solar/jobs/93480444-graduate-intern-engineer-expression-of-interest",
    "notes": "Posted 17 Sep. Software is one listed discipline – pitch data/automation work.",
    "status": "Not started",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": "Live posting · Solar cell tech (Blackbird-backed)"
  },
  {
    "kind": "startup",
    "company": "NinjaTech AI",
    "role": "Full Stack Software Engineer – Agentic AI (entry-level)",
    "job_type": "Full-time",
    "cycle": null,
    "link": "https://au.indeed.com/q-internship-software,-ai-l-sydney-nsw-jobs.html",
    "notes": "Entry-level. Ask if they take a summer intern instead.",
    "status": "Not started",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": "Live posting · Agentic AI assistants"
  },
  {
    "kind": "startup",
    "company": "Nuix",
    "role": "Associate Software Engineer, AI Team",
    "job_type": "Full-time",
    "cycle": null,
    "link": "https://au.linkedin.com/jobs/view/associate-software-engineer-ai-team-at-nuix-4442594641",
    "notes": "Entry-level AI role in Sydney.",
    "status": "Not started",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": "Live posting · Investigative analytics (scale-up)"
  },
  {
    "kind": "startup",
    "company": "Mutinex",
    "role": "Software Engineer – ask for summer intern",
    "job_type": "Full-time",
    "cycle": null,
    "link": "https://au.linkedin.com/jobs/view/software-engineer-at-mutinex-4448262572",
    "notes": "Small team = more ownership. Message the hiring manager directly.",
    "status": "Not started",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": "Live posting · Marketing-mix AI SaaS (early stage)"
  },
  {
    "kind": "startup",
    "company": "Nullify",
    "role": "Software Engineer – ask for summer intern",
    "job_type": "Full-time",
    "cycle": null,
    "link": "https://au.linkedin.com/jobs/view/software-engineer-nullify-at-black-nova-venture-capital-4458357510",
    "notes": "Security + AI – good if you like backend/pipelines.",
    "status": "Not started",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": "Live posting · AI app-security (Black Nova VC)"
  },
  {
    "kind": "startup",
    "company": "Blue Zebra",
    "role": "Software Engineer – ask for summer intern",
    "job_type": "Full-time",
    "cycle": null,
    "link": "https://au.linkedin.com/jobs/view/software-engineer-at-blue-zebra-4459255487",
    "notes": "New build team in Sydney.",
    "status": "Not started",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": "Live posting · Insurtech underwriting agency"
  },
  {
    "kind": "startup",
    "company": "Henderson Advocacy",
    "role": "Software Engineer – AI Systems & Automation",
    "job_type": "Full-time",
    "cycle": null,
    "link": "https://au.linkedin.com/jobs/view/software-engineer-ai-systems-automation-at-henderson-advocacy-4448957509",
    "notes": "Small business – often open to interns.",
    "status": "Not started",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": "Live posting · Property advisory using AI automation"
  },
  {
    "kind": "startup",
    "company": "Rokt",
    "role": "Junior Software Engineer",
    "job_type": "Full-time",
    "cycle": null,
    "link": "https://apply.workable.com/rokt/j/783A754DDB",
    "notes": "Check it's still open. Rokt runs a summer intern program – ask about 2026/27.",
    "status": "Not started",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": "Live posting · E-commerce tech (Sydney HQ scale-up)"
  },
  {
    "kind": "startup",
    "company": "Imitation Machines",
    "role": "Internship – Robot Learning / Robotics Software (UNPAID)",
    "job_type": "Intern (unpaid)",
    "cycle": null,
    "link": "https://www.adzuna.com.au",
    "notes": "From your Adzuna email 17 Sep. Unpaid – only if the learning is worth it.",
    "status": "Not started",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": "Live posting · Robot learning startup"
  },
  {
    "kind": "startup",
    "company": "Relevance AI",
    "role": "Email an engineer / founder – pitch summer intern",
    "job_type": "Cold",
    "cycle": null,
    "link": "https://jobs.ashbyhq.com/relevanceai",
    "notes": "Only senior roles listed, so go direct: LinkedIn message an engineering manager.",
    "status": "Not started",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": "Cold outreach · AI agent platform (Sydney HQ)"
  },
  {
    "kind": "startup",
    "company": "harrison.ai",
    "role": "Pitch ML / SWE summer intern",
    "job_type": "Cold",
    "cycle": null,
    "link": "https://harrison.ai",
    "notes": "No intern posting now – reach out to ML team members on LinkedIn.",
    "status": "Not started",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": "Cold outreach · Medical imaging AI"
  },
  {
    "kind": "startup",
    "company": "SafetyCulture",
    "role": "Summer internship EOI (ran one last year)",
    "job_type": "Watch",
    "cycle": null,
    "link": "https://jobs.blackbird.vc/companies/safetyculture-2-d0ff86a5-3d05-4aa1-a51f-a3a13f7b2cf7",
    "notes": "Last year's EOI was open – check if a 2026/27 one appears.",
    "status": "Not started",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": "Cold outreach · Workplace safety SaaS (scale-up)"
  },
  {
    "kind": "startup",
    "company": "UpGuard",
    "role": "Software Engineer – ask for intern",
    "job_type": "Cold",
    "cycle": null,
    "link": "https://startup.jobs/software-engineer-upguard-inc-10138695",
    "notes": "Posted 21 Sep, remote-friendly.",
    "status": "Not started",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": "Cold outreach · Cybersecurity SaaS"
  },
  {
    "kind": "startup",
    "company": "Secure Code Warrior",
    "role": "Software Engineer – ask for intern",
    "job_type": "Cold",
    "cycle": null,
    "link": "https://startup.jobs/software-engineer-secure-code-warrior-9870856",
    "notes": "Sydney hybrid.",
    "status": "Not started",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": "Cold outreach · Dev security training"
  },
  {
    "kind": "startup",
    "company": "Startup Link USYD",
    "role": "Ask organisers for founder intros",
    "job_type": "Network",
    "cycle": null,
    "link": "https://www.linkedin.com/search/results/all/?keywords=Startup%20Link%20USYD",
    "notes": "You were in their Hacker House (Apr) – use that network. Warm intros beat cold applications.",
    "status": "Not started",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": "Network · USYD startup community"
  },
  {
    "kind": "startup",
    "company": "Hatch",
    "role": "Check weekly",
    "job_type": "Board",
    "cycle": null,
    "link": "https://hatch.team/jobs/software-engineering/intern/sydney",
    "notes": "Part-time student roles (Deloitte etc.).",
    "status": "Not started",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": "Job board · Student jobs, many startups"
  },
  {
    "kind": "startup",
    "company": "Blackbird job board",
    "role": "Search 'intern' / 'graduate'",
    "job_type": "Board",
    "cycle": null,
    "link": "https://jobs.blackbird.vc/jobs",
    "notes": "Top AU startups.",
    "status": "Not started",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": "Job board · Startups Blackbird has invested in"
  },
  {
    "kind": "startup",
    "company": "Airtree job board",
    "role": "Search 'intern' / 'graduate'",
    "job_type": "Board",
    "cycle": null,
    "link": "https://jobs.airtree.vc/jobs",
    "notes": "Top AU startups.",
    "status": "Not started",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": "Job board · Startups Airtree has invested in"
  },
  {
    "kind": "startup",
    "company": "startup.jobs – Sydney",
    "role": "Check weekly",
    "job_type": "Board",
    "cycle": null,
    "link": "https://startup.jobs/locations/sydney",
    "notes": "Filter by software engineer.",
    "status": "Not started",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": "Job board · Startup job aggregator"
  },
  {
    "kind": "startup",
    "company": "Wellfound – Sydney",
    "role": "Set alert for 'intern'",
    "job_type": "Board",
    "cycle": null,
    "link": "https://wellfound.com/location/sydney",
    "notes": "Lets you message founders directly.",
    "status": "Not started",
    "priority": null,
    "intl_ok": null,
    "closes_on": null,
    "applied_on": null,
    "last_update": null,
    "next_action": null,
    "next_action_due": null,
    "about": "Job board · Startup jobs (was AngelList)"
  }
];
