import type { CompanySystemDesignSeed } from "./types";

const RUBRIC = ["Requirements clarification", "High-level architecture", "Data model", "Scaling & bottlenecks", "Trade-offs"];

export const AMAZON: CompanySystemDesignSeed = {
  company: "Amazon",
  questions: [
    {
      prompt:
        "Design a distributed rate limiter that Amazon's API gateway could use to throttle requests per customer/API-key across a fleet of gateway servers. It must be accurate under highly concurrent requests, add minimal latency, and must not become a single point of failure for the whole gateway.",
      modelAnswer:
        "Clarify the limit shape first: is it a fixed quota per fixed window (e.g. 1000 requests/minute), or a smoother rate (e.g. a token bucket allowing bursts up to a cap)? Sliding-window/token-bucket algorithms are usually preferred over fixed windows because a fixed window lets a client burst 2x its limit right across a window boundary (all its quota at the end of one window, then all its quota again at the start of the next).\n\nArchitecture: gateway servers are stateless and horizontally scaled, so the rate-limit counters can't live in any single gateway instance's memory — they need a shared, low-latency store. Use a centralized in-memory store (e.g. Redis) holding one counter (or token-bucket state) per API key, updated via an atomic increment-and-check operation (Redis's INCR plus TTL, or a Lua script for the token-bucket variant) so concurrent requests from the same key across different gateway hosts don't race past each other.\n\nData model is intentionally tiny: a key like `ratelimit:{apiKey}:{windowStart}` mapping to a count, with a TTL equal to the window length so old windows self-expire without a cleanup job. For the token-bucket variant, store `{tokens, lastRefillTimestamp}` per key and compute the refill amount lazily on each check rather than running a background refill process per key.\n\nScaling and single-point-of-failure concerns: a single Redis instance is both a latency risk (every request now round-trips to it) and an availability risk. Shard the store by API key hash across multiple Redis nodes so no one node is a hotspot, and run each shard as a small replicated cluster so a node failure doesn't wipe out rate-limit state for the keys it owned. For availability, the key trade-off is fail-open vs. fail-closed when the rate-limit store is unreachable: fail-open (let requests through) protects availability at the cost of temporarily losing throttling, which is usually the right default for a gateway, since an outage in the rate limiter should not take down the whole API — losing precision briefly is far cheaper than an outage.",
      rubric: RUBRIC,
    },
    {
      prompt:
        "Design the backend that manages product inventory and order placement for an e-commerce checkout flow at Amazon's scale. Cover how you prevent overselling when many customers try to buy the last few units of a popular item at the same time, and how an order flows through payment, inventory reservation, and fulfillment.",
      modelAnswer:
        "The central risk this design has to solve is overselling: two customers both see \"1 left in stock\" and both complete checkout. Naive read-then-write inventory checks (read the count, check it's > 0, decrement) race under concurrency. The fix is to make the decrement itself the check: an atomic conditional update like `UPDATE inventory SET quantity = quantity - 1 WHERE product_id = ? AND quantity > 0`, checking the affected-row count to know whether the reservation actually succeeded. This pushes the correctness guarantee into the database's atomicity rather than the application's read-then-write logic.\n\nOrder flow: checkout is a multi-step process — reserve inventory, charge payment, confirm the order, hand off to fulfillment — and these steps can each fail independently (payment declines after inventory is reserved, fulfillment is temporarily unavailable, etc.), so model it as an explicit state machine per order (e.g. `pending_payment -> paid -> reserved -> fulfilling -> shipped`, with a `cancelled`/`failed` branch from any state) rather than a single synchronous transaction spanning services that don't share a database. If payment fails after inventory was reserved, a compensating action releases the reservation (increment the quantity back) rather than trying to roll back a distributed transaction.\n\nData model: an `inventory` table keyed by (product_id, warehouse/fulfillment-center) since large catalogs are stocked across many locations, not one global count; an `orders` table holding the order's current state and a foreign key to its line items; and a `reservations` table linking an order to the specific inventory rows it holds, with a short expiry (e.g. 15 minutes) so an abandoned checkout releases its hold automatically via a background sweep rather than tying up stock indefinitely.\n\nScaling: shard inventory by product ID so hot products (flash-sale items) don't bottleneck the whole inventory service, and consider a short-lived per-product semaphore or queue in front of extremely hot items so thousands of simultaneous requests for the same nearly-sold-out product don't all hammer the same database row at once — trading a small amount of added latency for those specific items for much lower contention. The overall trade-off is strict consistency on the inventory count (never oversell, occasionally reject a checkout that a slightly-stale read would have allowed) over eventual consistency, which is the right choice here because the cost of overselling (a broken promise to a paying customer) is much higher than the cost of an occasional false \"out of stock.\"",
      rubric: RUBRIC,
    },
  ],
};
