import type { CompanySystemDesignSeed } from "./types";

const RUBRIC = ["Requirements clarification", "High-level architecture", "Data model", "Scaling & bottlenecks", "Trade-offs"];

export const ATLASSIAN: CompanySystemDesignSeed = {
  company: "Atlassian",
  questions: [
    {
      prompt:
        "Design the backend for a real-time collaborative document editor (like Confluence's live editing), where multiple users can type in the same document at once and see each other's changes within milliseconds, without overwriting each other's work.",
      modelAnswer:
        "The core problem is merging concurrent edits without last-write-wins clobbering someone's changes. The standard approaches are Operational Transformation (OT) — transforming each incoming operation against every operation it \"missed\" so it still applies correctly to the current document state — or a CRDT (Conflict-free Replicated Data Type) for text, which structures the document so concurrent operations commute and merge deterministically without needing a central transform step. OT is battle-tested (Google Docs) but the transform logic is notoriously easy to get subtly wrong; CRDTs are simpler to reason about per-operation but historically carried higher memory overhead per character, though modern CRDT implementations have mostly closed that gap. Either is a defensible choice; the important part is naming the trade-off rather than hand-waving \"just merge the changes.\"\n\nArchitecture: each open document has a single authoritative session, hosted by one server process (or a per-document actor) that all connected clients' edits flow through over a persistent connection (WebSocket). That server holds the current in-memory document state plus the operation log needed for OT/CRDT reconciliation, broadcasts each accepted operation to every other connected client, and periodically flushes a snapshot plus the operation log to durable storage. Routing all of a document's traffic to one owning process avoids needing distributed consensus on every keystroke, at the cost of needing a way to reassign ownership if that process dies (a lease held in a coordination store, re-acquired by another process on failure).\n\nData model: durable storage holds periodic full-document snapshots (so reload doesn't require replaying the entire edit history since document creation) plus an append-only operation log since the last snapshot, tagged with a monotonically increasing sequence number the OT/CRDT algorithm uses to order and transform operations. Presence data (who's currently in the document, their cursor position) is ephemeral and lives only in the owning process's memory plus a lightweight broadcast to connected clients — it doesn't need durability.\n\nScaling: because each document's edit traffic is owned by one process, horizontal scale comes from spreading documents across many such processes (sharded by document ID) rather than scaling a single document's throughput, which is inherently bounded by how fast one process can sequence operations — an acceptable trade-off since even a very actively co-edited document sees nowhere near the write volume of, say, a global inventory counter.",
      rubric: RUBRIC,
    },
    {
      prompt:
        "Design the backend for an issue-tracking system (like Jira) that supports millions of projects, each with potentially thousands of issues, flexible custom fields per project, and fast full-text plus filtered search across a user's accessible projects.",
      modelAnswer:
        "Two requirements pull the data model in different directions: flexible per-project custom fields (schema that varies per tenant) and fast filtered search (which favors a fixed, indexable schema). Resolve this by splitting storage: a relational store holds the fixed core fields every issue has regardless of project (id, project_id, title, status, assignee, created_at, updated_at) as real indexed columns, while custom fields are stored as a separate key-value structure (an EAV-style table, or a JSON/JSONB column) keyed by issue ID and field ID, since custom fields vary per project and a fully dynamic ALTER TABLE-per-project approach doesn't scale operationally.\n\nSearch is a separate concern from the system of record: issues are written to the relational store first (the source of truth for correctness — an issue's existence and core state must never depend on a search index being up to date), then asynchronously indexed into a dedicated search engine (e.g. an inverted-index/full-text search system) that combines the core fields, custom field values, and issue description/comment text into one searchable document per issue, tagged with the project ID and the set of permission groups allowed to see it. Filtered search queries (\"status = open AND assignee = me AND project in my-accessible-projects\") run against this search index rather than the relational store, since it's purpose-built for combining full-text matching with structured filtering at low latency.\n\nData model, concretely: `issues` (core fixed columns, one row per issue, partitioned/sharded by project_id since a project's issues are almost always queried together), `custom_field_values` (issue_id, field_id, value), and a `comments` table keyed by issue_id. The search index is a derived, rebuildable copy — if it's lost or falls behind, it can be fully reconstructed by re-reading the relational store, which is the standard justification for treating an async index as eventually consistent rather than trying to keep it transactionally in sync.\n\nScaling: shard the relational store by project_id, since almost every real query (\"show me this project's board\") is scoped to one project, making cross-shard queries rare. The main trade-off is search freshness — a newly created issue might take a few hundred milliseconds to a few seconds to become searchable, since indexing is asynchronous — which is an acceptable lag for a project-management tool where search freshness is not safety-critical, unlike the issue's actual state in the system of record.",
      rubric: RUBRIC,
    },
  ],
};
