import type { CompanySystemDesignSeed } from "./types";

const RUBRIC = ["Requirements clarification", "High-level architecture", "Data model", "Scaling & bottlenecks", "Trade-offs"];

export const META: CompanySystemDesignSeed = {
  company: "Meta",
  questions: [
    {
      prompt:
        "Design a URL shortening service (like bit.ly) that Meta could run internally for sharing links across its apps. Reads (redirects) vastly outnumber writes (link creation), and a single link can suddenly go viral. Cover the API, the short-code generation strategy, storage, and how you'd keep redirects fast under a traffic spike.",
      modelAnswer:
        "Clarify scale first: assume on the order of a few hundred million new links a month and redirect traffic two to three orders of magnitude higher than that, with p99 redirect latency in the tens of milliseconds. The write path is a single POST /links endpoint that takes a long URL and returns a short code; the read path is GET /{code}, which looks up the long URL and issues an HTTP 301/302 redirect.\n\nFor code generation, avoid a naive incrementing counter shared across writers (contention, and it leaks creation order). Instead, hand out non-overlapping counter ranges to each write-serving host from a lightweight coordination service (or use a Snowflake-style ID: timestamp + shard ID + sequence), then base62-encode the resulting integer into a 6-8 character code. This keeps writes fully parallel with no cross-host locking, at the cost of a small amount of wasted range if a host restarts mid-range — an acceptable trade for a keyspace this large.\n\nData model: a single table keyed by short_code, storing long_url, created_at, and optionally an expiry. This is a pure key-value access pattern, so back it with a key-value store (or a sharded relational table keyed by short_code) rather than anything that needs joins. Because reads dominate by orders of magnitude, put a CDN/edge cache or a large in-memory cache (e.g. Redis) in front of the datastore, keyed by short_code, with a long TTL — a short code's mapping never changes once created, so cache invalidation is a non-issue; the only invalidation event is explicit link deletion.\n\nScaling and the viral-link case: with the cache layer above, even a single link taking 100k+ requests/second is just a hot cache key, which in-memory caches handle far better than hitting the backing store repeatedly. Shard the backing store by short_code hash so no single shard is a bottleneck for the write path or for cache-miss traffic. The main trade-off is cache staleness vs. simplicity — since mappings are immutable, this is the rare case where an aggressive cache has no real downside.",
      rubric: RUBRIC,
    },
    {
      prompt:
        "Design the backend for a social news feed (like Facebook's) that ranks and delivers posts from a user's friends/follows in near real time. Cover the write path (fan-out on write vs. fan-out on read), the ranking step, and how the feed stays fresh without being recomputed from scratch on every page load.",
      modelAnswer:
        "Start by separating two problems that are often conflated: distribution (getting a new post in front of the right followers) and ranking (deciding what order to show them in). For distribution, the standard trade-off is fan-out-on-write (push a new post into every follower's precomputed feed at publish time) vs. fan-out-on-read (merge each followee's recent posts at request time). Fan-out-on-write is cheap to read but expensive to write for accounts with huge follower counts (a celebrity post fanning out to millions of feed lists); fan-out-on-read is the reverse. The standard hybrid: fan out on write for ordinary users, but for accounts above a follower threshold, skip the fan-out and merge their posts in at read time for the (relatively few) users who follow them.\n\nEach user's precomputed feed is a bounded-length list (e.g. the most recent few hundred candidate post IDs, not full post bodies) stored in a fast key-value store, since post content itself is fetched separately and can change (edits, deletion) after the feed entry was written. A separate post-storage service holds the actual content, sharded by post ID.\n\nRanking is a separate service that takes the candidate post IDs for a feed request (merging the precomputed list with any real-time fan-out-on-read posts) and scores them using signals like recency, the viewer's historical engagement with the poster, and content type — this can start as a straightforward weighted-feature score and later be replaced with a learned model without changing the surrounding architecture, since ranking is cleanly isolated behind a \"given these candidate IDs and this viewer, return a ranked order\" interface.\n\nFreshness without full recomputation: the client requests a bounded page of ranked posts and remembers a cursor (e.g. the last-seen post's rank score or timestamp); the next page request only needs to rank posts on either side of that cursor, not the whole history. New posts arriving after the user started scrolling are queued into a small \"new posts\" banner rather than reshuffling posts already on screen, which is both a UX improvement and an implementation simplification. The key trade-off throughout is push (fast reads, background cost, some staleness for busy accounts) vs. pull (always fresh, but a heavier request-time computation) — the hybrid exists because no single choice is right at both ends of the follower-count distribution.",
      rubric: RUBRIC,
    },
  ],
};
