import type { ExamPaperSeed } from "../types";

const PAPER: ExamPaperSeed = {
  course: "INFO6007",
  week: 8,
  paperNumber: 3,
  title: "Final Exam Practice Paper (Weeks 1–8, essay/scenario style)",
  topics:
    "A closed-book style essay paper matching the Final Exam's stated format: 4 essay questions, each with 3-4 parts, each built around a brief scenario that can draw on any topic from any lecture or tutorial. Draws on: Week 1 (project vs program vs portfolio, the Triple Constraint, the Project Charter, stakeholder identification); Week 2 (Waterfall vs Agile/Scrum vs Kanban methodology selection, the Power/Interest Grid); Week 3 (WBS decomposition and the 100% rule, AON scheduling chains, schedule compression via crashing and fast-tracking); Week 4 (contingency vs management reserves, Earned Value Management — CPI and SPI); Week 5 and 6 (Pareto charts and fishbone/Ishikawa diagrams, the Cost of Quality — prevention vs external failure cost); Week 6 and 7 (resource loading and leveling, Tuckman stages, Lencioni-style team dysfunctions, Herzberg's two-factor motivation theory); and Week 7 and 8 (positive/negative risk response strategies, Expected Monetary Value, Make-or-Buy analysis, contract type selection, the weighted scoring vendor evaluation model). Each question deliberately combines concepts from at least two different weeks, the way the real cumulative final exam is described as doing.",
  sourceFiles: [
    "exam-content/info6007/week-1.ts",
    "exam-content/info6007/week-2.ts",
    "exam-content/info6007/week-3.ts",
    "exam-content/info6007/week-4.ts",
    "exam-content/info6007/week-5.ts",
    "exam-content/info6007/week-6.ts",
    "exam-content/info6007/week-7.ts",
    "exam-content/info6007/week-8.ts",
  ],
  questions: [
    {
      type: "scenario",
      prompt:
        "Scenario: A national supermarket chain is running three linked initiatives from one shared technology budget: (1) a new customer-facing loyalty and rewards mobile app, (2) a backend inventory-forecasting upgrade, and (3) a staff rostering system replacement. The three initiatives are only loosely connected — each has its own team and its own timeline, and none of them depends on outputs from the other two to succeed. The company's Head of Digital is now scoping the loyalty app in detail.\n\n(a) Using the definitions of a project, a program, and a portfolio, which term best describes the collection of all three initiatives together, and why does it not qualify as the other two?",
      modelAnswer:
        "Think of the supermarket's tech budget like a household's monthly spending money split across three separate hobbies — one person's gym membership, another's guitar lessons, a third's cooking classes. They all draw from the same pot of money, but finishing the gym membership doesn't help anyone play guitar better.\n\n• What the three initiatives are together: they form a portfolio, not a program. A program only applies when projects are coordinated together to unlock a benefit that none of them could deliver alone, like puzzle pieces that only show the full picture combined. Here the loyalty app, the inventory upgrade, and the rostering system each stand on their own and don't depend on each other's results, so they're just grouped together because they share the same investment budget and strategic goal, which is exactly what a portfolio is, managed by a portfolio manager or PMO.\n\n• Why not a single project: a project is one temporary effort producing one unique outcome, and here there are three separate outcomes, not one.\n\n• Why not a program: a program specifically needs coordination between its pieces to create extra benefit beyond what each could deliver alone, and this scenario says the three initiatives are only loosely connected, each with its own team and timeline, with no such dependency between them.\n\nSo the answer: the three initiatives together form a portfolio, not a project or a program, because they share one budget and strategic goal without depending on each other's outputs.",
    },
    {
      type: "scenario",
      prompt:
        "Scenario: A national supermarket chain is running three linked initiatives from one shared technology budget: (1) a new customer-facing loyalty and rewards mobile app, (2) a backend inventory-forecasting upgrade, and (3) a staff rostering system replacement. The three initiatives are only loosely connected — each has its own team and its own timeline, and none of them depends on outputs from the other two to succeed. The company's Head of Digital is now scoping the loyalty app in detail.\n\n(b) Three months into building the loyalty app, the marketing team insists a new referral-bonus feature be added, but the CEO refuses to move the original 4-month launch date. Using the Triple Constraint, explain what must happen to the project's cost or scope as a result, and why leaving both unchanged is not realistic.",
      modelAnswer:
        "Picture scope, time and cost as three corners of a triangle held together by rubber bands, so pulling on one corner stretches the others.\n\n• What adding the referral-bonus feature does: it grows the scope corner of the triangle, since the team now has to build something that wasn't in the original plan.\n\n• Why cost has to move: the CEO is refusing to loosen the time corner by keeping the 4-month deadline fixed, so the cost corner is the only one left that can stretch to absorb the extra scope, meaning the team needs a bigger budget, for example to pay for extra developers or overtime, to fit the new feature into the same timeframe.\n\n• Why leaving both unchanged fails: the whole point of the Triple Constraint is that these three factors are locked together, so demanding more scope while refusing to move time or cost is like asking for a fourth corner on a triangle — something always gives, whether the team admits it or not, and if nobody manages that trade-off explicitly, quality is usually what secretly breaks instead, since it sits at the centre of the triangle absorbing the pressure.\n\nSo the answer: since scope is growing and time is fixed, cost must increase to absorb the referral-bonus feature — leaving both cost and scope unchanged isn't realistic because it ignores where the extra pressure in the triangle has to go.",
    },
    {
      type: "scenario",
      prompt:
        "Scenario: A national supermarket chain is running three linked initiatives from one shared technology budget: (1) a new customer-facing loyalty and rewards mobile app, (2) a backend inventory-forecasting upgrade, and (3) a staff rostering system replacement. The three initiatives are only loosely connected — each has its own team and its own timeline, and none of them depends on outputs from the other two to succeed. The company's Head of Digital is now scoping the loyalty app in detail.\n\n(c) The loyalty app has two distinct pieces of work: the core points-and-rewards engine, where requirements are locked in by a signed vendor contract and won't change, and the in-app promotional banners, which the marketing team wants to keep tweaking weekly based on customer click-through data even after launch. Recommend a delivery methodology for each of these two pieces and justify each choice.",
      modelAnswer:
        "Think of the rewards engine like a signed building contract with fixed blueprints that can't change once construction starts, and the promotional banners like a shop window display that gets restyled every week based on what's actually selling.\n\n• Methodology for the rewards engine: use Waterfall. The requirements are locked in by a signed vendor contract and are not expected to change, which is exactly the situation Waterfall is built for, since it plans every phase upfront and doesn't adapt well to change once development begins.\n\n• Methodology for the banners: use Scrum or Kanban. The requirements keep evolving from real customer click-through data even after launch, which matches Agile's value of responding to change over following a fixed plan — Scrum would suit a Product Owner prioritising a backlog in fixed cycles, while Kanban would suit better if updates need to flow continuously with no fixed iteration length.\n\nSo the answer: the rewards engine should use Waterfall because its requirements are frozen by contract, while the banners should use Scrum or Kanban because they need to keep changing after launch.",
    },
    {
      type: "scenario",
      prompt:
        "Scenario: A national supermarket chain is running three linked initiatives from one shared technology budget: (1) a new customer-facing loyalty and rewards mobile app, (2) a backend inventory-forecasting upgrade, and (3) a staff rostering system replacement. The three initiatives are only loosely connected — each has its own team and its own timeline, and none of them depends on outputs from the other two to succeed. The company's Head of Digital is now scoping the loyalty app in detail.\n\n(d) Name the one formal document that authorises the loyalty app project and grants the project manager authority to use company resources, then identify two stakeholders for this project and explain how each should be engaged based on their power and interest in the outcome.",
      modelAnswer:
        "Think of the Project Charter like a work permit that officially lets someone start a building site and use the crew and equipment on it — without it, nobody has the authority to actually begin.\n\n• The authorising document: it's the Project Charter, the formal document that authorises the project and gives the project manager the authority to use organisational resources.\n\n• Stakeholder 1, the CEO: high power and high interest, since they control the budget and the deadline, so they need close, active, regular engagement — the kind of stakeholder you manage closely and keep no surprises from.\n\n• Stakeholder 2, the marketing team: lower power but high interest, since they want the referral feature but don't control the final deadline decision, so they should be kept informed and consulted rather than managed as closely as the CEO.\n\nSo the answer: the Project Charter authorises the project; the CEO, as high power/high interest, should be managed closely, while the marketing team, as lower power/high interest, should be kept informed and consulted.",
    },
    {
      type: "scenario",
      prompt:
        "Scenario: An insurance company is building a claims-processing portal. The work is a single sequential chain: Requirements (2 weeks) then Design (3 weeks) then Development (6 weeks) then Testing (4 weeks) then Deployment (1 week), each activity only able to start once the one before it finishes. Four weeks into Development, the team discovers a legacy data-migration requirement that will add 3 extra weeks to Development.\n\n(a) Using WBS principles, name the WBS approach that would decompose 'Development' into concrete work packages like 'build claims intake API' and 'build document upload module', and state one rule the WBS must follow.",
      modelAnswer:
        "Think of 'Development' like a builder given the job 'build the house' — that's too vague to hand to anyone, so the builder breaks it into work packages like 'pour the foundation', 'frame the walls' and 'wire the electrics', each one small enough that a single crew knows exactly what they owe.\n\n• The WBS approach: this is decomposition — breaking a big deliverable like 'Development' down into smaller, concrete work packages such as 'build claims intake API' and 'build document upload module', the same way the house gets broken into named trades.\n\n• The rule it must follow: the 100% rule — the WBS must capture 100% of the work required to deliver 'Development', with everything at each level adding up to exactly what the level above it covers, no more and no less. Skipping a piece of work means it silently falls through the cracks; adding scope that isn't really part of 'Development' means the work packages stop matching the plan.\n\nSo the answer: decomposition breaks 'Development' down into concrete work packages, and the WBS must obey the 100% rule — capturing all of the work, and nothing outside it.",
    },
    {
      type: "scenario",
      prompt:
        "Scenario: An insurance company is building a claims-processing portal. The work is a single sequential chain: Requirements (2 weeks) then Design (3 weeks) then Development (6 weeks) then Testing (4 weeks) then Deployment (1 week), each activity only able to start once the one before it finishes. Four weeks into Development, the team discovers a legacy data-migration requirement that will add 3 extra weeks to Development.\n\n(b) Given the chain above, what is the new total project duration if no schedule compression is applied, and name ONE schedule compression technique the project manager could use to try to recover time, describing briefly what it does.",
      modelAnswer:
        "Picture the five phases as train carriages coupled one behind the other on a single track — if one carriage gets longer, every carriage behind it arrives later, because none of them can move until the one in front has fully passed.\n\n• The new duration: the original chain is 2 (Requirements) + 3 (Design) + 6 (Development) + 4 (Testing) + 1 (Deployment) weeks, which adds up to 16 weeks. Since Development now needs 3 extra weeks and every activity is finish-to-start with nothing running in parallel, the new total duration without any compression is 19 weeks.\n\n• A compression technique: crashing — adding extra resources, such as more developers, to the delayed Development activity to shorten how long it takes, usually at extra cost. The alternative is fast-tracking, where normally sequential activities are run in parallel instead, for example starting Testing on the parts of Development that are already finished before the whole phase wraps up — that saves time but raises the risk of rework if problems turn up late.\n\nSo the answer: without compression the project now takes 19 weeks, and the project manager could try crashing (add resources to speed up Development) or fast-tracking (overlap Development and Testing) to try to recover some of that lost time.",
    },
    {
      type: "scenario",
      prompt:
        "Scenario: An insurance company is building a claims-processing portal. The work is a single sequential chain: Requirements (2 weeks) then Design (3 weeks) then Development (6 weeks) then Testing (4 weeks) then Deployment (1 week), each activity only able to start once the one before it finishes. Four weeks into Development, the team discovers a legacy data-migration requirement that will add 3 extra weeks to Development.\n\n(c) At the point the extra work was discovered, the project's planned value is $200,000, its earned value is $150,000, and its actual cost is $180,000. Calculate CPI and SPI and state, in plain terms, what each number says about cost and schedule performance.",
      modelAnswer:
        "Think of Earned Value Management like a report card that compares three numbers: what you planned to have done by now, what you've actually finished, and what you've spent getting there.\n\n• CPI (cost performance): CPI equals earned value divided by actual cost, so $150,000 ÷ $180,000 ≈ 0.83. A CPI below 1 means the project is over budget — for every dollar spent, it's only getting about 83 cents of planned value back, like paying $180,000 for work that should have cost $150,000.\n\n• SPI (schedule performance): SPI equals earned value divided by planned value, so $150,000 ÷ $200,000 = 0.75. An SPI below 1 means the project is behind schedule — it has only completed 75% of the work value it should have achieved by this point, which lines up with the 3 extra weeks just discovered in Development.\n\nSo the answer: CPI ≈ 0.83 and SPI = 0.75 — both numbers below 1 mean the project is simultaneously over budget and behind schedule.",
    },
    {
      type: "scenario",
      prompt:
        "Scenario: An insurance company is building a claims-processing portal. The work is a single sequential chain: Requirements (2 weeks) then Design (3 weeks) then Development (6 weeks) then Testing (4 weeks) then Deployment (1 week), each activity only able to start once the one before it finishes. Four weeks into Development, the team discovers a legacy data-migration requirement that will add 3 extra weeks to Development.\n\n(d) The company holds a $50,000 contingency reserve set aside specifically for known risks like this one, separate from a management reserve held for unknown risks. Explain which reserve should fund the 3-week data-migration delay and why.",
      modelAnswer:
        "Think of a contingency reserve like an umbrella you packed because the forecast already said 'chance of rain', versus a management reserve like emergency cash kept aside for a disaster nobody could have predicted at all.\n\n• Which reserve applies: the contingency reserve should fund the 3-week data-migration delay.\n\n• Why: contingency reserves are specifically set aside for known risks — things the team already identified as possible before they happened — and a legacy data-migration complication in an insurance claims system is exactly the sort of risk a project like this would anticipate in advance. The management reserve, by contrast, is held back for unknown, unforeseeable risks that genuinely couldn't have been planned for, so using it here would be like raiding an emergency fund for a bill you already knew was probably coming.\n\nSo the answer: the $50,000 contingency reserve should fund the data-migration delay, because it's a known risk the project should already have anticipated, not an unknown one.",
    },
    {
      type: "scenario",
      prompt:
        "Scenario: A payroll software vendor received 40 defect reports last month. When grouped by cause, 32 of the 40 trace back to one single cause: incorrect handling of public-holiday pay rates. Fixing that logic properly now, including adding automated test coverage, is estimated to cost $2,000. Leaving it and continuing to pay for customer support and refunds each time it fails in production is estimated to cost $20,000 over the same period. Separately, the 3-person QA team is unevenly loaded: two testers are each scheduled for 50 hours of testing work next week but only have 35 hours of availability, while the third tester has just 10 hours booked against 35 hours available. The QA lead has also noticed that when one tester quietly falls behind on their assigned tickets, the other two just pick up the extra work themselves rather than raising it in the daily stand-up.\n\n(a) Which quality tool would best confirm that 'incorrect public-holiday pay rate handling' really is the dominant cause worth fixing first, given 32 of the 40 defects trace to it, and which tool would you then use to explore why that specific cause keeps happening?",
      modelAnswer:
        "Picture detectives investigating repeated break-ins at a warehouse — they need to work out which door the burglar is actually using before spending money fixing every window in the building.\n\n• Confirming the dominant cause: a Pareto chart is the right tool. It ranks defect causes by frequency, and here it would show public-holiday pay handling — 32 of 40 defects — as by far the biggest slice, the classic 80/20 pattern where a small number of causes account for most of the problems.\n\n• Exploring why it keeps happening: once that cause is confirmed as the priority, a fishbone (Ishikawa) diagram is the tool to dig into why, branching out possible root causes such as outdated pay-rate reference data or untested edge cases around public holidays.\n\nSo the answer: a Pareto chart confirms public-holiday handling as the dominant cause, and a fishbone diagram is then used to explore why it keeps happening.",
    },
    {
      type: "scenario",
      prompt:
        "Scenario: A payroll software vendor received 40 defect reports last month. When grouped by cause, 32 of the 40 trace back to one single cause: incorrect handling of public-holiday pay rates. Fixing that logic properly now, including adding automated test coverage, is estimated to cost $2,000. Leaving it and continuing to pay for customer support and refunds each time it fails in production is estimated to cost $20,000 over the same period. Separately, the 3-person QA team is unevenly loaded: two testers are each scheduled for 50 hours of testing work next week but only have 35 hours of availability, while the third tester has just 10 hours booked against 35 hours available. The QA lead has also noticed that when one tester quietly falls behind on their assigned tickets, the other two just pick up the extra work themselves rather than raising it in the daily stand-up.\n\n(b) Using the Cost of Quality framework, name which category each of the $2,000 and $20,000 costs falls under, and state which one the company should choose.",
      modelAnswer:
        "Think of the $2,000 like paying for a smoke detector before a fire, and the $20,000 like paying to rebuild a kitchen after one has already happened.\n\n• The $2,000 (fixing the logic and adding test coverage upfront): this is a Cost of Conformance, specifically a prevention cost — money spent to stop the defect from happening in the first place.\n\n• The $20,000 (support and refunds every time the bug reaches customers): this is a Cost of Non-Conformance, specifically an external failure cost — the cost of a defect that has already escaped all the way to the customer.\n\n• Which to choose: the company should spend the $2,000 on prevention, since it's ten times cheaper than continuing to absorb $20,000 in external failure costs for the same underlying problem — paying a small amount upfront to prevent a defect is almost always cheaper than paying to clean up after it reaches production.\n\nSo the answer: the $2,000 is a prevention cost, the $20,000 is an external failure cost, and the company should choose to spend the $2,000 on prevention.",
    },
    {
      type: "scenario",
      prompt:
        "Scenario: A payroll software vendor received 40 defect reports last month. When grouped by cause, 32 of the 40 trace back to one single cause: incorrect handling of public-holiday pay rates. Fixing that logic properly now, including adding automated test coverage, is estimated to cost $2,000. Leaving it and continuing to pay for customer support and refunds each time it fails in production is estimated to cost $20,000 over the same period. Separately, the 3-person QA team is unevenly loaded: two testers are each scheduled for 50 hours of testing work next week but only have 35 hours of availability, while the third tester has just 10 hours booked against 35 hours available. The QA lead has also noticed that when one tester quietly falls behind on their assigned tickets, the other two just pick up the extra work themselves rather than raising it in the daily stand-up.\n\n(c) The two overloaded testers and the underused third tester describe a resource loading problem. Explain what should be done to fix the imbalance, and name the technique being used.",
      modelAnswer:
        "Picture three delivery drivers sharing one route roster — two of them are handed twice as many parcels as they can carry in a shift, while the third drives around half-empty.\n\n• The imbalance: the two testers booked for 50 hours against only 35 hours available are over-allocated, while the third tester, booked for just 10 hours against 35 available, has plenty of spare capacity.\n\n• The fix: shift some of the excess testing work from the two overloaded testers onto the underused third tester's spare capacity, so nobody is scheduled beyond what they can realistically deliver, even if that means some tasks shift a little later.\n\n• The technique: this is resource leveling — adjusting a schedule so that resource demand doesn't exceed the resources actually available, smoothing out peaks and troughs in workload.\n\nSo the answer: the fix is to move excess work from the two overloaded testers to the underused third tester, using the technique of resource leveling.",
    },
    {
      type: "scenario",
      prompt:
        "Scenario: A payroll software vendor received 40 defect reports last month. When grouped by cause, 32 of the 40 trace back to one single cause: incorrect handling of public-holiday pay rates. Fixing that logic properly now, including adding automated test coverage, is estimated to cost $2,000. Leaving it and continuing to pay for customer support and refunds each time it fails in production is estimated to cost $20,000 over the same period. Separately, the 3-person QA team is unevenly loaded: two testers are each scheduled for 50 hours of testing work next week but only have 35 hours of availability, while the third tester has just 10 hours booked against 35 hours available. The QA lead has also noticed that when one tester quietly falls behind on their assigned tickets, the other two just pick up the extra work themselves rather than raising it in the daily stand-up.\n\n(d) Name the team dysfunction shown by testers not calling out a colleague who has fallen behind on commitments, and recommend one motivation-theory-based leadership action to help fix it.",
      modelAnswer:
        "Think of a group assignment where everyone notices a classmate skipping their part, but nobody says anything and the rest of the group just quietly does the extra work instead.\n\n• The dysfunction: this is avoidance of accountability, one of Lencioni's five team dysfunctions — team members see a colleague falling behind on their commitments but don't hold them to account, silently absorbing the extra work rather than raising it.\n\n• The leadership action: applying Herzberg's two-factor theory, the QA lead should focus on motivators rather than hygiene factors — for example, building real ownership and recognition into how tickets are tracked, so it becomes visible and valued when someone finishes their share, rather than hoping unspoken peer pressure alone will close the accountability gap.\n\nSo the answer: the dysfunction is avoidance of accountability, and the fix is a motivator-focused leadership action, such as making individual ownership and recognition visible, rather than just a process reminder.",
    },
    {
      type: "scenario",
      prompt:
        "Scenario: A bank is migrating its core ledger system to the cloud. Two risks have been identified: Risk X, a 20% chance the new cloud provider's authentication API has a compatibility issue requiring $150,000 of rework, and Risk Y, a 30% chance the migration finishes early enough to trigger a $40,000 early-delivery bonus from the sponsor. Separately, the bank is deciding whether to build a new fraud-detection module in-house or buy an existing vendor product; the module has strict, well-understood regulatory requirements that are unlikely to change, and the bank has no in-house team with fraud-detection expertise. The bank is evaluating two vendors, DataGuard and TrustShield, against three weighted criteria: cost (weight 0.5), security certification (weight 0.3), and integration support (weight 0.2). On a 10-point scale, DataGuard scores 6 on cost, 9 on security, and 7 on integration; TrustShield scores 8 on cost, 6 on security, and 9 on integration.\n\n(a) Classify Risk X and Risk Y as positive or negative risks, and name one appropriate response strategy for each, explaining why that strategy fits.",
      modelAnswer:
        "Think of Risk X like a possible pothole on the road ahead — something that could damage the trip — and Risk Y like a lottery ticket sitting in the glovebox — a nice bonus if it pays off, but not something to bet the whole trip on.\n\n• Risk X: this is a negative risk, a threat — a 20% chance of a $150,000 rework cost if the authentication API has a compatibility issue. The appropriate response is to mitigate it, for example by running a compatibility test with the new provider's authentication API early, before full migration, to reduce the chance or impact of the problem rather than just hoping it won't happen.\n\n• Risk Y: this is a positive risk, an opportunity — a 30% chance of a $40,000 bonus for finishing early. The appropriate response is to exploit it, for example by adding extra short-term resources to the migration specifically to try to guarantee that early finish.\n\nSo the answer: Risk X is a negative risk to mitigate (test the authentication API early), and Risk Y is a positive risk to exploit (push resources at guaranteeing the early finish).",
    },
    {
      type: "scenario",
      prompt:
        "Scenario: A bank is migrating its core ledger system to the cloud. Two risks have been identified: Risk X, a 20% chance the new cloud provider's authentication API has a compatibility issue requiring $150,000 of rework, and Risk Y, a 30% chance the migration finishes early enough to trigger a $40,000 early-delivery bonus from the sponsor. Separately, the bank is deciding whether to build a new fraud-detection module in-house or buy an existing vendor product; the module has strict, well-understood regulatory requirements that are unlikely to change, and the bank has no in-house team with fraud-detection expertise. The bank is evaluating two vendors, DataGuard and TrustShield, against three weighted criteria: cost (weight 0.5), security certification (weight 0.3), and integration support (weight 0.2). On a 10-point scale, DataGuard scores 6 on cost, 9 on security, and 7 on integration; TrustShield scores 8 on cost, 6 on security, and 9 on integration.\n\n(b) Calculate the Expected Monetary Value of both Risk X and Risk Y, and explain what the combined figure tells the bank about the migration's overall risk exposure.",
      modelAnswer:
        "Think of Expected Monetary Value like weighing up a bet: how likely is it, and how much is actually at stake if it lands?\n\n• Risk X's EMV: 20% × –$150,000 = –$30,000.\n\n• Risk Y's EMV: 30% × +$40,000 = +$12,000.\n\n• What the combined figure means: adding the two together gives a combined EMV of –$18,000, meaning that on balance the bank should expect to come out $18,000 behind overall from these two risks together — the potential downside from the authentication risk outweighs the potential upside from the early-finish bonus, so the bank should prioritise mitigating Risk X over chasing Risk Y.\n\nSo the answer: Risk X's EMV is –$30,000, Risk Y's EMV is +$12,000, and the combined –$18,000 means the migration is net risk-exposed, with the authentication threat outweighing the bonus opportunity.",
    },
    {
      type: "scenario",
      prompt:
        "Scenario: A bank is migrating its core ledger system to the cloud. Two risks have been identified: Risk X, a 20% chance the new cloud provider's authentication API has a compatibility issue requiring $150,000 of rework, and Risk Y, a 30% chance the migration finishes early enough to trigger a $40,000 early-delivery bonus from the sponsor. Separately, the bank is deciding whether to build a new fraud-detection module in-house or buy an existing vendor product; the module has strict, well-understood regulatory requirements that are unlikely to change, and the bank has no in-house team with fraud-detection expertise. The bank is evaluating two vendors, DataGuard and TrustShield, against three weighted criteria: cost (weight 0.5), security certification (weight 0.3), and integration support (weight 0.2). On a 10-point scale, DataGuard scores 6 on cost, 9 on security, and 7 on integration; TrustShield scores 8 on cost, 6 on security, and 9 on integration.\n\n(c) Using Make-or-Buy reasoning, recommend build or buy for the fraud-detection module, and then recommend a contract type (fixed-price, cost-reimbursable, or time-and-materials) that matches the risk allocation the bank would want.",
      modelAnswer:
        "Think of Make-or-Buy like deciding whether to cook a meal from scratch or order from a restaurant that already specialises in exactly that dish — if you have no kitchen skills and the recipe is fixed and well known, ordering in makes more sense.\n\n• Build or buy: the bank should buy the fraud-detection module rather than build it. The requirements are strict, well understood, and unlikely to change, which removes the main reason to build custom software, and the bank has no in-house fraud-detection expertise, meaning building it internally would carry high delivery risk on top of the missing skill set.\n\n• Contract type: a fixed-price contract fits best, because the requirements are well-defined and stable. Fixed-price contracts put the risk of cost overruns on the seller for a clearly scoped deliverable — a time-and-materials or cost-reimbursable contract would make more sense if the requirements were still uncertain, since those contract types shift more of the risk onto the buyer in exchange for flexibility.\n\nSo the answer: buy the fraud-detection module, under a fixed-price contract.",
    },
    {
      type: "scenario",
      prompt:
        "Scenario: A bank is migrating its core ledger system to the cloud. Two risks have been identified: Risk X, a 20% chance the new cloud provider's authentication API has a compatibility issue requiring $150,000 of rework, and Risk Y, a 30% chance the migration finishes early enough to trigger a $40,000 early-delivery bonus from the sponsor. Separately, the bank is deciding whether to build a new fraud-detection module in-house or buy an existing vendor product; the module has strict, well-understood regulatory requirements that are unlikely to change, and the bank has no in-house team with fraud-detection expertise. The bank is evaluating two vendors, DataGuard and TrustShield, against three weighted criteria: cost (weight 0.5), security certification (weight 0.3), and integration support (weight 0.2). On a 10-point scale, DataGuard scores 6 on cost, 9 on security, and 7 on integration; TrustShield scores 8 on cost, 6 on security, and 9 on integration.\n\n(d) Using the weighted scoring model with the criteria and scores given, calculate the total weighted score for each vendor and recommend which one the bank should select.",
      modelAnswer:
        "Think of weighted scoring like a judged competition where some categories count for more points than others, so a contestant can lose on one category but still win overall if they're strong where it matters most.\n\n• DataGuard's weighted score: (6 × 0.5) + (9 × 0.3) + (7 × 0.2) = 3.0 + 2.7 + 1.4 = 7.1.\n\n• TrustShield's weighted score: (8 × 0.5) + (6 × 0.3) + (9 × 0.2) = 4.0 + 1.8 + 1.8 = 7.6.\n\n• Recommendation: TrustShield has the higher weighted score, 7.6 versus DataGuard's 7.1, driven mainly by TrustShield's stronger cost score, which carries the heaviest weight at 0.5 — so the bank should select TrustShield even though DataGuard actually scored higher on security certification alone.\n\nSo the answer: TrustShield wins with a weighted score of 7.6 against DataGuard's 7.1, and should be the bank's selected vendor.",
    },
  ],
};

export const INFO6007_FINAL_PRACTICE_PAPERS: ExamPaperSeed[] = [PAPER];
