import type { ExamPaperSeed } from "../types";

const PAPER: ExamPaperSeed = 
  {
    course: "INFO6007",
    week: 2,
    paperNumber: 1,
    title: "Week 2 Practice Paper",
    topics: "Project lifecycle phases, Waterfall methodology, Agile values, Scrum roles and events; Kanban, Scrum vs Kanban, DevOps, emerging 'Ops' cultures, methodology selection; Requirement gathering techniques, project charter, stakeholder identification, Power/Interest Grid, knowledge areas across the lifecycle",
    sourceFiles: ["lecture/Lecture - INFO6007 Week 02 - PM Methodologies.pdf", "tutorial/Tutorial Sheet - INFO6007 Week 02.pdf"],
    questions: [
      {
        type: "mcq",
        prompt: "Which of the five phases of the Project Lifecycle has 'Approved Project Management Plan' as its output?",
        options: ["Initiation", "Planning", "Execution", "Monitoring & Controlling"],
        correctIndex: 1,
        modelAnswer: "The Planning phase's stated purpose is to 'build a comprehensive plan that guides the team,' with output 'Approved Project Management Plan.'",
      },
      {
        type: "mcq",
        prompt: "Per the Project Lifecycle diagram (Figure 2.1), during which phase does the 'Level of effort' typically peak?",
        options: ["Defining", "Planning", "Executing", "Closure"],
        correctIndex: 2,
        modelAnswer: "The diagram shows the 'Executing' curve reaching the highest level of effort, well above Defining, Planning, and Closure.",
      },
      {
        type: "mcq",
        prompt: "Which of the following is a listed disadvantage of the Waterfall methodology?",
        options: ["Not flexible to changes once development begins", "Requires daily stand-up meetings", "Cannot produce any documentation", "Only usable for software projects"],
        correctIndex: 0,
        modelAnswer: "The Waterfall disadvantages listed are: not flexible to changes once development begins, difficult to go back to a previous phase, delayed testing can uncover late-stage problems, and poor fit for dynamic/evolving requirements.",
      },
      {
        type: "mcq",
        prompt: "In the Waterfall model, what happens in the 'Requirements Gathering' phase?",
        options: ["All requirements are collected up-front and no changes are expected once the phase ends", "Requirements are continuously renegotiated throughout the project", "Only non-functional requirements are gathered", "Requirements are gathered after deployment"],
        correctIndex: 0,
        modelAnswer: "The lecture states: 'Requirements Gathering - All requirements of the project are collected up-front and no changes are expected once this phase ends.'",
      },
      {
        type: "mcq",
        prompt: "Per the lecture's HRMS example, why was Waterfall chosen for that project?",
        options: ["Requirements were well understood and unlikely to change, and development was outsourced requiring clear handoffs", "The company wanted daily stand-ups and fast iteration", "There was no defined budget or timeline", "The vendor refused to provide any documentation"],
        correctIndex: 0,
        modelAnswer: "The example lists: requirements well understood and unlikely to change, success depends on complete documentation, stakeholders prefer formal approvals at each phase, and development is outsourced requiring clear handoffs.",
      },
      {
        type: "mcq",
        prompt: "Which of the 4 Key Agile Values does the lecture list as being valued over 'comprehensive documentation'?",
        options: ["Working software", "Following a plan", "Contract negotiation", "Processes and tools"],
        correctIndex: 0,
        modelAnswer: "The '4 Key Agile Values' slide lists 'Working Software over comprehensive documentation' as one of the four values.",
      },
      {
        type: "mcq",
        prompt: "In Scrum, who is responsible for defining features, managing the backlog, and prioritizing work?",
        options: ["Product Owner", "Scrum Master", "Scrum Team", "Portfolio Manager"],
        correctIndex: 0,
        modelAnswer: "The Scrum Roles slide states: 'Product Owner - Defines the features, manages backlog, prioritizes work.'",
      },
      {
        type: "truefalse",
        prompt: "True or False: A Scrum Sprint is typically time-boxed between 1 and 4 weeks, and produces a potentially shippable Increment at its end.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "The lecture defines Sprint as a 'Time-boxed development cycle (ranges from 1 to 4 weeks usually)' and Increment as 'The potentially shippable product at the end of the Sprint.'",
      },
      {
        type: "short",
        prompt: "List the five phases of the Project Lifecycle and, for each, name one output described in the lecture.",
        modelAnswer: "Initiation → project is approved and formally initiated. Planning → an approved Project Management Plan. Execution → project deliverables are developed and reviewed. Monitoring & Controlling → status reports, updates, and course corrections. Closure → final project report, lessons learned, and client sign-off.",
      },
      {
        type: "short",
        prompt: "Explain why Waterfall is described as poorly suited to 'dynamic or evolving requirements,' and connect this to why it was NOT chosen in the Scrum example (university mobile app).",
        modelAnswer: "Waterfall requires all requirements to be locked in during the Requirements Gathering phase, with each subsequent phase completed sequentially and no expectation of returning to change things — so it can't absorb new information discovered mid-project. In the university mobile app example, requirements were explicitly evolving as different departments requested features, and the Product Owner wanted incremental delivery so students could test and give feedback regularly; this is exactly the kind of changing, feedback-driven environment Waterfall's linear, fixed-upfront model cannot accommodate, which is why Scrum was chosen instead.",
      },
      {
        type: "short",
        prompt: "Define the four key Scrum artifacts/components (Sprint, Product Backlog, Sprint Backlog, Increment) in your own words.",
        modelAnswer: "Sprint — a time-boxed development cycle, typically 1-4 weeks, during which a set amount of work is completed. Product Backlog — the full list of all desired features for the product, maintained and prioritised by the Product Owner. Sprint Backlog — the subset of backlog items selected to be completed within the current Sprint. Increment — the potentially shippable version of the product produced at the end of each Sprint.",
      },
      {
        type: "short",
        prompt: "List the four Scrum events described in the lecture and state the purpose of each in one phrase.",
        modelAnswer: "Sprint Planning — define what work will be done in the upcoming Sprint. Daily Stand-up — a 15-minute quick check-in for the team to synchronise. Sprint Review — showcase the completed work to stakeholders. Sprint Retrospective — reflect on the Sprint and identify improvements for next time.",
      },
      {
        type: "scenario",
        prompt: "A government agency is building a compliance-focused taxation portal (from the tutorial's Part B scenarios), where requirements come from fixed legislation and every phase requires formal sign-off before the next can begin. Using the lecture's Waterfall content, justify why Waterfall is the better fit here than Scrum, referencing at least two specific Waterfall advantages.",
        modelAnswer: "Waterfall is a better fit because the lecture lists 'ideal for government, construction, or compliance-heavy projects' as an explicit advantage, and 'clear milestones and documentation' as another — a taxation portal governed by fixed legislation needs formal sign-off and an audit trail at each phase, matching Waterfall's sequential structure where each phase (requirements, design, implementation, testing, deployment) is completed and approved before the next begins. Scrum's continuously evolving backlog and incremental delivery model would be a poor fit here, since compliance requirements aren't expected to change mid-project the way a startup's product features would.",
      },
      {
        type: "scenario",
        prompt: "An open-world RPG game studio (from the tutorial's Part B scenarios) has a storyline that keeps evolving as playtesters give feedback. Using the lecture's Agile values and Scrum roles, explain why this scenario favours Scrum over Waterfall, and name which Scrum role would likely own decisions about which story features get built first.",
        modelAnswer: "This scenario favours Scrum because it exhibits exactly the conditions Agile is built for: evolving requirements (storylines change based on playtesting) and a need for 'Responding to change over following a plan' — one of the lecture's 4 Key Agile Values. Waterfall would lock in the story design upfront and resist the mid-development changes playtesting is meant to produce. The Product Owner would own prioritisation decisions about which story features get built first, since the lecture defines that role as the one who 'Defines the features, manages backlog, prioritizes work.'",
      },
      {
        type: "mcq",
        prompt: "Which of the following is a key element of Kanban, per the lecture?",
        options: ["WIP Limits — a restriction on the number of items in a column to prevent overload", "Sprint — a fixed 1-4 week iteration", "Product Backlog — a list of desired features", "Daily Stand-up meeting"],
        correctIndex: 0,
        modelAnswer: "Kanban's key elements are Kanban Board, Cards/User stories, WIP Limits, and Cycle Time — Sprint, Product Backlog, and Daily Stand-up are Scrum concepts, not Kanban ones.",
      },
      {
        type: "mcq",
        prompt: "Per the 'Scrum vs Kanban' comparison table, how does Kanban handle workload compared to Scrum?",
        options: ["Kanban work is pulled as capacity allows, while Scrum work is planned per sprint", "Both handle workload identically", "Kanban requires a fixed sprint length, Scrum does not", "Kanban has no visual board while Scrum requires one"],
        correctIndex: 0,
        modelAnswer: "The comparison table's 'Workload' row states: Scrum = 'Planned per sprint', Kanban = 'Pulled as capacity allows.'",
      },
      {
        type: "mcq",
        prompt: "In the lecture's customer support ticket example, why was Kanban chosen over Scrum?",
        options: ["There was no strict deadline and the team needed continuous flow with flexibility to handle incoming tickets anytime", "The team needed fixed 2-week sprints", "The company wanted zero visual tracking", "The team had only one person"],
        correctIndex: 0,
        modelAnswer: "The example states Kanban was chosen for 'continuous flow of work with no fixed-length iterations' and 'flexibility to handle incoming tickets anytime,' since there was no strict deadline for resolving tickets.",
      },
      {
        type: "mcq",
        prompt: "What does 'WIP' stand for in the Kanban methodology?",
        options: ["Work In Progress", "Work In Planning", "Weekly Iteration Plan", "Workflow Integration Process"],
        correctIndex: 0,
        modelAnswer: "The lecture defines Kanban as focusing on 'limiting work in progress (WIP)' and defines WIP Limits as a 'Restriction on number of items in a column to prevent overload.'",
      },
      {
        type: "mcq",
        prompt: "DevOps is best described in the lecture as which of the following?",
        options: ["A set of practices that integrates software development and IT operations to shorten the development lifecycle and increase deployment frequency", "A single specific software tool for bug tracking", "A project scheduling technique identical to Waterfall", "A stakeholder engagement framework"],
        correctIndex: 0,
        modelAnswer: "The lecture defines DevOps as 'A set of practices that integrates software development and IT operations to shorten the development lifecycle, increase deployment frequency, and deliver high-quality software continuously.'",
      },
      {
        type: "mcq",
        prompt: "Which emerging 'Ops' culture from the lecture 'adds security early in the development process'?",
        options: ["DevSecOps", "FinOps", "GreenOps", "GitOps"],
        correctIndex: 0,
        modelAnswer: "The 'Beyond DevOps' slide states: 'DevSecOps: Adds security early in the development process.'",
      },
      {
        type: "mcq",
        prompt: "Which emerging 'Ops' culture 'tracks and controls cloud spending with finance teams'?",
        options: ["FinOps", "MLOps", "AIOps", "TestOps"],
        correctIndex: 0,
        modelAnswer: "The 'Beyond DevOps' slide states: 'FinOps: Tracks and controls cloud spending with finance teams.'",
      },
      {
        type: "truefalse",
        prompt: "True or False: Per the 'Waterfall vs Agile vs DevOps' diagram, DevOps is shown cycling through design/code/test/deploy far more frequently than Agile, which in turn cycles more frequently than Waterfall.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "The diagram shows Waterfall as one long Design → Code → Test → Deploy pass, Agile repeating Code → Test a handful of times before one Deploy, and DevOps repeating short Code → Test → Deploy cycles many times over, reflecting increasing release frequency.",
      },
      {
        type: "short",
        prompt: "Define the four key elements of Kanban (Kanban Board, Cards/User stories, WIP Limits, Cycle Time) in your own words.",
        modelAnswer: "Kanban Board — a visual board tracking tasks through stages such as To Do → Doing → Done. Cards/User stories — individual tasks or work items represented on the board. WIP Limits — a restriction on how many items can sit in a given column at once, to prevent the team from being overloaded. Cycle Time — the time it takes for a single task to move from start to finish.",
      },
      {
        type: "short",
        prompt: "Compare Scrum and Kanban across at least three dimensions from the lecture's comparison table.",
        modelAnswer: "Structure: Scrum uses time-boxed sprints, Kanban uses continuous flow. Roles: Scrum has defined roles (Product Owner, Scrum Master, Team), Kanban requires no specific roles. Change handling: Scrum limits changes during a Sprint, Kanban allows change at any time. (A further valid dimension: visual management is optional in Scrum but mandatory in Kanban.)",
      },
      {
        type: "short",
        prompt: "List the four goals of DevOps described in the lecture, and explain how 'Infrastructure as Code (IaC)' supports one of them.",
        modelAnswer: "The four goals: faster delivery cycles (CI/CD), improved collaboration between teams, automated testing/deployment/monitoring, and Infrastructure as Code (IaC) for scalability and reliability. IaC supports the automated deployment and faster delivery goals by letting infrastructure be provisioned and changed through version-controlled code rather than manual configuration, making environment setup repeatable, consistent, and quick to redeploy — reducing the manual errors and deployment risk the e-commerce company's example specifically wanted to fix.",
      },
      {
        type: "short",
        prompt: "Name four of the eight emerging 'Ops' cultures listed in the lecture (beyond DevOps) and state what each focuses on.",
        modelAnswer: "Any four of: DevSecOps (adds security early in development), DataOps (helps teams manage and move data quickly and reliably), MLOps (makes it easier to build, test, and run ML models), AIOps (uses AI to find and fix IT problems automatically), GreenOps (focuses on making IT systems more energy-efficient), TestOps (includes testing in every step to catch bugs early), GitOps (uses Git to safely automate software deployments), FinOps (tracks and controls cloud spending with finance teams).",
      },
      {
        type: "scenario",
        prompt: "A freelance web developer builds multiple small business websites, with work arriving unpredictably from different clients and no fixed sprint cadence that makes sense across all of them (from the tutorial's Part B scenarios). Using the lecture's Kanban content, justify why Kanban fits better than Scrum here.",
        modelAnswer: "Kanban fits better because it supports continuous flow with no fixed-length iterations, and work is 'pulled as capacity allows' rather than planned per sprint — matching a freelancer who needs to handle incoming client requests anytime rather than batching them into a shared sprint cadence across unrelated clients. Scrum's defined roles (Product Owner, Scrum Master, Team) and sprint planning overhead assume a single team working toward one coordinated backlog, which doesn't match independent, client-by-client work with no shared roadmap.",
      },
      {
        type: "scenario",
        prompt: "An e-commerce company (from the lecture's DevOps example) has developers and operations working in silos, causing slow releases and frequent outages. Using the DevOps benefits and iterative-cycle diagram from the lecture, explain two concrete improvements DevOps adoption would deliver, and how the DevOps cycle differs structurally from a single Waterfall pass.",
        modelAnswer: "Two concrete improvements: (1) Automation & Efficiency — CI/CD pipelines and automated testing/deployment would reduce the manual, error-prone handoffs between developers and operations that were causing outages. (2) Improved Cross-Functional Collaboration — integrating development and operations into one iterative cycle (Steer/Plan → Develop & Test → Deploy → Operate) rather than developers 'throwing it over the wall' means both teams share ownership of reliability. Structurally, the 'Waterfall vs Agile vs DevOps' diagram shows Waterfall completing a single design→code→test→deploy pass, Agile repeating code→test several times before one deploy, while DevOps cycles through code→test→deploy repeatedly and continuously — matching the DevOps goal of 'increase deployment frequency' rather than one big release at the end.",
      },
      {
        type: "mcq",
        prompt: "Which of the following is NOT one of the five requirement gathering techniques listed in the lecture?",
        options: ["Interviews", "Surveys/Questionnaires", "Workshops", "Code review"],
        correctIndex: 3,
        modelAnswer: "The five listed techniques are Interviews, Surveys/Questionnaires, Workshops, Observation, and Document Analysis — code review is not among them.",
      },
      {
        type: "mcq",
        prompt: "Per the lecture, what is the primary purpose of a Project Charter?",
        options: ["It is a formal document that authorizes the project and grants the project manager authority to use organizational resources", "It is a technical design document for the system architecture", "It replaces the need for stakeholder identification", "It is only used after the project has been completed"],
        correctIndex: 0,
        modelAnswer: "The lecture states: 'It is a formal document that authorizes the project and grants the project manager the authority to use organizational resources.'",
      },
      {
        type: "mcq",
        prompt: "Which of the following is listed as a 'tool used' in developing a Project Charter?",
        options: ["Business Case", "Sprint Backlog", "Kanban Board", "Daily Stand-up"],
        correctIndex: 0,
        modelAnswer: "The Project Charter tools listed are Expert Judgment, Business Case, Enterprise Environmental Factors, and Organizational Process Assets.",
      },
      {
        type: "mcq",
        prompt: "According to the lecture, a stakeholder is defined as?",
        options: ["Anyone who impacts or is impacted by the project, positively or negatively", "Only the people who fund the project", "Only the end users of the final product", "Only the project manager and their direct reports"],
        correctIndex: 0,
        modelAnswer: "The lecture defines a stakeholder as 'anyone who impacts or is impacted by the project: positively or negatively,' with examples including customers, sponsors, team members, suppliers, and regulators.",
      },
      {
        type: "mcq",
        prompt: "What tool does the lecture recommend for categorising and prioritising stakeholders based on power and interest?",
        options: ["The Power/Interest Grid", "The Triple Constraint triangle", "The Kanban Board", "The RACI matrix"],
        correctIndex: 0,
        modelAnswer: "The 'Stakeholder Identification and Engagement' slide lists 'Prioritize: Categorize using tools like the Power/Interest Grid.'",
      },
      {
        type: "mcq",
        prompt: "Which knowledge area's activity during the 'Defining' phase is 'Project Charter,' per the knowledge-area table?",
        options: ["Integration Management", "Scope Management", "Risk Management", "Procurement Management"],
        correctIndex: 0,
        modelAnswer: "The knowledge-area table lists 'Integration Management → Defining: Project Charter,' while Scope Management's Defining activity is 'Initial Scope Idea.'",
      },
      {
        type: "mcq",
        prompt: "Which of the following is listed as a common challenge during Project Initiation/Definition?",
        options: ["Unclear objectives and scope", "Too much executive support", "Excessive stakeholder engagement", "Overly detailed risk assessment"],
        correctIndex: 0,
        modelAnswer: "The 'Common challenges in Project Initiation/Definition' slide lists unclear objectives and scope, lack of executive support, poor stakeholder engagement, weak business case, unrealistic timelines/budgets, undefined roles, and inadequate risk awareness — the other options are opposites of these listed problems.",
      },
      {
        type: "truefalse",
        prompt: "True or False: Per the knowledge-area table, Time Management, Cost Management, Resource Management, and Procurement Management all show 'X' (not applicable) during the Defining phase, since detailed schedules, budgets, resourcing, and procurement plans are developed later in Planning.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "The table marks 'X' for Time, Cost, Resource, and Procurement Management in the Defining column — these knowledge areas only get concrete deliverables (e.g. schedules, budgeting/estimation, resource management plan, procurement management plan) starting in the Planning phase.",
      },
      {
        type: "short",
        prompt: "List the five requirement gathering techniques from the lecture and give a one-sentence description of each.",
        modelAnswer: "Interviews — one-on-one conversations with stakeholders. Surveys/Questionnaires — used to gather wide input quickly from many people. Workshops — collaborative group sessions to surface requirements together. Observation — watching users interact with current systems to identify needs they might not articulate. Document Analysis — reviewing existing system or process documentation for insight into requirements.",
      },
      {
        type: "short",
        prompt: "List the key activities of Project Initiation/Defining from the lecture (at least five).",
        modelAnswer: "Any five of: identify the business need or problem, define project goals and objectives, define the high-level scope, identify stakeholders, appoint the PM and key roles, develop the Project Charter, determine high-level budget and timeline, conduct initial risk and feasibility analysis, align with organisational strategy.",
      },
      {
        type: "short",
        prompt: "Explain the Power/Interest Grid and how it should be used, drawing on both the lecture and the tutorial's hint questions.",
        modelAnswer: "The Power/Interest Grid is a stakeholder-prioritisation tool that categorises stakeholders along two dimensions: how much power/influence they hold over the project, and how much interest they have in its outcome. Per the tutorial's hints, this means asking who holds power in the project, who has high interest but low power, and then tailoring the engagement strategy per quadrant — e.g. stakeholders with high power and high interest need close, active management, while those with high interest but low power mainly need to be kept informed.",
      },
      {
        type: "short",
        prompt: "Using the knowledge-area table, explain what 'Monitoring & Controlling' involves for Scope Management and Risk Management specifically.",
        modelAnswer: "For Scope Management, Monitoring & Controlling covers 'Scope validation, Scope control' — checking delivered work against agreed scope and managing any changes. For Risk Management, it covers 'Monitor risks' — tracking identified risks and watching for new ones as the project progresses, distinct from the earlier Planning-phase activities of risk identification and creating a response plan.",
      },
      {
        type: "scenario",
        prompt: "You are the project manager described in the Week 2 case study: a mid-sized company wants a new e-commerce platform in 6 months, the CEO hasn't defined detailed requirements, marketing is eager to start, IT is unsure about feasibility, and there's no formal project charter yet. List three immediate steps you would take, referencing specific 'Key activities' from the Project Initiation slide.",
        modelAnswer: "(1) Identify the business need/problem and define project goals and objectives with the CEO, since detailed requirements don't yet exist — this is explicitly the first listed key activity of initiation. (2) Conduct initial risk and feasibility analysis with IT to resolve their uncertainty about platform feasibility before committing to the 6-month timeline. (3) Develop the Project Charter and identify stakeholders (CEO, marketing, IT) so there's a single authorising document and a documented list of who needs to be engaged, rather than marketing proceeding informally while IT remains unaligned.",
      },
      {
        type: "scenario",
        prompt: "For the same e-commerce platform case study, identify at least four stakeholders and classify two of them on the Power/Interest Grid, explaining how each should be engaged based on their quadrant.",
        modelAnswer: "Stakeholders: the CEO (sponsor), the marketing team, the IT department, external customers, the assigned project manager, a potential technology vendor, and end users/store staff. Example classification: the CEO is high power / high interest — since they set the deadline and fund the project, they need to be closely managed with regular direct updates. The IT department may sit as high power / initially lower interest until feasibility is resolved, closer to 'keep satisfied' — they need to be consulted early on technical constraints even before they're fully engaged in delivery, since their buy-in materially affects whether the 6-month deadline is realistic.",
      },
    ],
  }

export const WEEK_2_PAPERS: ExamPaperSeed[] = [PAPER];
