import type { ExamPaperSeed } from "../types";

const PAPER: ExamPaperSeed =
  {
    course: "INFO6007",
    week: 3,
    paperNumber: 1,
    title: "Week 3 Practice Paper",
    topics: "Project Scope Management (6 processes: Plan Scope Management, Collect Requirements, Define Scope, Create WBS, Validate Scope, Control Scope), Requirement Traceability Matrix, WBS approaches/types/rules, scope management issues and mitigation; Project Schedule Management (6 processes: Plan Schedule Management, Define Activities, Sequence Activities, Estimate Activity Durations, Develop Schedule, Control Schedule), dependency types, network diagrams (AON, AOA, PDM), lead/lag time, PERT/analogous/parametric estimating, Gantt charts, Critical Path Method, schedule compression",
    sourceFiles: [
      "lecture/Lecture - INFO6007 Week 03 - Time Management.pdf",
      "tutorial/Reading 1 - Using WBS for a project.pdf",
      "tutorial/Tutorial sheet Week 03  INFO6007.pdf",
    ],
    questions: [
      {
        type: "mcq",
        prompt: "What is the main purpose of a Scope Management Plan?",
        options: ["To define how the project scope will be defined, validated, and controlled", "To calculate the project's total budget", "To assign daily stand-up responsibilities", "To replace the WBS entirely"],
        correctIndex: 0,
        modelAnswer: "The lecture states a Scope Management Plan 'is a crucial component of a project management plan that defines how the project scope will be defined, validated, and controlled,' and ensures 'all project work, and only that work, is included and completed successfully.'",
      },
      {
        type: "mcq",
        prompt: "Per the 'Key components of Scope Management Plan' table, which component is described as a 'high-level narrative of what the project will deliver (and won't)'?",
        options: ["Scope Statement", "Scope Management Approach", "Requirement Collection", "Scope Validation Process"],
        correctIndex: 0,
        modelAnswer: "The table lists Scope Statement's description as 'High-level narrative of what the project will deliver (and won't).'",
      },
      {
        type: "mcq",
        prompt: "Which key component of the Scope Management Plan is described as 'a hierarchical decomposition of the project deliverables'?",
        options: ["Work Breakdown Structure", "Scope Control Process", "Roles and Responsibilities", "Assumptions and Constraints"],
        correctIndex: 0,
        modelAnswer: "The Key Components table describes 'Work Breakdown Structure' as 'A hierarchical decomposition of the project deliverables.'",
      },
      {
        type: "mcq",
        prompt: "Which of the following is NOT one of the six main processes in Project Scope Management?",
        options: ["Estimate Costs", "Plan Scope Management", "Collect Requirements", "Validate Scope"],
        correctIndex: 0,
        modelAnswer: "The six processes are Plan Scope Management, Collect Requirements, Define Scope, Create WBS, Validate Scope, and Control Scope. 'Estimate Costs' belongs to Cost Management, not Scope Management.",
      },
      {
        type: "mcq",
        prompt: "What are the inputs to 'Plan Scope Management,' per the lecture?",
        options: ["Project charter, Project management plan, Enterprise environmental factors, and Organisational process assets", "Verified deliverables and Work performance data", "Change requests and Scope baseline", "Requirements documentation and Requirement traceability matrix"],
        correctIndex: 0,
        modelAnswer: "The lecture lists Plan Scope Management's inputs as: 'Project charter, Project management plan, Enterprise environmental factors, and Organisational process assets.'",
      },
      {
        type: "mcq",
        prompt: "Which requirement-gathering technique does Week 3's 'Collecting Requirements' process list that was NOT among Week 2's five requirement gathering techniques?",
        options: ["Prototyping", "Interviews", "Workshops", "Surveys/Questionnaires"],
        correctIndex: 0,
        modelAnswer: "Week 3 lists Interviews, Workshops, Surveys/Questionnaires, Prototyping, and Observation. Week 2 listed Interviews, Surveys/Questionnaires, Workshops, Observation, and Document Analysis — Prototyping is new in Week 3, replacing Document Analysis.",
      },
      {
        type: "mcq",
        prompt: "What is the purpose of a Requirement Traceability Matrix (RTM), per the Week 3 material?",
        options: ["To link each requirement through to its acceptance criteria, test cases, and objectives so nothing gets lost or left untested", "To record the project's daily stand-up notes", "To replace the WBS dictionary", "To calculate PERT estimates"],
        correctIndex: 0,
        modelAnswer: "The RTM example (Requirements Traceability Matrix Example, 'Website Launch') tracks each requirement's ID, description, type, source, priority, potential risks, status, owner, acceptance criteria, test cases, and objectives/goals — linking a requirement all the way through to how it will be tested and what it's meant to achieve.",
      },
      {
        type: "mcq",
        prompt: "What is the output of the 'Define Scope' process?",
        options: ["Project Scope Statement", "Scope management plan", "Work Breakdown Structure", "Accepted deliverables"],
        correctIndex: 0,
        modelAnswer: "The lecture states: 'The output of this process is a Project Scope statement,' which 'includes product scope description, deliverables, exclusions, and criteria for success.'",
      },
      {
        type: "mcq",
        prompt: "What technique is used to create a WBS, per the 'Creating WBS' slide?",
        options: ["Decomposition", "PERT analysis", "Fast tracking", "Variance analysis"],
        correctIndex: 0,
        modelAnswer: "The lecture states: 'The technique used to create a WBS is called decomposition. It is the process of breaking high-level deliverables into sub-deliverables, and then into work packages.'",
      },
      {
        type: "mcq",
        prompt: "Which WBS-development approach 'starts with the specific tasks and rolls them up,' per the lecture?",
        options: ["Bottom-Up approach", "Top-Down approach", "Analogy approach", "Mind-mapping"],
        correctIndex: 0,
        modelAnswer: "The lecture defines the Bottom-Up approach as: 'Start with the specific tasks and roll them up' — the opposite of the Top-Down approach, which starts with the largest items and breaks them down.",
      },
      {
        type: "mcq",
        prompt: "Per 'Things to remember when creating the WBS,' which statement is correct?",
        options: ["A WBS item is the responsibility of only one individual, even though many people may be working on it", "A unit of work should appear in multiple places in the WBS for redundancy", "Project team members should NOT be involved in developing the WBS", "The WBS need not be consistent with how work is actually performed"],
        correctIndex: 0,
        modelAnswer: "The lecture states: 'A WBS item is the responsibility of only one individual, even though many people may be working on it.' The other options contradict the listed rules: a unit of work should appear at only ONE place in the WBS, team members SHOULD be involved for buy-in, and the WBS MUST be consistent with how work is actually performed.",
      },
      {
        type: "mcq",
        prompt: "What is the main objective of 'Validating Scope'?",
        options: ["To gain formal acceptance of the completed project deliverables by the customer or sponsor", "To break deliverables into work packages", "To collect stakeholder requirements", "To calculate schedule variance"],
        correctIndex: 0,
        modelAnswer: "The lecture states: 'The main objective is to gain formal acceptance of the completed project deliverables by the customer or sponsor,' and notes this is also where 'scope creep can be caught before it escalates.'",
      },
      {
        type: "truefalse",
        prompt: "True or False: Scope creep is defined as uncontrolled changes or continuous growth in a project's scope without adjustments to time, cost, and resources.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "The 'Scope Management Issues' table defines Scope Creep exactly this way, with the listed impact being 'Delays, budget overruns, team burnout.'",
      },
      {
        type: "mcq",
        prompt: "Project Schedule Management is best described, per the lecture, as?",
        options: ["The process of planning, developing, managing, executing, and controlling a project's schedule so it can be completed within the agreed time frame", "A budgeting technique only used in Waterfall", "A stakeholder engagement framework", "A synonym for the WBS"],
        correctIndex: 0,
        modelAnswer: "The lecture defines Project Schedule Management as 'the process of planning, developing, managing, executing, and controlling a project's schedule so that it can be completed within the agreed time frame' — or more simply, 'deciding what needs to be done, in what order, how long it will take, and making sure it stays on track.'",
      },
      {
        type: "mcq",
        prompt: "Which of the following is NOT one of the six main processes in Project Schedule Management?",
        options: ["Validate Scope", "Define Activities", "Sequence Activities", "Develop Schedule"],
        correctIndex: 0,
        modelAnswer: "The six Schedule Management processes are Plan Schedule Management, Define Activities, Sequence Activities, Estimate Activity Durations, Develop Schedule, and Control Schedule. 'Validate Scope' is a Scope Management process, not a Schedule Management one.",
      },
      {
        type: "mcq",
        prompt: "Mandatory dependencies are also known as?",
        options: ["Hard logic", "Soft logic", "External logic", "Lag logic"],
        correctIndex: 0,
        modelAnswer: "The lecture defines mandatory dependencies as 'Dependencies that are inherent to the work and cannot be changed; also called hard logic,' as opposed to discretionary dependencies ('soft logic').",
      },
      {
        type: "mcq",
        prompt: "An external dependency, per the 'Four types of dependencies' slide, is one that?",
        options: ["Relies on activities outside the project team's control", "Is always mandatory", "Only occurs within Scrum projects", "Can never cause a delay"],
        correctIndex: 0,
        modelAnswer: "The lecture defines external dependencies as 'Dependencies that rely on activities outside the project team's control,' contrasted with internal dependencies, which are 'between activities within the project team's control.'",
      },
      {
        type: "mcq",
        prompt: "Which network diagram represents activities as arrows (with nodes as events/milestones), and is the only one that usually requires dummy activities?",
        options: ["Activity on Arrow (AOA)", "Activity on Node (AON)", "Precedence Diagramming Method (PDM)", "Gantt Chart"],
        correctIndex: 0,
        modelAnswer: "The lecture states AOA 'is also the only network diagram that usually requires dummy activities (arrows with 0 duration) to show dependencies properly,' unlike AON, which represents activities as nodes/boxes and is described as 'the most widely used method today.'",
      },
      {
        type: "mcq",
        prompt: "Per the Precedence Diagramming Method (PDM), which relationship means 'Activity B starts after A finishes' — the most common type?",
        options: ["Finish to Start (FS)", "Start to Start (SS)", "Finish to Finish (FF)", "Start to Finish (SF)"],
        correctIndex: 0,
        modelAnswer: "The lecture defines Finish to Start (FS) as 'Activity B starts after A finishes (most common).'",
      },
      {
        type: "mcq",
        prompt: "Lead time's main purpose, per the lecture, is to?",
        options: ["Accelerate the schedule, by letting a successor activity start before its predecessor finishes", "Slow the schedule down to account for waiting periods", "Increase project cost", "Eliminate dependencies entirely"],
        correctIndex: 0,
        modelAnswer: "The lecture defines Lead Time as 'The amount of time by which a successor activity can start before its predecessor finishes,' with the 'main purpose... to accelerate the schedule' — the opposite of Lag Time, which 'technically slows down the schedule.'",
      },
      {
        type: "mcq",
        prompt: "What is the formula for the PERT three-point estimate?",
        options: ["(O + 4M + P) / 6", "(O + M + P) / 3", "(O + P) / 2", "(4O + M + P) / 6"],
        correctIndex: 0,
        modelAnswer: "The lecture gives the formula as PERT = (O + 4M + P) / 6, where O = Optimistic, M = Most Likely, and P = Pessimistic.",
      },
      {
        type: "mcq",
        prompt: "Analogous Estimating is best described as?",
        options: ["A top-down technique that predicts duration or cost based on historical data from similar projects", "A bottom-up technique that sums individual task estimates", "A technique that only works late in a project", "A technique used exclusively for cost, never time"],
        correctIndex: 0,
        modelAnswer: "The lecture defines Analogous Estimating as 'a top-down project estimation technique where you predict the duration or cost of a task based on historical data from similar projects or activities,' noting it 'works well in the early stages of a project' and 'can be used for both time and cost estimates.'",
      },
      {
        type: "mcq",
        prompt: "A Gantt Chart is best described as?",
        options: ["A bar chart displaying project activities or tasks against time, with each bar's length representing its duration", "A diagram showing only dependency arrows with no time axis", "A financial ledger of the project budget", "A stakeholder engagement matrix"],
        correctIndex: 0,
        modelAnswer: "The lecture defines a Gantt Chart as 'a bar chart that displays project activities or tasks against time. Each task is represented by a horizontal bar whose length represents its duration,' used for visualising the timeline, tracking progress, identifying overlaps/leads/lags, and communicating the schedule.",
      },
      {
        type: "mcq",
        prompt: "The Critical Path Method identifies?",
        options: ["The longest sequence of dependent activities in a project, which determines the shortest possible project duration", "The cheapest sequence of activities", "The path with the fewest dependencies", "The path assigned to the Product Owner"],
        correctIndex: 0,
        modelAnswer: "The lecture defines the Critical Path Method as 'a scheduling technique used to identify the longest sequence of dependent activities in a project, the path that determines the shortest possible project duration,' and notes 'any delay on the Critical Path will DELAY the entire project.'",
      },
      {
        type: "mcq",
        prompt: "'Crashing,' as a schedule compression technique, involves?",
        options: ["Adding more resources to critical path activities to finish sooner, which increases cost", "Performing sequential activities in parallel", "Removing activities from the WBS entirely", "Reducing quality standards"],
        correctIndex: 0,
        modelAnswer: "The lecture defines Crashing as 'Add more resources to critical path activities to finish sooner,' which 'increases cost, may increase risk' — distinct from Fast Tracking, which performs activities in parallel and increases risk without necessarily adding cost.",
      },
      {
        type: "truefalse",
        prompt: "True or False: Per the lecture, in the Google Cloud Expansion case study, Project Scope Management is applied using six key processes, and Project Schedule Management is separately applied using its own six main processes.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "Both Google Cloud case study slides state the same structure: 'Project Scope Management is applied using the six key processes' and, separately, 'Project Schedule Management is applied using the six main processes' — the same overall project mapped through both sets of six processes.",
      },
      {
        type: "short",
        prompt: "List and briefly describe the six processes of Project Scope Management.",
        modelAnswer: "Plan Scope Management — create the scope management plan defining how scope will be defined, validated, and controlled. Collect Requirements — determine, document, and manage stakeholder needs and expectations. Define Scope — develop a detailed project scope statement (deliverables, boundaries, acceptance criteria, assumptions/constraints). Create WBS — decompose deliverables into smaller, manageable work packages. Validate Scope — gain formal acceptance of completed deliverables from the customer/sponsor. Control Scope — monitor scope status and manage changes to the scope baseline, preventing scope creep.",
      },
      {
        type: "short",
        prompt: "Explain what a WBS is and why the lecture calls it 'the backbone of project planning.'",
        modelAnswer: "A WBS is 'a deliverable-oriented grouping of the work involved in a project that defines the total scope of the project,' built through decomposition — breaking high-level deliverables into sub-deliverables and then into work packages. It's the backbone of planning because, per the lecture, it 'clarifies deliverables, aids in resource planning, and sets up cost/schedule tracking' — nearly every later planning activity (estimating durations, sequencing activities, assigning resources) depends on the work packages the WBS defines.",
      },
      {
        type: "short",
        prompt: "Compare Week 2's five 'Requirement gathering techniques' (from Project Initiation) with Week 3's five 'Collecting Requirements' techniques (from Scope Management). What changed, and why might Prototyping fit specifically into the Scope Management process?",
        modelAnswer: "Week 2 listed Interviews, Surveys/Questionnaires, Workshops, Observation, and Document Analysis. Week 3's Collect Requirements process lists Interviews, Workshops, Surveys/Questionnaires, Observation, and Prototyping — four techniques carry over, but Document Analysis is replaced by Prototyping. This fits Scope Management specifically because, per the lecture, Prototyping produces 'early versions to refine requirements' — useful once a project has moved from the high-level Initiation stage (where Document Analysis of existing systems helps establish initial context) into Collect Requirements, where the goal is to pin down concrete, testable requirements (feeding the Requirement Traceability Matrix) before Define Scope locks in the official scope statement.",
      },
      {
        type: "short",
        prompt: "Explain scope creep, drawing on the 'Scope Management Issues' table, and list at least three of the mitigation strategies the lecture recommends.",
        modelAnswer: "Scope creep is 'uncontrolled changes or continuous growth in a project's scope without adjustments to time, cost, and resources,' with impacts of 'delays, budget overruns, team burnout.' It's often driven by related issues in the same table: lack of stakeholder engagement, miscommunication about what's in/out of scope, and overambitious scope. Mitigations from 'Mitigating the issues' include: a clear Scope Statement with inclusions/exclusions/assumptions, a Requirements Traceability Matrix linking requirements to deliverables, stakeholder sign-off at each stage, a formal Change Control Process, and regular scope reviews.",
      },
      {
        type: "short",
        prompt: "Using the Week 3 reading's WBS Dictionary examples (Cleaning Dictionary, Interior Dictionary), explain what information a WBS dictionary entry captures, and connect this to the lecture's own WBS Dictionary concept (Table 5-6, 'Database Update').",
        modelAnswer: "Both the reading's dictionaries and the lecture's sample entry capture the same underlying idea: for a given WBS item, document what it is and what's needed to deliver it. The reading's format records Location, Activity, and Resources (Man Power, Material, Equipment) — e.g. the Interior Dictionary lists 'Renovation of additional facility' with a Project Manager and Tukang doing the work, using Paint, Tinner, and hardware. The lecture's WBS Dictionary Entry for 'Database Update' instead uses a narrative Description field explaining the task, its dependencies (WBS Item 2.1 must precede it), and who's responsible. Both apply the lecture's point that 'each WBS item must be documented in the WBS dictionary' — the reading just tailors the fields (adding Materials/Equipment columns) to a physical repair project rather than an IT upgrade project.",
      },
      {
        type: "short",
        prompt: "List and briefly describe the six processes of Project Schedule Management.",
        modelAnswer: "Plan Schedule Management — decide tools, techniques, formats, and assign responsibilities for how the schedule will be developed, monitored, and controlled. Define Activities — break WBS work packages into specific, manageable tasks with attributes (duration, resources, predecessors). Sequence Activities — determine the logical order of tasks and their dependencies, producing network diagrams. Estimate Activity Durations — predict how long each activity will take using techniques like Analogous, Parametric, or Three-point/PERT estimating. Develop Schedule — integrate durations, sequences, and resources into a complete timeline using the Critical Path Method, producing the schedule baseline. Control Schedule — monitor progress, compare actual vs planned performance (e.g. via SPI/SV), and apply schedule compression if needed.",
      },
      {
        type: "short",
        prompt: "Explain the four types of dependencies (mandatory, discretionary, external, internal) with an example of each.",
        modelAnswer: "Mandatory (hard logic) — inherent to the work and cannot be changed, e.g. you cannot test software before it's built. Discretionary (soft logic) — set by best practice, preference, or convenience, e.g. choosing to complete all design work before starting any development, even though some could overlap. External — depend on activities outside the project team's control, e.g. waiting on a vendor's payroll-software integration approval. Internal — depend on activities within the project team's control, e.g. one developer's module needing another developer's completed component.",
      },
      {
        type: "short",
        prompt: "Explain the difference between lead time and lag time and how each affects the schedule.",
        modelAnswer: "Lead time is 'the amount of time by which a successor activity can start before its predecessor finishes' — its purpose is to accelerate the schedule, technically speeding it up (e.g. starting testing before development is 100% complete). Lag time is 'the amount of time that must pass after a predecessor finishes before the successor can start' — its purpose is to account for delays or waiting periods, technically slowing the schedule down (e.g. waiting for concrete to cure before starting the next task).",
      },
      {
        type: "short",
        prompt: "Explain the three techniques for estimating activity durations covered in the lecture (Analogous, Parametric, Three-point/PERT) and when each is most appropriate.",
        modelAnswer: "Analogous Estimating is a top-down technique using historical data from similar projects — fast, low-cost, and best in early stages when little detail is available, but requires expert judgment to validate the similarity. Parametric Estimation uses a measurable relationship between variables (a unit rate × number of units) with historical data and mathematical models — works best when that relationship is consistent and scalable. Three-point/PERT estimating (O+4M+P)/6 accounts for uncertainty and variability by combining an Optimistic, Most Likely, and Pessimistic estimate — most appropriate when there's meaningful uncertainty about how long an activity will take and a single-point guess would understate the risk.",
      },
      {
        type: "short",
        prompt: "Using the PERT formula from the lecture, calculate the estimated duration for an activity with Optimistic = 4 days, Most Likely = 6 days, and Pessimistic = 14 days. What does the result represent?",
        modelAnswer: "PERT = (O + 4M + P) / 6 = (4 + 4×6 + 14) / 6 = (4 + 24 + 14) / 6 = 42 / 6 = 7 days. This weighted average leans heavily toward the Most Likely estimate (weighted ×4) while still pulling the estimate slightly above the simple average of 4, 6, and 14 (which would be 8) toward a more realistic single duration that accounts for the wide pessimistic tail without being dominated by it.",
      },
      {
        type: "short",
        prompt: "Explain fast tracking vs crashing as schedule compression techniques, including their trade-offs.",
        modelAnswer: "Fast Tracking performs activities in parallel that were originally sequential — it shortens the schedule but increases risk, since activities that depended on each other's outputs now run concurrently with less certainty. Crashing adds more resources to critical path activities to finish them sooner — it increases cost (and may increase risk) but doesn't necessarily change the sequencing of work the way fast tracking does. Both are 'Control Schedule' techniques used when a project needs to recover time on the critical path.",
      },
      {
        type: "short",
        prompt: "The Week 3 reading's Fault Tree Analysis (FTA) found that 'Procurement of Resources' (material and labour shortages) was the main factor causing the XYZ ship repair project's delay. Connect this finding to two Week 3 lecture concepts that could have prevented or mitigated it.",
        modelAnswer: "Two connections: (1) External/internal dependencies — the reading's material delays (e.g. 'Material Terlambat'/'material late') are effectively external dependencies on suppliers outside the project team's control, which the lecture's dependency framework flags as a distinct risk category needing buy-in ahead of time. (2) The WBS Dictionary's resource fields — the lecture's WBS dictionary documents required resources per work package (as does the reading's own WBS dictionary, with explicit Man Power/Material/Equipment columns); properly populating and reviewing those resource fields during Create WBS and Estimate Activity Durations would have surfaced the material and labour shortfall before it caused a 4-day project delay, rather than discovering it mid-execution.",
      },
      {
        type: "scenario",
        prompt: "Using the lecture's Activity on Node (AON) example (Activities A–J with the durations and predecessors below), determine the critical path and the total project duration, showing your reasoning.\n\nA: 5 days, no predecessor. B: 4 days, predecessor A. C: 5 days, predecessor B. D: 6 days, predecessor B. E: 7 days, predecessor D. F: 3 days, predecessors C,D. G: 6 days, predecessor D. H: 7 days, predecessors F,G. I: 8 days, predecessors E,G. J: 3 days, predecessors H,I.",
        modelAnswer: "Forward pass (Earliest Start/Finish): A 0-5, B 5-9, C 9-14, D 9-15, E 15-22, F 15-18 (max of C's 14, D's 15), G 15-21, H 21-28 (max of F's 18, G's 21), I 22-30 (max of E's 22, G's 21), J 30-33 (max of H's 28, I's 30). Project duration = 33 days. Backward pass shows zero slack on A, B, D, E, I, J (e.g. C has 6 days slack, F has 5, G has 1, H has 2). Critical path: A → B → D → E → I → J, totalling 5+4+6+7+8+3 = 33 days — matching the forward-pass project duration, per the lecture's definition that the critical path is 'the path that determines the shortest possible project duration' and any delay along it delays the whole project.",
      },
      {
        type: "scenario",
        prompt: "You are managing the lecture's HR Management System case study: a 12-month project (requirements gathering, design, development, testing, training, deployment) that must deploy by December. Constraints: only two senior developers at a time; the design team is tied up on another project and free only after 4 weeks; vendor approval for payroll integration may take up to 3 weeks. Identify three possible scope risks in this project and how you would address each, referencing WBS/RTM concepts from the lecture.",
        modelAnswer: "(1) Scope creep from the client adding features once development starts, given the fixed December deadline — mitigate with a clear Scope Statement (inclusions/exclusions) and a formal Change Control Process, per the lecture's mitigation list. (2) Ambiguity about what 'training' and 'deployment' actually include (e.g. does scope cover post-launch support?) — mitigate by using a Requirements Traceability Matrix to tie each requirement to explicit acceptance criteria and test cases, so 'done' is unambiguous. (3) Resource-driven scope risk — only two senior developers and a design team unavailable for 4 weeks may force cutting corners on deliverables to hit December — mitigate by decomposing the WBS early (Create WBS) so work packages and their resource needs are visible up front, allowing the PM to negotiate scope or timeline before the resource crunch causes uncontrolled descoping later.",
      },
      {
        type: "scenario",
        prompt: "For the same HR Management System case study: if the vendor's payroll integration approval takes 5 weeks instead of the expected 3, explain how that could impact the critical path, using the lecture's Critical Path Method and dependency concepts.",
        modelAnswer: "Vendor payroll approval is an external dependency (relies on an organisation outside the project team's control) and, per the case study, a mandatory one for a working payroll integration. If this activity sits on or feeds into the critical path (which it likely does, since testing and training can't proceed on the payroll module until integration is approved), extending it from 3 to 5 weeks adds 2 weeks of delay directly onto the critical path — per the lecture, 'any delay on the Critical Path will DELAY the entire project' by that same amount, unless the PM applies schedule compression (crashing the payroll-integration-dependent tasks with more resources, or fast-tracking testing to start on already-approved components in parallel) to absorb the extra 2 weeks before the fixed December deployment date.",
      },
      {
        type: "scenario",
        prompt: "Tutorial Part A: your organisation is building a new mobile app for a healthcare provider, involving doctors, patients, and regulatory bodies, with strict legal and security compliance requirements. Compare Agile and Waterfall for this project, recommend a methodology (or hybrid), and identify three risks of your chosen approach with mitigation strategies.",
        modelAnswer: "Waterfall's strengths (per Week 2's lecture) fit the compliance side well: 'ideal for government, construction, or compliance-heavy projects' with 'clear milestones and documentation' — useful for regulatory sign-off on a healthcare app. But pure Waterfall risks missing patient/doctor usability feedback until too late, since requirements are locked upfront. A hybrid is the stronger recommendation: use a Waterfall-style formal scope/compliance backbone (Define Scope, Validate Scope with regulatory sign-off at each phase) while running Agile/Scrum sprints for the UI and feature development, so clinicians can give iterative feedback. Three risks: (1) Regulatory non-compliance if Agile iteration outpaces documentation — mitigate with a Scope Management Plan requiring compliance sign-off before each release. (2) Scope creep from competing doctor/patient/regulator requirements — mitigate with a Requirements Traceability Matrix and a Power/Interest Grid to prioritise whose requirements govern conflicts. (3) Schedule risk from external dependencies (regulatory approval timelines outside the team's control) — mitigate by building lag time into the schedule around known approval windows and treating them as explicit external dependencies in the network diagram.",
      },
      {
        type: "scenario",
        prompt: "Tutorial Part B: your team is developing an Online Course Registration System for a university. List at least six stakeholders, place at least two of them on a Power/Interest Grid (from Week 2), and explain how the Collect Requirements process (Week 3) would gather each one's needs.",
        modelAnswer: "Stakeholders: university registrar, students, academic advisors, IT/systems administrators, faculty (who set enrolment caps), and the university's finance office (billing integration). Power/Interest Grid: the registrar is high power / high interest — they own the business rules and need close, active management, best engaged via Workshops (per Collect Requirements) to jointly define registration rules. Students are low power / high interest — they need to be kept informed and consulted via Surveys/Questionnaires, per the lecture's technique for reaching 'large stakeholder groups efficiently,' since interviewing every student individually isn't feasible. IT/systems administrators would be engaged via Interviews for technical constraints, and a clickable Prototype would let both the registrar and a sample of students validate the registration flow before Define Scope locks in the final scope statement.",
      },
      {
        type: "scenario",
        prompt: "Google Cloud's Global Data Center Expansion case study applies Project Scope Management's six processes to building new data centers, integrating cooling systems, and ensuring regulatory compliance across regions. Briefly describe what each of the six processes would concretely involve for this project.",
        modelAnswer: "Plan Scope Management — define how Google will define/validate/control scope across multiple countries' regulatory regimes. Collect Requirements — gather needs from regional compliance teams, data center engineers, and AI/cloud product teams (e.g. via workshops and interviews) into a Requirement Traceability Matrix. Define Scope — produce a scope statement specifying which locations, cooling technologies, and compliance certifications are in scope (and which, e.g. unapproved regions, are excluded). Create WBS — decompose 'build a data center' into sub-deliverables like site construction, cooling system integration, and network buildout, down to work packages per region. Validate Scope — get formal sign-off from regional stakeholders and compliance officers that each completed data center meets agreed acceptance criteria. Control Scope — manage change requests as, e.g., new regional regulations emerge mid-project, using variance analysis to keep the rollout aligned with the original plan.",
      },
      {
        type: "scenario",
        prompt: "The same Google Cloud case study separately applies Project Schedule Management's six processes 'to ensure the project is delivered on time across diverse geographical regions.' Briefly describe what each of the six processes would concretely involve for this project.",
        modelAnswer: "Plan Schedule Management — decide the scheduling tools/format (e.g. MS Project) and metrics used across all regional sub-teams. Define Activities — break each region's WBS work packages (construction, cooling, network) into specific tasks with durations and predecessors. Sequence Activities — determine dependencies, e.g. site construction (mandatory dependency) must finish before cooling system installation, while regulatory approval in each country is an external dependency outside Google's control. Estimate Activity Durations — use Analogous estimating from prior data center builds, or Three-point/PERT where a region's timeline is uncertain (e.g. weather-dependent construction). Develop Schedule — apply the Critical Path Method across all regions to find which region's construction pace determines the overall rollout timeline, setting the schedule baseline. Control Schedule — track SPI/SV per region, and apply schedule compression (crashing extra construction crews, or fast-tracking cooling installation to start before construction fully finishes) if a region falls behind, since a delay in a critical-path region delays the whole global rollout.",
      },
    ],
  }

export const WEEK_3_PAPERS: ExamPaperSeed[] = [PAPER];
