import type { ExamPaperSeed } from "../types";

const PAPER: ExamPaperSeed = 
  {
    course: "INFO6007",
    week: 1,
    paperNumber: 1,
    title: "Week 1 Practice Paper",
    topics: "Course logistics, assessment weightings, hurdle requirement, learning outcomes, schedule; Project definition, triple constraint, project success, project vs program vs portfolio; PM key elements, PM skills, project management framework, PMBOK knowledge areas, case study application",
    sourceFiles: ["lecture/INFO6007 Week 01 - Introduction.pdf"],
    questions: [
      {
        type: "mcq",
        prompt: "What percentage of the final mark comes from the Final Exam in INFO6007?",
        options: ["40%", "50%", "60%", "70%"],
        correctIndex: 2,
        modelAnswer: "The Assessments table lists the Written exam (Final Exam) at 60% weighting, held in the formal exam period.",
      },
      {
        type: "mcq",
        prompt: "Per the Hurdle Requirement slide, what happens if a student doesn't achieve at least 40% on the written exam and an overall mark of 50?",
        options: ["They fail automatically regardless of other marks", "Their final mark is capped at a maximum of 45, regardless of their overall average", "They receive an automatic 5% penalty on their next assignment", "They must retake the entire unit next semester with no exceptions"],
        correctIndex: 1,
        modelAnswer: "The slide states: 'Any student who does not meet these hurdles requirements may be awarded a maximum final mark of 45, regardless of their overall average.'",
      },
      {
        type: "truefalse",
        prompt: "True or False: The Group Assignment (25%) requires groups of 4-5 students formed within the same tutorial, with submission in Week 13.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "The Assessments slide confirms: 'Group Assignment (25%) — Groups of 4–5 students: Form your group within the same tutorial activity — Submission in Week 13.'",
      },
      {
        type: "mcq",
        prompt: "What is the weighting and format of the Early Semester Feedback Task?",
        options: ["5%, an individual auto-graded multiple-choice quiz on Weeks 1-3 content, due Week 4", "25%, a group presentation delivered in Week 6", "10%, a written report submitted in Week 2", "60%, a closed-book exam held in Week 4"],
        correctIndex: 0,
        modelAnswer: "The Assessments slides describe it as an individual, auto-graded multiple choice/true-false quiz worth 5%, covering Week 1 to Week 3 content, held in Week 4.",
      },
      {
        type: "mcq",
        prompt: "According to the schedule slide, when are tutorials held and from which week?",
        options: ["Monday only, from Week 1", "Tuesday to Friday, from Week 2", "Weekends only, from Week 3", "Thursday evenings, at the same time as lectures"],
        correctIndex: 1,
        modelAnswer: "The Schedule slide states tutorials are 'Held from Tuesday to Friday from Week 2', face to face, and are important to attend for weekly progress evaluations in weeks 6-12.",
      },
      {
        type: "truefalse",
        prompt: "True or False: The Weekly progress evaluation (10%) is marked individually, based on the progressive project board (GitHub), and conducted during tutorials from Week 6 to Week 12.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "Both the Assessments table and the follow-up slide confirm this: conducted during tutorials, based on the GitHub project board, marked individually, held Weeks 6-12.",
      },
      {
        type: "mcq",
        prompt: "Which of the following is NOT one of the five learning outcomes (LO1-LO5) listed for INFO6007?",
        options: ["Understand each of the core project management knowledge areas", "Apply project management knowledge, tools and techniques", "Master advanced statistical modelling techniques", "Demonstrate team and management skills"],
        correctIndex: 2,
        modelAnswer: "The five learning outcomes are: LO1 understand core PM knowledge areas, LO2 apply PM knowledge/tools/techniques, LO3 demonstrate developed and refined PM skills, LO4 develop basic proficiency in PM tools and practices, LO5 demonstrate team and management skills — statistical modelling is not among them.",
      },
      {
        type: "truefalse",
        prompt: "True or False: The Final Exam is a fully closed-book exam permitting no notes of any kind.",
        options: ["True", "False"],
        correctIndex: 1,
        modelAnswer: "The Final Exam is a restricted open-book exam: one A4 sheet of handwritten and/or typed notes, double-sided, is allowed.",
      },
      {
        type: "short",
        prompt: "List the four assessment components of INFO6007 described in the Week 1 lecture excluding the Final Exam, and their weightings.",
        modelAnswer: "Early Semester Feedback Task (5%, held Week 4, covering Weeks 1-3 content); Weekly progress evaluation (10%, conducted in tutorials Weeks 6-12, based on the group project's GitHub board); Group Assignment (25%, groups of 4-5, submitted Week 13). Together with the Final Exam (60%), these make up the full assessment weighting.",
      },
      {
        type: "short",
        prompt: "Explain the INFO6007 hurdle requirement in your own words, including both conditions a student must meet to pass.",
        modelAnswer: "To pass, a student must achieve at least 40% in the written examination AND an overall final mark of 50 or more. If either condition isn't met, the student's final mark is capped at a maximum of 45 regardless of how high their combined average would otherwise be — so strong coursework marks cannot compensate for failing the exam hurdle.",
      },
      {
        type: "short",
        prompt: "According to the 'Expectations' slide, list four things students are expected to do beyond attending scheduled classes.",
        modelAnswer: "Devote about 6-9 hours per week to study beyond lectures/tutorials; read weekly readings before attending lecture; check Canvas at least once a week and Ed-Forum at least once a day; and notify academics and team members honestly and promptly about difficulties.",
      },
      {
        type: "short",
        prompt: "What resources does Canvas provide for INFO6007 students, and what is the Ed Forum used for, per the Resources slide?",
        modelAnswer: "Canvas (accessed via Unikey/password) provides lecture recordings, lecture slides, tutorial slides, assignment specs, weekly readings, and announcements, plus assignment submission links and rubrics. The Ed Forum is used to communicate with the rest of the cohort, ask doubts to tutors/TAs/the professor, and receive announcements.",
      },
      {
        type: "scenario",
        prompt: "A student scores 85% on the Group Assignment, 90% on the Weekly progress evaluation, and full marks on the Early Semester Feedback Task, but only scores 35% on the Final Exam. Using the hurdle requirement, determine whether this student passes the unit, and explain why.",
        modelAnswer: "Even though this student's weighted average across coursework and exam might otherwise exceed 50, they scored only 35% on the written exam, below the required 40% hurdle. Per the Hurdle Requirement slide, failing to meet the exam hurdle caps the final mark at a maximum of 45 regardless of overall average — so this student does not pass the unit, despite strong coursework performance.",
      },
      {
        type: "scenario",
        prompt: "A friend in your tutorial says: 'I'll just skip the tutorials since only the lecture content is examined.' Using the schedule and assessment information from Week 1, explain why this is a risky strategy.",
        modelAnswer: "This is risky because tutorials are where the Weekly progress evaluation (10% of the final mark) is conducted, assessed against the group project's GitHub board progress across Weeks 6-12 — missing tutorials directly forfeits this contribution mark. Tutorials are explicitly flagged as 'important to attend,' and since the unit is hurdle-assessed (requiring both 40% on the exam and 50 overall), losing 10 achievable percentage points makes it harder to clear the overall 50 threshold even if the exam itself is passed comfortably.",
      },
      {
        type: "mcq",
        prompt: "Per the PMBOK Guide (6th edition), a project is defined as what?",
        options: ["A temporary effort undertaken to create a unique product, service, or result", "An ongoing operational activity with no defined end date", "Any task assigned to more than one person", "A recurring business process performed the same way each time"],
        correctIndex: 0,
        modelAnswer: "PMBOK (6th ed., p.4) defines a project as 'a temporary effort/work undertaken to create a unique product, service, or result.'",
      },
      {
        type: "mcq",
        prompt: "Which of the following is NOT listed as one of the four key characteristics of a project?",
        options: ["Temporary", "Unique outcome", "Specific objectives", "Unlimited resources"],
        correctIndex: 3,
        modelAnswer: "The four characteristics are temporary, unique outcome, specific objectives, and constraints — projects work within limitations of scope, time, cost, and resources, not unlimited resources.",
      },
      {
        type: "mcq",
        prompt: "According to the Triple Constraint table, if a project's time is reduced, what must happen?",
        options: ["Cost must increase or scope must decrease", "Quality automatically improves", "Nothing else needs to change", "Scope must always increase"],
        correctIndex: 0,
        modelAnswer: "The Triple Constraint table states: 'If Time is reduced → Cost must increase or Scope must decrease.'",
      },
      {
        type: "mcq",
        prompt: "Which of the following sits at the centre of the Triple Constraint triangle (Scope, Time, Cost)?",
        options: ["Quality", "Risk", "Stakeholders", "Communication"],
        correctIndex: 0,
        modelAnswer: "The Triple Constraint diagram places 'Quality' at the centre of the triangle formed by Scope (features, functionality), Time (deadlines, schedule), and Cost (budget, resources).",
      },
      {
        type: "mcq",
        prompt: "Which of these is a listed 'common misconception about success' in the lecture?",
        options: ["\"Finishing on time and budget = success\", even if the product isn't usable or valuable", "Success always requires exceeding the original budget", "Only the project manager's personal opinion of success matters", "Success can only be measured after the project starts"],
        correctIndex: 0,
        modelAnswer: "The 'Common misconceptions about success' slide directly lists this: 'Finishing on time and budget = success' — 'Not if the product isn't usable or valuable.'",
      },
      {
        type: "mcq",
        prompt: "Which of the following best distinguishes a 'program' from a 'project,' per the lecture?",
        options: ["A program is a collection of related projects managed in a coordinated way to achieve benefits not possible by managing them separately", "A program is simply a smaller task within a single project", "A program never has a manager assigned to it", "A program is always shorter in duration than a single project"],
        correctIndex: 0,
        modelAnswer: "The lecture defines a program as 'a collection of related projects managed in a coordinated way to achieve benefits not possible by managing them separately,' overseen by a Program Manager.",
      },
      {
        type: "mcq",
        prompt: "Who typically manages a portfolio, per the lecture?",
        options: ["A Portfolio Manager or PMO (Project Management Office)", "A single individual developer", "The Program Manager only, with no separate oversight", "External auditors only"],
        correctIndex: 0,
        modelAnswer: "The 'Portfolio Management' slide states a portfolio is 'Managed by a Portfolio Manager or PMO (Project Management Office).'",
      },
      {
        type: "truefalse",
        prompt: "True or False: Per the lecture's comparative overview, a program's success is measured by the program's ability to deliver its intended benefits to the organisation, not solely by individual project metrics like timeliness or budget compliance.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "The comparative table states program success is 'measured by the program's ability to deliver its intended benefits to an organization' and 'the program's efficiency and effectiveness in delivering those benefits' — distinct from project success, which is measured by product/project quality, timeliness, and budget compliance.",
      },
      {
        type: "short",
        prompt: "Define 'project' using the PMBOK definition, and list its four key characteristics from the lecture.",
        modelAnswer: "A project is 'a temporary effort/work undertaken to create a unique product, service, or result' (PMBOK Guide, 6th ed.). Its four key characteristics: temporary (clear start/end, not ongoing), unique outcome (produces something new), specific objectives (aims to meet particular goals or solve a problem), and constraints (operates within limits of scope, time, cost, and resources).",
      },
      {
        type: "short",
        prompt: "Explain the Triple Constraint relationship described in the lecture using an original example different from the slides.",
        modelAnswer: "Scope, time, and cost are interdependent: if scope increases, time and/or cost must also increase; if time is reduced, cost must increase or scope must decrease; if budget is reduced, scope must reduce. Example: if a client asks for a new payment-gateway integration to be added to an app (scope increase) but insists the original 3-month deadline stays fixed (time held constant), the team must add more developers or pay for overtime (cost increase) to absorb the added scope without slipping the deadline.",
      },
      {
        type: "short",
        prompt: "Using the case study's four causes of project failure at Aurora Tech, briefly explain each cause in your own words.",
        modelAnswer: "Scope creep: sales leadership kept requesting new features during execution without going through formal change management, so the agreed scope kept expanding uncontrolled. Poor communication: developers built the system without staying aligned to what end users actually needed, leading to usability problems discovered too late. Lack of stakeholder involvement: the sales team wasn't engaged during testing, so problems weren't caught until costly rework was needed. Underestimated technical complexity: integrating with legacy systems was harder than planned, causing repeated delays.",
      },
      {
        type: "short",
        prompt: "List the three tiers of management described in the lecture (Project → Program → Portfolio) and state the key objective of each in one phrase.",
        modelAnswer: "Project Management: tactical execution, with the key objective to deliver a successful individual project. Program Management: strategic coordination of related projects, with the key objective to deliver business value across multiple projects. Portfolio Management: enterprise alignment of programs and projects, with the key objective to maximise value and alignment with organisational strategy.",
      },
      {
        type: "scenario",
        prompt: "Aurora Tech's CRM project ran 4 months over its original 6-month timeline and 40% over its $500,000 budget, after sales leadership added multiple features mid-project without formal change control. Using the Triple Constraint relationships from the lecture, explain what should have happened instead when the new feature requests came in.",
        modelAnswer: "Per the Triple Constraint table, if scope increases, time and/or cost must also increase — so the correct response would have been to formally evaluate each new feature request through change management, and either extend the timeline and/or increase the budget to absorb the added scope, or reject/defer the new features to protect the existing time and cost baselines. Instead, scope grew unchecked while time and cost were left unadjusted until the damage was already done, which is exactly why the project overran both its schedule and its budget simultaneously.",
      },
      {
        type: "scenario",
        prompt: "A CIO is deciding whether to describe her company's current initiative — 'roll out AI tools, cloud migration, and productivity software across the business, each run somewhat independently but all funded from the same technology investment budget' — as a project, a program, or a portfolio. Using the lecture's definitions, which term fits best, and why?",
        modelAnswer: "This best fits the definition of a portfolio: it's a collection of largely independent initiatives (AI tools, cloud migration, productivity software) grouped together to meet strategic business goals and managed around investment decisions and resource allocation from a shared budget — matching the lecture's own example: 'IT Portfolio: Includes cybersecurity, cloud, AI, and productivity tools.' It isn't a program, because a program specifically requires the projects to be coordinated to achieve benefits not available from managing them separately, whereas here the initiatives are described as run 'somewhat independently.'",
      },
      {
        type: "mcq",
        prompt: "Per PMBOK (6th ed.), project management is defined as?",
        options: ["The application of knowledge, skills, tools, and techniques to project activities to meet project requirements", "The process of hiring staff for a new business unit", "A method for tracking employee attendance", "A financial audit conducted at the end of a project"],
        correctIndex: 0,
        modelAnswer: "PMBOK (6th ed., p.10) defines project management as 'the application of knowledge, skills, tools, and techniques to project activities to meet project requirements.'",
      },
      {
        type: "mcq",
        prompt: "Which of the following is one of the seven key elements of Project Management listed in the lecture?",
        options: ["Risk", "Marketing", "Sales forecasting", "Recruitment"],
        correctIndex: 0,
        modelAnswer: "The seven key elements are Scope, Time, Cost, Quality, Risk, Communication, and Resources — Risk is explicitly one of them ('what could go wrong, and how do we mitigate it?').",
      },
      {
        type: "mcq",
        prompt: "Which category do 'Jira, Trello, or Asana' fall under in the 'Skills required for Project Management' slide?",
        options: ["Technical skills", "Soft skills", "Strategic skills", "Core PM skills"],
        correctIndex: 0,
        modelAnswer: "The slide lists 'Technical skills' as including 'Understanding of PM methodologies, Tools like Jira, Trello, or Asana, Reporting, etc.'",
      },
      {
        type: "mcq",
        prompt: "Which of these is listed as a 'soft skill' for project managers, per the lecture?",
        options: ["Conflict resolution", "Budgeting & cost control", "Understanding of PM methodologies", "Stakeholder management"],
        correctIndex: 0,
        modelAnswer: "Soft skills listed are Communication, Leadership, Conflict resolution, Negotiation, Decision making, and Adaptability — budgeting is a core PM skill, PM methodologies is a technical skill, and stakeholder management is a strategic skill.",
      },
      {
        type: "mcq",
        prompt: "According to the PMBOK knowledge-areas diagram, which knowledge area sits across all the others, connecting stakeholder needs to project success?",
        options: ["Project integration management", "Procurement management", "Communications management", "Quality management"],
        correctIndex: 0,
        modelAnswer: "The diagram shows 'Project integration management' as a horizontal band spanning all ten knowledge areas, connecting stakeholders' needs and expectations through to project success and the project portfolio.",
      },
      {
        type: "mcq",
        prompt: "How many knowledge areas are shown in the PMBOK framework diagram from the lecture?",
        options: ["6", "8", "10", "12"],
        correctIndex: 2,
        modelAnswer: "The diagram is explicitly labelled '10 Knowledge areas', covering scope, schedule, cost, quality, resource, communications, risk, procurement, and stakeholder management, plus integration management.",
      },
      {
        type: "mcq",
        prompt: "Per the 'Why use a Framework?' slide, which of the following is NOT listed as a benefit of using a Project Management Framework?",
        options: ["Ensures consistency across projects", "Reduces risk and increases predictability", "Guarantees zero project cost", "Improves communication and accountability"],
        correctIndex: 2,
        modelAnswer: "The listed benefits are consistency, reduced risk/increased predictability, improved communication/accountability, better decision-making support, and alignment with organisational goals — 'guaranteeing zero cost' is not a claim the lecture makes.",
      },
      {
        type: "truefalse",
        prompt: "True or False: Per the lecture's core components of a Project Management Framework, 'Tools and Templates' is one of the four listed components, alongside Project Lifecycle, Processes and Knowledge Areas, and Methodologies.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "The 'Introduction' slide for the Project Management Framework lists exactly these four core components: Project Lifecycle, Processes and Knowledge Areas, Tools and Templates, and Methodologies within the framework.",
      },
      {
        type: "short",
        prompt: "List the seven key elements of Project Management from the lecture and give a one-sentence description of each, using an example different from the slides.",
        modelAnswer: "Scope — what the project must achieve and its deliverables, e.g. 'build and launch a customer-facing mobile app with login, catalogue, and checkout.' Time — how long it will take and its deadlines, e.g. 'launch within 4 months.' Cost — the available budget and required resources, e.g. 'stay within a $200,000 development budget.' Quality — whether outcomes meet required standards, e.g. 'the app must pass accessibility and load-testing benchmarks before release.' Risk — what could go wrong and how to mitigate it, e.g. 'the third-party payment API might change its interface mid-project.' Communication — how information is shared among stakeholders, e.g. 'weekly stand-ups and a shared project dashboard.' Resources — the people, tools, and technologies needed, e.g. 'two backend developers, one designer, and a CI/CD pipeline.'",
      },
      {
        type: "short",
        prompt: "Explain the four categories of skills required for project management (core PM, soft, technical, strategic) listed in the lecture, with one example skill from each category.",
        modelAnswer: "Core PM skills — the fundamental mechanics of running a project, e.g. risk management. Soft skills — interpersonal capabilities for working with people, e.g. negotiation. Technical skills — familiarity with PM methodologies and tools, e.g. using Jira for sprint tracking. Strategic skills — bigger-picture business capability, e.g. stakeholder management.",
      },
      {
        type: "short",
        prompt: "Using the PMBOK 10-knowledge-areas diagram, name at least six of the ten knowledge areas shown.",
        modelAnswer: "Any six of: Scope management, Schedule management, Cost management, Quality management, Resource management, Communications management, Risk management, Procurement management, Stakeholder management, and Project integration management (which connects stakeholders' needs/expectations, through the other knowledge areas and supporting tools/techniques, to the project portfolio and enterprise success).",
      },
      {
        type: "short",
        prompt: "In the Aurora Tech case study, which specific knowledge area(s) from the PMBOK diagram were most directly failed by (a) the scope creep problem and (b) the lack of stakeholder involvement during testing?",
        modelAnswer: "(a) Scope creep directly failed Scope management, and since features were added without a formal process, it also touches Project integration management, which is meant to coordinate change control across the other knowledge areas. (b) Lack of stakeholder involvement during testing failed Stakeholder management, and indirectly Quality management, since the usability issues that resulted from skipping user engagement were essentially undetected quality defects.",
      },
      {
        type: "scenario",
        prompt: "You are assigned as project manager on a new internal tool, and your sponsor says 'just use whatever process feels natural, we don't need a formal framework — we know what we're doing.' Using the lecture's 'Why use a Framework?' slide, write a short response explaining two concrete risks of skipping a structured Project Management Framework.",
        modelAnswer: "First, without a framework there's no guaranteed consistency across the project's phases, so different team members may follow different informal processes, increasing risk and reducing predictability of outcomes — directly contradicting the framework benefit of 'reduces risk and increases predictability.' Second, without structured processes for decision-making and communication, accountability breaks down: it becomes unclear who owns which decisions or how issues are escalated, which is exactly the kind of 'weak governance and unclear decision rights' the lecture lists as a common IT project failure pattern, and which showed up at Aurora Tech as scope creep with no formal change management.",
      },
      {
        type: "scenario",
        prompt: "Redesign Aurora Tech's approach using the seven key elements of Project Management (Scope, Time, Cost, Quality, Risk, Communication, Resources). For each of the four causes of failure identified in the case study, name the ONE element of project management that, if properly managed, would have most directly prevented it.",
        modelAnswer: "Scope creep → Scope management: a formal change-control process attached to the defined scope would have required sales leadership's new feature requests to go through approval before being added. Poor communication → Communication management: a defined communication plan between developers and end users would have surfaced requirements misalignment earlier. Lack of stakeholder involvement in testing → Communication management: a defined engagement plan for the sales team during testing phases would have caught usability issues before go-live. Underestimated technical complexity → Risk management: a risk register identifying legacy-system integration as a high-impact risk early would have prompted contingency time/budget instead of repeated unplanned delays.",
      },
    ],
  }

export const WEEK_1_PAPERS: ExamPaperSeed[] = [PAPER];
