import type { ExamPaperSeed } from "../types";

// NOTE: In Week 6 the lecture and the tutorial cover different topics. The
// Week 6 LECTURE is Resource Management (the 6 resource processes, motivation
// theory, RACI/RBS/histogram, loading and leveling, Tuckman, conflict modes,
// Agile resource management; the guest talk on project management in a
// space-imaging startup is not examined). The Week 6 TUTORIAL is Quality Management tools and
// Cost of Quality (the tutorial always trails the lecture by one week: it
// applies the Week 5 quality lecture). Paper 1 (tutorial) is therefore a
// quality-tools paper; Paper 2 (lecture) is the resource-management paper.
// The lecturer only reached "Acquiring resources" in the recording and said
// the rest of the deck would continue next week; the whole deck is covered
// here because the slides are the exam material.

const TUTORIAL_PAPER: ExamPaperSeed = {
  course: "INFO6007",
  week: 6,
  paperNumber: 1,
  title: "Week 6 Practice Paper — Tutorial",
  topics:
    "Quality management tools applied to IT scenarios: cause-and-effect (fishbone/Ishikawa) diagram for payroll calculation errors and matching preventive measures to causes; checksheets and Pareto (80/20) reading of defect counts; choosing run chart, Pareto, control chart or scatter diagram to find trends and patterns in intermittent crashes; Cost of Quality — Cost of Conformance (prevention plus appraisal) versus Cost of Non-Conformance (internal plus external failure), the $2,000 prevention versus $20,000 external failure trade-off, and cost-benefit reasoning; cost, time and quality trade-offs; Part C weekly progress evaluation (individual marking, best 5 of 7, ticket assignment, descriptive naming, links to the shared document); continuity with Week 4 cost and the Week 5 quality lecture.",
  sourceFiles: [
    "tutorial/Tutorial sheet INFO6007 Week 06 Tutorial sheet.pdf",
    "lecture/Week 06 - Project Ma-s1-low.transcript.md",
  ],
  questions: [
    {
      type: "mcq",
      prompt: "The tutorial's Scenario 1 says a cloud-based HR system keeps producing payroll calculation errors and asks you to draw a cause-and-effect diagram. What is that diagram also called, and what is it used for?",
      options: [
        "It is also called a Pareto diagram, and it is used to rank defect types from most to least frequent with a cumulative line",
        "It is also called a fishbone or Ishikawa diagram, and it is used to map out the possible root causes of a problem",
        "It is also called a run chart, and it is used to plot a measure over time so that trends and unusual periods stand out",
        "It is also called a scatter diagram, and it is used to test whether two measured variables rise and fall together",
      ],
      correctIndex: 1,
      modelAnswer: "Think of a detective's wall with the crime in the middle and strings running out to every possible suspect — you are not solving it yet, you are listing everything that could have caused it.\n\n• What it is: a drawing shaped like a fish skeleton. The problem sits at the head and the possible causes are grouped on the bones that lead into it.\n\n• Its other names: fishbone diagram or Ishikawa diagram (after the person who popularised it).\n\n• Why the others are wrong: ranking defects is a Pareto chart, plotting over time is a run chart, and testing whether two things move together is a scatter diagram.\n\nSo the answer is: the cause-and-effect diagram, a.k.a. fishbone or Ishikawa, maps the possible root causes of a problem.",
    },
    {
      type: "mcq",
      prompt: "You draw the payroll fishbone. Where does the problem itself, 'payroll calculation errors', go on the diagram?",
      options: [
        "At the tail of the fish, because it happened first and every branch then flows outward from it",
        "On the smallest outer twigs, because the finest sub-causes are the ones that produce the final effect",
        "In a separate box beside the diagram, because the branches are meant to hold only causes and never the effect",
        "At the head of the fish, with the possible causes grouped on branches that lead into it",
      ],
      correctIndex: 3,
      modelAnswer: "Picture a tree of arrows all pointing at one target: the target is the thing you are trying to explain, and the arrows are the reasons.\n\n• The head: holds the effect, here 'payroll calculation errors'.\n\n• The bones: carry categories of cause such as People, Process, Software, Data and Environment, each with smaller causes hanging off them.\n\n• Why the others are wrong: the tail, the twigs or a separate box all hide the link between the causes and the problem they explain.\n\nSo the answer is: the problem goes at the head and the causes branch in toward it.",
    },
    {
      type: "multi",
      prompt: "Which of these are sensible possible causes to place on the branches of the payroll fishbone? Select all that apply.",
      options: [
        "The checksheet the team plans to use, which is only a tool for recording defects",
        "Test cases that do not cover overtime, bonus and deductions",
        "No second person reviewing the payroll calculation logic",
        "'Payroll calculation errors' itself, which is the problem the diagram explains",
        "Outdated tax rates or deduction rules stored in the payroll data",
        "Rounding or formula bugs inside the payroll software",
      ],
      correctIndices: [1, 2, 4, 5],
      modelAnswer: "Think of a broken-down car: worn tyres, an empty tank and a flat battery are causes, but 'the car will not go' is just the problem you started with.\n\n• Real causes: outdated tax rates (Data), missing reviews and thin test cases (Process), formula or rounding bugs (Software). Each one could actually produce a wrong payslip.\n\n• Not causes: the error itself sits at the head of the fishbone as the effect, and a checksheet is a tool for counting defects, not something that creates them.\n\nSo the answer is: the four real causes, and not the effect or the tracking tool.",
    },
    {
      type: "mcq",
      prompt: "Part A asks for three preventive measures using the fishbone as a reference. Which pairing of a cause with the measure that targets it is correct?",
      options: [
        "Outdated tax rates or bad employee data → validate the data and update payroll parameters before each release",
        "Faulty overtime or bonus formulas → validate the data and update payroll parameters before each release",
        "Incomplete test cases → have a second engineer review the payroll formulas against the business rules",
        "Bad employee records → write automated tests that check salary, tax, overtime and bonus results",
      ],
      correctIndex: 0,
      modelAnswer: "Match the medicine to the illness: you would not treat a broken arm with cough syrup, even though both are 'health measures'.\n\n• Data problems: outdated tax rates or wrong employee data are fixed by data validation and regular updates before each release.\n\n• Formula problems: a second engineer reviewing the logic against approved business rules catches wrong formulas (code review).\n\n• Missing-coverage problems: automated tests for salary, tax, overtime, bonus and deductions catch calculation errors before release.\n\nSo the answer is: data causes go with data validation and updates; the other pairings swap a cause with the wrong measure.",
    },
    {
      type: "mcq",
      prompt: "Part A also asks for a small checksheet to track similar defects in future releases. What is a checksheet?",
      options: [
        "A diagram that maps the steps of a process to reveal gaps, repeated work and points where quality risks arise",
        "A bar chart with a cumulative line that highlights the few causes responsible for most of the defects",
        "A structured form used to collect and tally data as it happens, such as how often each defect type occurs",
        "A graph of process results over time with upper and lower limits that flags unusual variation",
      ],
      correctIndex: 2,
      modelAnswer: "It is like the tally marks a shopkeeper makes on paper each time someone buys a particular item — quick, simple and done at the moment it happens.\n\n• What it does: makes data collection easy for defects, errors or process failures by giving a ready-made grid to tick.\n\n• In the tutorial: rows are defect types (salary, tax, overtime, claims, bonus), columns are releases, with totals at the end.\n\n• Why the others are wrong: mapping process steps is a flowchart, the cumulative bar chart is a Pareto chart, and the graph with limits is a control chart.\n\nSo the answer is: a checksheet is a simple form for tallying data in real time.",
    },
    {
      type: "mcq",
      prompt: "A payroll checksheet over two releases shows these defect totals:\n\n• Incorrect salary information: 3\n\n• Incorrect tax calculation: 5\n\n• Overtime calculation: 7\n\n• Claim calculation: 9\n\n• Bonus calculation: 7\n\nThe grand total is 31, with 16 defects in release 1 and 15 in release 2. Which conclusion does the checksheet directly support?",
      options: [
        "Overtime calculation is the most frequent defect category, at 9 of the 31 defects",
        "Claim calculation is the most frequent defect category, at 9 of the 31 defects",
        "Bonus calculation is the most frequent defect category, at 9 of the 31 defects",
        "The total number of defects rose from release 1 to release 2 across the board",
      ],
      correctIndex: 1,
      modelAnswer: "A checksheet is like a scoreboard: you do not need clever analysis to see who is winning, you just read down the totals.\n\n• Reading the totals: claim calculation has 9, overtime 7, bonus 7, tax 5 and salary 3, so claims is the biggest single category.\n\n• Reading the trend: release 1 had 16 defects and release 2 had 15, so the total went down slightly, not up.\n\n• Why the others are wrong: overtime and bonus each have 7, not 9, and the overall total fell.\n\nSo the answer is: claim calculation is the most frequent category with 9 of 31.",
    },
    {
      type: "mcq",
      prompt: "Using the same counts (claim 9, overtime 7, bonus 7, tax 5, salary 3, total 31), roughly what share of all defects do the three biggest categories cover, and how does a Pareto chart use this?",
      options: [
        "About 52% (16 of 31), so a Pareto chart directs effort at the few biggest categories first",
        "About 26% (8 of 31), so a Pareto chart directs effort at the few biggest categories first",
        "About 74% (23 of 31), so a Pareto chart directs effort at the few biggest categories first",
        "About 74% (23 of 31), so a Pareto chart directs effort evenly across every category",
      ],
      correctIndex: 2,
      modelAnswer: "Imagine a messy room where three piles of clutter make up most of the mess — you tidy those three first and the room looks much better fast.\n\n• The sum: 9 + 7 + 7 = 23 defects out of 31, which is about 74%.\n\n• The 80/20 rule: roughly 80% of problems come from about 20% of the causes, so a Pareto chart (a bar chart plus a cumulative line) shows where fixing pays off most.\n\n• Why the others are wrong: 16 of 31 is only the top two categories, 8 of 31 is the bottom two, and spreading effort evenly is the opposite of what a Pareto chart is for.\n\nSo the answer is: about 74%, and the Pareto chart says fix those biggest categories first.",
    },
    {
      type: "mcq",
      prompt: "The Pareto chart shows overtime miscalculation causes most payroll defects. Which tool would the team most naturally use next to dig into why?",
      options: [
        "A checksheet turned into a second Pareto chart of overtime miscalculation itself",
        "A run chart of total payroll defects plotted release by release",
        "A cost-benefit analysis comparing the price of every possible quality tool",
        "A cause-and-effect (fishbone) diagram focused on overtime miscalculation",
      ],
      correctIndex: 3,
      modelAnswer: "It is like a doctor: first a scan tells you which organ has the problem, then further tests find out why that organ is failing.\n\n• Pareto chart: tells you which problem to focus on (overtime miscalculation).\n\n• Fishbone diagram: lists the possible root causes of that one problem so the team can investigate systematically.\n\n• Why the others are wrong: another chart of the same counts adds nothing new, and a release-by-release run chart or a tool cost comparison does not explain causes.\n\nSo the answer is: use the fishbone next, to find the root causes of the biggest problem.",
    },
    {
      type: "truefalse",
      prompt: "A checksheet is mainly a tool for working out the root causes of a defect.",
      options: [
        "True",
        "False",
      ],
      correctIndex: 1,
      modelAnswer: "A checksheet is like a tally sheet by a shop till: it counts what happened, it does not explain why.\n\n• What it does: collects and tallies data in real time, for example how many defects of each type appear in each release.\n\n• What finds root causes: a cause-and-effect (fishbone) diagram is the tool used to identify possible root causes.\n\nSo the answer is: False — a checksheet collects data; the fishbone is the root-cause tool.",
    },
    {
      type: "mcq",
      prompt: "In Scenario 2 a module crashes intermittently during report generation. Which tool plots the number of crashes per release or per day in time order, so you can see whether they rise, fall or cluster?",
      options: [
        "A run chart, which plots crash counts in time order so trends and unusual periods stand out",
        "A Pareto chart, which ranks crash causes from biggest to smallest with a cumulative percentage line",
        "A histogram, which groups crash counts into ranges to show how the values are distributed",
        "A fishbone diagram, which lays out the possible root causes of the crashes on branches",
      ],
      correctIndex: 0,
      modelAnswer: "Think of a heart-rate monitor: it draws the reading as time passes so you can spot when it spikes or drifts.\n\n• The run chart: points plotted in time order, so a rising trend, a falling trend or an odd cluster of crashes becomes visible.\n\n• Why it suits intermittent crashes: the crashes come and go, so seeing them across releases, days or report types can reveal when they happen.\n\n• Why the others are wrong: a Pareto chart ranks causes, a histogram shows distribution, and a fishbone lists causes — none of them shows behaviour over time.\n\nSo the answer is: a run chart.",
    },
    {
      type: "mcq",
      prompt: "The team logs each crash by cause: database timeout (most), then memory issue, invalid report data, API failure and other. Why is a Pareto chart a good second tool here?",
      options: [
        "It shows when each crash happened, so a rising or falling trend across releases can be spotted",
        "It shows whether crashes are linked to another measure such as report size, so a correlation can be checked",
        "It shows which few causes produce most of the crashes, so investigation can start with those",
        "It shows how far crash counts sit from upper and lower limits, so unusual variation can be flagged",
      ],
      correctIndex: 2,
      modelAnswer: "Picture a list of complaints sorted from the most common to the least — you would obviously start by fixing the top one or two.\n\n• What it does: a bar chart with a cumulative line that ranks causes by how many crashes each one produced (the 80/20 rule).\n\n• Why it helps: the team can focus on the causes responsible for most of the crashes instead of investigating every possible cause equally.\n\n• Why the others are wrong: trends over time are a run chart, links between two variables are a scatter diagram, and limits belong to a control chart.\n\nSo the answer is: it points the team at the few biggest causes first.",
    },
    {
      type: "mcq",
      prompt: "The team suspects crashes get more likely as reports cover more employees. Which tool best tests whether crashes and report size move together?",
      options: [
        "A checksheet, tallying how many crashes occur in each report module as they happen",
        "A scatter diagram, plotting report size against crashes to see whether the two variables are related",
        "A flowchart, mapping each step the report generator takes so gaps and repeats become visible",
        "A fishbone diagram, listing possible causes of the crashes under People, Process and Software",
      ],
      correctIndex: 1,
      modelAnswer: "It is like plotting shoe size against height to see whether taller people tend to have bigger feet: each person is one dot, and the pattern of dots shows the link.\n\n• What it does: a scatter diagram is a graph showing the relationship between two variables so a correlation can be spotted.\n\n• Here: one axis is report size (number of employees), the other is crash count, so a rising cloud of dots suggests size is a cause.\n\n• Why the others are wrong: tallying, process mapping and cause lists do not compare two measured variables.\n\nSo the answer is: a scatter diagram.",
    },
    {
      type: "multi",
      prompt: "Scenario 2 asks you to choose two quality tools to identify trends or patterns in the crash data. Which of these could serve that purpose? Select all that apply.",
      options: [
        "A control chart showing crashes against upper and lower limits",
        "A run chart of crashes over time",
        "A cost-benefit analysis of each quality activity",
        "A flowchart of the report generation process",
        "A scatter diagram of crashes against report size",
        "A Pareto chart of crashes by cause",
      ],
      correctIndices: [0, 1, 4, 5],
      modelAnswer: "Think of four different lenses for looking at the same pile of data: one shows change over time, one shows the biggest causes, one shows unusual swings, and one shows links between two things.\n\n• Pattern tools: the run chart (trends over time), Pareto chart (biggest causes), control chart (variation outside limits) and scatter diagram (relationship between two variables) all reveal something about patterns in the data.\n\n• Not pattern tools: cost-benefit analysis weighs the cost of a quality activity against its benefit, and a flowchart maps process steps to find gaps.\n\nSo the answer is: run chart, Pareto chart, control chart and scatter diagram.",
    },
    {
      type: "mcq",
      prompt: "Part B: skipping some preventive measures would save $2,000 now. In Cost of Quality terms, what is that $2,000?",
      options: [
        "Cost of Conformance, money spent on prevention so defects do not happen in the first place",
        "Cost of Non-Conformance, money lost because defects have already reached the users",
        "Internal failure cost, the price of fixing a defect that was found during testing",
        "External failure cost, the price of fixing a defect that was found after release",
      ],
      correctIndex: 0,
      modelAnswer: "It is like paying for a smoke alarm: you spend a little before anything goes wrong so you never face the fire damage.\n\n• Cost of Conformance: the money spent to make sure the product meets quality requirements. It has two parts, prevention and appraisal.\n\n• The $2,000: it is spent on preventive measures, so it is a prevention cost inside the Cost of Conformance.\n\n• Why the others are wrong: failure costs are what you pay after a defect exists.\n\nSo the answer is: the $2,000 is Cost of Conformance (prevention).",
    },
    {
      type: "mcq",
      prompt: "During testing the QA team found defects that cost $8,000 to fix internally. How is that $8,000 classified in the lecture's Cost of Quality breakdown?",
      options: [
        "Appraisal cost, part of the Cost of Conformance because the QA team found the defect through testing",
        "Prevention cost, part of the Cost of Conformance because fixing it early stops it reaching customers",
        "External failure cost, part of the Cost of Non-Conformance because customers had to be told about it",
        "Internal failure cost, part of the Cost of Non-Conformance because the defect had already been created",
      ],
      correctIndex: 3,
      modelAnswer: "Testing to find a leak is one cost; paying a plumber to repair the leak once it has appeared is a different cost.\n\n• Cost of Conformance: prevention plus appraisal, for example automated tests, code reviews and training done to stop or detect defects.\n\n• Cost of Non-Conformance: internal failures plus external failures, for example bug fixes, downtime and customer complaints.\n\n• The $8,000: it is the money spent fixing defects that already exist but were caught before release, so it is an internal failure cost.\n\nSo the answer is: internal failure cost, which belongs to the Cost of Non-Conformance.",
    },
    {
      type: "mcq",
      prompt: "If the preventive measures are skipped, the defects may reach customers and cost $20,000 to fix after release. How is that $20,000 classified?",
      options: [
        "Internal failure cost, a Cost of Non-Conformance for defects that were found before the release went out",
        "External failure cost, a Cost of Non-Conformance that appears when defects reach customers after release",
        "Prevention cost, a Cost of Conformance for money spent to stop defects being created in the first place",
        "Appraisal cost, a Cost of Conformance for money spent on testing and reviews to detect defects",
      ],
      correctIndex: 1,
      modelAnswer: "Fixing a mistake in your homework before handing it in is cheap; having the teacher, the parents and the class see the mistake afterwards is expensive.\n\n• External failure: a defect that reaches customers and has to be fixed after release. Examples are emergency fixes, downtime and customer complaints.\n\n• Cost of Non-Conformance: the internal failure costs plus the external failure costs.\n\n• Why the others are wrong: prevention and appraisal costs are spent before a defect reaches anyone, and internal failures are caught before release.\n\nSo the answer is: external failure cost, part of the Cost of Non-Conformance.",
    },
    {
      type: "multi",
      prompt: "Which of these are Cost of Conformance items (prevention or appraisal) rather than Cost of Non-Conformance? Select all that apply.",
      options: [
        "Code reviews of the payroll formulas",
        "Emergency bug fixes after a release",
        "System downtime caused by a defect in production",
        "Training developers on the payroll rules",
        "Handling customer complaints about wrong pay",
        "Automated tests run before each release",
      ],
      correctIndices: [0, 3, 5],
      modelAnswer: "Think of the difference between servicing your car regularly and paying for a tow truck after it breaks down on the highway.\n\n• Cost of Conformance (spending to prevent or detect): automated tests, code reviews and training all aim to stop or catch defects early.\n\n• Cost of Non-Conformance (spending because defects happened): bug fixes, downtime and customer complaints are all consequences of defects.\n\nSo the answer is: automated tests, code reviews and training.",
    },
    {
      type: "multi",
      prompt: "Which of these belong to the Cost of Non-Conformance? Select all that apply.",
      options: [
        "Prevention: training and standards meant to stop defects being created",
        "Appraisal: testing and reviews meant to detect defects before release",
        "Internal failure: defects that are fixed during testing before release",
        "External failure: defects that customers find after release",
      ],
      correctIndices: [2, 3],
      modelAnswer: "Picture two piles of receipts: one pile is money spent to avoid trouble, the other is money spent because trouble happened.\n\n• Cost of Non-Conformance: internal failures plus external failures — the reactive cost of fixing defects.\n\n• Cost of Conformance: prevention plus appraisal — the proactive cost of stopping or detecting defects.\n\nSo the answer is: internal failure and external failure.",
    },
    {
      type: "mcq",
      prompt: "Skipping the preventive measures saves $2,000 but could lead to $20,000 in external failure costs. What is the potential net effect of skipping?",
      options: [
        "A net saving of $2,000, because the $20,000 is only a possibility and has not actually been spent",
        "A potential net loss of $22,000, because the $2,000 saved is added on top of the $20,000 failure cost",
        "A potential net loss of $18,000, because the $20,000 risk is far larger than the $2,000 saved",
        "A potential net loss of $12,000, because the $8,000 already spent is taken off the $20,000 risk",
      ],
      correctIndex: 2,
      modelAnswer: "It is like skipping a $2 bike lock and risking a $20 hit if the bike is stolen: you saved a little but exposed yourself to a much bigger loss.\n\n• The sum: the skipped prevention saves $2,000, but the failure it could cause costs $20,000, so the potential difference is 20,000 − 2,000 = $18,000.\n\n• Why the others are wrong: adding the $2,000 instead of subtracting it gives $22,000, and the $8,000 internal cost is a separate, already-incurred cost that does not offset the risk.\n\nSo the answer is: a potential net loss of $18,000.",
    },
    {
      type: "mcq",
      prompt: "Part B asks which single action the project manager should take to minimise total Cost of Quality. What is the best action?",
      options: [
        "Skip the preventive measures, because the $2,000 saved is certain while the $20,000 is only a possibility",
        "Skip the preventive measures and fix defects after release, because internal fixes at $8,000 cost less than prevention",
        "Cancel further testing this cycle, because $8,000 of defects have already been found and the quality budget is spent",
        "Spend the $2,000 on preventive measures, because prevention costs far less than the $20,000 failure it may avoid",
      ],
      correctIndex: 3,
      modelAnswer: "Paying a small repair bill now is usually better than waiting for something to break at the worst possible moment.\n\n• The principle: prevention is cheaper than failure, so spending $2,000 to potentially avoid $20,000 lowers the total Cost of Quality.\n\n• The trade-off: a little extra time and cost now protects quality and avoids much larger costs later.\n\n• Why the others are wrong: they keep the $2,000 but ignore the much larger expected failure cost, or they wrongly treat internal fixes as a substitute for prevention.\n\nSo the answer is: spend the $2,000 on preventive measures.",
    },
    {
      type: "mcq",
      prompt: "Which statement best describes the cost, time and quality trade-off in Part B?",
      options: [
        "Skipping prevention saves cost and time now, but raises the risk of lower quality and far higher failure costs later",
        "Skipping prevention saves cost and time and leaves quality unchanged, because testing will find every defect anyway",
        "Spending on prevention lowers quality, because effort goes into testing and reviews instead of building features",
        "Adding prevention shortens the schedule, because fewer defects means no testing time is needed at all",
      ],
      correctIndex: 0,
      modelAnswer: "Think of cramming for an exam the night before: you save time now, but you risk a much worse result and a much bigger problem later.\n\n• Cost and time now: cutting preventive work does save some money and effort in the short term.\n\n• Quality later: it raises the risk of lower quality, customer dissatisfaction and costly external failures after release.\n\n• Why the others are wrong: they claim skipping is free, that prevention harms quality, or that prevention removes the need for testing, none of which the lecture says.\n\nSo the answer is: cutting prevention trades short-term savings for a bigger risk to quality and cost later.",
    },
    {
      type: "multi",
      prompt: "Which of these statements about quality trade-offs are correct according to the Week 5 lecture? Select all that apply.",
      options: [
        "Extending the timeline always lowers total cost, because extra testing time is free",
        "Adding more features can dilute the focus on the quality of existing functionality",
        "Cutting costs never affects quality, because any defects can be fixed later at the same price",
        "Investing in prevention through training and standards reduces defects later",
        "Tight schedules can force teams to cut testing and put quality at risk",
        "Higher quality often needs more investment up front, such as prevention, testing and training",
      ],
      correctIndices: [1, 3, 4, 5],
      modelAnswer: "Project trade-offs are like a see-saw: pushing hard on one side (speed, features, low cost) tends to lift something else off the ground, often quality.\n\n• Cost versus quality: more investment in prevention and testing costs money up front; cutting costs can increase defects and rework.\n\n• Time versus quality: tight timelines may force shortcuts; a longer timeline allows thorough testing but may cost more.\n\n• Scope versus quality: piling on features can dilute attention to what already exists.\n\n• Prevention versus quality: training and standards reduce defects later.\n\nSo the answer is: the four true statements, not the two that claim cuts are free or extra time is always cheaper.",
    },
    {
      type: "mcq",
      prompt: "The tutorial asks you to minimise total Cost of Quality (CoQ). What does Cost of Quality mean?",
      options: [
        "The cost of the rework needed after a product has already failed its acceptance tests",
        "The total cost of preventing, detecting and correcting defects so that the product meets its quality requirements",
        "The salary budget for the quality manager and QA team members over the whole project",
        "The price of buying quality tools such as automated testing software and code analysers",
      ],
      correctIndex: 1,
      modelAnswer: "Think of everything a restaurant spends on food safety: inspections, staff training, and also the cost of dealing with a customer who got sick.\n\n• Cost of Quality: everything spent to make sure the product meets requirements — preventing defects, finding them and fixing them.\n\n• Its two halves: Cost of Conformance (prevention plus appraisal) and Cost of Non-Conformance (internal plus external failures).\n\n• Why the others are wrong: they only cover one slice, such as post-failure rework, salaries or tool purchases.\n\nSo the answer is: the total cost of preventing, detecting and correcting defects.",
    },
    {
      type: "mcq",
      prompt: "In Part B you compare a $2,000 prevention spend against a possible $20,000 failure cost. Which Week 5 quality technique does that comparison most resemble?",
      options: [
        "Cost-benefit analysis, weighing the cost of a quality activity against the benefits it is expected to bring",
        "A control chart, tracking process performance over time against upper and lower control limits",
        "A flowchart, mapping process steps to find gaps, redundancies and quality risk points",
        "A histogram, showing the frequency distribution of defects to reveal patterns in the data",
      ],
      correctIndex: 0,
      modelAnswer: "It is like deciding whether a $50 warranty is worth it by comparing it with the price of a possible $400 repair.\n\n• Cost-benefit analysis: compares the cost of doing a quality activity with the benefit it should bring, so the team can prioritise by return on investment.\n\n• In Part B: $2,000 of prevention is set against $20,000 of avoided failure, so prevention wins clearly.\n\nSo the answer is: cost-benefit analysis.",
    },
    {
      type: "truefalse",
      prompt: "Prevention is usually cheaper than fixing defects after release, so spending on it tends to lower the total Cost of Quality.",
      options: [
        "True",
        "False",
      ],
      correctIndex: 0,
      modelAnswer: "It is cheaper to put a helmet on before riding than to pay for hospital care after a fall.\n\n• The principle: the lecture calls this the cost of quality principle — preventing a defect is far cheaper than fixing it later.\n\n• In the tutorial: $2,000 of prevention may avoid $20,000 of external failure cost.\n\nSo the answer is: True.",
    },
    {
      type: "multi",
      prompt: "Part C says the tutor will visit your team and each member needs to be ready to do certain things. Which of these are required? Select all that apply.",
      options: [
        "Hand in the finished group report so the tutor can mark it",
        "Explain your own progress over the past week",
        "Explain your plan for the next week",
        "Be ready to show your work evidence to the tutor",
        "Speak only about the group's overall progress, not your own part",
      ],
      correctIndices: [1, 2, 3],
      modelAnswer: "It is like a daily stand-up: each person says what they did, what they will do next, and can point to proof.\n\n• What is asked: each member explains their progress in the past week, plans for the next week, and shows work evidence.\n\n• Why the others are wrong: the final report is a Week 13 deliverable, and the evaluation is marked individually, so you must speak about your own work.\n\nSo the answer is: explain progress, explain next week's plan, and show evidence.",
    },
    {
      type: "multi",
      prompt: "At the start of the lecture the lecturer described what he noticed in the weekly evaluations. Which improvements did he ask for? Select all that apply.",
      options: [
        "Give tickets descriptive names",
        "Link the ticket directly to the relevant place in the shared document",
        "Keep one large ticket per person to reduce admin",
        "Assign every ticket to a specific individual team member",
        "Assign tickets to the whole team so anyone can pick them up later",
        "Explain both progress to date and the plan for next week",
      ],
      correctIndices: [0, 1, 3, 5],
      modelAnswer: "Think of a shared to-do list on a fridge: a note that says 'someone please do the dishes' gets ignored, while 'Sam: wash the pans by 6pm' gets done.\n\n• Assign to individuals: some tickets had not been given to any specific person.\n\n• Descriptive names: so anyone reading the board understands the ticket at a glance.\n\n• Direct links: a link to the exact place in the shared document lets the lecturer check later what was done.\n\n• Two-part update: clearly explain progress to date and the plan for next week.\n\nSo the answer is: individual assignment, descriptive names, direct links and a two-part update.",
    },
    {
      type: "mcq",
      prompt: "Why did the lecturer suggest linking each ticket straight to the specific place in the shared document, for example the cost management plan?",
      options: [
        "It lets the ticket close automatically as soon as the linked document section is saved",
        "It removes the need to keep the group's work in a shared folder in the first place",
        "It allows the tutor to rewrite the linked section on the group's behalf before marking",
        "It makes it easy to check later, at the end of the semester, exactly what was done on that ticket",
      ],
      correctIndex: 3,
      modelAnswer: "It is like putting a page number on a bookmark: it takes the reader straight to the proof instead of making them search.\n\n• The reason: the lecturer wants to be able to look back, at the end of semester, and see what was actually done for each ticket.\n\n• The setup: he recommended a shared folder for the project and a link in the ticket pointing to the exact spot in the document.\n\nSo the answer is: so the work can be checked easily later.",
    },
    {
      type: "mcq",
      prompt: "According to the unit's assessment overview, how is the weekly progress evaluation scored?",
      options: [
        "All 7 evaluations counted at 2 marks each across Weeks 6 to 12, marked as a group, worth 10%",
        "Best 3 of 5 evaluations across Weeks 8 to 12, up to 4 marks each, marked individually, worth 15%",
        "Best 5 of 7 evaluations across Weeks 6 to 12, up to 2 marks each, marked individually, worth 10%",
        "Best 5 of 7 evaluations across Weeks 6 to 12, up to 2 marks each, marked as a group, worth 25%",
      ],
      correctIndex: 2,
      modelAnswer: "It is like a season of matches where only your best five results count, so one bad week does not sink you.\n\n• Format: a short stand-up-style meeting in tutorial, based on the group project board.\n\n• Scoring: best 5 out of the 7 evaluations held in Weeks 6 to 12, up to 2 marks each, so 10 marks and 10% of the unit.\n\n• Marking: individually, not as a group.\n\nSo the answer is: best 5 of 7, 2 marks each, marked individually, 10%.",
    },
    {
      type: "truefalse",
      prompt: "The weekly progress evaluation is marked for the whole group together, so an individual's own contribution does not affect their mark.",
      options: [
        "True",
        "False",
      ],
      correctIndex: 1,
      modelAnswer: "It is like a group project where everyone gets called on to explain their own part, not just the loudest person.\n\n• What the assessment overview says: the weekly progress evaluation is marked individually.\n\n• What that means: each member has to explain their own progress and plan and show evidence.\n\nSo the answer is: False.",
    },
  ],
};

const LECTURE_PAPER: ExamPaperSeed = {
  course: "INFO6007",
  week: 6,
  paperNumber: 2,
  title: "Week 6 Practice Paper — Lecture",
  topics:
    "Project Resource Management, applied: spotting which resource process is failing (Acquire versus Develop Team and Manage Team); leadership style for a crisis versus a skilled self-motivated team; Maslow's hierarchy (job-advert mapping, the reading's clarification and its alignment with Herzberg); Herzberg hygiene factors versus motivators and the unpaid-salary example; Covey's habits in scenarios; RACI role assignment and reading a RACI chart; Resource Breakdown Structure (three-level paths, RBS versus WBS) and reading a resource histogram; classifying IT project resources; multi-source acquisition; estimating mismatches; resource loading (over-allocation) and resource leveling using slack, its techniques and its effect on the schedule; Tuckman stage descriptions; conflict handling modes and the team dysfunction of avoiding accountability; productivity, availability and cost trade-off calculations (Bill, Mary, Minh and Nora); Agile resource management; and the Cloud Banking case study (covering an absence and staying within a fixed budget).",
  sourceFiles: [
    "lecture/Lecture - INFO6007 Week 06 - Resource Management Plan.pdf",
    "lecture/Reading 1 - Maslow's Hierarchy of Needs.pdf",
    "lecture/Week 06 - Project Ma-s1-low.transcript.md",
  ],
  questions: [
    {
      type: "mcq",
      prompt: "A production system goes down at 2am and the team cannot agree what to try first. Which leadership style does the lecture say suits this best, and why?",
      options: [
        "Democratic, because involving everyone produces the most innovative fix even though it takes longer",
        "Laissez-faire, because skilled people work best when given minimal direction and full autonomy",
        "Autocratic, because one person decides quickly and unilaterally, which is useful in a crisis such as an outage",
        "Democratic, because engagement matters more than speed whenever systems are down",
      ],
      correctIndex: 2,
      modelAnswer: "When a fire alarm goes off, you want one person shouting clear instructions, not a committee vote about which exit to use.\n\n• Autocratic (directive): the leader decides alone. Pros: fast decisions, useful in crises such as a system outage. Cons: low motivation and stifled creativity.\n\n• Why the others are wrong: democratic decisions are slower, and laissez-faire leaves too much unclear in an emergency.\n\nSo the answer is: autocratic, for fast decisions in a crisis.",
    },
    {
      type: "mcq",
      prompt: "Which team is the best fit for a hands-off, laissez-faire leader?",
      options: [
        "A brand-new team whose members do not yet know one another's roles",
        "A team facing a live outage with no time to discuss options",
        "A highly skilled, self-motivated team that can work well without much direction",
        "A team with unclear responsibilities and a history of overlapping work",
      ],
      correctIndex: 2,
      modelAnswer: "A group of expert musicians can play well with a light-touch conductor, but a group of beginners needs a lot more guidance.\n\n• Laissez-faire: minimal direction, lots of autonomy. It works with highly skilled, self-motivated teams.\n\n• The risk: it can lead to confusion or lack of coordination when roles are unclear or the team needs direction.\n\nSo the answer is: a highly skilled, self-motivated team.",
    },
    {
      type: "multi",
      prompt: "The lecturer said a job advertisement quietly covers Maslow's levels. Which advert lines are matched to the correct level? Select all that apply.",
      options: [
        "'Join a top-tier Fortune 500 company' → physiological needs",
        "'Join a vibrant community' → love and belonging",
        "'Join a top-tier Fortune 500 company' → esteem",
        "'Competitive salary' → physiological needs",
        "'Join a vibrant community' → safety needs",
        "'Clear path to grow your career' → self-actualisation",
        "'Permanent role with good resources' → safety needs",
      ],
      correctIndices: [1, 2, 3, 5, 6],
      modelAnswer: "Read any job advert and you will see it is quietly answering 'will I eat, will I be safe, will I belong, will I be respected, will I grow?'\n\n• Salary: pays for food, rent and clothes, so it meets physiological needs.\n\n• Continuing role and resources: security, so safety needs.\n\n• Community and connection: love and belonging; the prestige of joining a top company or university: esteem; a career direction: self-actualisation.\n\nSo the answer is: the five correct pairings, not the two mismatches.",
    },
    {
      type: "multi",
      prompt: "Which of these are Herzberg hygiene factors? Select all that apply.",
      options: [
        "Job security",
        "Meaningful or challenging work",
        "Salary and benefits",
        "Working conditions",
        "Quality of supervision",
        "Recognition for good work",
      ],
      correctIndices: [0, 2, 3, 4],
      modelAnswer: "Hygiene is like brushing your teeth: nobody thanks you for doing it, but they notice if you stop.\n\n• Hygiene factors (job context): salary and benefits, company policies, job security, working conditions, quality of supervision and relationships with colleagues.\n\n• Motivators (job content): achievement, recognition, responsibility, advancement, personal growth and meaningful or challenging work.\n\nSo the answer is: salary and benefits, job security, working conditions and quality of supervision.",
    },
    {
      type: "mcq",
      prompt: "The lecturer said that if the university announced it could not pay staff this fortnight, people would be very dissatisfied. Which Herzberg idea does that illustrate?",
      options: [
        "A missing hygiene factor causes dissatisfaction, while its presence only prevents dissatisfaction rather than adding motivation",
        "A missing motivator causes dissatisfaction, because pay is really a form of recognition for the work done",
        "A missing hygiene factor lowers only motivation and not satisfaction, because pay is simply an expected part of the job",
        "A present hygiene factor strongly raises motivation, so the university should have increased everyone's pay this fortnight",
      ],
      correctIndex: 0,
      modelAnswer: "You do not thank the electricity company every day for keeping the lights on, but you are furious the moment they go off.\n\n• Hygiene factors: things you expect, such as salary. When absent they cause dissatisfaction; when present they do not increase motivation.\n\n• The example: people pay rent and mortgages, so missing pay causes a lot of dissatisfaction.\n\nSo the answer is: a missing hygiene factor causes dissatisfaction.",
    },
    {
      type: "mcq",
      prompt: "The lecturer knows a member of his teaching team will soon be away for a major life event, so he already has backup plans ready. Which of Covey's habits is this?",
      options: [
        "Begin with the end in mind",
        "Put first things first",
        "Sharpen the saw",
        "Be proactive",
      ],
      correctIndex: 3,
      modelAnswer: "Packing an umbrella when the sky is still sunny but the forecast says rain is being proactive.\n\n• Be proactive: understand what is going to happen and act before it does, for example by preparing backup plans.\n\n• Why the others are wrong: beginning with the end in mind is about setting the goal first, first things first is about priorities, and sharpen the saw is about continuous improvement.\n\nSo the answer is: be proactive.",
    },
    {
      type: "mcq",
      prompt: "In the sample RACI chart, for 'Install parts' the Shop Owner is A, the Mechanic is R and the Car Owner is I. What does that mean?",
      options: [
        "The shop owner does the installing, the mechanic approves it, and the car owner must be consulted first",
        "The car owner approves the installing, the mechanic does it, and the shop owner is consulted beforehand",
        "The mechanic does the installing, the shop owner answers for it, and the car owner is only kept informed",
        "The mechanic answers for the installing, the shop owner does it, and the car owner is consulted after",
      ],
      correctIndex: 2,
      modelAnswer: "It is like a school project where one student does the work, the teacher signs it off, and the parents just get a progress note.\n\n• R (Mechanic): does the work.\n\n• A (Shop Owner): ultimately answerable and approves it.\n\n• I (Car Owner): kept updated one way, with no input requested.\n\nSo the answer is: mechanic does, shop owner answers for it, car owner is informed.",
    },
    {
      type: "mcq",
      prompt: "The lecturer prepares next week's exam paper. He writes it himself and is answerable for it, asks a peer reviewer for input beforehand, and keeps the head of school updated on progress. How are the roles assigned?",
      options: [
        "Lecturer is Responsible, head of school is Accountable, peer reviewer is Informed",
        "Lecturer is Responsible and Accountable, peer reviewer is Consulted, head of school is Informed",
        "Lecturer is Responsible, peer reviewer is Accountable, head of school is Consulted",
        "Peer reviewer is Responsible, lecturer is Consulted, head of school is Accountable",
      ],
      correctIndex: 1,
      modelAnswer: "Whoever does the job and is on the hook for it is R and A; whoever gives advice before is C; whoever just gets the news is I.\n\n• The lecturer: does the writing and is answerable, so Responsible and Accountable.\n\n• The peer reviewer: asked for input beforehand, so Consulted (two-way).\n\n• The head of school: kept updated on progress, so Informed (one-way).\n\nSo the answer is: lecturer R and A, peer reviewer C, head of school I.",
    },
    {
      type: "mcq",
      prompt: "Which is a correct example of a three-level RBS path from the lecture?",
      options: [
        "Level 1: Backend developer; Level 2: Human; Level 3: Software",
        "Level 1: a named licence; Level 2: Software; Level 3: Equipment",
        "Level 1: Software; Level 2: cloud platforms; Level 3: a specific licence or version",
        "Level 1: Human; Level 2: a named engineer; Level 3: Backend developer role",
      ],
      correctIndex: 2,
      modelAnswer: "Think of a library: floor, then shelf, then the exact book — you go from broad to specific.\n\n• Level 1: broad categories such as Human, Equipment, Software and Materials.\n\n• Level 2: subcategories — roles for humans, tools or platforms for software.\n\n• Level 3: specific resources such as names, tools, versions, servers and licences.\n\nSo the answer is: Software, then cloud platforms, then a specific licence or version.",
    },
    {
      type: "truefalse",
      prompt: "An RBS replaces the WBS, because resources are more important to plan than tasks.",
      options: [
        "True",
        "False",
      ],
      correctIndex: 1,
      modelAnswer: "A shopping list of ingredients does not replace the recipe; you need both.\n\n• The lecture: the RBS complements the WBS but focuses on resources instead of tasks.\n\n• So the WBS still breaks down the work, while the RBS breaks down what the work needs.\n\nSo the answer is: False.",
    },
    {
      type: "mcq",
      prompt: "In the sample resource histogram (January to June, with managers, business analysts, programmers and technical writers), which statement is correct?",
      options: [
        "Technical writers first appear in April and are still on the project in June",
        "Business analysts are needed in greater numbers in June than in March",
        "Programmers are the largest group in every month from January to June",
        "Managers double from one in March to two in April",
      ],
      correctIndex: 0,
      modelAnswer: "Reading a histogram is like reading a class attendance chart: you check each month's bar and see who is in it.\n\n• Technical writers: no hatched segment in January to March, one in April and May, and one in June.\n\n• Managers: one in every month, so they never double.\n\n• Business analysts: two in January to March, one in April to June, so fewer in June, not more.\n\n• Programmers: only one in January and February, fewer than the business analysts, so they are not the largest group in every month.\n\nSo the answer is: technical writers first appear in April.",
    },
    {
      type: "multi",
      prompt: "Which resource-type examples are correctly classified in the lecture's list of IT project resources? Select all that apply.",
      options: [
        "Testers and DevOps engineers are human resources",
        "Documentation templates are equipment or hardware",
        "Test scripts and user manuals are materials",
        "Software licences are materials",
        "Servers, laptops and networking gear are equipment or hardware",
        "IDEs, licences and cloud platforms are software and tools",
      ],
      correctIndices: [0, 2, 4, 5],
      modelAnswer: "Sorting a school bag: books and worksheets in one pocket, the laptop in another, and the person carrying it is separate again.\n\n• The four types: human resources, equipment or hardware, software and tools, and materials.\n\n• Materials: documentation templates, test scripts and user manuals.\n\n• Software and tools: IDEs, project management software, licences and cloud platforms.\n\nSo the answer is: the four correct classifications.",
    },
    {
      type: "mcq",
      prompt: "What does the Acquire Resources process do?",
      options: [
        "It improves the competencies and team interaction of the people already on the project through training and team-building",
        "It tracks team performance, gives feedback and resolves issues that arise among the members of the project team",
        "It determines the types and quantities of the resources that each activity in the project is going to require",
        "It obtains the human, physical and material resources needed so that the right resources are available at the right time",
      ],
      correctIndex: 3,
      modelAnswer: "Estimating tells you how many pizzas you need; acquiring is actually ordering them so they arrive when the party starts.\n\n• Acquire Resources: obtaining the human, physical and material resources needed, so nothing delays the work.\n\n• Its outputs: physical resource assignments, project team assignments and resource calendars.\n\n• Why the others are wrong: improving the team is Develop Team, tracking performance is Manage Team, and working out quantities is Estimate Activity Resources.\n\nSo the answer is: it gets the resources so they are there when needed.",
    },
    {
      type: "mcq",
      prompt: "A project uses existing staff, adds two contractors and buys cloud services from a vendor. Which acquisition method is this?",
      options: [
        "Multi-source acquisition",
        "Internal acquisition",
        "External acquisition",
        "Procurement",
      ],
      correctIndex: 0,
      modelAnswer: "Building a team from your own friends, some hired helpers and a rented van is using several sources at once.\n\n• Multi-source acquisition: a combination of internal resources, contractors and vendors.\n\n• Why the others are wrong: each of the others is only one of those three sources.\n\nSo the answer is: multi-source acquisition.",
    },
    {
      type: "mcq",
      prompt: "Priya is allocated 46 hours of work this week and has 40 hours available. Using Resource Load = allocated hours ÷ available hours, what is her load and what does it mean?",
      options: [
        "87%, so she is under-utilised",
        "115%, so she is over-allocated",
        "115%, so she is under-utilised",
        "87%, so she is over-allocated",
      ],
      correctIndex: 1,
      modelAnswer: "A delivery van rated for 40 boxes carrying 46 is overloaded.\n\n• The formula: allocated hours divided by available hours, so 46 ÷ 40 = 1.15, or 115%.\n\n• What it means: anything above 100% is over-allocated. Below 100% would be under-utilised.\n\n• The trap: dividing the other way round gives 87%, which is wrong.\n\nSo the answer is: 115%, over-allocated.",
    },
    {
      type: "multi",
      prompt: "Which of these are techniques of resource leveling listed in the lecture? Select all that apply.",
      options: [
        "Split tasks",
        "Reassign tasks",
        "Cut the scope of the project",
        "Fast-track by overlapping dependent tasks",
        "Adjust work hours",
        "Delay tasks",
      ],
      correctIndices: [0, 1, 4, 5],
      modelAnswer: "To fix a crowded weekend you can move something later, cut it in two, hand it to someone else, or change when people work.\n\n• Leveling techniques: delay tasks, split tasks, reassign tasks and adjust work hours.\n\n• Not leveling: fast-tracking and cutting scope are other ways of changing a project, not techniques for leveling resources.\n\nSo the answer is: delay, split, reassign and adjust work hours.",
    },
    {
      type: "mcq",
      prompt: "In the resource leveling slide, all three activities starting on day one need 8 workers at the peak (A has 2 workers, B has 4, C has 2). Delaying activity C by 2 days, its total slack, does what?",
      options: [
        "It lowers the peak to 6 workers but pushes the project end from day 5 to day 7",
        "It leaves the peak at 8 workers, because C uses the same workers however it is scheduled",
        "It lowers the peak to 4 workers, because C is removed from the days A and B run",
        "It lowers the peak to 6 workers without delaying the project end date",
      ],
      correctIndex: 3,
      modelAnswer: "If two loud events are scheduled for the same hour, you can move the one with spare room to a quieter time and the whole day still finishes on time.\n\n• Before: A (2), B (4) and C (2) all run in the first days, so the peak is 8 workers.\n\n• After: C is delayed 2 days. A and B run together (6), then B and C run together (6), so the peak is 6.\n\n• The end date: C had 2 days of slack, so delaying it by 2 days does not delay the finish.\n\nSo the answer is: peak falls to 6 workers and the end date is unchanged.",
    },
    {
      type: "truefalse",
      prompt: "Resource leveling never affects the project schedule, because it only rearranges who does what.",
      options: [
        "True",
        "False",
      ],
      correctIndex: 1,
      modelAnswer: "Rearranging a busy week can push things to Friday, and Friday might be after the deadline.\n\n• The lecture: leveling adjusts the schedule or redistributes resources, aiming to keep the timeline as intact as possible.\n\n• The catch: when a delay uses up a task's slack, the finish date can move; the example only kept the end date because C had slack.\n\nSo the answer is: False.",
    },
    {
      type: "multi",
      prompt: "Which of these Tuckman stage descriptions are matched correctly? Select all that apply.",
      options: [
        "Performing: hierarchy is very important and flexibility is discouraged",
        "Forming: the team acquaints and sets ground rules, and members are treated as strangers",
        "Adjourning: the team assesses its work and transitions roles, recognising contributions",
        "Norming: people feel part of the team and accept other viewpoints",
        "Norming: members resist control by group leaders and show hostility",
        "Storming: members resist control by group leaders and show hostility",
      ],
      correctIndices: [1, 2, 3, 5],
      modelAnswer: "Matching stages to behaviour is like matching seasons to weather: each has its own recognisable pattern.\n\n• Forming: polite, formal, strangers setting ground rules. Storming: friction and resistance to leaders. Norming: acceptance of other viewpoints. Performing: trust and flexibility. Adjourning: assessing and transitioning roles.\n\n• The wrong options swap the descriptions: performing has little hierarchy, and hostility belongs to storming.\n\nSo the answer is: the forming, storming, norming and adjourning matches shown.",
    },
    {
      type: "multi",
      prompt: "Which of these conflict handling modes are matched with the situation the lecture says they suit? Select all that apply.",
      options: [
        "Accommodating: critical issues needing a quick decision",
        "Competing: critical issues needing a quick decision with limited time",
        "Collaborating: complex issues requiring input from all parties",
        "Compromising: time-constrained situations or temporary solutions",
        "Avoiding: minor issues, or when emotions run high",
        "Competing: preserving relationships when the issue matters more to others",
      ],
      correctIndices: [1, 2, 3, 4],
      modelAnswer: "Choosing a conflict mode is like choosing the right tool: a hammer for a nail, a screwdriver for a screw.\n\n• The table: competing suits quick decisions; collaborating suits complex issues; compromising suits time pressure or temporary fixes; avoiding suits minor issues or heated emotions; accommodating suits preserving relationships or when the issue matters more to others.\n\n• The wrong options swap modes with the wrong situation.\n\nSo the answer is: the four correct pairings.",
    },
    {
      type: "mcq",
      prompt: "A senior colleague cares far more about a design choice than you do, and keeping the working relationship healthy matters most to you. Which conflict handling mode fits?",
      options: [
        "Competing",
        "Collaborating",
        "Avoiding",
        "Accommodating",
      ],
      correctIndex: 3,
      modelAnswer: "Letting your friend pick the film because they really want to see it and you value the friendship is accommodating.\n\n• Accommodating: yield to others' needs over your own. Low assertiveness, high cooperativeness. Use to preserve relationships or when the issue matters more to others.\n\n• Why the others are wrong: competing pushes your view, collaborating searches for a joint solution, and avoiding ignores the issue.\n\nSo the answer is: accommodating.",
    },
    {
      type: "mcq",
      prompt: "In stand-ups everyone agrees to their tasks, but nobody ever calls out a colleague who keeps missing deadlines. Which team dysfunction is this?",
      options: [
        "Absence of trust",
        "Avoidance of accountability",
        "Fear of conflict",
        "Inattention to results",
      ],
      correctIndex: 1,
      modelAnswer: "It is like a class where everyone sees a classmate not doing their part, but nobody says anything.\n\n• Avoidance of accountability: team members do not hold each other to account for commitments.\n\n• Why the others are wrong: absence of trust means people do not feel safe being open, fear of conflict means avoiding healthy disagreement, and inattention to results means putting personal goals above the team's.\n\nSo the answer is: avoidance of accountability.",
    },
    {
      type: "mcq",
      prompt: "A project has every role filled and its milestones still look achievable, yet work is taking longer, decisions are getting harder and participation is uneven. What is the best reading?",
      options: [
        "Nothing is wrong, because filled roles and achievable milestones mean the team must be functioning well",
        "Acquire Resources has failed, because a properly resourced project would show none of these symptoms",
        "Control Resources has failed, because only utilisation figures can reveal a team problem",
        "Acquisition worked, but Develop Team and Manage Team need attention because these are early warning signs of a team problem",
      ],
      correctIndex: 3,
      modelAnswer: "A car can have four wheels and a full tank but still make worrying noises; having the parts is not the same as running well.\n\n• What is fine: the right people are assigned, so acquiring was successful.\n\n• What is not: slower work, harder decisions and uneven participation are signs the team is not functioning, which is the job of Develop Team and Manage Team.\n\n• Why it matters: human performance varies, so problems can appear well before any milestone is missed.\n\nSo the answer is: acquisition succeeded, but team development and management need attention.",
    },
    {
      type: "mcq",
      prompt: "Bill (60% productivity, 50% availability, $45 per hour), Mary (120%, 40%, $80) and Minh (100%, 40%, $60) could each do a 90-hour task. If cost is the primary consideration, who should be assigned?",
      options: [
        "Minh, at $5,400 in total",
        "Mary, at $6,000 in total",
        "Bill, at $6,750 in total",
        "Bill, because he has the lowest hourly rate at $45",
      ],
      correctIndex: 0,
      modelAnswer: "The cheapest hourly rate is not always the cheapest job, because a slower person needs more hours.\n\n• Bill: 90 ÷ 0.6 = 150 hours, times $45 = $6,750.\n\n• Mary: 90 ÷ 1.2 = 75 hours, times $80 = $6,000.\n\n• Minh: 90 ÷ 1.0 = 90 hours, times $60 = $5,400, the lowest.\n\nSo the answer is: Minh, at $5,400.",
    },
    {
      type: "mcq",
      prompt: "Using the same three people, if schedule (minimising time to complete) is the primary consideration, who should be assigned?",
      options: [
        "Minh, with 225 hours of available time",
        "Mary, with about 188 hours of available time",
        "Bill, with 300 hours of available time",
        "Minh, because he has 100% productivity and needs only 90 actual hours",
      ],
      correctIndex: 1,
      modelAnswer: "The task finishes fastest for whoever has the fewest calendar hours once you account for how much of their time they can give.\n\n• Available time = actual time ÷ availability.\n\n• Bill: 150 ÷ 0.5 = 300. Mary: 75 ÷ 0.4 = 187.5. Minh: 90 ÷ 0.4 = 225.\n\n• Mary wins on schedule because her high productivity outweighs her low availability.\n\nSo the answer is: Mary, about 188 hours.",
    },
    {
      type: "mcq",
      prompt: "A task needs 60 effort hours. Nora has 80% productivity, 50% availability and costs $50 per hour. What are her actual time and cost on the task?",
      options: [
        "48 hours of actual time, costing $2,400",
        "75 hours of actual time, costing $1,875",
        "75 hours of actual time, costing $3,750",
        "150 hours of actual time, costing $7,500",
      ],
      correctIndex: 2,
      modelAnswer: "Nora works at 80% speed, so the job takes more than 60 hours; you pay her for the working hours, not for the calendar time.\n\n• Actual time: 60 ÷ 0.8 = 75 hours.\n\n• Cost: 75 × $50 = $3,750.\n\n• The traps: multiplying by productivity gives 48; dividing by availability gives 150 hours of available time, which is not the hours you pay for.\n\nSo the answer is: 75 hours and $3,750.",
    },
    {
      type: "mcq",
      prompt: "How does the lecture say resource management differs in Agile environments?",
      options: [
        "It is less about fixed long-term allocation and more about matching team capacity to sprint goals",
        "It is not needed, because self-managing teams have no resource constraints",
        "It is about fixing each person's allocation for the whole project before the first sprint",
        "It is focused on hitting individual utilisation targets set at the start of the project",
      ],
      correctIndex: 0,
      modelAnswer: "Instead of booking the whole year's timetable in advance, you plan each week based on who is actually free.\n\n• Agile: teams plan based on available time, skills and workload rather than assuming full availability.\n\n• Continuous: resource management is reviewed regularly as priorities and capacity change.\n\nSo the answer is: match team capacity to sprint goals.",
    },
    {
      type: "multi",
      prompt: "Which of these are sensible strategies for keeping work moving while Backend Developer 1 is on leave in the case study? Select all that apply.",
      options: [
        "Ignore the absence and keep the original plan unchanged",
        "Reassign some tasks to the other two backend developers",
        "Bring in unbudgeted contractors regardless of the $100,000 limit",
        "Adjust work hours or the schedule to cover the most critical work",
        "Cross-train someone to cover Backend Developer 1's area",
        "Delay or re-sequence non-critical tasks using their slack",
      ],
      correctIndices: [1, 3, 4, 5],
      modelAnswer: "When one player is injured, a coach moves others around, rearranges the game plan and trains a substitute.\n\n• Leveling techniques: reassign, delay, split and adjust hours.\n\n• Cross-training: reduces dependence on a single person, which the end-of-lecture questions raise.\n\n• Not sensible: ignoring the gap or overspending a fixed budget.\n\nSo the answer is: reassign, delay non-critical work, cross-train and adjust hours.",
    },
    {
      type: "mcq",
      prompt: "The case study budget is fixed at $100,000. Which approach best fits the lecture's ideas for staying within budget?",
      options: [
        "Give every task equal priority and ask the team to absorb the extra work by putting in additional hours",
        "Cut QA testing first because it does not produce visible features, then use the savings to cover cloud usage",
        "Replace the cloud servers with permanent hardware purchases straight away so that usage costs stop growing",
        "Prioritise critical tasks, level or delay lower-priority work, and monitor cloud spend against the plan",
      ],
      correctIndex: 3,
      modelAnswer: "With a fixed pocket money budget you spend first on the things that matter most and check your balance often.\n\n• Prioritise: focus resources on critical tasks first.\n\n• Level: delay or reassign lower-priority work rather than adding cost.\n\n• Control: compare actual cloud usage with the plan and correct early.\n\nSo the answer is: prioritise, level and monitor spend.",
    },
    {
      type: "mcq",
      prompt: "The reading compares Maslow with Herzberg. How do they line up?",
      options: [
        "Maslow's higher-level needs resemble Herzberg's hygiene factors, and his lower-level needs match Herzberg's motivators",
        "Maslow's needs match Herzberg's hygiene factors at every level, and Herzberg has no equivalent of motivators",
        "The two theories do not overlap at all, because one is about work and the other about life",
        "Maslow's lower-level needs resemble Herzberg's hygiene factors, and his higher-level needs match Herzberg's intrinsic motivators",
      ],
      correctIndex: 3,
      modelAnswer: "Both theories say the basics stop you being unhappy, but only meaningful growth really drives you.\n\n• Lower needs: physiological and safety, like salary, job security and working conditions, which are hygiene factors.\n\n• Higher needs: esteem and self-actualisation, like recognition and growth, which are motivators.\n\n• The message for managers: address both basic extrinsic needs and higher intrinsic needs.\n\nSo the answer is: lower needs are hygiene factors; higher needs are motivators.",
    },
  ],
};

export const WEEK_6_PAPERS: ExamPaperSeed[] = [TUTORIAL_PAPER, LECTURE_PAPER];
