import { existsSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, basename, extname, dirname } from "node:path";

export const DEFAULT_MODEL = join(process.env.HOME ?? "", ".whisper-models", "ggml-base.en.bin");

// Runs ffmpeg + whisper-cpp's whisper-cli as subprocesses rather than a JS
// binding, since both are already installed via Homebrew and neither has a
// maintained Bun/Node binding worth adding as a dependency for a two-step
// pipeline (mp4 -> 16kHz mono wav -> txt).
export async function transcribeVideo(input: string, model: string, outPath: string): Promise<void> {
  if (!existsSync(input)) throw new Error(`Video not found: ${input}`);
  if (!existsSync(model)) {
    throw new Error(
      `Whisper model not found: ${model}\nInstall with: brew install ffmpeg whisper-cpp, then download a ggml model (e.g. ggml-base.en.bin) into ${dirname(model)}`,
    );
  }

  const tmpDir = mkdtempSync(join(tmpdir(), "transcribe-"));
  try {
    const wavPath = join(tmpDir, "audio.wav");
    const extract = Bun.spawn(
      ["ffmpeg", "-y", "-i", input, "-ar", "16000", "-ac", "1", "-c:a", "pcm_s16le", wavPath],
      { stdout: "ignore", stderr: "pipe" },
    );
    if ((await extract.exited) !== 0) {
      throw new Error(`ffmpeg failed to extract audio:\n${await new Response(extract.stderr).text()}`);
    }

    const txtBase = join(tmpDir, "transcript");
    const whisper = Bun.spawn(["whisper-cli", "-m", model, "-f", wavPath, "-otxt", "-of", txtBase, "-nt", "-np"], {
      stdout: "ignore",
      stderr: "pipe",
    });
    if ((await whisper.exited) !== 0) {
      throw new Error(`whisper-cli failed to transcribe:\n${await new Response(whisper.stderr).text()}`);
    }

    const transcript = (await Bun.file(`${txtBase}.txt`).text()).trim();
    const header = `# Transcript: ${basename(input)}\n\nAuto-generated by \`scripts/transcribe-lecture.ts\` (whisper-cpp, base.en model). Speech-to-text, not a human transcript — expect occasional misheard names/terms and no speaker labels. Cross-check anything load-bearing against the slides before writing a question from it alone.\n\n`;
    await Bun.write(outPath, header + transcript + "\n");
  } finally {
    rmSync(tmpDir, { recursive: true, force: true });
  }
}

function parseArgs(argv: string[]): { input: string; model: string; force: boolean } {
  const get = (flag: string) => {
    const i = argv.indexOf(flag);
    return i === -1 ? undefined : argv[i + 1];
  };
  const input = argv[0];
  if (!input || input.startsWith("--")) {
    throw new Error("Usage: bun scripts/transcribe-lecture.ts <video-file> [--model <path>] [--force]");
  }
  return { input, model: get("--model") ?? DEFAULT_MODEL, force: argv.includes("--force") };
}

if (import.meta.main) {
  const { input, model, force } = parseArgs(process.argv.slice(2));
  const outPath = join(dirname(input), basename(input, extname(input)) + ".transcript.md");
  if (existsSync(outPath) && !force) {
    console.error(`${outPath} already exists — pass --force to overwrite`);
    process.exit(1);
  }
  await transcribeVideo(input, model, outPath);
  console.log(`Wrote transcript to ${outPath}`);
}
