import type { ExamPaperSeed } from "../types";

const PAPER: ExamPaperSeed =
  {
    course: "COMP5348",
    week: 2,
    paperNumber: 1,
    title: "Week 2 Practice Paper",
    topics: "State: session, resource, local computation, and derived state; lifetime, sharing, and integrity of state; stateful vs stateless; state management and persistent state; Concurrency: interleaving, lost updates, the general rule for needing concurrency control; Concurrency control: optimistic vs pessimistic, locking, deadlocks, lock granularity; Transactions: ACID properties, explicit (JTA) vs declarative (Spring @Transactional) transactions; Tutorial: functionality/shared-variable conflict analysis, BankAccount.java race condition, bank.zip optimistic/pessimistic locking bug, deadlock avoidance via canonical lock ordering",
    sourceFiles: ["COMP5348_W2.pdf", "Tutorial/COMP5348_Tutorial 2.pdf", "Tutorial/BankAccount.java", "Tutorial/bank.zip"],
    questions: [
      {
        type: "mcq",
        prompt: "According to the lecture, what is 'state'?",
        options: ["The data accessed and altered by programs", "The set of architecture patterns a system uses", "The physical hardware a system runs on", "The version history of an application's source code"],
        correctIndex: 0,
        modelAnswer: "The lecture defines state simply as 'the data accessed and altered by programs,' with varying lifetimes, visibility, 'sharedness,' and 'criticality.'",
      },
      {
        type: "mcq",
        prompt: "A shopping cart's contents during a user's browsing session, held server-side and keyed by a token sent from the client, is best classified as which kind of state?",
        options: ["Local computation state", "Session state", "Derived state only", "Stateless state"],
        correctIndex: 1,
        modelAnswer: "Session state holds the state of the overall session (e.g. 'books ordered'), and the lecture explicitly gives 'shopping cart' as an example of state modelling real-world aspects that is tracked across a session, kept server-side with a key token sent by the client — exactly the cookie/session-entity pattern described.",
      },
      {
        type: "mcq",
        prompt: "Which property does the lecture attribute to local computation state?",
        options: ["It is shared across distinct operations and durable across failure", "It is private to one operation and transient — its lifetime is limited to that operation", "It is always stored in a relational database", "It is the only kind of state that needs concurrency control"],
        correctIndex: 1,
        modelAnswer: "Local computation state has 'local visibility only (private)... not shared across distinct operations' and is transient, with lifetime limited to the operation — local variables and parameters are the lecture's examples.",
      },
      {
        type: "mcq",
        prompt: "Resource state is described in the lecture as being held where, and characterised by what?",
        options: ["In local variables only, characterised by being transient", "In specialised state stores such as databases, characterised by data models with relationships, constraints, and integrity rules independent of any particular application", "In client-side cookies only, characterised by being stateless", "In session tokens only, characterised by being non-durable"],
        correctIndex: 1,
        modelAnswer: "Resource state — bank accounts, transaction histories, catalogues, customers — is 'held in specialised state stores' (databases or an equivalent) with data models describing relationships, and 'data is a first class citizen in the enterprise... independent of any particular application.'",
      },
      {
        type: "mcq",
        prompt: "The lecture's example of derived state is a bank account balance. Why does it say keeping a running total is preferred over summing all transactions each time?",
        options: ["Summing transactions is not mathematically possible", "Keeping a running total is computationally more efficient, even though the balance could in principle be computed by summing all transactions", "Databases cannot store transaction histories", "Derived state must always be recomputed on every read for correctness"],
        correctIndex: 1,
        modelAnswer: "The lecture states the balance 'could be computed by summing all transactions' but 'keeping running total is computationally more efficient' — the running total is a cached/derived value maintained for performance, matching the caching example of the 'next order number' too.",
      },
      {
        type: "truefalse",
        prompt: "True or False: According to the lecture, session state could be lost on system failure, whereas resource state stores care about durability and integrity.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "The 'Lifetime of state' slide explicitly contrasts them: resource state stores 'care about durability & integrity,' while session state 'could lose on system failure.'",
      },
      {
        type: "mcq",
        prompt: "Per the 'Sharing of state' slide, which statement is correct?",
        options: ["Resource state is usually shared across many sessions/applications, while each session state instance is used only within a single session", "Session state is usually shared across many sessions, while resource state is private to one session", "Local computation state is the most commonly shared kind of state", "Resource state and session state have identical sharing rules"],
        correctIndex: 0,
        modelAnswer: "Resource state 'holds the persistent data that underpins the entire enterprise' and is 'accessed by many sessions/applications... possibly at the same time,' whereas 'each session state instance is only used within a single session... not shared across distinct sessions.'",
      },
      {
        type: "mcq",
        prompt: "Which of the following is an example the lecture gives of an integrity constraint on resource state?",
        options: ["Every session must expire after exactly 30 minutes", "Cannot assign an employee to a non-existent department (referential integrity)", "Every API response must be returned in under 200ms", "Local variables must be declared before use"],
        correctIndex: 1,
        modelAnswer: "The 'Integrity of state' slide lists referential-integrity-style constraints, including 'cannot assign an employee to a non-existent department (referential integrity)' and 'cannot delete a department that still has allocated employees.'",
      },
      {
        type: "mcq",
        prompt: "What distinguishes 'stateful' from 'stateless' server-side code, per the lecture?",
        options: ["Stateful code is always faster than stateless code", "Stateful code holds state between operations and is tied to a client session; stateless code discards state after each operation and can be shared across clients", "Stateless code cannot access a database", "Stateful code only exists on the client, never the server"],
        correctIndex: 1,
        modelAnswer: "Stateful code 'holds state, waiting for next operation request from client' so the program instance is tied to a client session; stateless code 'discards state after operation completes, reloads it as needed,' so program instances can be shared across clients.",
      },
      {
        type: "mcq",
        prompt: "According to 'Persistent state,' what is the typical pattern for stateless server-side application code handling a request?",
        options: ["Find/restore state, perform operation, update/save state", "Discard the request without accessing any state store", "Hold the state in a local variable indefinitely", "Always create a new database on every request"],
        correctIndex: 0,
        modelAnswer: "The lecture states application code is 'usually stateless,' with necessary state kept in an external persistent state store, following the pattern: 'find/restore state, perform operation, update/save state.'",
      },
      {
        type: "mcq",
        prompt: "Why does the lecture say concurrency is the 'solution' to performance/scaling demands, but also introduces 'new problems'?",
        options: ["Concurrency lets systems do more than one operation at a time to meet speed/scale demands, but interference between concurrent operations over shared resources can lead to constraint violations", "Concurrency always slows systems down, so it is never actually used", "Concurrency eliminates the need for state stores entirely", "Concurrency problems only occur on single-processor machines"],
        correctIndex: 0,
        modelAnswer: "Concurrency (doing more than one operation at a time, using multiple processors/systems) is needed because customers 'can't be kept waiting' at scale, but it 'introduces new problems': 'interference between programs/operations... conflicts over shared resources can lead to constraint violations,' e.g. selling the same seat twice.",
      },
      {
        type: "mcq",
        prompt: "The lecture's 'interleaving' diagram shows two concurrent computations C1 and C2 each doing 'Check balance' then 'Withdraw money.' What does this diagram illustrate?",
        options: ["That each application's code is internally sequential, but when observed from outside, operations from different concurrent computations can be interleaved with each other", "That C1 always finishes entirely before C2 starts", "That databases prevent all interleaving automatically without configuration", "That interleaving only happens across different physical machines"],
        correctIndex: 0,
        modelAnswer: "'The code in each application is (effectively) sequential... blissfully unaware of other applications' but 'observed from outside, the computations can be interleaved' — the diagram shows C1's and C2's steps interspersed in time.",
      },
      {
        type: "mcq",
        prompt: "In the lecture's 'lost updates' example, T1 wants to increase x by 1 and T2 wants to increase x by 2, both starting from x=10. Why does the final value end up as x=11 instead of x=13?",
        options: ["Both transactions read x=10 before either writes, so T2's set of x=12 is overwritten by T1's set of x=11, losing T2's increment", "The database rejected T2's transaction", "T1 and T2 ran on different databases", "x can only ever be incremented by one transaction per day"],
        correctIndex: 0,
        modelAnswer: "T1 sees x=10, T2 sees x=10 (before either writes), T2 sets x=10+2=12, then T1 sets x=10+1=11 — T1's write overwrites T2's, so the final state reflects only T1's increment, losing T2's update entirely.",
      },
      {
        type: "mcq",
        prompt: "Per the lecture's 'General rules' slide, when is a concurrency-control mechanism needed?",
        options: ["Only when three or more threads are involved", "When two code segment instances can interleave, both access the same shared state item, and at least one modifies it — including two instances of the same code segment", "Only when the state is stored in a file rather than a database", "Only when the operations are on different machines"],
        correctIndex: 1,
        modelAnswer: "'If instances of two code segments can interleave, and both access the same item of shared state, and at least one of the instances modifies that item, then some mechanism is needed... same applies for two instances of the same code segment.'",
      },
      {
        type: "mcq",
        prompt: "How does optimistic concurrency control typically work, per the lecture?",
        options: ["It locks all shared data before any access is allowed", "It always allows access, then checks for damage and repairs/undoes if necessary — e.g. keeping a modification count, checking it hasn't changed before committing, and retrying if it has", "It prevents any two transactions from ever running concurrently", "It is implemented entirely by the network layer, never by application code"],
        correctIndex: 1,
        modelAnswer: "Optimistic concurrency control 'always allows access but check for damage & repair/undo if necessary' — programmed by keeping a modification count, remembering it on read, checking it hasn't changed on write, and retrying if it has.",
      },
      {
        type: "mcq",
        prompt: "How does pessimistic concurrency control typically work, per the lecture?",
        options: ["Tasks must obtain an exclusive lock over shared data before access, and concurrent tasks wait for the lock, which limits concurrency and could have severe performance impacts", "It never uses locks, only retries", "It is always faster than optimistic concurrency control regardless of contention", "It only applies to local computation state"],
        correctIndex: 0,
        modelAnswer: "'Tasks must obtain exclusive lock over shared data before access... concurrent tasks will wait for lock before continuing... holding locks limits concurrency (and performance)... could potentially have severe performance impacts.'",
      },
      {
        type: "truefalse",
        prompt: "True or False: The lecture states optimistic concurrency control often performs well at low contention, since it may waste some work on unsuccessful computation but avoids the cost of locking.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "'This may waste work/time on unsuccessful computation' but 'at low contention it often performs well (as do transactions...)' — the trade-off favours optimistic control when conflicts are rare.",
      },
      {
        type: "mcq",
        prompt: "What is a deadlock, as illustrated by the lecture's T1/T2 lock-ordering example?",
        options: ["A situation where a transaction commits twice", "A situation where T1 holds lock A and waits for lock B, while T2 holds lock B and waits for lock A, so both wait forever", "A situation where a database automatically rolls back all transactions every hour", "A situation where only one user can ever be logged in at a time"],
        correctIndex: 1,
        modelAnswer: "In the deadlock diagram, T1 has granted lock A and is waiting for lock B, while T2 has granted lock B and is waiting for lock A — each is waiting on a resource the other holds, so neither can proceed ('waiting for it to be unlocked... possibly forever').",
      },
      {
        type: "mcq",
        prompt: "Which technique does the lecture list for avoiding deadlocks (as opposed to just detecting/recovering from them)?",
        options: ["Increasing the number of database replicas", "Imposing a 'canonical locking order' constraint so all tasks acquire locks in the same order", "Disabling all locks entirely", "Only allowing one transaction per day"],
        correctIndex: 1,
        modelAnswer: "Alongside 'lock timeouts, deadlock cycle detection → exceptions,' the lecture lists 'avoidance by imposing canonical locking order constraints' — if every task locks resources in the same fixed order, the circular-wait pattern that causes deadlock cannot form.",
      },
      {
        type: "mcq",
        prompt: "Per 'Granularity of locks,' what is the trade-off between finer-grain and coarse-grain locks?",
        options: ["Finer-grain locks can give better concurrency/performance but more overhead and more chance of deadlocks; coarse-grain locks are simpler with less overhead but less parallelism", "Coarse-grain locks always outperform finer-grain locks in every scenario", "Lock granularity has no effect on performance or deadlock risk", "Finer-grain locks eliminate the need for transactions"],
        correctIndex: 0,
        modelAnswer: "'Finer-grain locks can give better concurrency and performance... more overhead, more chance of deadlocks. Coarse-grain lock are simpler... less overhead and less chance of deadlock... less parallelism – harmless concurrency may be prevented.'",
      },
      {
        type: "mcq",
        prompt: "How does the lecture define a 'transaction'?",
        options: ["Any single line of application code", "A complete, indivisible business operation — a segment of code executed as a whole or not at all", "A network request that always succeeds", "A synonym for 'session state'"],
        correctIndex: 1,
        modelAnswer: "'A complete, indivisible business operation... a segment of code that will be executed as a whole (or not at all)' — examples given include booking a seat, transferring money, and withdrawing cash.",
      },
      {
        type: "mcq",
        prompt: "In the ACID properties, what does 'Atomic' mean?",
        options: ["The transaction is split into as many small pieces as possible", "The transaction executes completely or not at all, even across failure and recovery — successful transactions commit, failing ones abort/rollback", "The transaction can only touch one table", "The transaction always runs on a single CPU core"],
        correctIndex: 1,
        modelAnswer: "Atomic (all-or-nothing): 'execute completely or not at all, even across failure and recovery... successful transactions commit... failing transactions abort or rollback... changes backed out, as if they had never happened.'",
      },
      {
        type: "mcq",
        prompt: "The lecture notes that the 'Consistent' property of ACID is 'really an application program responsibility.' What does Consistent mean here?",
        options: ["The database automatically guarantees business-level invariants with no application involvement", "The transaction moves the system from one consistent state to another — e.g. all money in the bank is accounted for and not 'lost'", "Every transaction must run at exactly the same speed", "Consistent means the transaction never touches more than one row"],
        correctIndex: 1,
        modelAnswer: "'Move from one consistent state to another consistent state — all money in bank is accounted for somewhere and not lost. Really an application program responsibility' — the database enforces atomicity/isolation/durability, but business-level consistency depends on the application logic being correct.",
      },
      {
        type: "mcq",
        prompt: "What does the 'Isolated' property of ACID mean, and what trade-off does the lecture note about isolation levels?",
        options: ["Every transaction thinks it is running alone even though others run concurrently; databases offer isolation-level choices, and lower isolation often trades performance for weaker protection against interleaving problems", "Isolation means each transaction must run on a separate physical server", "Isolation guarantees transactions never need to wait for locks", "Isolation is unrelated to concurrency"],
        correctIndex: 0,
        modelAnswer: "'Every transaction thinks it is running all alone... reality of concurrency is hidden.' Databases provide isolation-level choices; 'usually good performance under load is only available with lower isolation... but lower isolation level does not prevent all interleaving problems.'",
      },
      {
        type: "mcq",
        prompt: "What does 'Durable' mean in ACID?",
        options: ["Once changes are committed, they are permanent — even after failure and recovery, since changes are written to storage before the commit completes", "Durable transactions can be rolled back at any time in the future", "Durable means the transaction is retried indefinitely until it succeeds", "Durable is a synonym for 'Isolated'"],
        correctIndex: 0,
        modelAnswer: "'Once changes are committed, they are permanent... even after failure and recovery... changes written to storage, wait for write to complete.'",
      },
      {
        type: "mcq",
        prompt: "Which code pattern does the lecture show as an example of an *explicit* transaction (JTA)?",
        options: ["@Transactional public void methodName(...) { ... }", "t.begin(); ... t.commit(); // or t.rollback()", "SELECT * FROM accounts;", "spring.jpa.hibernate.ddl-auto=update"],
        correctIndex: 1,
        modelAnswer: "The JTA example is `UserTransaction t = ...; t.begin(); t.commit(); // or t.rollback()` — the application explicitly starts and ends the transaction boundary, unlike the annotation-based declarative style.",
      },
      {
        type: "mcq",
        prompt: "What is a 'declarative' transaction, as shown by Spring Boot's @Transactional annotation?",
        options: ["A transaction whose characteristics are determined by annotations, so a method can be declared to always run as a transaction without explicit begin/commit calls in the method body", "A transaction that must be manually committed by the database administrator", "A transaction type that only exists in C#", "A transaction that never rolls back"],
        correctIndex: 0,
        modelAnswer: "'Frameworks can allow transaction characteristics to be determined by annotations... you can declare a method so it always runs as a transaction' — `@Transactional` on a Spring Boot method wraps the whole method body in a transaction implicitly.",
      },
      {
        type: "short",
        prompt: "Distinguish resource state, session state, and local computation state, and give one original example of each that is not from the lecture.",
        modelAnswer: "Resource state models real-world, persistent, usually-shared data held in a state store (e.g. databases) — original example: a hotel's room-inventory table. Session state tracks one user's progress through a multi-step interaction and is scoped to a single session, not shared across sessions — original example: the current step of a multi-page tax-return form a user is filling in. Local computation state is transient, private data used only within one operation — original example: a loop counter inside a function that computes a discount total, discarded once the function returns.",
      },
      {
        type: "short",
        prompt: "Explain the lost-update problem in your own words using an original example (not the lecture's x=10 example or the bank-transfer example), and state what general rule (from the lecture) tells you this scenario needs concurrency control.",
        modelAnswer: "Two support agents simultaneously open the same customer ticket to add a note. Agent A reads the ticket (notes field = 'called customer'), agent B reads the same ticket at nearly the same time (also 'called customer'), agent A appends 'left voicemail' and saves, then agent B appends 'sent follow-up email' and saves — but B's save overwrites A's version, so A's update is silently lost. This needs concurrency control per the lecture's general rule: two concurrent instances (agent A's save, agent B's save) interleave, both access the same shared item (the notes field), and at least one of them (in fact both) modifies it.",
      },
      {
        type: "short",
        prompt: "Compare optimistic and pessimistic concurrency control: how does each work, and under what contention conditions does the lecture suggest each performs better?",
        modelAnswer: "Optimistic concurrency control always allows access, then checks (e.g. via a stored modification count) whether the data changed since it was read, and retries if so — it wastes work on failed retries but 'at low contention it often performs well.' Pessimistic concurrency control requires acquiring an exclusive lock before any access, so conflicting tasks simply wait rather than retry — this prevents wasted work but 'holding locks limits concurrency (and performance)' and 'could potentially have severe performance impacts,' making it more appropriate under high contention where optimistic retries would happen constantly.",
      },
      {
        type: "short",
        prompt: "Explain what a deadlock is, why 'imposing a canonical locking order' prevents it, and connect this to how BankService.performTransfer in the tutorial's bank.zip project avoids deadlock.",
        modelAnswer: "A deadlock happens when two tasks each hold a lock the other is waiting for (T1 holds A, waits for B; T2 holds B, waits for A), so both wait forever. A canonical locking order prevents this by forcing every task to acquire multiple locks in the same fixed order, so the circular-wait pattern can never form — if everyone locks the lower-ID account first, two transfers in opposite directions can never each be holding what the other wants next. This is exactly what performTransfer does: `if (fromAccountId > toAccountId) { swap fromAccountId/toAccountId, negate amount }` before acquiring locks, so regardless of which direction money is being transferred, the two accounts are always locked in ascending ID order.",
      },
      {
        type: "short",
        prompt: "Explain the ACID properties in one sentence each, and identify which one the lecture explicitly calls 'really an application program responsibility' rather than something the transaction infrastructure alone guarantees.",
        modelAnswer: "Atomic: the transaction executes completely or not at all, even across failure. Consistent: the transaction moves the system from one valid state to another valid state (e.g. total money is conserved). Isolated: each transaction behaves as if it ran alone, even when others run concurrently. Durable: once committed, changes survive failure and recovery. Consistent is the one the lecture calls 'really an application program responsibility' — the database can guarantee atomicity, isolation, and durability mechanically, but only correct application logic can guarantee that a given operation actually preserves business-level invariants.",
      },
      {
        type: "short",
        prompt: "Using Week 1's layered architecture (controller / service / business / repository) and Week 2's declarative transactions, explain where in a Spring Boot application you would put a @Transactional annotation and why, using the tutorial's BankService.performTransfer as the example.",
        modelAnswer: "@Transactional belongs on the service-layer method that performs the whole multi-step business operation — in the tutorial, `performTransfer` in BankService.java — because a transaction boundary should wrap the complete business operation (read both accounts, debit one, credit the other, save both) as one atomic unit, matching Week 1's idea that the service/business layer owns business logic while the repository layer only does data access. Putting it on the repository layer instead would only wrap individual queries, not the whole transfer, breaking atomicity across the two account updates.",
      },
      {
        type: "short",
        prompt: "The tutorial's BankAccount.java runs two threads that each call account.deposit(1) 10,000 times on a shared account starting at balance 0, where deposit() does `balance += amount` with no synchronisation. Explain, using the lecture's interleaving/lost-update concept, why the final printed balance is often less than 20,000 and varies between runs.",
        modelAnswer: "`balance += amount` is not a single atomic operation — it is really 'read balance, add amount, write balance back,' i.e. exactly the read/modify/write pattern in the lecture's lost-update example. When both threads interleave such that both read the same balance value before either writes back, one thread's increment overwrites the other's, so that increment is lost — over 20,000 total deposit calls, some number of these races cause lost updates, so the final balance is usually less than 20,000 and differs each run because the exact thread interleaving (and thus which updates get lost) is non-deterministic.",
      },
      {
        type: "short",
        prompt: "The tutorial's AccountRepository declares both findByIdWithOptimisticLock and findByIdWithPessimisticUpdateLock using the same plain `@Query(\"SELECT a FROM Account a WHERE a.id = :id\")` with no lock modifier. Explain what is wrong with this and what needs to change for each method to actually apply its named locking strategy.",
        modelAnswer: "Neither method actually applies any lock — a plain JPQL @Query with no `@Lock` annotation or `LockModeType` performs an ordinary unlocked SELECT, so both 'optimistic' and 'pessimistic' code paths currently behave identically (and unsafely) under concurrent transfers. To fix this: findByIdWithPessimisticUpdateLock needs `@Lock(LockModeType.PESSIMISTIC_WRITE)` added so the database row is locked for the duration of the transaction; findByIdWithOptimisticLock needs `@Lock(LockModeType.OPTIMISTIC)` (or OPTIMISTIC_FORCE_INCREMENT) plus a `@Version` field added to the Account entity, since JPA's optimistic locking is implemented via a version column that is checked on write and causes an OptimisticLockException on conflict.",
      },
      {
        type: "short",
        prompt: "Identify at least two distinct types of state present in the bank.zip tutorial application, matching Week 2's categories (local computation, session, resource state), with one concrete example of each from the code.",
        modelAnswer: "Resource state: the Account rows (id, balance, customer) persisted in the PostgreSQL 'bank' database via AccountRepository — this is the shared, durable state the whole application is built around. Local computation state: the `fromAccountId`/`toAccountId`/`amount` local variables inside performTransfer, and the `successfulTransferToA`/`successfulTransferToB` AtomicInteger counters in BankController — transient values scoped to one request/operation. The application has no meaningful session state, since each `/simulate_transfer_*` HTTP request is a self-contained, stateless simulation rather than part of a multi-request user session.",
      },
      {
        type: "short",
        prompt: "Explain why lock granularity involves a trade-off, and connect this to Week 1's point that quality attributes 'are rarely orthogonal' and interact with each other.",
        modelAnswer: "Finer-grain locks (e.g. locking one row) allow more concurrent operations to proceed in parallel, improving throughput, but require more locks to be tracked and increase the chance of deadlock; coarse-grain locks (e.g. locking a whole table) are simpler and have less deadlock risk, but serialise operations that could otherwise run safely in parallel, hurting performance. This mirrors Week 1's 'Design Trade-offs' point that quality attributes interact rather than being independent: here, correctness/safety (avoiding lost updates) and performance/scalability are in tension, and the 'right' lock granularity is a deliberate compromise rather than a setting that maximises both at once.",
      },
      {
        type: "scenario",
        prompt: "(Tutorial Q4, worked exercise) An application has three resource-state variables S, T, U and one session-state variable V. Functionality A: read S, read U, read V, write V. Functionality B: read S, read U, read V, write S. Functionality C: read S, read T, read U, write T. Assuming no concurrency control, and that two concurrent threads run in *different sessions*, fill in the conflict matrix for pairs (A/A, A/B, A/C, B/B, B/C, C/C), naming which shared variable(s) conflict in each cell, or 'none' if there is no conflict. Remember that V is session state and so is never shared across different sessions.",
        modelAnswer: "A/A: none — both instances of A only read the shared resource variables S and U (A's only write is to V, which is session-scoped and not shared across the two different sessions). A/B: S — A reads S, B writes S, so a read/write conflict exists on S; U is read-only in both so no conflict there. A/C: none — A and C both only read S and U (C writes only T, which A never touches), so nothing is jointly written. B/B: S — both instances read and write S, a direct lost-update risk on S. B/C: S — B writes S, C reads S, so a conflict on S (C's read of T is irrelevant since B never touches T). C/C: T — both instances write T (and only read S and U), exactly matching the tutorial's own worked example marking C/C with T as a lost-update risk.",
      },
      {
        type: "scenario",
        prompt: "You are reviewing bank.zip's BankController.simulateConcurrentTransfers, which fires 100 iterations of two opposite-direction transfer Runnables (A→B and B→A) into a 2-thread ExecutorService, then sums both account balances afterwards expecting 70 (50+20). Suppose a teammate proposes removing all locking from performTransfer entirely 'to make it faster,' relying only on the fact that each transfer method is wrapped in @Transactional. Using Week 2 concepts, explain whether @Transactional alone (with default isolation) would guarantee the combined balance stays 70, and why the tutorial instead asks you to add explicit optimistic or pessimistic locking.",
        modelAnswer: "@Transactional alone does not guarantee correctness here: it defines a transaction boundary (atomicity/durability for that method), but under typical default isolation levels a database still allows two concurrent transactions to each read the same account row's balance before either commits its write — exactly the lost-update interleaving from the lecture — meaning fromAccount.transfer()/toAccount.transfer() in two concurrent transfers could each compute a new balance from a stale read and overwrite each other's update, breaking the 'combined balance stays 70' invariant. Explicit locking closes this gap: pessimistic locking (`findByIdWithPessimisticUpdateLock`) blocks a second transaction from reading the row until the first transaction commits, serialising conflicting transfers; optimistic locking (`findByIdWithOptimisticLock` plus a `@Version` column) instead lets both proceed but fails/retries the second writer if the version changed underneath it — either way, correctness of the invariant depends on this explicit mechanism, not on @Transactional by itself.",
      },
      {
        type: "scenario",
        prompt: "The tutorial's final step asks you to remove the deadlock-prevention lines from performTransfer (`if (fromAccountId > toAccountId) { swap ids; negate amount; }`) after switching to pessimistic locking, then rerun the concurrent-transfer simulation. Predict and explain what you would observe, referencing the lecture's deadlock diagram.",
        modelAnswer: "With the swap removed, a transferAToB Runnable locks account A first then requests a lock on account B, while a concurrent transferBToA Runnable locks account B first then requests a lock on account A — this is exactly the lecture's deadlock pattern (T1 holds Lock A, waits for Lock B; T2 holds Lock B, waits for Lock A). With pessimistic locking now actually enforced (per the earlier fix), some pairs of concurrently-scheduled opposite-direction transfers will deadlock: each waits forever for a lock the other holds, until the database's lock-timeout or deadlock-detection kicks in and one (or both) transactions is aborted with an exception, which would show up as failed/incomplete transfers (and likely an exception in the executor) rather than a clean 100-iteration run, whereas with the canonical-ordering swap in place this circular-wait pattern can never occur.",
      },
      {
        type: "scenario",
        prompt: "(Final-exam style, open-book/cheat-sheet format) You are designing the checkout flow for an online ticketing platform where two customers might try to buy the last seat for a concert at the same time. Using Week 1's non-functional-requirements framing and Week 2's concurrency-control options, propose a locking strategy for the 'reserve seat' operation, and justify your choice against a strategy you rejected.",
        modelAnswer: "Choose pessimistic locking for the seat-reservation row: when a customer initiates checkout, acquire a pessimistic write lock on that specific seat row so a second concurrent customer's read is blocked until the first transaction commits or rolls back, guaranteeing the seat can never be double-sold — this directly matches the lecture's 'can't sell the same seat twice' concurrency-problem example. I would reject a purely optimistic approach here: under optimistic locking, both customers could get all the way through entering payment details before discovering (at commit time) that someone else already bought the seat, which is a poor user experience for a rare-but-high-stakes conflict; pessimistic locking's cost (customer B briefly waits, or is told the seat is being purchased) is an acceptable trade-off given seat availability has low overall contention (most seats aren't contested) but each individual conflict is high-stakes — matching Week 1's point that quality attributes like performance and correctness must be traded off deliberately rather than assuming one strategy is universally 'faster.'",
      },
      {
        type: "scenario",
        prompt: "(Final-exam style) A junior developer says: 'Our database enforces ACID, so as long as I wrap my code in a transaction, my application logic can never leave the data in an inconsistent state.' Using the lecture's distinction of which ACID properties the database enforces versus which depend on the application, evaluate this claim with an original example of application logic that would violate it despite ACID.",
        modelAnswer: "The claim conflates properties the database guarantees mechanically (Atomic, Isolated, Durable) with Consistent, which the lecture explicitly calls 'really an application program responsibility.' A transaction boundary and ACID guarantee that the transaction's writes either all happen or none do, that concurrent transactions don't corrupt each other (per the chosen isolation level), and that committed changes survive failure — but they say nothing about whether the business logic inside the transaction is itself correct. Example: a funds-transfer method that debits the sender's account but, due to a coding bug, credits the wrong recipient account instead of the intended one — this can commit as a perfectly atomic, isolated, durable transaction (money left one account, money arrived somewhere), yet the overall system state is now inconsistent from a business standpoint (money 'lost' relative to its intended destination), because Consistent depends on the application correctly implementing the invariant ('all money in bank is accounted for somewhere'), not on the database's ACID machinery alone.",
      },
    ],
  }

export const WEEK_2_PAPERS: ExamPaperSeed[] = [PAPER];
