import type { ExamPaperSeed } from "../types";

const TUTORIAL_PAPER: ExamPaperSeed = {
  course: "COMP5348",
  week: 3,
  paperNumber: 1,
  title: "Week 3 Tutorial Practice Paper",
  topics: "ERD notation (entities, attributes, primary/foreign keys, cardinality indicators); UML class diagram relationships (association, directed association, multiplicity, aggregation vs composition, inheritance vs realization, dependency); mapping the bank ERD (TransactionRecord/Account/Customer) to a class diagram; the tutorial-3-student Spring Boot bank-transaction app (Account/TransactionRecord/Customer model, service, controller, repository, and DTO layers; the deliberately-incomplete Customer entity 'fix' exercise; InsufficientBalanceException/NegativeTransferAmountException; the performTransaction transfer/deposit flow)",
  sourceFiles: [
    "tutorial/COMP5348_Tutorial 3 Slides.pdf",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/model/Account.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/model/TransactionRecord.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/model/Customer.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/service/AccountService.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/service/TransactionRecordService.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/service/CustomerService.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/controller/AccountController.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/controller/CustomerController.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/controller/TransactionRecordController.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/dto/AccountDTO.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/dto/CustomerDTO.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/dto/TransactionRecordDTO.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/repository/AccountRepository.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/repository/TransactionRecordRepository.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/repository/CustomerRepository.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/errors/InsufficientBalanceException.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/errors/NegativeTransferAmountException.java",
  ],
  questions: [
    {
      type: "mcq",
      prompt: "Per the Week 3 tutorial slides, what is an ERD 'entity'?",
      options: ["A UML relationship connecting two or more classes", "A method exposed by a class's public interface", "A foreign key constraint linking two tables", "An object (e.g. book, account, student) tracked in the database"],
      correctIndex: 3,
      modelAnswer: "The tutorial slides define an entity as 'an object (book, account, student) tracked in the database' — the Student example box shown is one instance of this definition.",
    },
    {
      type: "mcq",
      prompt: "In the tutorial's Student entity table (student_id PK; mobileNum, firstName, lastName, dob, enrolled all marked NOT NULL), what does the 'PK' marking on student_id specifically indicate that the other NOT NULL columns don't have?",
      options: ["That student_id uniquely identifies each row and is the entity's primary key, not just a required (non-null) value", "That student_id is a foreign key referencing another table", "That student_id is calculated automatically from the other columns", "That student_id is optional and can be left blank"],
      correctIndex: 0,
      modelAnswer: "PK marks student_id as the primary key — the column that uniquely identifies each row — which is a stronger property than merely being NOT NULL; the other attributes are required values but don't uniquely identify a row on their own.",
    },
    {
      type: "mcq",
      prompt: "Per the tutorial's Cardinality indicator table, what is the difference between '0..*' and '1..*'?",
      options: ["'0..*' means exactly zero; '1..*' means exactly one", "They are two notations for exactly the same thing", "'0..*' applies only to ERDs, '1..*' applies only to class diagrams", "'0..*' means zero or more; '1..*' means one or more — the difference is whether zero instances is allowed"],
      correctIndex: 3,
      modelAnswer: "The Cardinality table lists 0..* as 'Zero or more' and 1..* as 'One or more' — the only difference is whether the relationship permits zero related instances or requires at least one.",
    },
    {
      type: "mcq",
      prompt: "In the tutorial's ERD, Transaction Record has two separate foreign keys, to_account_id and from_account_id, both referencing the same Account table. Why two FKs instead of one?",
      options: ["Because one FK is for read access and the other is for write access", "Because a single transaction record needs to distinguish which account money left from and which account it arrived at — a transfer inherently touches two different accounts in two different roles", "It's redundant data duplicated for backup purposes", "Because Account is a many-to-many join table and needs two keys by convention"],
      correctIndex: 1,
      modelAnswer: "A transfer moves money between two accounts, so the record needs to capture both ends of the movement in their distinct roles — source and destination — which requires two separate foreign keys into the same Account table rather than one shared reference.",
    },
    {
      type: "mcq",
      prompt: "The tutorial's class diagram slide shows a directed association with an arrow from Airplane to Passenger, versus a plain undirected line for Students–Tutorial. What does the arrow/direction specifically add over a plain association?",
      options: ["It means the relationship is optional only in one direction", "It means Airplane inherits from Passenger", "It has no semantic difference from an undirected line", "It shows navigability — that Airplane has a reference to/knowledge of Passenger, without necessarily implying Passenger holds a reference back to Airplane"],
      correctIndex: 3,
      modelAnswer: "A directed association arrow shows navigability: the class at the tail (Airplane) knows about/references the class at the head (Passenger), without implying the reverse reference exists — unlike a plain undirected association line, which doesn't specify a direction of knowledge.",
    },
    {
      type: "mcq",
      prompt: "The tutorial slide shows Library —◇ Books as aggregation (open/hollow diamond) and Person —♦ Name as composition (filled diamond). What is the key difference between these two relationships?",
      options: ["In composition, the part (Name) cannot meaningfully exist independently of the whole (Person); in aggregation, the part (Books) can exist independently of the whole (Library)", "Composition only applies to primitive-typed fields like Name, aggregation only applies to object-typed fields like Books", "They are the same relationship drawn with different diamond styles for readability only", "Aggregation is stronger than composition"],
      correctIndex: 0,
      modelAnswer: "Composition (filled diamond) is the stronger 'owns and cannot exist without' relationship — a Person's Name has no independent existence — while aggregation (hollow diamond) is a weaker 'has-a' relationship where Books can exist (e.g. in another library, or on their own) independently of this particular Library.",
    },
    {
      type: "mcq",
      prompt: "The tutorial slide shows Corporate Account → Bank Account with a solid line and hollow triangle (inheritance), and Printer Setup → Printer with a dashed line and hollow triangle (realization). What distinguishes realization from inheritance here?",
      options: ["Realization (dashed line) shows a class implementing an interface's contract; inheritance (solid line) shows a class extending another concrete class's implementation", "The dashed line means the relationship is optional and may not exist at runtime", "Realization is only used for database tables, never for classes", "There is no meaningful difference — both symbols mean the exact same thing"],
      correctIndex: 0,
      modelAnswer: "Both use a hollow triangle, but the line style differs: a solid line (Corporate Account → Bank Account) is inheritance/extension of a concrete class, while a dashed line (Printer Setup → Printer) is realization — implementing an interface's contract without inheriting a concrete implementation.",
    },
    {
      type: "mcq",
      prompt: "The tutorial slide shows a dashed arrow (dependency) from LibraryMember to Book, distinct from the solid diamond relationships. What does a dependency arrow represent?",
      options: ["That the two classes are actually the same class under two different names", "A weaker relationship than association — that one class uses another (e.g. as a parameter, return type, or local variable) without a persistent structural link between them", "That Book cannot be instantiated without LibraryMember existing first", "The strongest possible ownership relationship between two classes"],
      correctIndex: 1,
      modelAnswer: "Dependency is a weaker relationship than association: it shows that one class (LibraryMember) makes use of another (Book) — e.g. via a method signature — without holding a persistent structural reference to it the way an association's field would.",
    },
    {
      type: "mcq",
      prompt: "In the tutorial's Class Diagram Example, Order and OrderItem are connected by an aggregation (hollow diamond at the OrderItem end) with multiplicities '1' on the Order side and '1..n' on the OrderItem side. What does this specifically require?",
      options: ["Every Order must have exactly one OrderItem, never more", "Every Order must be composed of at least one OrderItem, and each OrderItem belongs to exactly one Order", "Every OrderItem must belong to at least one Order, but an Order can have zero OrderItems", "Order and OrderItem have no required relationship at all"],
      correctIndex: 1,
      modelAnswer: "The '1' on the Order end and '1..n' on the OrderItem end mean each OrderItem is aggregated by exactly one Order, and each Order must aggregate at least one (one-or-more) OrderItem — not zero, and not capped at exactly one.",
    },
    {
      type: "mcq",
      prompt: "The Week 3 tutorial exercise asks for a bank application that tracks account balances 'through both implicit transaction records and explicit account balances.' How does this connect to the Week 2 lecture's discussion of state types?",
      options: ["Week 2 said derived state should never be cached, contradicting this tutorial's design", "It mirrors Week 2's derived-vs-resource-state example: the balance is derivable ('implicit') by summing TransactionRecord rows, but is also kept as a cached running total ('explicit') on Account.balance for efficiency, exactly like Week 2's own bank-balance example", "It means the balance should only ever be stored implicitly, never explicitly, per Week 2's guidance", "It has no connection — Week 2 covered concurrency, and this is purely a database design topic"],
      correctIndex: 1,
      modelAnswer: "Week 2's lecture used the bank account balance as its own worked example of derived state — 'could be computed by summing all transactions' but kept as a cached running total for efficiency. This tutorial's design does exactly both: TransactionRecord rows are the implicit/derivable source of truth, while Account.balance is the explicit, cached total that Account.modifyBalance() maintains directly.",
    },
    {
      type: "mcq",
      prompt: "Account.java declares two separate @OneToMany collections — fromTransactionRecords (mappedBy = \"fromAccount\") and toTransactionRecords (mappedBy = \"toAccount\"). Why two collections instead of one combined list of an account's transactions?",
      options: ["Because Hibernate requires exactly two @OneToMany fields per entity by convention", "Because one collection is for reading and the other is for writing, per JPA's read/write separation rule", "It's a bug in the student starter code with no architectural reason", "Because TransactionRecord itself has two distinct @ManyToOne fields (fromAccount and toAccount) in two different roles, so JPA needs a separate mapped collection for each role an Account can play in a transaction"],
      correctIndex: 3,
      modelAnswer: "TransactionRecord has two separate @ManyToOne relationships to Account — fromAccount and toAccount — reflecting the two roles an account can play in one transaction. Account's mappedBy attributes must match each of those role names individually, which is why it needs two separate @OneToMany collections rather than one.",
    },
    {
      type: "mcq",
      prompt: "What does Account.modifyBalance(Double amount) do?",
      options: ["Replaces the balance entirely with the given amount, discarding the previous balance", "Only allows positive amounts and throws an exception for negative ones", "Acquires a pessimistic database lock before changing the balance", "Adds amount to the current balance (this.balance = this.balance + amount), so a negative amount decreases the balance and a positive amount increases it"],
      correctIndex: 3,
      modelAnswer: "modifyBalance is a simple additive update: `this.balance = this.balance + amount;` — TransactionRecordService calls it with a negative amount to debit the fromAccount and a positive amount to credit the toAccount, with no locking performed inside the method itself.",
    },
    {
      type: "mcq",
      prompt: "Unlike Account's customer field (@JoinColumn(nullable = false)), TransactionRecord's toAccount and fromAccount fields have no nullable = false constraint. Why does this matter given how TransactionRecordService.performTransaction is written?",
      options: ["Because nullable = false only applies to primary keys, never to @ManyToOne fields", "Because a deposit only populates toAccount (fromAccountId is null), so exactly one of the two ends must be allowed to be null for a single-sided transaction to be recorded", "Because TransactionRecord entities are never actually persisted, so the constraint doesn't matter", "It's an oversight — both fields should be nullable = false like Account.customer"],
      correctIndex: 1,
      modelAnswer: "performTransaction only builds a fromAccount when fromAccountId is non-null, and only a toAccount when toAccountId is non-null — the deposit endpoint passes fromCustomerId/fromAccountId as null. If either @ManyToOne column were nullable = false, deposits (no fromAccount) would violate the database constraint and fail to save.",
    },
    {
      type: "mcq",
      prompt: "In TransactionRecordService.performTransaction, why is the `if (amount <= 0) throw new NegativeTransferAmountException();` check placed before either account is looked up or modified?",
      options: ["Because negative amounts are actually valid for withdrawals and this check is dead code", "It has no effect on behaviour and could be moved anywhere in the method", "Because JPA requires all validation to occur before any @Autowired field is used", "To reject an invalid request immediately, before doing any repository lookups or balance changes that would otherwise need to be undone"],
      correctIndex: 3,
      modelAnswer: "Validating the amount first is a fail-fast check: it rejects a clearly invalid request before spending effort on repository lookups (getReferenceById, findByIdAndCustomer) or mutating any account balance, avoiding the need to undo partial work.",
    },
    {
      type: "mcq",
      prompt: "InsufficientBalanceException is annotated @ResponseStatus(value = HttpStatus.PRECONDITION_FAILED, ...). What does this annotation achieve, compared to NegativeTransferAmountException's @ResponseStatus(value = HttpStatus.BAD_REQUEST, ...)?",
      options: ["Each exception is automatically translated into its own distinct HTTP status code by Spring when thrown, without the controller needing a try/catch block — 412 for insufficient balance vs 400 for a negative amount", "The annotation only affects logging output, not the actual HTTP response sent to the client", "Both exceptions always return the same 500 Internal Server Error regardless of the annotation", "@ResponseStatus requires the controller to manually catch and rethrow the exception to take effect"],
      correctIndex: 0,
      modelAnswer: "@ResponseStatus lets Spring MVC map an uncaught exception directly to an HTTP status automatically — InsufficientBalanceException maps to 412 Precondition Failed and NegativeTransferAmountException maps to 400 Bad Request — so TransactionRecordController needs no explicit try/catch to return the correct status for each distinct failure.",
    },
    {
      type: "mcq",
      prompt: "AccountDTO has two constructors: AccountDTO(Account) which defaults includeRelatedEntities to false, and AccountDTO(Account, boolean). Why does TransactionRecordDTO's constructor call `new AccountDTO(toAccount)` (the single-argument form) instead of passing true?",
      options: ["Because the single-argument constructor is faster at runtime for unrelated reasons", "Because TransactionRecordDTO never needs the account's name or balance at all", "To avoid an overly heavy/circular payload — a TransactionRecordDTO embedding an AccountDTO that itself embeds that account's full transactionRecords set (including this very transaction) would recurse", "It's arbitrary and could safely be changed to true without any effect"],
      correctIndex: 2,
      modelAnswer: "Passing true would make the nested AccountDTO include its own transactionRecords set (via AccountDTO's includeRelatedEntities branch), which would embed TransactionRecordDTOs pointing back to AccountDTOs, risking a much heavier or effectively circular payload — so nested accounts inside a TransactionRecordDTO stay 'shallow' (false), while the top-level AccountDTO returned directly by the controller passes true to include its full detail.",
    },
    {
      type: "mcq",
      prompt: "AccountRepository declares `Optional<Account> findByIdAndCustomer(long id, Customer customer);` with no method body. What SQL-equivalent condition does Spring Data JPA generate from this method name?",
      options: ["WHERE id = ? OR customer = ?", "It requires a corresponding @Query annotation to work at all — an empty method body alone will fail", "WHERE id = ? AND customer = ? (i.e. matching both the given id and the given Customer)", "It generates a query that ignores the customer parameter entirely"],
      correctIndex: 2,
      modelAnswer: "Spring Data JPA parses the method name 'findByIdAndCustomer' into a query joining the two conditions with AND — this is the same derived-query mechanism used elsewhere in the course (e.g. Week 1's findByTitleContaining) — no method body or @Query annotation is required.",
    },
    {
      type: "mcq",
      prompt: "The tutorial's starter Customer.java is deliberately left incomplete as part of the 'fixing Customer entity' exercise. Given the ERD (Customer: id, first_name, last_name) and that Account already declares `@ManyToOne @JoinColumn(nullable = false) private Customer customer;`, which annotation should the completed Customer entity use on its collection of accounts to mirror the existing bidirectional pattern already used between Account and TransactionRecord?",
      options: ["@ManyToMany private Collection<Account> accounts;", "@OneToOne private Account account;", "@ManyToOne(mappedBy = \"customer\") private Collection<Account> accounts;", "@OneToMany(mappedBy = \"customer\") private Collection<Account> accounts;"],
      correctIndex: 3,
      modelAnswer: "The same bidirectional pattern already used between Account and TransactionRecord (@OneToMany(mappedBy = ...) on the 'one' side, @ManyToOne on the 'many' side) applies here: since Account already holds the owning @ManyToOne Customer field, Customer's inverse side should be @OneToMany(mappedBy = \"customer\") over a Collection<Account>, exactly mirroring Account.fromTransactionRecords/toTransactionRecords being mappedBy their respective TransactionRecord fields.",
    },
    {
      type: "mcq",
      prompt: "The tutorial slides state ERD's focus is '___' while Class Diagram's focus is '___'.",
      options: ["database design; object-oriented structure design", "concurrency control; transaction management", "object-oriented structure design; database design", "network topology; UI layout"],
      correctIndex: 0,
      modelAnswer: "The slides state this explicitly: 'Entity Relationship Diagram (ERD) — Focus: database design' and 'Class Diagram — Focus: object-oriented structure design.'",
    },
    {
      type: "mcq",
      prompt: "CustomerController.createCustomer delegates entirely to customerService.createCustomer(request.firstName, request.lastName) and returns the resulting CustomerDTO. Per the layered architecture pattern this course has used since Week 1, what should the controller layer specifically NOT contain?",
      options: ["Any HTTP method verbs like @PostMapping", "Any reference to a DTO class", "Direct repository/database access or business logic (e.g. validation, persistence) — that belongs in the service and repository layers respectively", "Any @RequestMapping annotations"],
      correctIndex: 2,
      modelAnswer: "Consistent with Week 1's layering (controller = request/response handling, service = business logic, repository = persistence), CustomerController only translates the HTTP request into a service call and wraps the result in a ResponseEntity — it never touches CustomerRepository or constructs a Customer entity directly.",
    },
    {
      type: "mcq",
      prompt: "TransactionRecordRepository and CustomerRepository both simply extend JpaRepository<Entity, Long> with an empty body and no custom methods declared. What functionality do they still provide as a result?",
      options: ["No functionality at all — an empty interface body means the repository cannot be used", "Only read operations; write operations require a custom method to be declared", "The same custom findByIdAndCustomer method that AccountRepository declares, inherited automatically", "The standard CRUD operations (save, findById, findAll, delete, etc.) that JpaRepository provides out of the box, with no custom query methods needed for the tutorial's current use cases"],
      correctIndex: 3,
      modelAnswer: "Extending JpaRepository<Entity, Long> alone already provides the standard CRUD operations (save, findById, findAll, deleteById, etc.) via Spring Data JPA — an interface only needs additional method declarations when it requires a query beyond that standard set, which CustomerService and TransactionRecordRepository's current callers don't.",
    },
    {
      type: "mcq",
      prompt: "TransactionRecordController's deposit endpoint calls the same transactionRecordService.performTransaction(...) method as the transfer endpoint, but passes fromCustomerId and fromAccountId as null. What does this reuse rely on inside performTransaction?",
      options: ["The amount <= 0 check, which is what distinguishes a deposit from a transfer", "The fromAccountId != null guard, which skips looking up/debiting a source account entirely when it's null, so the same method naturally handles a one-sided (deposit) transaction as well as a two-sided (transfer) one", "Nothing — this is a bug, and deposits silently fail", "A separate overloaded performTransaction method specifically for deposits"],
      correctIndex: 1,
      modelAnswer: "performTransaction guards both the fromAccountId and toAccountId branches with null checks (`if (fromAccountId != null) { ... }`), so passing null for the 'from' side simply skips the debit branch entirely — the same method handles transfers (both branches run) and deposits (only the credit branch runs) without needing a separate code path.",
    },
  ],
};

const LECTURE_PAPER: ExamPaperSeed = {
  course: "COMP5348",
  week: 3,
  paperNumber: 2,
  title: "Week 3 Lecture Practice Paper",
  topics: "Distributed computing's ideal vs its reality; motivations for distribution (autonomy/independence, load balancing, reliability via redundancy) and the historical arc from 1960s conceptual origins through 1970s networking and 1980s Ethernet commercialisation to RPC/CORBA/DCOM/EJB; the Eight Fallacies of Distributed Computing (Deutsch); local vs remote method calls, stubs/skeletons, marshalling/unmarshalling, request/response message structure, SOAP; distributed architectures (peer-to-peer vs multi-tier); transparency's limits (network latency, partial failures, coarse- vs fine-grained interfaces); interface evolution strategy; Java EE application model and tiers (client/web/business/EIS), Enterprise Java Beans (stateless session beans, remote interfaces, JNDI lookup), deployment descriptors, JEE glossary (JNDI/RMI/JMS/JTA/JTS/JDBC); Spring Boot layering mapped onto the same tiered model",
  sourceFiles: ["lecture/COMP5348_W3.pdf", "lecture/Week 03 - Enterprise-s2-low.transcript.md"],
  questions: [
    {
      type: "mcq",
      prompt: "Per Peter Deutsch's 'Eight Fallacies of Distributed Computing' as presented in the lecture, which of the following is NOT one of the eight fallacies?",
      options: ["Latency is zero", "The network is fast", "Bandwidth is infinite", "The network is homogeneous"],
      correctIndex: 1,
      modelAnswer: "The lecture's list of eight fallacies is: the network is reliable, latency is zero, bandwidth is infinite, the network is secure, topology doesn't change, there is one administrator, transport cost is zero, and the network is homogeneous. 'The network is fast' is not one of the eight — the closest listed fallacies are 'latency is zero' and 'bandwidth is infinite', which are more specific claims.",
    },
    {
      type: "mcq",
      prompt: "What does the fallacy 'There is one administrator' actually warn against, per the lecture's framing of the eight fallacies as false assumptions?",
      options: ["Assuming only one client can call a remote service at a time", "Assuming a system needs exactly one system administrator on staff", "Assuming the network administrator is also the database administrator", "Assuming a single person/organisation controls and can be trusted to coordinate the entire network path a distributed call travels over, when in reality it usually spans multiple independent administrative domains"],
      correctIndex: 3,
      modelAnswer: "The eight fallacies are false assumptions developers wrongly rely on. 'There is one administrator' warns against assuming a single administrative authority governs the whole network path a call traverses — in practice a distributed call between organisations crosses multiple independently-administered networks with no single point of control. The lecture's own post-class discussion made this concrete: a company integrating with a third-party partner deals with that partner's own separate IT team and administration, not one shared administrator spanning both sides — exactly the kind of case the fallacy warns against assuming away.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's description of local method calls, which of the following correctly describes what happens at the hardware/runtime level?",
      options: ["A hardware-level 'call' instruction branches to the method, saving the return address; arguments are passed via registers and/or a new stack frame; a 'return' instruction exits the method", "The call is looked up via JNDI before the method executes", "A stub intercepts the call and forwards it to a remote object", "Arguments are marshalled into a message and sent to a listening skeleton over the network"],
      correctIndex: 0,
      modelAnswer: "The lecture's Local Method Calls slide describes the hardware-level 'call' instruction (branch + saved return address), argument passing via registers/stack frame, and a 'return' instruction to exit — the marshalling/stub/skeleton/JNDI machinery described afterwards is specific to remote calls, not local ones.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's Remote Method Call (client) slide, what does the client-side stub (proxy) do?",
      options: ["Determines whether the target server object is stateful or stateless", "Represents the target server object within the client system, takes the call arguments, marshals them plus related information into a message, and sends the request to the server machine", "Listens on a network endpoint and unmarshals incoming call requests", "Executes the actual business logic of the remote method"],
      correctIndex: 1,
      modelAnswer: "The stub represents the remote (server) object locally on the client side — from the programmer's perspective it looks like the remote object itself. Using the lecture's own worked example, a call like getStockByBookId(bookId) looks like an ordinary local method call, but it is actually a call on the stub: the stub takes the method name and the bookId argument, marshals them plus related information into a message, and sends the request to the server machine. The corresponding server-side responsibilities (listening, unmarshalling, dispatching) belong to the skeleton instead.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's Remote Method Call (server) slide, what does the server-side skeleton do after a request message arrives?",
      options: ["Unmarshals the call request message, extracts the arguments, determines which method/instance to call (raising the stateful/stateless question), and then does a normal method call to the server code/object", "Caches the result so future identical calls skip the network entirely", "Marshals the client's arguments into a request message before sending it", "Compiles the IDL/WSDL interface definition into a stub"],
      correctIndex: 0,
      modelAnswer: "The skeleton is the server-side counterpart to the client's stub: it listens on a network endpoint, unmarshals the incoming request, extracts arguments and determines the target method/instance (this is exactly where the lecture notes the 'stateful/stateless question' arises), then makes an ordinary local call into the server object.",
    },
    {
      type: "mcq",
      prompt: "The lecture notes a 'stateful/stateless question' arises specifically when the server-side skeleton determines which object instance should handle an incoming call. Using Week 2's stateful/stateless definitions, what is this question actually asking?",
      options: ["Whether the skeleton should marshal the response as XML or binary", "Whether the client stub or the server skeleton is responsible for encryption", "Whether the skeleton must route the call to one specific instance tied to that client's session (stateful), or whether any pooled instance can service the call because state is discarded/reloaded per operation (stateless)", "Whether the network connection itself uses TCP or UDP"],
      correctIndex: 2,
      modelAnswer: "Week 2 defined stateful code as holding state between operations and being tied to a client session, versus stateless code discarding state after each operation so any instance can serve any client. That's exactly the decision the skeleton faces: a stateful server object must be routed to specifically, while a stateless one can be served by any available pooled instance — this is the same design choice EJB's @Stateless annotation makes explicit.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's Remote Method Call (return path) slide, what is the correct order of steps once the remote method finishes executing?",
      options: ["The client stub re-executes the method locally to verify the server's answer", "Method returns to the skeleton → skeleton marshals the return values into a message and sends it to the client stub → client stub unmarshals the reply and returns the values to the caller", "Client stub marshals the return values → skeleton sends the request → method executes", "The return values skip the skeleton entirely and go straight from the server object to the client caller"],
      correctIndex: 1,
      modelAnswer: "The return path mirrors the request path in reverse: the method returns to the calling skeleton code, the skeleton marshals the results and sends them back to the client-side stub, and the stub unmarshals the reply and returns the extracted values to the original caller.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Stubs etc' slide, where do stubs and skeletons come from?",
      options: ["They are written entirely by hand for every remote call, with no tooling support", "They're generated by compilers/development environments from the set of methods/interfaces (which need to be known to the client), typically produced from server method definitions or an interface definition language such as IDL or WSDL", "They are generated at runtime by the network's DNS server", "They come pre-installed as part of the operating system kernel"],
      correctIndex: 1,
      modelAnswer: "The slide states stubs/skeletons are generated by compilers/development environments, which need to know the methods and interfaces plus the runtime layout/calling conventions of the language — generated from server method definitions or an interface definition language like IDL or WSDL, sometimes copied by hand or looked up in a repository. As the lecture put it, the application programmer's real job is only to provide the interface — what methods are available, what parameters they take, what types they return — not to hand-write the stub/skeleton plumbing underneath.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's History slide, which of the following pairings is correct?",
      options: ["RPC (1980s, procedural languages) came before CORBA (1990s, integrating objects across OO languages, standardised by OMG)", "Web services/REST were the first distributed computing technology, predating RPC", "DCOM predates RPC by several decades", "CORBA (1980s, procedural languages) came before RPC (1990s, object integration standardised by OMG)"],
      correctIndex: 0,
      modelAnswer: "The History slide places RPC in the 1980s for procedural languages (still used 'under the covers' today, e.g. file/mail servers), followed by CORBA in the 1990s for integrating objects written in multiple OO languages under OMG standards, followed later by DCOM/Java/WCF (components) and then web services/REST/MQ.",
    },
    {
      type: "mcq",
      prompt: "The lecture's 'Distributed architectures' slide lists peer-to-peer computing (e.g. mail server to mail server, B2B partners, supply chains) separately from multi-tier applications (layered roles/deployment, specialisation of servers, sharing load). Based on the accompanying online-retail diagram's Client Tier / Business Tier / Data Tier structure, which architecture style does that diagram illustrate?",
      options: ["Peer-to-peer, because the diagram also shows external Suppliers and Shippers", "Neither — the diagram is unrelated to either architecture style discussed in this section", "Peer-to-peer — every component in the diagram talks directly and symmetrically to every other component with no tiering", "Multi-tier — the diagram shows layered roles (web pages/user apps, then business components like Order/Payment/Stock, then databases) deployed across specialised, distinguishable tiers"],
      correctIndex: 3,
      modelAnswer: "The online-retail diagram explicitly labels Client Tier, Business Tier, and Data Tier, with business components (Order, Customer, Payment, Goods/Stock, Delivery) specialised and layered between the client apps and the databases — this is the multi-tier pattern (layered roles, specialisation of servers), not peer-to-peer, even though the diagram also shows peer-style connections to external suppliers/shippers/banks around the edges.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Transparency?' slide, what specifically does a 'partial failure' mean in a distributed system?",
      options: ["Some parts of a distributed operation succeed while other parts fail, rather than the whole operation cleanly succeeding or cleanly failing together", "The network fails completely and no messages get through at all", "The client application crashes but the server keeps running unaffected", "A method call fails only 50% of the time on average"],
      correctIndex: 0,
      modelAnswer: "The slide lists 'partial failures — some bits working, some not' alongside broken links, lost messages, and delays as new failure possibilities introduced by real networks — the defining trait is that a distributed operation can fail in a way where some of its parts succeeded and others didn't, unlike a local call which either fully executes or doesn't.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Transparency?' slide, why are standard OO techniques like frequent getters/setters and fine-grained objects specifically bad for remote/distributed interfaces?",
      options: ["Fine-grained objects use more memory than coarse-grained ones", "Getters and setters are always insecure and expose data to attackers", "Each small call becomes a full network round trip carrying its own latency and marshalling overhead, so many small remote calls are far more expensive in aggregate than one coarse-grained call that returns everything needed at once", "JVMs cannot marshal primitive return types like int or boolean"],
      correctIndex: 2,
      modelAnswer: "The slide's point is about round trips: standard OO patterns (getters/setters, frequent small method calls, assuming a shared address space) work fine locally but translate into poor performance once distributed, because each call now costs a network round trip. The lecture makes this concrete: an object with 10 fields exposed as 10 separate getter methods costs nothing extra locally, but calling all 10 remotely means paying for 10 separate marshal/send/unmarshal round trips — the lecture's fix is to 'design coarse-grained components which offer meaningful services' (e.g. one call that returns everything needed) instead of many fine-grained ones.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Evolution?' slide, which strategy does it recommend for evolving a distributed interface once client code is already deployed 'in the wild'?",
      options: ["Always change the existing interface in place and require every client to update immediately", "Never add new methods or parameters under any circumstances, ever", "Keep existing interfaces unchanged, and add new interfaces for new situations, rather than mutating an interface (which requires finding and changing every caller) or freezing it forever", "Delete the old interface immediately once a new one is published"],
      correctIndex: 2,
      modelAnswer: "The slide weighs 'immutable interfaces, defined once and never changed' against 'change interfaces and find/change every caller', and lands on a third option: 'Keep existing interfaces, and add new ones for new situations!' — old clients keep working against the interface they already use, while new functionality is exposed through additional interfaces.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Lessons Learned' slide, what does 'transparency' in distributed computing actually deliver, and what does it NOT deliver?",
      options: ["It guarantees zero latency regardless of network conditions", "It fully eliminates every difference between local and remote calls, so no special design is ever required", "It lets programmers keep structuring code in terms of familiar local procedures/objects ('as-if' local), hiding hardware/platform complexity — but it does not make the remote call actually local, so pitfalls must still be planned for with technological assistance", "It only applies to CORBA and DCOM, not to modern web services"],
      correctIndex: 2,
      modelAnswer: "The slide is explicit: transparency is 'mainly with regard to the programming paradigm' — programmers can keep thinking in procedures/objects, used 'as-if' they are local — 'but remember: they are not local!' Designing a reliable, fast distributed system still requires awareness of distributed computing's pitfalls, addressed with technological assistance like reliable messaging, distributed transactions, and redundancy.",
    },
    {
      type: "mcq",
      prompt: "In the lecture's 'Distributed Multitiered Applications' diagram, JSP Pages and Enterprise Beans are shown in two different tiers of the same Java EE Server. Which tier is each placed in?",
      options: ["JSP Pages are in the Web Tier; Enterprise Beans are in the Business Tier", "Both JSP Pages and Enterprise Beans are in the Client Tier", "Both JSP Pages and Enterprise Beans are in the EIS Tier", "JSP Pages are in the Business Tier; Enterprise Beans are in the Web Tier"],
      correctIndex: 0,
      modelAnswer: "The diagram places JSP Pages inside the Web Tier and Enterprise Beans inside the Business Tier, both sitting within the Java EE Server between the Client Tier (Application Client / Dynamic HTML Pages) and the EIS Tier (Database).",
    },
    {
      type: "mcq",
      prompt: "The lecture's Enterprise Java Beans example annotates CalculatorService with @Stateless. Using Week 2's stateful/stateless definitions, what does this annotation guarantee about how calls are handled?",
      options: ["Exactly one dedicated instance is permanently reserved for each client for the lifetime of their session", "No client-specific state is retained between calls, so the container can hand any incoming request to any pooled CalculatorService instance, matching Week 2's definition of stateless code discarding state after each operation", "The bean automatically persists its fields to the database after every method call", "It has no relationship to the stateful/stateless distinction — @Stateless only affects thread priority"],
      correctIndex: 1,
      modelAnswer: "Week 2 defined stateless code as discarding state after an operation so instances can be shared across clients, versus stateful code being tied to one client's session. @Stateless session beans are exactly this: since add/subtract/multiply/divide hold no per-client data between calls, the EJB container can pool instances and hand any of them to any client's request.",
    },
    {
      type: "mcq",
      prompt: "The lecture's example shows CalculatorServiceRemote as a separate @Remote-annotated interface, implemented alongside a local interface by CalculatorService. What is the purpose of this separate remote interface?",
      options: ["It defines which database columns the bean is allowed to modify", "It is required only when the bean has no local interface at all", "It duplicates the local interface purely for documentation, with no functional effect", "It declares which methods are exposed for cross-JVM/network invocation, forming the contract the client-side stub is generated from — distinct from a local interface used for in-process calls within the same JVM"],
      correctIndex: 3,
      modelAnswer: "@Remote marks CalculatorServiceRemote as the contract for calls arriving from outside the JVM — this is the interface a client-side stub is generated against — separate from any @Local interface used for calls from within the same JVM/container, which don't need the marshalling overhead of a remote call.",
    },
    {
      type: "mcq",
      prompt: "The lecture's Java EE Server Communications example does `Context ctx = new InitialContext(env); CalculatorServiceRemote calculatorService = (CalculatorServiceRemote) ctx.lookup(\"calculatorApp/CalculatorService/remote\");` before calling add/subtract/multiply/divide. What is JNDI being used for here?",
      options: ["Load-balancing requests across multiple database replicas", "Compiling the CalculatorServiceRemote interface into bytecode at runtime", "Encrypting the arguments before they are marshalled into the request message", "Locating/looking up the remote service's stub by a logical, published name, rather than the client hardcoding a network address — matching the JEE Glossary's 'Naming-and-Directory Service (JNDI)' entry"],
      correctIndex: 3,
      modelAnswer: "The JEE Glossary lists JNDI (Java Naming and Directory Interface) under 'Naming-and-Directory Service.' The lookup() call resolves a logical name ('calculatorApp/CalculatorService/remote') to the actual remote stub, so the client doesn't need to hardcode a server address — this is the naming/lookup step that happens before any add/subtract/multiply/divide call can be marshalled and sent.",
    },
    {
      type: "mcq",
      prompt: "The lecture's Deployment Descriptors slide shows an ejb-jar.xml with <session-type>Stateless</session-type>, <transaction-type>Container</transaction-type>, and a <container-transaction><trans-attribute>Required</trans-attribute> entry. Comparing this to Week 2's Spring @Transactional annotation, what do both mechanisms have in common?",
      options: ["The XML descriptor and @Transactional are functionally identical to SQL COMMIT statements typed directly into application code", "Both require the developer to manually call UserTransaction.begin() and commit() inside the method body", "Both are declarative transaction configurations — the transaction boundary is specified outside the business-logic code itself (XML descriptor here vs an annotation in Spring), rather than the code explicitly calling begin()/commit() as in JTA's explicit-transaction style", "Neither mechanism has anything to do with transactions — the descriptor only configures security"],
      correctIndex: 2,
      modelAnswer: "The lecture states deployment descriptors 'separate business logic from infrastructure concerns (eg: transactions and security)' — <transaction-type>Container</transaction-type> with <trans-attribute>Required</trans-attribute> declares that the method should run inside a container-managed transaction, without any begin()/commit() code, exactly matching Week 2's declarative @Transactional pattern; both stand in contrast to Week 2's JTA explicit-transaction example, which requires the code to call begin() and commit() itself.",
    },
    {
      type: "mcq",
      prompt: "A developer looks up a remote EJB stub via JNDI once at application startup and caches the reference for the app's entire lifetime, reasoning 'it's a name lookup, so it will always resolve to a working instance.' Which fallacy of distributed computing does this reasoning ignore, and why can the cached stub eventually start failing?",
      options: ["'Bandwidth is infinite' — caching the stub consumes bandwidth that should have been reserved elsewhere", "'Topology doesn't change' — the server or network path behind that logical name can change over time (e.g. redeployment, failover, a restarted instance), so a stub cached once can point at a no-longer-valid endpoint even though the lookup name itself never changed", "'The network is homogeneous' — different machines use different byte orders, which caching doesn't account for", "'Transport cost is zero' — caching a stub incurs a monetary transport cost that grows over time"],
      correctIndex: 1,
      modelAnswer: "The eight fallacies include 'Topology doesn't change.' A JNDI name is a logical lookup, but what it resolves to (the actual server/endpoint behind that name) can change at any time — redeployments, failovers, restarts — so a stub resolved and cached once at startup can silently go stale, even though nothing about the lookup call itself changed.",
    },
    {
      type: "mcq",
      prompt: "Using the lecture's bookshop/warehouse example, 'local computing and data' gives autonomy & independence as one motivation for keeping systems distributed rather than centralised. What two further motivations does the lecture give for actively distributing the application across multiple systems?",
      options: ["Making every component byte-code compatible, and guaranteeing zero latency between machines", "Reducing the total number of machines needed, and eliminating the need for a network entirely", "Centralising all data in one database, and giving every warehouse the exact same catalogue component", "Distributing load across systems via a load balancer, and reliability — if one warehouse's system goes down (e.g. a power outage), work can be routed to a different warehouse instead"],
      correctIndex: 3,
      modelAnswer: "The slide's own bullets are 'distributing load across many systems' and 'high reliability through autonomy'; the lecture gives them concrete voice with the bookshop/warehouse example: if thousands of users suddenly hit one machine it can't cope, so putting a load balancer in front of multiple warehouses/systems spreads the work, and if one warehouse's system goes down (e.g. a power outage), orders can still be routed to a different warehouse rather than the whole application failing.",
    },
    {
      type: "mcq",
      prompt: "Walking through the lecture's SOAP Request example live, the lecturer asked the class to identify which method was being called remotely and what parameter was being sent. Per the <soap:Body> shown (`<m:GetLastTradePrice ...><symbol>DIS</symbol></m:GetLastTradePrice>`), what are the correct answers?",
      options: ["Method: UsernameToken; parameter: Password = weYI3nXd8LjMNVksCKFV8t3rgHh3Rw==", "Method: wsa:Action; parameter: MessageID", "Method: GetLastTradePrice; parameter: symbol = DIS", "Method: soap:Envelope; parameter: xmlns:wsa"],
      correctIndex: 2,
      modelAnswer: "The lecturer's live walkthrough pointed to the <soap:Body> element as the actual remote call being made: the method is GetLastTradePrice and the parameter passed is symbol, with value DIS. The surrounding <soap:Header> block (UsernameToken/Password, wsa:Action, wsa:MessageID) is security/addressing plumbing the framework handles for you — as the lecture put it, 'you don't have to understand every line ... everything around just supports its distributed interaction,' with the actual application-programmer-visible content being the method call and its parameters.",
    },
    {
      type: "truefalse",
      prompt: "True or False: per the lecture, the conceptual goal of distributed computing was already being discussed as early as the 1960s — well before 1970s networking became commonplace and 1980s Ethernet commercialisation — with the RPC/CORBA/DCOM technologies on the lecture's History slide arriving only later, as ways of actually achieving that older goal.",
      options: ["True", "False"],
      correctIndex: 0,
      modelAnswer: "The lecture's verbal framing (not printed on the slides) traces this arc explicitly: people were already asking whether different things could run across different machines/locations back in the 1960s; networking became more and more common through the 1970s; Ethernet was becoming commercialised by the 1980s, at which point the slide's own History timeline picks up — RPC for procedural languages in the 1980s, then CORBA for object integration under OMG in the 1990s. The underlying motivation (autonomy/independence combined with the need to communicate and cooperate) predates any of the specific technologies that eventually delivered on it.",
    },
    {
      type: "short",
      prompt: "Using the lecture's own worked example of a client calling a remote getStockByBookId(bookId) method, trace the full round trip from the client's call to the value being returned — naming every component involved — and explain why the lecture stresses minimising the number of such round trips (e.g. its '10 fields, 10 remote getter calls' example) rather than just accepting that frameworks make remote calls 'look local'.",
      modelAnswer: "The client calls getStockByBookId(bookId) on what looks like a normal local object, but is actually the stub/proxy. The stub marshals the method identifier and the bookId parameter into a request message and sends it over the network to the server-side skeleton, which unmarshals the message, determines the target method/instance, and makes an ordinary local call into the real server object. The method executes and returns to the skeleton, which marshals the result into a response message and sends it back over the network; the client-side stub unmarshals the reply and hands the value back to the original caller — the full client → stub → network → skeleton → server, then server → skeleton → network → stub → client path. This machinery makes the call look local syntactically, but each round trip still costs real network latency (the lecture's own point: local calls are microseconds, remote calls are milliseconds). The lecture's example makes this concrete: an object with 10 fields exposed as 10 separate getter methods is fine to call locally, but calling all 10 remotely means paying for 10 separate marshal/send/unmarshal round trips instead of one — exactly why the lecture recommends combining such calls into one coarse-grained request that returns everything needed at once, rather than trusting the stub/skeleton illusion of locality to make many small remote calls free.",
    },
    {
      type: "scenario",
      prompt: "Your team's remote CatalogueService interface, including getStockByBookId(bookId), has already been deployed and is being called by several partner bookshops' client code 'out in the wild.' Product now wants getStockByBookId to also accept an optional promoCode parameter, so promotional stock can be filtered differently. Using the lecture's 'Evolution?' guidance, explain the tradeoffs of your options and recommend one.",
      modelAnswer: "The lecture frames this exact dilemma: an immutable, frozen interface means you'd have to publish a whole new interface and drop the old one, breaking every partner who hasn't migrated; changing the existing interface in place (e.g. adding a required promoCode parameter to getStockByBookId) means finding and updating every one of those already-deployed partner clients, which for external partners you don't control may not even be possible. The lecture's recommended middle path is to keep the existing interface unchanged — getStockByBookId(bookId) keeps working exactly as before for partners who haven't adopted promoCode — and add a new interface/method for the new situation (e.g. an overload or a new getStockByBookIdWithPromo(bookId, promoCode) method, or a new interface version). Existing partner integrations keep working untouched, while new or updated partners can opt into the richer method — avoiding both the 'break everyone today' cost of mutating the interface and the 'break everyone eventually' cost of an immutable interface that can never grow.",
    },
  ],
};

export const WEEK_3_PAPERS: ExamPaperSeed[] = [TUTORIAL_PAPER, LECTURE_PAPER];
