import type { ExamPaperSeed } from "../types";

const PAPER: ExamPaperSeed = 
  {
    course: "COMP5348",
    week: 1,
    paperNumber: 1,
    title: "Week 1 Practice Paper",
    topics: "Architecture definitions, structure vs communication, 4+1 view model, architecture patterns, layering; Non-functional requirements, performance, scalability, security, availability, modifiability, trade-offs; Course administration/assessment, Spring Boot + JPA + REST fundamentals, layered/MVC architecture in practice",
    sourceFiles: ["COMP5348_W1.pdf", "Tutorial/COMP5348_Tutorial 1.pdf"],
    questions: [
      {
        type: "mcq",
        prompt: "According to Garlan and Shaw, designing and specifying the overall system structure is a new kind of problem that goes beyond what?",
        options: ["The algorithms and data structures of the computation", "The syntax and semantics of the programming language", "The UI design and user experience", "The database indexing strategy"],
        correctIndex: 0,
        modelAnswer: "Garlan and Shaw's definition explicitly says architecture 'goes beyond the algorithms and data structures of the computation' — structural issues like control structure, protocols, physical distribution and design-alternative selection are a distinct kind of problem.",
      },
      {
        type: "mcq",
        prompt: "Per the SEI definition quoted in the lecture, software architecture comprises which three things?",
        options: ["The structure(s) of the system, the externally visible properties of its elements, and the relationships among them", "The source code, its comments, and its version history", "The UI, the API, and the database schema", "The requirements document, the design document, and the test plan"],
        correctIndex: 0,
        modelAnswer: "The SEI definition: 'the structure or structures of the system, which comprise software elements, the externally visible properties of those elements, and the relationships among them.'",
      },
      {
        type: "mcq",
        prompt: "In Kruchten's 4+1 view model, which view 'depicts how the major processes and components are mapped on to the application's hardware'?",
        options: ["Logical view", "Process view", "Physical view", "Development view"],
        correctIndex: 2,
        modelAnswer: "The Physical view is explicitly defined in the lecture as depicting how major processes and components map onto the application's hardware; the Process view instead covers concurrency and communication.",
      },
      {
        type: "mcq",
        prompt: "Which of the following is NOT one of the four things the lecture says architecture defines about structure?",
        options: ["Component parts", "Component interfaces", "Component test coverage", "Component responsibilities"],
        correctIndex: 2,
        modelAnswer: "The 'Architecture Defines Structure' slide lists component parts, component interfaces, component communications/dependencies, and component responsibilities — test coverage is not one of them.",
      },
      {
        type: "truefalse",
        prompt: "True or False: The lecture describes architecture patterns like client-server, message bus, and message broker as reusable, proven architectural blueprints that help efficiently communicate a design.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "The 'Architecture Patterns/Styles' slide states patterns are 'reusable and proven architectural blueprints' that 'help efficiently communicate a design,' and that large systems comprise a number of individual patterns.",
      },
      {
        type: "mcq",
        prompt: "In the layered stack the lecture maps onto Browser+React / Spring Boot / PostgreSQL, which tier contains the Controller layer, Service/business layer, and Repository/data-access layer?",
        options: ["User/Client Tier", "Application Tier", "Data Tier", "Presentation Layer only"],
        correctIndex: 1,
        modelAnswer: "The Application Tier (Spring Boot) is shown containing all three sub-layers — Controller layer, Service/business layer, and Repository/data-access layer — sitting between the User/Client Tier and the Data Tier.",
      },
      {
        type: "mcq",
        prompt: "The lecture says each application should have a comprehensible architecture defining structure, behaviour, and allocation. What does 'allocation' refer to?",
        options: ["What software components exist", "When and how components call one another", "Where components are deployed", "Which stakeholders requested the component"],
        correctIndex: 2,
        modelAnswer: "'Allocation' is listed alongside structure ('what software components are there') and behaviour ('when and how they call one another') as 'where are they deployed.'",
      },
      {
        type: "truefalse",
        prompt: "True or False: The ANSI/IEEE Std 1471-2000 definition of architecture explicitly includes 'the principles governing its design and evolution,' not just its current structure.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "The quoted definition is: 'Architecture is the fundamental organization of a system, embodied in its components, their relationships to each other and the environment, and the principles governing its design and evolution.'",
      },
      {
        type: "short",
        prompt: "Compare the ANSI/IEEE 1471-2000 definition and the SEI definition of software architecture in your own words. What's the key overlap between them?",
        modelAnswer: "Both definitions centre on the idea that architecture is fundamentally about elements/components and the relationships among them, not implementation detail. The IEEE definition is broader — it also folds in 'the environment' the system sits in and 'the principles governing its design and evolution' (how the system is expected to change over time). The SEI definition is narrower and more static: structure(s) of the system, the externally visible properties of its elements, and the relationships among them. The overlap is the core claim that architecture = elements + relationships between elements, distinct from internal implementation.",
      },
      {
        type: "short",
        prompt: "Explain the difference between what architecture 'defines about structure' and what it 'specifies about component communication.' Give one original example of each.",
        modelAnswer: "Structure covers the decomposition into components, their interfaces, and their responsibilities — e.g. in an e-commerce app, a PaymentService component with a charge() interface and the sole responsibility of processing payments. Communication covers how components pass data and coordinate control flow — function call, remote method invocation, or asynchronous message, plus whether the flow is sequential, concurrent, or synchronised — e.g. PaymentService making a synchronous REST call to a third-party gateway, versus emitting an asynchronous 'PaymentCompleted' event onto a message queue for other services to consume.",
      },
      {
        type: "short",
        prompt: "List the five views in Kruchten's 4+1 view model and give a one-sentence description of each, using an example different from the lecture's building analogy.",
        modelAnswer: "Logical view: architecturally significant elements and the relationships between them (e.g. a class diagram of Order, Customer, and Payment domain objects). Process view: the concurrency and communication elements of an architecture (e.g. how order-processing worker threads coordinate with a payment worker pool). Physical view: how major processes/components map onto hardware (e.g. the web tier deployed on one VM, the database on a separate managed instance). Development view: the internal organisation of the software components as held in a configuration management tool (e.g. a Maven multi-module project layout). Architecture use cases (the '+1'): requirements that exercise more than one view at once (e.g. 'place an order' touching the logical, process, and physical views together).",
      },
      {
        type: "short",
        prompt: "Why does the lecture argue that quality attributes (QAs) like scalability must be made precise/measurable rather than left as vague statements such as 'the application must be scalable'? Give a rewritten, measurable version of that statement.",
        modelAnswer: "A vague QA statement gives the architect no way to verify whether a design actually satisfies it, or to reason about trade-offs against other requirements — 'scalable' could mean handling ten more users or ten million more. Precise, measurable QAs are testable and drive concrete design decisions. Rewritten example, in the lecture's own style: 'It must be possible to scale the deployment from an initial 100 geographically dispersed user desktops to 10,000 without an increase in effort/cost for installation and configuration.'",
      },
      {
        type: "scenario",
        prompt: "You are the architect for a new enterprise timesheet system. Stakeholders tell you it must be 'reliable' and 'fast.' Using the 4+1 view model and the lecture's discussion of QA specification, describe how you would (a) turn 'fast' into a measurable requirement, and (b) which view(s) you'd use to communicate the deployment topology to the operations team.",
        modelAnswer: "(a) Turn 'fast' into something measurable, mirroring the lecture's own response-time example: 'X% of timesheet-submission requests return within 2 seconds, and 99.9% within 5 seconds, under a load of 500 concurrent users.' (b) Use the Physical view to show operations how processes/components map onto actual servers/VMs/containers, since that's the view specifically defined to depict hardware deployment; the Process view would supplement this by showing the concurrency and communication paths between those deployed components (e.g. which service instances talk to which database replicas).",
      },
      {
        type: "scenario",
        prompt: "A junior developer on your team proposes a single Java class that does authentication, business logic, and direct SQL queries, arguing 'it's simpler, and we're only one team.' Using the lecture's concepts of layering, component responsibilities, and modifiability, argue against this design and describe what should change if the company later needs to 'move to the Cloud' (one of the listed modifiability scenarios).",
        modelAnswer: "The proposal violates the lecture's layering pattern (presentation / services / business / data) and the idea that each component should have a single, well-defined responsibility with a clear interface. Mixing auth, business logic, and SQL in one class means a database schema change risks breaking authentication or business rules, since there is no clean boundary between them — this fails the 'component interfaces' and 'component responsibilities' properties the lecture calls out. When the 'move to the Cloud' modifiability scenario hits, the data-access code embedded throughout the class has to be found and rewritten by hand, instead of swapping out a well-defined repository/data-access layer for a cloud-native equivalent; the same problem recurs for switching auth providers. Splitting into layers (controller → service/business → repository) means each of these changes touches only one layer.",
      },
      {
        type: "mcq",
        prompt: "Which of the following best matches the lecture's definition of 'throughput'?",
        options: ["A measure of the latency an application exhibits processing a single request", "A measure of the amount of work an application performs in a unit of time", "The percentage of scheduled time a system is usable", "The ability of an application to run on a different hardware/software platform"],
        correctIndex: 1,
        modelAnswer: "Throughput is defined as 'a measure of the amount of work an application must perform in unit time' (e.g. transactions per second, messages per minute) — response time is the latency metric instead.",
      },
      {
        type: "mcq",
        prompt: "Why does the lecture say '99th percentile latency' matters more than a simple average latency figure?",
        options: ["Because averages hide worst-case outliers that some users still experience ('averages are evil')", "Because percentiles are cheaper to compute than averages", "Because the 99th percentile is always lower than the average", "Because regulators require percentile reporting for all software"],
        correctIndex: 0,
        modelAnswer: "The Performance slide lists '99th percentile latency (averages are evil)' as more meaningful than a plain average, since an average can look fine even while a meaningful fraction of requests are slow.",
      },
      {
        type: "mcq",
        prompt: "In the ISP scalability example, what ultimately caused the 'tech crash'?",
        options: ["Each user connection spawned a new process, exceeding server virtual memory at ~2,000 users while the business needed to support hundreds of thousands", "The database ran out of disk space", "The load balancer had a misconfigured DNS entry", "The firewall blocked too many legitimate requests"],
        correctIndex: 0,
        modelAnswer: "'Scalability - connections' describes an ISP where each user connection spawned a new process; virtual memory on each server was exceeded at 2000 users, but the business needed to support 100Ks of users — leading to a tech crash.",
      },
      {
        type: "mcq",
        prompt: "Which of the following is one of the lecture's four common scalability issues in IT systems?",
        options: ["Request load", "Code readability", "Compiler version", "Font rendering"],
        correctIndex: 0,
        modelAnswer: "The Scalability slide lists four common issues: request load, connections, data size, and deployments.",
      },
      {
        type: "truefalse",
        prompt: "True or False: 'Scale-up' means replicating an application across multiple separate machines, while 'scale-out' means running a single instance on a bigger multiprocessor machine.",
        options: ["True", "False"],
        correctIndex: 1,
        modelAnswer: "This is reversed. Scale-up means a single application instance executed on a bigger multiprocessor machine; scale-out means the application is replicated across different machines.",
      },
      {
        type: "mcq",
        prompt: "Which security property ensures 'neither party can subsequently refute their participation in a message exchange'?",
        options: ["Authentication", "Authorization", "Integrity", "Non-repudiation"],
        correctIndex: 3,
        modelAnswer: "Non-repudiation is defined as: the sender has proof of delivery and the receiver is assured of the sender's identity, so neither can later refute their participation in the exchange.",
      },
      {
        type: "mcq",
        prompt: "According to the lecture's availability strategies, which of the following is NOT listed as a strategy for achieving high availability?",
        options: ["Eliminate single points of failure", "Replication and failover", "Automatic failure detection and restart", "Increasing the average response time"],
        correctIndex: 3,
        modelAnswer: "The 'Availability' slide lists eliminating single points of failure, replication and failover, and automatic failure detection and restart as strategies — increasing response time is unrelated and not one of them.",
      },
      {
        type: "truefalse",
        prompt: "True or False: The lecture states that quality attributes are rarely orthogonal — they interact and trade off against each other, e.g. a highly secure system may be difficult to integrate.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "The 'Design Trade-offs' slide states QAs 'are rarely orthogonal' and 'interact, affect each other,' giving the example that a highly secure system may be difficult to integrate, and a high-performance application tied to one platform may not be portable.",
      },
      {
        type: "short",
        prompt: "Explain the difference between 'response time' and 'throughput' as performance metrics, and give one original example of a system where you'd care more about one than the other.",
        modelAnswer: "Response time is the latency to process a single request (how quickly), while throughput is how many events/transactions can be processed per unit time (how much). Example: an interactive chat app cares more about response time, since users directly notice per-message delay, while an overnight batch payroll job cares more about throughput, since the total number of records processed per hour matters more than any single record's latency.",
      },
      {
        type: "short",
        prompt: "Using the lecture's four scalability issues (request load, connections, data size, deployments), pick one and explain, with an original example, how a system might fail to scale along that dimension.",
        modelAnswer: "Data size example: a reporting dashboard's query does a full table scan over an 'orders' table. This performs fine at 1 million rows but times out once the table grows to 20 million rows, because the query's effective complexity (roughly O(N) or worse, with no supporting index) doesn't scale with data volume — matching the lecture's warning that the scalability of your code, O(1) vs O(N) vs O(N²), 'has real impact.'",
      },
      {
        type: "short",
        prompt: "List the five security properties covered in the lecture and define each in one sentence.",
        modelAnswer: "Authentication: verifying the identity of users and other applications the system communicates with. Authorization: authenticated users/applications have defined access rights to the system's resources. Encryption: messages sent to/from the application are encrypted so they can't be read in transit. Integrity: ensures the contents of a message are not altered in transit. Non-repudiation: the sender has proof of delivery and the receiver is assured of the sender's identity, so neither can later deny participating in the exchange.",
      },
      {
        type: "short",
        prompt: "Explain why the lecture says architects must 'create solutions that make sensible design compromises' rather than fully satisfying every quality attribute. Give one original example of two QAs in tension.",
        modelAnswer: "Because QAs are rarely orthogonal — improving one can degrade another — and no single design can simultaneously maximise every competing requirement while satisfying all stakeholders and preparing for an unknown future, so trade-offs are unavoidable. Example: adding end-to-end encryption and multi-step authorization checks (security) adds processing overhead to every request, which can push response times up (performance) — a genuinely more secure design can become measurably slower.",
      },
      {
        type: "scenario",
        prompt: "Your enterprise application currently handles 200 requests/second with acceptable response times, but the business expects a 50x traffic spike during a holiday sale. Using the lecture's scalability concepts (scale-up vs scale-out, and the four scalability issues), propose a plan, and explain which single point of failure you'd address first and why (tie to the availability content).",
        modelAnswer: "Prefer scale-out (replicate the application across multiple machines behind a load balancer) over scale-up, since a 50x spike is better absorbed by adding commodity instances than by one ever-larger machine, and scale-out also improves availability by removing reliance on a single host. Address the database connection layer first as the most likely single point of failure, per the ISP 'Scalability - connections' example where a fixed per-server resource limit caused a crash at scale — introduce connection pooling limits, read replicas, and caching so request load and concurrent connections don't simultaneously exhaust the same resource. Tying this to availability: eliminating this single point of failure (per 'Strategies for high availability') reduces the risk that the spike itself causes an outage.",
      },
      {
        type: "scenario",
        prompt: "A payment microservice needs to guarantee that once a customer's payment request is accepted, the customer cannot later deny having authorised it, and the merchant cannot later claim they didn't receive it. Which security property from the lecture is being requested here, and what other properties would need to support it? Also state one measurable availability requirement appropriate for a payment service.",
        modelAnswer: "This is a non-repudiation requirement (sender/receiver have proof of participation and can't later deny it). It needs to be underpinned by authentication (verifying who actually submitted the request) and integrity (ensuring the payment details weren't altered in transit) — without both, there's no reliable proof of what was actually authorised. A measurable availability requirement, matching the lecture's own style: 'the payment service must be available 99.99% of the time, with no more than 1 hour of scheduled maintenance per month.'",
      },
      {
        type: "mcq",
        prompt: "According to the COMP5348 assessment breakdown, what percentage of the final mark comes from the Final Exam?",
        options: ["40%", "60%", "70%", "100%"],
        correctIndex: 1,
        modelAnswer: "Assessment Tasks total 40% (Assignment 1 10%, Assignment 2 10%, Group Project 20%) plus up to 5 supplementary attendance marks, and the Final Exam is 60%.",
      },
      {
        type: "mcq",
        prompt: "What is the minimum percentage of exam marks a student must achieve to pass the unit, per School of Computer Science policy?",
        options: ["30%", "40%", "50%", "60%"],
        correctIndex: 1,
        modelAnswer: "The slide states: 'School of Computer Science policy: you must get at least 40% of the marks available on the exam, in order to pass the unit.'",
      },
      {
        type: "mcq",
        prompt: "In the Spring Boot tutorial demo, what is the purpose of the @RestController annotation on BookController?",
        options: ["It marks the class as a Spring MVC controller whose methods return data (e.g. JSON) directly in the HTTP response body rather than rendering a view", "It configures the database connection string", "It defines a new REST endpoint route with no Java code required", "It automatically enables cross-origin requests for every domain"],
        correctIndex: 0,
        modelAnswer: "@RestController is a Spring Boot annotation that combines @Controller and @ResponseBody, so handler methods (like getAllBooks) return data directly as the HTTP response body instead of a view name to render.",
      },
      {
        type: "mcq",
        prompt: "What does the @Autowired annotation do when applied to the bookRepository field in BookController?",
        options: ["It tells Spring to automatically inject a managed bean instance (dependency injection) instead of the developer instantiating it manually", "It marks the field as read-only so it can never be reassigned", "It creates a new database table matching the field's type", "It schedules the field to be recalculated on every request"],
        correctIndex: 0,
        modelAnswer: "@Autowired triggers Spring's dependency injection: Spring finds (or creates) a managed BookRepository bean and injects it into the controller, so the developer never manually instantiates it with `new`.",
      },
      {
        type: "truefalse",
        prompt: "True or False: In the tutorial's BookRepository interface, the method findByTitleContaining(String title) works correctly even though no implementation body is written, because Spring Data JPA derives the query automatically from the method name.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "Tutorial question 3 asks exactly this: findByTitleContaining is declared with no body, but Spring Data JPA parses the method name and generates the corresponding query implementation automatically at runtime.",
      },
      {
        type: "mcq",
        prompt: "The tutorial's demo application (React frontend + Spring Boot backend + PostgreSQL) is described as an example of which software architecture pattern from the lecture?",
        options: ["Model-View-Controller (MVC)", "Peer-to-peer", "Monolithic single-tier", "Event sourcing"],
        correctIndex: 0,
        modelAnswer: "The tutorial explicitly states: 'You should have familiarized yourself with this sample Book Store application in a Model-View-Controller (MVC) software architecture.'",
      },
      {
        type: "mcq",
        prompt: "Per the tutorial's application.properties configuration, which Spring property controls whether Hibernate automatically updates the database schema to match the entity classes?",
        options: ["spring.datasource.url", "spring.jpa.hibernate.ddl-auto", "spring.application.name", "spring.jpa.properties.hibernate.dialect"],
        correctIndex: 1,
        modelAnswer: "The tutorial sets `spring.jpa.hibernate.ddl-auto=update` with the comment 'Hibernate ddl auto (create, create-drop, validate, update)' — this controls automatic schema synchronisation, distinct from the datasource URL, app name, or SQL dialect settings.",
      },
      {
        type: "truefalse",
        prompt: "True or False: Per the course outline, late assignment submissions are allowed without penalty as long as they are submitted within one week of the deadline.",
        options: ["True", "False"],
        correctIndex: 1,
        modelAnswer: "The outline states 'Late submissions: NOT ALLOWED unless special consideration' — there is no automatic one-week grace period.",
      },
      {
        type: "short",
        prompt: "The current Book Store demo application (from the tutorial) cannot store a price for books. Referencing the layered architecture from the lecture (model/controller/repository), briefly describe which files you would need to modify and why, without writing full code.",
        modelAnswer: "Add a price field (with an appropriate @Column mapping) to the Book entity/model class so the schema and JPA mapping include it. Update BookController so request/response handling accepts and returns the new field. BookRepository itself likely needs no change, since Spring Data JPA derives basic CRUD operations from the entity automatically — this mirrors the lecture's point that each layer has a distinct responsibility (model = data shape, controller = request/response, repository = persistence), so a new field mainly touches the model and controller layers.",
      },
      {
        type: "short",
        prompt: "Explain in your own words why the tutorial has you install PostgreSQL, IntelliJ, and Node.js separately, and connect this three-part setup to the lecture's layered architecture diagram (User/Client Tier, Application Tier, Data Tier).",
        modelAnswer: "PostgreSQL provides the Data Tier (persistent storage). The Spring Boot project built in IntelliJ provides the Application Tier — the controller, service, and repository layers that handle business logic and expose the API. The React app run via Node.js provides the User/Client Tier — the browser-based UI. Installing and configuring them separately mirrors the architectural separation of concerns from the lecture's layering diagram: each tier can be developed, deployed, and scaled independently of the others.",
      },
      {
        type: "short",
        prompt: "List three assessment components of COMP5348 and their weightings as stated in the course outline, and explain what 'up to 5 supplementary marks' for attendance means for a student's final grade.",
        modelAnswer: "Assignment 1 (10%, due week 7), Assignment 2 (10%, due week 11), and the Group Project (20%, due week 13, split into 10% integration/components and 10% presentation); the Final Exam separately makes up 60%. The attendance component adds up to 5 supplementary marks on top of the graded total — it can only add to a student's mark (e.g. pushing a borderline result up), it is not part of the base 100% and cannot be relied on to make up a shortfall elsewhere.",
      },
      {
        type: "short",
        prompt: "What are the four pieces of assumed knowledge listed in the course outline's 'Expectations (technical)' slide? Briefly justify why each is needed given the tutorial's Spring Boot + React + PostgreSQL stack.",
        modelAnswer: "(1) An OO language (Java/C#/C++) — needed because the backend is written in Java/Spring Boot using classes and interfaces, e.g. BookRepository extends JpaRepository. (2) Relational database fundamentals / simple SQL — needed to configure and query PostgreSQL, e.g. CREATE DATABASE demo and SELECT * FROM books. (3) Data modelling (entity-relationship or OO class design) — needed to design entities like Book with fields that JPA maps to database columns. (4) Software development processes (requirements, documenting, testing) — needed because the group project requires producing a properly documented, working system, not just code that happens to run.",
      },
      {
        type: "scenario",
        prompt: "You're pairing with a teammate who set spring.jpa.hibernate.ddl-auto=update in application.properties, and the team now wants to deploy to a shared staging database used by multiple developers. Using the lecture's modifiability and availability concepts plus the tutorial's config file, explain one risk of leaving ddl-auto=update in a shared environment and propose a safer alternative.",
        modelAnswer: "With ddl-auto=update, Hibernate automatically alters the shared schema whenever any developer's local entity classes change, which can silently drop or alter columns other developers depend on, or apply a half-finished schema change to a shared environment — an uncontrolled version of the 'constant evolution' the lecture describes as a fact of life for enterprise systems, and a risk to the availability of the shared environment if a broken migration takes down the app for everyone. A safer alternative is to set ddl-auto=validate (or none) in shared/staging environments and manage schema changes explicitly through versioned migration scripts (e.g. Flyway/Liquibase), so schema evolution is reviewed and repeatable rather than automatic.",
      },
      {
        type: "scenario",
        prompt: "A tutor asks: 'Why does the Book Store demo separate BookController, Book, and BookRepository into three different classes/packages instead of one big class?' Using the lecture's concept of component responsibilities and the MVC architecture pattern, write a two-to-three sentence answer a student could give in a tutorial.",
        modelAnswer: "Each class has one clear responsibility: Book (model) defines the data shape and persistence mapping, BookController exposes HTTP endpoints and translates requests/responses, and BookRepository provides the actual database access — mirroring the lecture's 'Architecture Defines Structure' idea that each component should have a precise, single responsibility with a clear interface. This separation, an application of the MVC/layered pattern, means swapping PostgreSQL for a different database would only require changes in the repository layer, without touching the controller or model.",
      },
    ],
  }

export const WEEK_1_PAPERS: ExamPaperSeed[] = [PAPER];
