import type { ExamPaperSeed } from "../types";

const TUTORIAL_PAPER: ExamPaperSeed = {
  course: "COMP5348",
  week: 4,
  paperNumber: 1,
  title: "Week 4 Tutorial Practice Paper",
  topics: "gRPC fundamentals (client/server roles, Protobuf service/message definitions, generated stub/skeleton code) applied to a three-node distributed-transaction system (Central Bank, Bank 1, Bank 2) simulating Two-Phase Commit; bank.proto's Prepare/Commit RPCs and the incomplete Rollback RPC exercise; CentralBankController/CentralBankService's prepare-then-commit-or-rollback orchestration; BankRPCService's prepare()/commit() logic (signed TransactionRecord amounts, balance-sufficiency checks) and its unfinished rollback() TODO; the tutorial's own Success/Failure 2PC sequence diagrams and Saga/compensation diagram; continuity with Week 3's stub/skeleton concepts now realised as generated gRPC classes",
  sourceFiles: [
    "tutorial/COMP5348_Tutorial 4 Slides.pdf",
    "tutorial/COMP5348_Tutorial 4.pdf",
    "tutorial/tutorial-4-student/src/main/proto/bank.proto",
    "tutorial/tutorial-4-student/src/main/java/com/comp5348/centralbank/controller/CentralBankController.java",
    "tutorial/tutorial-4-student/src/main/java/com/comp5348/centralbank/service/CentralBankService.java",
    "tutorial/tutorial-4-student/src/main/java/com/comp5348/centralbank/model/Transaction.java",
    "tutorial/tutorial-4-student/src/main/java/com/comp5348/centralbank/model/TransactionStatus.java",
    "tutorial/tutorial-4-student/src/main/java/com/comp5348/centralbank/repository/TransactionRepository.java",
    "tutorial/tutorial-4-student/src/main/java/com/comp5348/bank/rpc/BankRPCService.java",
    "tutorial/tutorial-4-student/src/main/java/com/comp5348/bank/model/Account.java",
    "tutorial/tutorial-4-student/src/main/java/com/comp5348/bank/model/TransactionRecord.java",
    "tutorial/tutorial-4-student/src/main/java/com/comp5348/bank/model/TransactionStatus.java",
    "tutorial/tutorial-4-student/src/main/java/com/comp5348/bank/repository/AccountRepository.java",
    "tutorial/tutorial-4-student/src/main/java/com/comp5348/bank/repository/TransactionRecordRepository.java",
    "tutorial/tutorial-4-student/src/main/java/com/comp5348/bank1/Bank1Application.java",
  ],
  questions: [
    {
      type: "mcq",
      prompt: "Per the tutorial's 'What is the gRPC?' slide, what is gRPC?",
      options: [
        "A REST-only framework restricted to JSON payloads over HTTP/1.1",
        "A database replication protocol for keeping two SQL databases in sync",
        "An open-source RPC framework developed by Google for making remote procedure calls between distributed systems, using Protocol Buffers and offering cross-platform/language-agnostic code generation",
        "A front-end UI framework for building admin dashboards",
      ],
      correctIndex: 2,
      modelAnswer: "The slide defines gRPC as 'an open-source framework developed by Google for making remote procedure calls (RPCs) between distributed systems,' listing cross-platform/language-agnostic support, efficient communication, Protocol Buffers, load balancing/authentication/security, and code generation as its key features.",
    },
    {
      type: "mcq",
      prompt: "Which of the following is NOT one of the key features of gRPC listed on the tutorial's 'What is the gRPC?' slide?",
      options: [
        "Efficient communication",
        "Protocol Buffers (Protobuf)",
        "A built-in graphical dashboard for monitoring every registered service",
        "Code Generation",
      ],
      correctIndex: 2,
      modelAnswer: "The slide's listed key features are: Cross-Platform and Language-Agnostic, Efficient Communication, Protocol Buffers (Protobuf), Load Balancing/Authentication/Security, and Code Generation — no built-in monitoring dashboard is mentioned.",
    },
    {
      type: "mcq",
      prompt: "Per the tutorial's 'How gRPC Works' slide, what is the client's role, and why doesn't it implement the service's functions itself?",
      options: [
        "The client requests services from the server by making remote procedure calls to the server's functions; its responsibility is to call those functions, not to define how they work — that's the server's job",
        "The client and server both implement identical copies of every function so either side can execute the business logic",
        "The client only defines the .proto file; the server has no visibility into the service contract at all",
        "The client listens for incoming requests and dispatches them to whichever function name matches, exactly like the server",
      ],
      correctIndex: 0,
      modelAnswer: "The slide states the server 'defines the services it offers by implementing functions... These functions contain the actual business logic,' while the client's role is only 'to request services from the server... The client does not need to implement these functions because its primary responsibility is to call the functions implemented by the server, not to define how these functions work.'",
    },
    {
      type: "mcq",
      prompt: "In CentralBankService.prepareTransaction, bank1Stub.prepare(...) is built with .setAction(REDUCE_BALANCE) for the 'from' account, while bank2Stub.prepare(...) is built with .setAction(ADD_BALANCE) for the 'to' account. Why the different Action values for the two calls?",
      options: [
        "Because bank2Stub always uses a different Action enum than bank1Stub regardless of which side of a transfer it plays",
        "Because REDUCE_BALANCE/ADD_BALANCE are chosen at random per request to balance load across the two banks",
        "Because ADD_BALANCE is only valid on newly-created accounts, and Bank 2's account happens to be new in this exercise",
        "A transfer debits the source account and credits the destination account, so the 'from' account's prepare request must reduce its balance while the 'to' account's prepare request must add to its balance",
      ],
      correctIndex: 3,
      modelAnswer: "prepareTransaction is called with (from, to, amount): the from-account's request uses REDUCE_BALANCE (it's the debited side) and the to-account's request uses ADD_BALANCE (it's the credited side) — matching bank.proto's PrepareRequest.Action enum, which exists precisely to tell each bank which direction to apply the pending change in.",
    },
    {
      type: "mcq",
      prompt: "CentralBankService declares `BankServiceGrpc.BankServiceFutureStub bank1Stub`, and CentralBankController calls methods on it (e.g. bank1Stub.prepare(...)) as if they were ordinary local method calls. Using Week 3's stub/skeleton terminology, what role does bank1Stub play?",
      options: [
        "The client-side stub — it represents Bank 1's remote BankRPCService locally, and marshals each call (prepare/commit/createAccount) into a gRPC request sent over the network, matching Week 3's description of a stub taking arguments and sending a message to the server",
        "The server-side skeleton — it unmarshals incoming requests and dispatches them to Bank 1's business logic",
        "A database connection pool shared between Bank 1 and Bank 2",
        "The transaction manager that coordinates the 2PC protocol",
      ],
      correctIndex: 0,
      modelAnswer: "bank1Stub is exactly Week 3's client-side stub: CentralBankService calls prepare()/commit()/createAccount() on it as if Bank 1's service were local, but the stub actually marshals the call and its arguments into a gRPC request and sends it across the network to Bank 1 — the server-side counterpart (unmarshalling and dispatching) is BankRPCService, which plays the skeleton role instead.",
    },
    {
      type: "mcq",
      promptDiagram:
        "flowchart TB\n    CB[\"&lt;&lt;device&gt;&gt; Central Bank Server\\nCentral Bank Application\"]\n    B1[\"&lt;&lt;device&gt;&gt; Bank 1 Server\\nBank 1 Application\"]\n    B2[\"&lt;&lt;device&gt;&gt; Bank 2 Server\\nBank 2 Application\"]\n    CB -- \"gRPC: 8081\" --> B1\n    CB -- \"gRPC: 8082\" --> B2",
      prompt: "Per the tutorial's deployment diagram (reproduced above), which port does the Central Bank Application use to reach Bank 2's Application?",
      options: ["8080", "8081", "8082", "8083"],
      correctIndex: 2,
      modelAnswer: "The diagram labels the Central Bank Server's connection to Bank 1 Server as 'gRPC: 8081' and its connection to Bank 2 Server as 'gRPC: 8082' — matching @GrpcClient(\"bank2\")'s configured target port in the tutorial's properties files.",
    },
    {
      type: "mcq",
      prompt: "The `/transaction` endpoint hard-codes account IDs \"1\"/\"2\" and always calls createTwoAccounts(from, to, 100) before every transfer. If the endpoint is invoked a second time, after the first transfer already moved $50 out of account \"1\" and into account \"2\", what happens to the account balances on this second call?",
      options: [
        "createAccount silently resets both accounts back to a balance of 100 before the second transfer runs",
        "The second call throws an unhandled exception because the account IDs are not unique across calls",
        "createAccount deletes the prior TransactionRecord history so the second transfer starts from a clean slate",
        "createAccount detects each account already exists (via accountRepository.existsById) and returns a status of 'Account already exists' without resetting the balance, so the second transfer proceeds against whatever balance each account currently holds — not a fresh $100",
      ],
      correctIndex: 3,
      modelAnswer: "BankRPCService.createAccount checks `accountRepository.existsById(request.getAccountId())` first and, if true, immediately responds with 'Account already exists' and returns — it never touches the existing Account row's balance. createTwoAccounts's own comment ('Ignore response: continue if the account already exists') confirms this is treated as a no-op, so the second transfer's prepare/commit steps act on the balance left over from the first transfer.",
    },
    {
      type: "mcq",
      prompt: "In CentralBankController.initiateTransaction, `transaction.setStatus(COMMITTED)` runs unconditionally right after commitTransaction(...) returns — before the code branches on commitSuccess to set SUCCESS or call rollbackTransaction and set FAILED. What is the practical effect of this ordering on the transaction's final persisted status?",
      options: [
        "None on the final value — COMMITTED is immediately overwritten by whichever of SUCCESS or FAILED the commitSuccess branch decides, since transactionRepository.save(transaction) only runs once, after the branch, with whatever status field is set at that point",
        "The transaction can never be marked FAILED, because COMMITTED always takes priority once set",
        "It causes a compile error, since COMMITTED is not declared in centralbank's TransactionStatus enum",
        "It prevents commitTransaction from ever being called a second time for the same transaction ID",
      ],
      correctIndex: 0,
      modelAnswer: "TransactionStatus.COMMITTED is set as an intermediate value, then immediately replaced by SUCCESS (if commitSuccess) or FAILED (via the else branch, after rollbackTransaction) before the single `transactionRepository.save(transaction)` call at the end of the method — so only the last-assigned status is ever actually persisted, regardless of the momentary COMMITTED assignment in between.",
    },
    {
      type: "mcq",
      prompt: "In BankRPCService.prepare, walk through the REDUCE_BALANCE branch: `if (request.getAction() == REDUCE_BALANCE && acc.getBalance() >= request.getMoney())`. What happens if the account's balance is less than the requested amount?",
      options: [
        "An unchecked exception propagates out of the gRPC call, crashing the server thread",
        "The condition's AND fails, so control falls through to the final `else` branch, setting the TransactionRecord's status to FAILURE and returning PrepareResponse{success=false} — correctly refusing to prepare an over-withdrawal",
        "It silently proceeds into the ADD_BALANCE branch instead, since REDUCE_BALANCE failed",
        "The account's balance is set to a negative number and the prepare still reports success=true",
      ],
      correctIndex: 1,
      modelAnswer: "When the AND condition is false (insufficient balance), none of the first two `if`/`else if` branches match, so execution reaches the trailing `else { transactionRecord.setStatus(TransactionStatus.FAILURE); }` — the method then saves that record and returns success=false, which is exactly the balance-sufficiency check 2PC's prepare phase is meant to perform before any participant commits to anything.",
    },
    {
      type: "mcq",
      prompt: "Unlike REDUCE_BALANCE, the ADD_BALANCE branch in BankRPCService.prepare sets the TransactionRecord to PENDING unconditionally, with no balance check at all. Why doesn't crediting an account need the same kind of precondition check that debiting it does?",
      options: [
        "It's a bug — ADD_BALANCE should also verify `acc.getBalance() >= request.getMoney()` before proceeding",
        "Adding money to an account has no lower bound that a request could violate the way a withdrawal can push a balance negative — there's nothing analogous to insufficient balance to check for a credit",
        "Because ADD_BALANCE requests are validated earlier, inside CentralBankService, before the gRPC call is even made",
        "Because the account lookup step (`accountRepository.findById`) already guarantees the account has enough balance to receive money",
      ],
      correctIndex: 1,
      modelAnswer: "A withdrawal (REDUCE_BALANCE) can be invalid if it would drive the balance negative, so prepare() checks `acc.getBalance() >= request.getMoney()` before promising to commit it. A deposit (ADD_BALANCE) has no equivalent failure condition on the receiving account's current balance — there's no upper bound being enforced — so the branch can unconditionally mark it PENDING once the account itself is found to exist.",
    },
    {
      type: "mcq",
      prompt: "BankRPCService.prepare stores `transactionRecord.setAmount(-request.getMoney())` for REDUCE_BALANCE but `setAmount(request.getMoney())` (positive) for ADD_BALANCE, and commit() later does `acc.setBalance(acc.getBalance() + transactionRecord.getAmount())`. Why store the amount pre-signed rather than storing the raw request.getMoney() alongside the Action?",
      options: [
        "So that CentralBankService can read the sign directly over gRPC without deserialising the Action enum",
        "Signed doubles serialize more compactly over gRPC's wire format than unsigned ones",
        "It has no real purpose — the sign could be dropped without changing any behaviour",
        "So that commit() can apply the exact same '+=' arithmetic to the account balance for both a debit and a credit, without needing to re-inspect which Action the original prepare request used",
      ],
      correctIndex: 3,
      modelAnswer: "Pre-signing the stored amount lets commit() stay simple and uniform: `acc.getBalance() + transactionRecord.getAmount()` correctly decreases the balance for a debit (negative amount) and increases it for a credit (positive amount) using one line of arithmetic, without commit() needing to know or re-check whether the original request was ADD_BALANCE or REDUCE_BALANCE.",
    },
    {
      type: "mcq",
      prompt: "BankRPCService.rollback() is currently `public void rollback() { ... }` with `//@Override TODO: uncomment this` commented out above it, and bank.proto has no `rpc Rollback` defined yet (only a `// TODO: define gRPC rollback service` comment). What must happen before `@Override` can correctly be restored on this method?",
      options: [
        "Only the @GrpcService annotation needs to be added above the class declaration",
        "bank.proto's Rollback RPC and its RollbackRequest/RollbackResponse messages must be defined, and the project rebuilt to regenerate BankServiceImplBase with a matching rollback(RollbackRequest, StreamObserver&lt;RollbackResponse&gt;) method — the current no-arg rollback() doesn't override anything in the generated base class",
        "Nothing further is needed — @Override can be restored immediately since the method name already matches",
        "The class needs to stop extending BankServiceGrpc.BankServiceImplBase entirely",
      ],
      correctIndex: 1,
      modelAnswer: "@Override only compiles if the method actually overrides a method inherited from BankServiceGrpc.BankServiceImplBase, and that generated base class only gets a rollback(...) method once bank.proto declares an `rpc Rollback` with matching request/response messages and the project is rebuilt — the current parameterless rollback() has no such counterpart to override yet.",
    },
    {
      type: "mcq",
      prompt: "The unfinished rollback() branches on `transactionRecord.getStatus()` being FAILURE, PENDING, or SUCCESS. Given commit()'s logic (it applies transactionRecord.getAmount() to the account balance only when it sets status to SUCCESS), which status should trigger reversing an already-applied balance change, and which requires no account change at all?",
      options: [
        "PENDING requires reversing a balance change; SUCCESS requires nothing",
        "SUCCESS requires reversing the balance change (apply the negated amount back to the account) since that's the only status commit() ever reaches after actually mutating the balance; FAILURE requires no account change, since prepare() never touched the balance for a failed record",
        "All three statuses require identically reversing the balance change",
        "FAILURE requires reversing a balance change; SUCCESS requires nothing",
      ],
      correctIndex: 1,
      modelAnswer: "Tracing commit(): a TransactionRecord only ever has its account balance actually modified when commit() sets its status to SUCCESS. FAILURE means prepare() itself already rejected the change (e.g. insufficient balance or missing account) without touching the balance, so rolling it back requires no account mutation — only SUCCESS represents a real, already-applied change that a rollback must undo.",
    },
    {
      type: "mcq",
      prompt: "For a TransactionRecord still in PENDING status (prepared, but commit was never reached because the other bank's prepare or commit failed), what does a correct rollback need to do?",
      options: [
        "Nothing to the account balance, since commit() — the only place that ever mutates a balance — was never reached for a PENDING record; rollback only needs to update the record itself (e.g. mark it abandoned/failed) so it can't later be committed by a stray retry",
        "Reverse a balance change that commit() already applied",
        "Delete the associated Account row entirely from the database",
        "Re-invoke prepare() a second time to double-check the balance",
      ],
      correctIndex: 0,
      modelAnswer: "PENDING means prepare() succeeded and locked in an intended change, but commit() — the only method that actually mutates acc.getBalance() — was never called for this record. Rolling it back is therefore only a bookkeeping change on the TransactionRecord itself, not an account balance reversal, since no balance mutation ever happened to undo.",
    },
    {
      type: "mcq",
      promptDiagram:
        "sequenceDiagram\n    participant Client\n    participant CentralBank\n    participant Bank1\n    participant Bank2\n    Client->>CentralBank: Request\n    CentralBank->>Bank1: Prepare\n    CentralBank->>Bank2: Prepare\n    Bank1-->>CentralBank: Prepared\n    Bank2-->>CentralBank: Prepared\n    CentralBank->>Bank1: Commit\n    CentralBank->>Bank2: Commit\n    Bank1-->>CentralBank: Done\n    Bank2--xCentralBank: Fatal (crash, no Done)\n    CentralBank-->>Client: Response",
      prompt: "The diagram above reproduces the tutorial's 'Failure' scenario: Bank1 commits successfully, but Bank2 crashes ('Fatal') during Commit and never returns Done. Given that CentralBankService.rollbackTransaction is currently an empty method body, what does the code actually do in this exact scenario?",
      options: [
        "It automatically retries Bank2's commit call until Bank2 comes back online",
        "commitTransaction returns false (since `bank1Response.getSuccess() && bank2Response.getSuccess()` is false), CentralBankController calls rollbackTransaction — which currently does nothing — and marks the transaction FAILED, leaving Bank1's already-committed balance change unreversed",
        "Spring automatically rolls back Bank1's already-committed change via a shared distributed transaction",
        "The whole request throws an unhandled exception and no transaction status is ever persisted",
      ],
      correctIndex: 1,
      modelAnswer: "commitTransaction's boolean AND means any single bank's commit failure makes the whole method return false. CentralBankController then calls centralBankService.rollbackTransaction(transaction.getId()) — but that method body is currently empty (a TODO) — and unconditionally sets the transaction's status to FAILED regardless of what rollback actually did. Since Bank1's commit already succeeded and rollback does nothing, Bank1's account balance change is left in place even though the transaction is marked FAILED — exactly the inconsistency the tutorial's rollback exercise exists to fix.",
    },
    {
      type: "mcq",
      prompt: "Per the tutorial's own 'Distributed Transaction – Saga' slide (shown immediately after its 2PC slide), what happens in the diagram when transaction T3 fails partway through the sequence T1→T2→T3→...→Tn?",
      options: [
        "The whole system halts and requires manual intervention, exactly like 2PC's blocked-coordinator problem",
        "Compensating transactions C2 and then C1 run — in that reverse order — to semantically undo T2 and T1, which had already completed before T3 failed",
        "T3 is retried indefinitely by the same participant until it eventually succeeds",
        "Nothing — the Saga diagram shows no failure-handling mechanism at all, unlike the 2PC diagram beside it",
      ],
      correctIndex: 1,
      modelAnswer: "The Saga diagram shows Normal transactions T1→T2→T3 with T3 marked FAILS, and Compensating transactions C1/C2/C3 arranged so that when T3 fails, C2 and C1 are triggered in reverse order of the original T1→T2 execution — undoing what already completed, rather than 2PC's approach of never letting anything commit until every participant has voted yes.",
    },
    {
      type: "mcq",
      promptDiagram:
        "flowchart LR\n    Client[Client] --> Stub[Stub]\n    Stub <--> Network[Network]\n    Network <--> Skeleton[Skeleton]\n    Skeleton --> Server[Server]",
      prompt: "Per the tutorial's Client–Stub–Network–Skeleton–Server diagram (above) and the tutorial code, which two classes correspond to the 'Stub' and 'Skeleton' boxes respectively?",
      options: [
        "CentralBankController is the Stub; CentralBankService is the Skeleton",
        "Account is the Stub; TransactionRecord is the Skeleton",
        "The same generated class plays both roles — gRPC does not distinguish a stub from a skeleton",
        "BankServiceGrpc.BankServiceFutureStub (used as bank1Stub/bank2Stub in CentralBankService) is the Stub; BankServiceGrpc.BankServiceImplBase (extended by BankRPCService) is the Skeleton",
      ],
      correctIndex: 3,
      modelAnswer: "BankServiceFutureStub is exactly the generated client-side proxy the diagram labels Stub — CentralBankService calls prepare()/commit()/createAccount() on it as if local. BankServiceImplBase is the generated server-side base class BankRPCService extends and overrides — the Skeleton that unmarshals incoming requests and dispatches to the actual business logic.",
    },
    {
      type: "mcq",
      prompt: "createTwoAccounts calls bank1Stub.createAccount(...) and bank2Stub.createAccount(...), storing both results as `Future<?>`, and only then calls `.get()` on each in sequence. Compared to blocking on bank1's call before even starting bank2's call, what does using Future gain here?",
      options: [
        "Both createAccount RPCs are dispatched to Bank 1 and Bank 2 before either .get() blocks, so the two network round trips overlap in time rather than happening one strictly after the other",
        "Future guarantees the two account-creation calls are wrapped in one atomic distributed transaction",
        "It has no timing benefit over calling and blocking on bank1Stub.createAccount(...).get() before starting bank2Stub.createAccount(...)",
        "Future defers making either network call at all until both .get() methods have been invoked",
      ],
      correctIndex: 0,
      modelAnswer: "Both createAccount(...) calls return immediately with a Future once dispatched — the actual gRPC requests to Bank 1 and Bank 2 are already in flight concurrently by the time the code reaches the two .get() calls — so the two round trips overlap instead of the second one only starting after the first one fully completes, as sequential blocking calls would force.",
    },
    {
      type: "mcq",
      prompt: "createTwoAccounts's comment says 'Ignore response: continue if the account already exists.' Given CreateAccountResponse's `status` field can be either 'Account created successfully' or 'Account already exists', why doesn't the calling code branch on that string at all?",
      options: [
        "It throws an exception whenever the status string equals 'Account already exists'",
        "It automatically retries account creation under a freshly-generated account ID if the account already exists",
        "createAccount is treated as an idempotent operation from the caller's point of view — both possible outcomes ('created' and 'already exists') mean the account is now guaranteed to exist, so the caller only needs to wait for completion via .get(), not inspect what happened",
        "It logs every response except 'Account already exists', which is silently discarded before logging",
      ],
      correctIndex: 2,
      modelAnswer: "Both possible status strings represent success from createTwoAccounts's perspective — either the account was just created, or it was already there from a previous call — so there's nothing to branch on; `.get()` is called purely to wait for the RPC to complete before the transfer proceeds, treating createAccount as safely repeatable.",
    },
    {
      type: "short",
      prompt: "Trace what happens, step by step, the very first time POST /transaction is called against fresh (empty) databases: name every gRPC call made between Central Bank, Bank 1, and Bank 2, and explain what determines whether the transaction ends up SUCCESS or FAILED.",
      modelAnswer: "First, centralBankService.createTwoAccounts(\"1\", \"2\", 100) fires bank1Stub.createAccount and bank2Stub.createAccount concurrently, each creating a fresh account with balance 100 (both succeed since the databases are empty). A Transaction row is saved with status OPEN. Then prepareTransaction(transactionId, \"1\", \"2\", 50) calls bank1Stub.prepare with REDUCE_BALANCE (debiting account \"1\") and bank2Stub.prepare with ADD_BALANCE (crediting account \"2\"); each bank's BankRPCService.prepare saves a signed TransactionRecord and returns success=true (account \"1\" has balance 100 ≥ 50, and ADD_BALANCE has no balance precondition). Since both prepares succeeded, commitTransaction(transactionId) calls bank1Stub.commit and bank2Stub.commit; each BankRPCService.commit looks up the TransactionRecord by transactionId, applies its signed amount to the account balance, and marks it SUCCESS. Since both commits report success, CentralBankController sets the Transaction's final status to SUCCESS. If either prepare or either commit had instead returned false, the code would call rollbackTransaction (currently an empty TODO) and set the Transaction's status to FAILED instead — regardless of whether that rollback actually undid anything on the bank side.",
    },
    {
      type: "short",
      prompt: "Explain why prepareTransaction's REDUCE_BALANCE branch checks `acc.getBalance() >= request.getMoney()` inside prepare(), rather than deferring that check to commit(). What could go wrong for the whole transaction if this balance check were moved to commit() instead?",
      modelAnswer: "2PC's whole point is that every participant votes before any participant makes an irreversible change: prepare() is where Bank 1 gets to check preconditions (like sufficient balance) and vote 'no' by returning success=false, letting the coordinator (CentralBankService) abort the transaction for every participant before anything is actually committed. If the balance check were deferred to commit() instead, Bank 1 could vote 'yes' in prepare() (locking in its intent) even though it can't actually honour it, and the coordinator — seeing both prepares succeed — would tell both banks to commit. Bank 2 might successfully credit account \"2\", while Bank 1's commit then discovers insufficient funds and fails, leaving the transfer half-applied: money added to account \"2\" that was never actually removed from account \"1\" — exactly the atomicity violation 2PC's Phase 1 vote is designed to prevent.",
    },
    {
      type: "scenario",
      prompt: "A colleague on your team proposes simplifying this tutorial's system by removing the Prepare phase entirely and just calling commit directly on both banks, arguing 'commit already checks whether the account and TransactionRecord exist, so Prepare is redundant.' Using this tutorial's own code and the 2PC concepts it implements, explain what would break.",
      modelAnswer: "Without a Prepare phase, no participant gets to check preconditions or vote before any change is attempted, and — more fundamentally — commit() in this code only works by looking up a TransactionRecord that prepare() itself created (`transactionRecordRepository.findByTransactionId(...)`), so calling commit() directly with no prior prepare() would find no record and immediately fail for every transaction. Even setting that aside conceptually: Prepare is where Bank 1 checks `acc.getBalance() >= request.getMoney()` and can refuse an over-withdrawal before anything is committed anywhere. If that check were skipped and commit were called directly on both banks, Bank 2 could successfully credit its account while Bank 1's commit discovers (too late) that the account doesn't have enough balance and must fail — leaving the transfer half-applied, money credited to Bank 2 that was never actually debited from Bank 1. This is exactly the lecture's own ATM/dispense-cash failure pattern: skipping the round where every participant promises readiness before any of them is told to actually finalize breaks atomicity across the distributed transaction.",
    },
  ],
};

const LECTURE_PAPER: ExamPaperSeed = {
  course: "COMP5348",
  week: 4,
  paperNumber: 2,
  title: "Week 4 Lecture Practice Paper",
  topics: "History of transaction processing (1960s SABRE, 1970s mainframe banking, 1980s Unix TP monitors, modern Spring Boot, future web-services/eventual consistency); recall of ACID and the transaction concept from Week 2; distributed transactions and the Two-Phase Commit (2PC) protocol (Phase 1 prepare/vote, Phase 2 commit/abort, coordinator/participant state diagram, XA TM/RM/TC roles, transaction trees with multiple TMs); resources beyond databases (ATM/printer dispense-cash failure modes); transaction API models (client-side explicit vs server-side declarative); stateless transactions vs sessions (continuity with Week 3's stateful/stateless EJB distinction); request integrity, idempotency, nested transactions vs Just-In-Time ('requires'/'requires new'); impact of transactions on ACID-in-practice, lock impacts (continuity with Week 2's locking/deadlock material), 2PC's cost as an 'unavailability protocol'; extended transaction models — Sagas & compensation, compensators, and Business Transaction standards (BizTalk/BPEL4WS/WS-BA)",
  sourceFiles: ["lecture/COMP5348_W4.pdf", "lecture/Week 04 - Enterprise-s1-low.transcript.md"],
  questions: [
    {
      type: "mcq",
      prompt: "Per the lecture's History slide, which pairing correctly matches an era of transaction system to its example?",
      options: [
        "Airline reservations in the 1960s (SABRE, 300,000 devices) came before banking/government systems on large mainframes (CICS, COMS) in the 1970s",
        "CICS and COMS were 1960s airline reservation systems, predating SABRE by a decade",
        "Banking/government mainframe systems (1970s) predate the earliest transaction systems, which only began with SABRE in the 1980s",
        "SABRE and CICS were both introduced in the same decade, the 1980s, alongside Unix TP monitors",
      ],
      correctIndex: 0,
      modelAnswer: "The History slide lists 'Earliest transaction systems' as airline reservations in the 1960s (SABRE, 300,000 devices), followed by banking, government and other very large systems in the 1970s (CICS, COMS, and others) on large, expensive mainframe computers.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Middle Ages' slide, which pairing correctly groups a 1980s-era technology with its category?",
      options: [
        "Oracle and Sybase are listed as Teleprocessing (TP) monitors, while Tuxedo and Encina are listed as databases",
        "Tuxedo, TopEnd, and Encina are listed as Teleprocessing (TP) monitors, while Oracle, Sybase, and Informix are listed as databases — both coexisting with mainframe TP as mainstream commercial computing",
        "Tuxedo and Oracle are both classified as Object Transaction Monitors with no distinction drawn between them",
        "The slide draws no distinction between TP monitors and databases in the 1980s",
      ],
      correctIndex: 1,
      modelAnswer: "The 'Middle Ages' slide separates UNIX-era 1980s technologies into two groups: Teleprocessing (TP) monitors/Object Transaction Monitors — Tuxedo, TopEnd, Encina — and Databases — Oracle, Sybase, Informix — describing this as mainstream commercial computing coexisting with mainframe TP.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Modern History' slide, which of the following is NOT one of the challenges it lists for supporting Internet applications?",
      options: [
        "Scale",
        "Lack of full trust",
        "Semi-connected",
        "Guaranteed zero-latency networking",
      ],
      correctIndex: 3,
      modelAnswer: "The slide's listed challenges are scale, lack of full trust, semi-connected, and variable latency — the opposite of 'guaranteed zero-latency networking', which is never claimed and would in fact match one of the classic fallacies of distributed computing (latency is zero) rather than a real capability.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Future' slide, how does it distinguish standard, open transaction protocols for Web Services transactions?",
      options: [
        "It only recognises tightly-coupled (ACID) protocols; loosely-coupled long-running protocols are dismissed as impractical",
        "It distinguishes tightly-coupled (ACID) protocols from loosely-coupled (long-running) protocols, and separately raises the question of what level of consistency is actually needed, up to 'living with partial consistency or accepting eventual consistency'",
        "It treats ACID and eventual consistency as identical concepts under a single 'Web Services transaction' umbrella",
        "It states that no transactional support of any kind exists for Web Services",
      ],
      correctIndex: 1,
      modelAnswer: "The slide lists 'Standard, open transaction protocols' split into 'Tightly-coupled (ACID)' and 'Loosely-coupled (long-running)', and separately raises 'No transactions at all or transactional pieces? What level of consistency is actually needed? Living with partial consistency or accepting eventual consistency.'",
    },
    {
      type: "mcq",
      prompt: "The lecture's 'Recall: ACID' slide restates Week 2's ACID test (Atomic, Consistent, Isolated, Durable) before introducing distributed transactions. Using Week 2's fuller definition, what does the 'I' (Isolated) property guarantee, and why is restating it here — right before 2PC — significant?",
      options: [
        "Isolated means data is never lost even after a crash; it's restated here because 2PC is fundamentally about durability, not isolation",
        "Isolated means every transaction behaves as if it runs alone, with concurrent execution hidden; it's restated here because 2PC's locking (held across the whole prepare/commit round trip) is precisely how each resource manager still provides that same guarantee once the transaction spans multiple systems",
        "Isolated means a transaction can be split across multiple databases without any coordination; it's restated here because that's exactly what 2PC eliminates",
        "Isolated has no connection to 2PC at all — the recall slide only exists to remind students of Atomicity",
      ],
      correctIndex: 1,
      modelAnswer: "Week 2 defined Isolated as: every transaction thinks it is running all alone, with concurrency's reality hidden. The lecture recalls the full ACID test immediately before introducing 2PC because 2PC's locks-in-each-RM mechanism (covered later in 'ACID in Practice') is exactly how that same isolation guarantee is preserved once a single transaction's operations are spread across multiple, independently-failing systems rather than one local database.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Recall: ACID' slide, what two properties does it say characterise the context ACID is 'mostly used for'?",
      options: [
        "Short duration and trusted participants",
        "Long duration and untrusted participants",
        "High latency and geographically dispersed participants",
        "Read-only operations and anonymous participants",
      ],
      correctIndex: 0,
      modelAnswer: "The slide states ACID is 'mostly used for local transactions' characterised by 'short duration' and 'trusted participants' — a framing the lecture immediately contrasts with distributed transactions across multiple systems.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Distributed Transactions' slide, what is added when a transaction updates data across multiple geographically dispersed systems, compared to a local transaction?",
      options: [
        "Full ACID properties are relaxed to only Atomicity and Durability once multiple systems are involved",
        "Multiple application servers and multiple database servers all work together, with a single transaction able to use all of these resources while full ACID properties are still maintained",
        "Isolation is dropped entirely, since it cannot be guaranteed across a network",
        "Consistency becomes the responsibility of each individual database server acting independently, with no coordination needed",
      ],
      correctIndex: 1,
      modelAnswer: "The slide states: 'Now do all this across multiple computer systems... Geographically dispersed, Multiple application servers, Multiple database servers, All working together... A single transaction can use all of these resources, Full ACID properties still maintained' — the challenge 2PC exists to solve is maintaining that same full ACID guarantee once it spans several independently-failing systems.",
    },
    {
      type: "mcq",
      prompt: "In the lecture's 'Without Distributed Transactions?' diagram, a withdraw-$100/deposit-$100 request is sent to Sydney and Melbourne separately; Sydney withdraws and commits successfully, but Melbourne's system fails before depositing. What does this diagram illustrate?",
      options: [
        "Without a coordinating protocol like 2PC, one side of a distributed update can succeed while the other fails, leaving updates lost and data inconsistent across the two systems",
        "That withdrawals should always be processed after deposits to avoid this exact failure",
        "That Sydney and Melbourne should never be allowed to communicate directly with each other",
        "That the failure is caused by using two different currencies between Sydney and Melbourne",
      ],
      correctIndex: 0,
      modelAnswer: "The slide's own caption states: 'Updates can be lost and data can become inconsistent when systems fail and recover' — the diagram shows exactly that: Sydney's withdrawal commits while Melbourne's deposit never happens because its system fails, leaving the $100 withdrawn but never redeposited, motivating 2PC as the coordination mechanism that prevents this partial outcome.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Phase 1' slide, what does the transaction manager (TM) ask participating resource managers (RMs) to do, and what is explicitly true about commits at this point?",
      options: [
        "The TM asks each RM to commit immediately, with no opportunity to vote no",
        "The TM asks only one designated RM to prepare, while the others wait passively for Phase 2",
        "The TM asks each RM to prepare to commit — RMs save their intended changes and vote yes/no, but 'no RM actually commits yet' regardless of how they vote",
        "RMs commit their changes as soon as they vote 'yes', without waiting for Phase 2",
      ],
      correctIndex: 2,
      modelAnswer: "Phase 1: 'TM asks all participating RMs to prepare to commit. RMs save their intended changes and then say \"yes\" if they can promise to commit. Any RM can say \"no\". No RM actually commits yet!' — the actual commit only happens in Phase 2, and only if every RM voted yes in Phase 1.",
    },
    {
      type: "mcq",
      promptDiagram:
        "flowchart LR\n    subgraph Successful transaction\n    direction LR\n    C1[Coordinator] -->|Prepare| P1[Participant]\n    P1 -->|Prepared| C1\n    C1 -->|Commit| P1\n    P1 -->|Done| C1\n    end\n    subgraph Failing transaction\n    direction LR\n    C2[Coordinator] -->|Prepare| P2[Participant]\n    P2 -->|No| C2\n    C2 -->|Abort| P2\n    P2 -->|Done| C2\n    end",
      prompt: "In the lecture's Two Phase Commit diagram (above), what replaces 'Prepared' in the failing transaction's message sequence, and what does the coordinator send back in response?",
      options: [
        "The participant sends no message at all, and the coordinator times out and sends 'Commit' anyway",
        "The participant replies 'Prepared' exactly as in the successful case, but the coordinator sends 'Rollback' instead of 'Commit'",
        "The participant replies 'No' instead of 'Prepared', and the coordinator responds with 'Abort' instead of 'Commit'",
        "The participant replies 'Abort', and the coordinator responds with 'Prepared'",
      ],
      correctIndex: 2,
      modelAnswer: "The diagram's failing-transaction path swaps 'Prepared' for 'No' as the participant's Phase 1 vote, which drives the coordinator to send 'Abort' instead of 'Commit' in Phase 2 — both paths still end with the participant replying 'Done' either way, matching Phase 2's description that the TM 'always knows the state of the transaction' regardless of outcome.",
    },
    {
      type: "mcq",
      promptDiagram:
        "flowchart TB\n    subgraph Coordinator\n    CI[INITIAL] -->|prepare / log begin_commit| CW[WAIT]\n    CW -->|all vote_commit / log commit| CC[COMMIT]\n    CW -->|any vote_abort / log abort| CA[ABORT]\n    end\n    subgraph Participant\n    PI[INITIAL] -->|Ready? Yes / log ready| PR[READY]\n    PI -->|Ready? No / log abort| PA[ABORT]\n    PR -->|global_commit / log commit| PC[COMMIT]\n    PR -->|global_abort / log abort| PA\n    end",
      prompt: "Per the lecture's 2PC Protocol State Diagram (simplified above), what state does the coordinator sit in while waiting for every participant's vote, and what does a participant log just before replying with a 'yes' vote?",
      options: [
        "The coordinator sits in READY; the participant logs 'begin_commit' before voting yes",
        "The coordinator sits in ABORT by default until every vote arrives; the participant logs nothing before voting",
        "The coordinator sits in COMMIT while waiting; the participant logs 'end_of_trans' before voting yes",
        "The coordinator sits in WAIT; the participant logs 'ready' before voting yes (vote_commit)",
      ],
      correctIndex: 3,
      modelAnswer: "The state diagram shows the coordinator moving INITIAL → (log begin_commit, send prepare) → WAIT, where it stays until it receives every participant's vote_commit or any vote_abort. On the participant side, 'Ready to Commit? Yes' leads to 'log ready' before the participant enters READY and replies vote_commit — READY is the participant's own waiting state, distinct from the coordinator's WAIT.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Distributed Transactions' (multiple TMs) slide, distributed transactions can involve multiple Transaction Managers arranged in a transaction tree, with a new branch created 'when apps invoke code or access a resource on a new node.' What is passed down to a new node when it is added this way?",
      options: [
        "The full commit log of every previously-completed transaction",
        "A copy of the root TM's database credentials",
        "The transactional context, so the new node is 'enlisted' in the same overall (global) transaction rather than starting an unrelated one",
        "Nothing — new nodes are always excluded from the current transaction tree until it fully commits",
      ],
      correctIndex: 2,
      modelAnswer: "The slide states: 'New branch when apps invoke code or access a resource on a new node. Transactional context passed down to new nodes when they are enlisted.' This is how a transaction tree grows — each new TM below the root coordinates its own local RMs but remains part of the same global transaction via that passed-down context.",
    },
    {
      type: "mcq",
      prompt: "The lecture's Resources slide shows two crash scenarios for an ATM: left box crashes between 'dispense cash' and 'Commit'; right box crashes between 'Commit' and 'dispense cash'. Which outcome corresponds to which crash timing?",
      options: [
        "Crashing before Commit (cash already dispensed, then crash, so the account update never commits) means the bank loses money; crashing after Commit but before dispensing cash means the customer loses money (account already debited, no cash given)",
        "Both crash timings produce the exact same outcome — the customer always loses money regardless of when the crash occurs",
        "Crashing before Commit means the customer loses money; crashing after Commit means the bank loses money",
        "Neither crash timing has any financial consequence, since the transaction's Isolation property prevents any observable inconsistency",
      ],
      correctIndex: 0,
      modelAnswer: "The left box (update account, dispense cash, **Crash**, then Commit never lands) is captioned 'Bank loses money' — cash already left the ATM but the debit was never durably committed. The right box (update account, Commit, **Crash** before dispense cash) is captioned 'You lose money' — the account was debited and committed, but the customer never received the cash. The slide's point is that this failure exists 'regardless of whether dispense code is inside or outside of the transaction', since dispensing cash is a physical resource action a database transaction alone cannot make atomic.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's second 'Resources' slide, how did older TP systems handle non-database resources like files, printers, and terminal output within a transaction, and what does the lecture pose as the modern equivalent question?",
      options: [
        "Older TP systems ignored non-database resources entirely; the modern question is whether GPUs should participate in 2PC",
        "Older TP systems deferred the actual output (via close OS/TP linkage) until the transaction committed; the modern question is how an application achieves the same effect now — e.g. writing to a database for a background app, using transactional message queues, or transactional file systems",
        "Older TP systems always dispensed output immediately regardless of transaction outcome, with no deferral mechanism",
        "Older TP systems required every printer to have its own dedicated Transaction Manager",
      ],
      correctIndex: 1,
      modelAnswer: "The slide states older TP systems supported files/printers/terminal output/data comm messages by writing output normally while the 'OS/TP deferred actual output until transaction committed', requiring 'close linkage... between OS and TP.' It then poses this as 'now application problem?' with three candidate modern approaches: write to a database for a background app, use transactional message queues, or transactional file systems.",
    },
    {
      type: "mcq",
      prompt: "Per Week 3's stateful/stateless distinction for EJBs, and the lecture's 'Stateless Transactions vs. Sessions' slide (Stateless: server responds without needing to know prior requests, e.g. a simple web page request; Session: has state, outcome may depend on prior transactions, e.g. booking systems/shopping carts), which of Week 4's two examples is closest to Week 3's 'stateful' definition, and why?",
      options: [
        "The simple web page request, because HTTP requests always carry cookies which the lecture defines as inherently stateful",
        "Neither — Week 3's stateful/stateless distinction only applies to EJBs, not to the general concept of a session",
        "The booking system/shopping cart example, because its outcome depends on the sequence of prior requests within the same session — matching Week 3's definition of stateful code being tied to a client session rather than discarding state after each operation",
        "Both examples are equally stateful, since any server-side code retains some state between requests",
      ],
      correctIndex: 2,
      modelAnswer: "Week 3 defined stateful code as holding state between operations and being tied to a client's session, versus stateless code discarding state after each operation. The slide's Session example (booking systems, shopping carts) is exactly this: 'outcome of a transaction might depend on previous transactions', unlike the simple web page request, where 'previous requests are irrelevant' to the current response — matching Week 3's stateless definition instead.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Request Integrity' slide, why does making the 'fetch request' operation itself part of the transaction matter for recovering from a failed transaction request sitting in a queue?",
      options: [
        "It doesn't matter — queued requests are always safe regardless of whether fetching them is transactional",
        "It guarantees the request will never fail a second time, since fetching removes it from the queue permanently on the first attempt",
        "It replaces the need for reliable messaging entirely",
        "Including the fetch inside the transaction means a failure undoes the fetch too, so the request is automatically re-queued on failure rather than being silently lost — enabling easy recovery from transient application errors, so long as failure loops are avoided",
      ],
      correctIndex: 3,
      modelAnswer: "The slide states: 'Fetch request operation included as part of transaction — Undone and request re-queued on failure. Need to avoid failure loops! Easy recovery from transient application errors.' Making the fetch itself transactional means a failed attempt rolls the fetch back too, so the request reappears in the queue for a retry rather than being lost — this is called out as 'another reason for reliable messages.'",
    },
    {
      type: "mcq",
      prompt: "The lecture defines idempotency as 'repeatable operations that result in the same state change.' Why does this property matter specifically for the request-integrity mechanism described just before it (failed requests being undone and re-queued for automatic retry)?",
      options: [
        "If the operation triggered by a request isn't idempotent, an automatic retry of a request that actually already partially succeeded before failing could apply its effect twice (e.g. double-debiting an account), whereas an idempotent operation produces the same end state whether it runs once or is retried",
        "Idempotency is unrelated to retries — it only matters for read-only operations like RequestBalance",
        "Idempotency guarantees a request can never fail in the first place, making retries unnecessary",
        "Idempotency is a property of the network layer, not of the application-level operation being retried",
      ],
      correctIndex: 0,
      modelAnswer: "The request-integrity mechanism relies on safely retrying a request that may have partially executed before failing. If that request's operation isn't idempotent, retrying it risks applying its effect more than once; the lecture's definition — 'repeatable operations that result in the same state change' — is precisely the property that makes automatic re-queue-and-retry safe rather than dangerous.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Just-in-time Transactions' slide, what is the difference between a method marked with the 'requires' attribute and one marked 'requires new'?",
      options: [
        "'requires' always starts a brand-new transaction; 'requires new' always joins whatever transaction is currently active",
        "'requires' and 'requires new' are two names for the exact same behaviour, kept for backward compatibility only",
        "'requires' runs in an existing transaction if there is one, starting a new one only if there isn't; 'requires new' always starts a new, independent transaction even if already inside a transactional context — useful when a sub-operation shouldn't be backed out if its 'parent' fails",
        "'requires' only applies to read-only operations; 'requires new' only applies to write operations",
      ],
      correctIndex: 2,
      modelAnswer: "The slide states 'requires': 'Run in existing transaction if there is one, Start new transaction otherwise', versus 'requires new': 'Start a new independent transaction even if already in a transactional context... May not want to back out a \"sub\"-transaction if its \"parent\" fails' — e.g. an audit-log write that should persist even if the surrounding business transaction later aborts.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's Nested vs Just-In-Time (JIT) Transactions code comparison, the Nested Transactions box gives withdraw(src, amt) and deposit(dest, amt) their own explicit tx_start/tx_commit, nested inside transfer's own tx_start/tx_commit. What does the JIT box do differently, and why does the lecture note nested transactions are 'rarely implemented in commercial products'?",
      options: [
        "The JIT box removes all transaction boundaries entirely, running every function outside any transaction",
        "The JIT box gives withdraw and deposit two separate tx_start/tx_commit pairs each, doubling the nesting depth shown in the Nested box",
        "There is no meaningful difference between the two boxes — both achieve identical behaviour via different syntax",
        "The JIT box marks every function 'requires' instead of giving each one an explicit tx_start/tx_commit, letting withdraw and deposit join transfer's already-open transaction automatically rather than needing true nested-transaction support that most commercial transaction managers don't actually provide",
      ],
      correctIndex: 3,
      modelAnswer: "The Nested Transactions box shows true nesting — transactions started inside an already-open transaction. The JIT Transactions box instead marks all functions as 'requires' (all marked as 'requires' transaction), so withdraw and deposit simply enlist in transfer's already-open transaction rather than opening genuinely separate nested ones — the lecture's own 'Nesting Transactions?' slide states nested transactions are 'rarely implemented in commercial products', motivating JIT's declarative 'requires'/'requires new' as the practical alternative.",
    },
    {
      type: "mcq",
      prompt: "Week 2's material described using a canonical lock-acquisition order to avoid deadlock cycles between two local transactions. The lecture's 'Lock Impacts' slide raises the same locking/deadlock concern, but in the context of 2PC. What does moving from a local transaction to a 2PC-coordinated distributed one specifically add to Week 2's locking concern?",
      options: [
        "It removes the deadlock risk entirely, since 2PC's coordinator prevents any two transactions from ever requesting the same lock",
        "Locks are now held for the duration of an entire 2PC round trip across the network (the slide's own point: 'all computers wait at the same speed... waiting 10ms always takes 10ms'), rather than just a single local operation — so the same blocking and single-threading risk Week 2 described gets substantially worse, on top of the deadlock risk still being present",
        "The deadlock risk becomes purely theoretical once a transaction is distributed, since each RM only ever locks its own local resources",
        "2PC eliminates the need for locks altogether by replacing them with message queues",
      ],
      correctIndex: 1,
      modelAnswer: "Week 2 already established that locks can block other transactions and that acquiring them out of a fixed canonical order risks deadlock. The lecture's 'Lock Impacts' slide (and 'More 2PC impacts') extends this into the distributed setting: '2PC has been called an \"unavailability protocol\"' precisely because a lock taken by a participant is held across the full round trip needed for 2PC's prepare-then-commit exchange — 'commit takes a long time... at least 4 cross-network messages, from time lock taken till time commit outcome is known and lock released' — so the same blocking problem Week 2 raised locally is now stretched over real network latency, and the deadlock risk from Week 2 is still present on top of it.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Sagas & Compensation' slide, what is the defining limitation of the Saga model, and what is a 'compensator' meant to provide?",
      options: [
        "Sagas are an extended model for isolation only (not atomicity); a compensator provides encryption for data in transit between saga steps",
        "Sagas fully replace both atomicity and isolation guarantees with no limitation compared to 2PC",
        "A compensator is a lock-timeout mechanism used to detect deadlocks between saga steps",
        "Sagas are an extended model for atomicity only (not isolation); a compensator provides a semantic 'undo' for a completed operation, e.g. cancelling an order or putting goods back on the shelf",
      ],
      correctIndex: 3,
      modelAnswer: "The slide states Sagas are an 'Extended model for atomicity only' — defining a long operation as a series of smaller ACID transactions, each with a defined 'compensator': a 'semantic \"undo\" for completed operation', with the slide's own examples being 'Cancel order, put goods back on shelf.' The 'atomicity only' qualifier matters because, unlike 2PC, sagas provide no isolation guarantee.",
    },
    {
      type: "truefalse",
      prompt: "True or False: per the lecture's '2PC impacts' slide, committing via 2PC requires at least 4 cross-network messages between the time a lock is taken and the time the commit outcome is known and the lock released, and other transactions remain blocked for that entire duration — requiring trust that the coordinator will be prompt, and will abort if other participants are delaying.",
      options: ["True", "False"],
      correctIndex: 0,
      modelAnswer: "The '2PC impacts' slide states this almost verbatim: 'Commit takes a long time — At least 4 cross-network messages, from time lock taken till time commit outcome is known and lock released. Other transactions are blocked for a long time — Must trust coordinator to be prompt, and to abort if other participants are delaying.'",
    },
    {
      type: "short",
      prompt: "Using Week 2's ACID/locking material and this week's 'Lock Impacts'/'2PC impacts' slides, explain why making a transaction distributed (spanning a full 2PC prepare-then-commit round trip) makes the same lock-blocking problem Week 2 described locally so much worse — and why the lecture calls 2PC an 'unavailability protocol'.",
      modelAnswer: "Week 2 already established that pessimistic locks block other transactions from accessing the same shared data, and that deadlock is a real risk unless locks are acquired in a canonical order. Locally, a lock is typically held only for the duration of one machine's own short operation. Under 2PC, the same lock at each resource manager must instead be held from the moment it's taken in Phase 1 (prepare) all the way through to Phase 2's outcome being known and the lock released — the lecture's own count is 'at least 4 cross-network messages' round-tripping over real network latency, not a single local operation. Every other transaction wanting that same data is blocked for that entire cross-network duration, and — per 'More 2PC impacts' — if the coordinator fails at exactly the wrong moment during that window, participants can remain blocked indefinitely, unsure of the transaction's outcome, forced into a manual 'heuristic' decision later. That combination of much longer lock-hold times plus the coordinator becoming a single point of blocking failure is exactly why the lecture calls 2PC an 'unavailability protocol' rather than just a slower version of Week 2's local locking.",
    },
    {
      type: "short",
      prompt: "Using the lecture's Sagas & Compensation model and its own T1→T2→T3(FAILS)→C2→C1 diagram, explain what a compensator is, why compensators must run in reverse order of the original execution, and the specific risk the 'Compensators' slide warns about.",
      modelAnswer: "A compensator is a semantic 'undo' defined for each smaller ACID transaction making up a longer saga — e.g. cancelling an order or putting goods back on the shelf — used to logically reverse a step that already committed, since sagas provide no isolation and can't simply roll back an uncommitted change the way a single ACID transaction can. In the diagram, if T3 fails after T1 and T2 have already completed, the saga runs their compensators in reverse order of execution — C2 (undoing T2) before C1 (undoing T1) — because T2 may have been built on top of state T1 produced, so unwinding out of order could leave the system in an invalid intermediate state, the same way undoing operations must generally happen last-in-first-out. The 'Compensators' slide's specific warning is that this model assumes 'compensators always work' and 'never fail themselves' — but because sagas give up isolation, a step's committed data is already visible to other transactions before its compensator runs, which 'can cause corruption and compensator failures', and writing a compensator that is itself reliable is hard precisely because it has no isolation to rely on either.",
    },
    {
      type: "scenario",
      prompt: "Your company's order service needs to call a partner shipping company's service — a separate, only semi-trusted organisation reached over the public internet — as part of completing a single business operation. Using the lecture's 'Impact of transactions' guidance, explain whether classic ACID 2PC is appropriate here, and if not, what alternative the lecture recommends and why.",
      modelAnswer: "The lecture is explicit that 'ACID transactions are only suitable among closely coupled systems' — ones that trust one another, where 'communication is fairly fast and very reliable', typically 'within an organisation, among closely-collaborating industry partners.' A call to a separate, only semi-trusted shipping partner over the public internet doesn't meet that bar: 2PC would mean holding locks on your order data across a slow, less-reliable cross-organisation network call, with the shipping partner's own coordinator behaviour outside your control — exactly the 'unavailability protocol' risk the lecture warns 2PC creates, now made worse by lower trust and reliability. The lecture's recommended alternative in this situation is to use an 'extended transaction model' — i.e. a Saga: break the operation into smaller local ACID steps (e.g. reserve stock locally, then request shipping) with a defined compensator for each (e.g. cancel the shipping request, restock the item) so that if the shipping call fails, the already-completed local steps can be semantically undone rather than requiring the shipping partner to participate in a 2PC vote it may not even support. This trades ACID's strict isolation for 'enough consistency' built carefully from ACID components — accepting things like publishing latency and stale data, which the lecture notes is 'hard work but done for some of the largest Web-scale apps.'",
    },
    {
      type: "scenario",
      requiresDrawing: true,
      answerDiagram:
        "sequenceDiagram\n    participant TM as Transaction Manager\n    participant P1 as Participant 1\n    participant P2 as Participant 2\n    TM->>P1: Prepare\n    TM->>P2: Prepare\n    P1-->>TM: Prepared (vote_commit)\n    P2-->>TM: No (vote_abort)\n    TM->>P1: Abort\n    TM->>P2: Abort\n    P1-->>TM: Done\n    P2-->>TM: Done",
      prompt: "Sketch the message sequence for 2PC's 'failing transaction' case where a Transaction Manager coordinates two Participants and Participant 2 votes 'no' during Phase 1. Label every message using the lecture's own Coordinator/Participant vocabulary (Prepare/Prepared/Commit/Done for the success path, and the Phase 1 'No'/Phase 2 'Abort' vocabulary for the failure path) — then check your sketch against the model answer.",
      modelAnswer: "Phase 1: the TM sends Prepare to both Participant 1 and Participant 2. Participant 1 saves its intended change and replies Prepared (vote_commit). Participant 2 cannot promise to commit and replies No (vote_abort) instead of Prepared — per the lecture's Phase 1 slide, 'Any RM can say \"no\". No RM actually commits yet!' Because at least one participant voted no, the TM does not proceed to a Commit message for anyone: instead, per Phase 1's rule ('If any RMs said \"no\", TM tells everyone to abandon their intended changes'), it sends Abort to both Participant 1 and Participant 2 — including Participant 1, which had voted yes but must still discard its saved intended change since the transaction as a whole cannot commit. Both participants then reply Done once they've abandoned their respective changes, exactly mirroring the state diagram's participant path: READY → (global_abort / log abort) → ABORT.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Reliability' slide, what does it say 24x7, 99.99%-available operation is achieved with, alongside stand-by systems (warm or hot) and clusters?",
      options: [
        "A dedicated reliability team that manually restarts any failed server within five minutes",
        "Solutions that are largely based on 'transactions'",
        "A second, entirely independent copy of the application that runs with weaker consistency guarantees",
        "Replacing two-phase commit with a single-phase best-effort commit",
      ],
      correctIndex: 1,
      modelAnswer: "The slide states: 'What happens when a computer system is down? Lost customers, sales, money, ... → 24x7 operations, 99.99% availability. Solutions: Stand-by systems (warm or hot), Clusters, Largely based on 'transactions'.' Reliability solutions like standby systems and clustering are explicitly framed as depending on the transaction concept the rest of the lecture builds on, not as a separate concern.",
    },
    {
      type: "mcq",
      prompt: "The lecture's 'Failure' slide lists hardware failures, system software bugs, and application program bugs as inevitable, then states the system still has to be reliable. What four things does it say a reliable system must do in response, rather than assume failures won't happen?",
      options: [
        "Detect the failing component and shut the whole system down until a human intervenes",
        "Retry every failed operation exactly three times before giving up silently",
        "Fail cleanly (maintain data integrity), recover from transient errors, recover from application failure, and recover after system failure",
        "Roll back to the last full database backup taken at midnight",
      ],
      correctIndex: 2,
      modelAnswer: "The 'Failure' slide states: 'Computer hardware fails! System software has bugs!! Application programs have bugs!!! System still has to be reliable — Fail cleanly (maintain data integrity), Recover from transient errors, Recover from application failure, Recover after system failure.' The point is designing for failure as a given rather than an exception — exactly the assumption 2PC's logging and recovery mechanics are built on.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Transaction Systems' slide, which of the following is NOT one of the goals it lists for transaction systems?",
      options: [
        "Efficiently and quickly handle high volumes of requests",
        "Avoid partial results after failure, and grow incrementally",
        "Avoid downtime, and never lose data",
        "Maximise throughput by relaxing durability guarantees whenever the system is under heavy load",
      ],
      correctIndex: 3,
      modelAnswer: "The slide's listed goals are: efficiently and quickly handle high volumes of requests; avoid errors from concurrency; avoid partial results after failure; grow incrementally; avoid downtime; and never lose data. Deliberately relaxing durability under load directly contradicts 'never lose data' and appears nowhere on the slide.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Transaction Managers' slide, which of the following correctly describes the ways it says a TM can actually be implemented?",
      options: [
        "Part of the database software itself (e.g. updating multiple Oracle databases), part of a 'transaction monitor' (CICS, Tuxedo, a J2EE app server), stand-alone (MS DTC, X/Open model), or internal to the run-time (MS Lightweight TM)",
        "Always a dedicated physical appliance, separate from every other server in the architecture",
        "Only ever implemented as a feature of the network router that forwards requests between participants",
        "A purely conceptual role with no real commercial implementation, unlike the resource manager",
      ],
      correctIndex: 0,
      modelAnswer: "The slide states: 'Can be part of the database software... Can be part of a 'transaction monitor' (CICS, Tuxedo, J2EE app server, …). Can be stand-alone (MS DTC, X/Open model). Can be internal to the run-time (MS Lightweight TM, cutdown for 1 process, one durable resource).' The TM's coordinating role stays conceptually the same even though its concrete implementation varies widely across systems.",
    },
    {
      type: "mcq",
      prompt: "The lecture's extended architecture discussion (illustrated by the '2PC Protocol – Implementation' XA-style diagram) introduces a transaction coordinator (TC) as a role distinct from the transaction manager (TM). Per the lecture's own narration, what does the TC do that the TM does not do directly?",
      options: [
        "The TC replaces the TM entirely — once a TC exists, the TM no longer participates in the transaction at all",
        "The TC is simply another name for a resource manager (RM), with no coordination responsibilities of its own",
        "The application asks the TM to commit the global transaction, and the TM in turn asks the TC to coordinate that commit; the TC is the role that actually talks directly to each participating RM ('are you prepared?') and drives them to a final commit or abort — this indirection exists mainly for portability and modularity across different systems",
        "The TC only exists to log transaction history for auditing, with no role in the commit/abort decision itself",
      ],
      correctIndex: 2,
      modelAnswer: "The lecture narrates: 'the application asks transaction manager, can you please commit the global transaction? And this transaction manager talks to transaction coordinator, can you please coordinate this commit?' — the TC is the role that actually asks each RM 'are you prepared?' and drives Phase 1/Phase 2, with the TM/TC split added mainly 'for modular property because there are different systems and applications... can be very easily integrated in other softwares.'",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Transaction API Models' slide, what distinguishes client-side transaction control from server-side transaction control?",
      options: [
        "Client-side control is always faster because it skips logging entirely; server-side control is slower because it logs every statement",
        "Client-side control requires explicit begin-transaction and explicit commit/abort calls written by the caller (e.g. Tx_begin ... Tx_commit around withdraw/deposit calls); server-side control is declarative — one complete business transaction per call, with transactional-ness treated as an attribute requiring no explicit coding (e.g. a single Acc.transfer(...) call)",
        "Client-side control can only be used with NoSQL databases; server-side control can only be used with relational databases",
        "There is no real difference — both terms describe the exact same API pattern under different names",
      ],
      correctIndex: 1,
      modelAnswer: "The slide contrasts client-side control — explicit `Tx_begin`, calls to withdraw/deposit, an audit insert, then explicit `Tx_commit` — against server-side, declarative control, illustrated by `Acc.transfer(accfrom, accto, amount)` where 'transactional-ness is an attribute' and 'no coding required': the caller never writes begin/commit at all, the framework applies it around the whole call.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Lock Performance' slide, what are its two named strategies for reducing the performance cost of blocking on locks?",
      options: [
        "Remove 'hot spots' — frequently-used shared data like 'next entry' counters, summary information, or end-of-file pointers (avoiding them altogether, or caching high-contention data outside the database) — and reduce 'path length' (the number of statements run while a lock is held)",
        "Increase the number of resource managers involved in every transaction, so no single RM becomes a bottleneck",
        "Switch every transaction from pessimistic to optimistic locking, with no other change required",
        "Always hold locks for the full duration of the enclosing 2PC round trip, since releasing them early risks losing atomicity",
      ],
      correctIndex: 0,
      modelAnswer: "The slide states: 'Remove hot spots — Frequently used shared data ('next entry' counters, summary information, end of file pointers) — Avoid altogether if possible — Cache high contention data outside database (and serialise access & handle consistency). Reduce 'path length' — # of statements run with locks held.' Both are concrete tactics for cutting how long and how often locks actually block other transactions, going beyond the general Lock Impacts problem description.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Business Transactions' slide, how do standards like BizTalk Server, BPEL4WS, and WS-BA use the compensation model, and what do they assume about the applications involved?",
      options: [
        "They require every application involved to be tightly coupled within a single organisation, using classic 2PC rather than compensation",
        "They use compensation only for read-only operations, never for operations that modify state",
        "They forbid partial compensation — every compensator for a transaction scope must always run, with no exceptions",
        "They use the compensation model for 'transaction' support in workflow engines, assuming loosely-coupled autonomous applications possibly across organisational borders, with support for a defined transaction scope, automatic compensator invocation, and no requirement to undo everything",
      ],
      correctIndex: 3,
      modelAnswer: "The slide states: 'Compensation model used for 'transaction' support in workflow engines/standards — BizTalk Server, BPEL4WS, WS-BA — Assume loosely-coupled autonomous applications, possibly across organisational borders. Support for compensators — Defined transaction scope, Automatic compensator invocation, Do not have to undo everything.' This names the industry standards that build on the earlier Sagas & Compensation slides, aimed at cross-organisation workflows rather than tightly-coupled 2PC-style systems.",
    },
    {
      type: "mcq",
      prompt: "In the lecture's opening recap quiz (revising Week 3's remote-call concepts), students were asked: an application needs 10 pieces of information from a remote service — is it generally better to make 10 separate remote calls, or one call that returns all the required information together? What did the lecture say, and why?",
      options: [
        "10 separate remote calls, because each individual call is smaller and therefore faster to marshal",
        "It makes no difference — remote calls and local calls cost the same amount of time and effort",
        "One call that returns the required information together, because every remote call takes much more effort and time than a local call, so batching avoids paying that per-call network cost 10 separate times",
        "10 separate remote calls, so that a failure in one call doesn't affect retrieval of the other nine pieces of information",
      ],
      correctIndex: 2,
      modelAnswer: "The lecture's answer: 'notice that every remote call takes much more effort and time than the local call. That's why we do not, for example, make 10 calls remotely — instead we just make one call that returns the required information together.' This is the 'chunky vs chatty' remote-call principle: batching amortises the fixed per-call network/marshalling cost that a purely local call never pays.",
    },
    {
      type: "mcq",
      prompt: "In the lecture's opening recap quiz, which statement was identified as best summarising 'transparency' in distributed computing?",
      options: [
        "Distributed calls are identical to local calls in every respect, including latency",
        "The framework can hide much of the communication complexity from the developer — a developer calling a remote service doesn't need to hand-code the networking details themselves, even though that complexity still exists underneath",
        "Developers must manually implement marshalling and unmarshalling for every remote call, since no framework can hide this",
        "Transparency means the architect is entirely unaware that any remote communication protocol exists at all",
      ],
      correctIndex: 1,
      modelAnswer: "The lecture states transparency means 'this framework can hide much of communication complexity... developers and architects should know there's a very complex communication protocol underneath, but we should not [have to] hand [code] that' — distinguishing it both from the false claim that distributed calls are identical to local ones, and from the false claim that architects have no need to even know the underlying complexity exists.",
    },
    {
      type: "mcq",
      prompt: "In the lecture's opening recap quiz, which statement about distributed systems and partial failures is correct?",
      options: [
        "Distributed systems do experience partial failures — e.g. a server going down, a machine crashing — unlike a single local system, which either fully works or fully fails as one unit",
        "Distributed systems never experience partial failures, because every node in the system fails or recovers in lockstep with every other node",
        "Partial failures only happen in local (non-distributed) systems, not in distributed ones",
        "Partial failures are a purely theoretical concern that never actually occurs in production distributed systems",
      ],
      correctIndex: 0,
      modelAnswer: "The lecture explicitly corrects a common quiz mistake here: 'distributed systems do not experience partial failures — No, distributed systems do experience partial failures. [A] server down, a machine crash, etc.' This is exactly the failure mode 2PC's Phase 1/Phase 2 logging and recovery machinery exists to survive — one participant can fail while the others keep running, unlike a single local transaction, which fails or succeeds as one indivisible unit.",
    },
    {
      type: "short",
      prompt: "Using the lecture's 'Speed and Scale' slide and Week 2's concurrency/locking material, explain why concurrency is described on that slide as both the 'solution' and the 'problem' for transaction systems, and how 2PC's isolation guarantee resolves that tension for a distributed transaction.",
      modelAnswer: "The 'Speed and Scale' slide frames concurrency as the solution to performance — 'doing more than one operation at a time, processing while waiting for I/O, using multiple processors' — because handling requests one at a time would be far too slow to scale. But it frames concurrency as the problem too: 'interference between programs' and 'conflicts over shared resources', with its own example being that you 'can't sell the same seat twice.' This is exactly Week 2's concurrency-anomaly territory (lost updates, interleaved transactions). The lecture's own 'ACID in Practice' slide is the resolution: Isolation is implemented 'using locks in each RM', coordinated through 2PC — each resource manager takes and holds locks for the resources it touches during Phase 1/Phase 2, so concurrent transactions trying to sell the same seat (or touch the same account) still get serialised against each other even though the transaction itself spans multiple machines, giving back the same isolation guarantee Week 2 described locally, just now enforced per-participant and coordinated globally by the TM.",
    },
    {
      type: "short",
      prompt: "The lecture's 'Transaction API Models' slide distinguishes client-side explicit transaction control (Tx_begin/Tx_commit written by the caller) from server-side declarative control (transactional-ness as an attribute, e.g. a single Acc.transfer(...) call). Which style does this week's tutorial code (CentralBankController/CentralBankService driving BankRPCService's prepare()/commit() over gRPC) actually follow, and why?",
      modelAnswer: "The tutorial code follows the client-side explicit style, not the server-side declarative style. CentralBankController/CentralBankService is written as an explicit sequence of application-level calls — createTwoAccounts, then prepareTransaction (which itself explicitly calls bank1Stub.prepare and bank2Stub.prepare), then commitTransaction (bank1Stub.commit/bank2Stub.commit), with commitTransaction's boolean result explicitly branched on to decide whether to call rollbackTransaction — mirroring the client-side example's `Tx_begin / call withdraw / call deposit / Tx_commit` pattern of hand-coded begin-then-commit-or-abort logic. There is no single declarative call like `Acc.transfer(...)` where 'transactional-ness is an attribute requiring no coding' — every step of the 2PC protocol (which bank to prepare, in what order, what to do if a prepare or commit fails) is explicit, hand-written orchestration logic in CentralBankService/CentralBankController, which is exactly why the tutorial's own rollback() TODO has to be filled in by hand rather than being handled automatically by a framework.",
    },
    {
      type: "scenario",
      prompt: "Your team is designing an internal warehouse inventory service that must stay available 24x7 and needs to survive a server crashing mid-operation, without ever silently losing an inventory update. Using the lecture's 'Reliability' and 'Failure' slides specifically (not the Sagas/compensation material), explain what design principles you'd apply, and why 'assume failures won't happen' is explicitly rejected as an approach.",
      modelAnswer: "The 'Failure' slide is explicit that hardware fails, system software has bugs, and application programs have bugs — failures are treated as a given, not a possibility to design around by hoping they won't occur. Instead the system 'still has to be reliable': it must fail cleanly (maintain data integrity even mid-crash), recover from transient errors, recover from application failure, and recover after system failure. For the warehouse service this means: never let a crash leave an inventory update half-applied (matching the ATM 'Bank loses money' / 'You lose money' failure pattern from the Resources slide, where a crash between two steps corrupts state), and ensure enough logging that the service can inspect its own state on restart and determine what to redo or discard — the same mechanism 2PC's TM/RM logs use to recover after a participant crash. The 'Reliability' slide adds the availability side of this: to hit 24x7, 99.99%-available operation, use stand-by systems (warm or hot) and clusters so a single crashed server doesn't take the whole service down, noting these solutions are 'largely based on transactions' — i.e. the same transactional logging/recovery discipline used to survive failures is also what makes failover to a standby safe, rather than these being two unrelated concerns.",
    },
    {
      type: "scenario",
      prompt: "Per the lecture's 'Lock Performance' slide, your team's flash-sale checkout system uses a single shared 'remaining stock' counter row that every checkout transaction locks and updates, and lock contention on that row is now the site's dominant bottleneck during flash sales. Using the slide's own two named strategies, propose a concrete fix, and explain why simply making the checkout transaction 2PC-compliant would not fix this problem by itself.",
      modelAnswer: "The 'remaining stock' counter is exactly the slide's own example of a 'hot spot' — frequently-used shared data like a 'next entry' counter — and the slide's first strategy is to 'avoid altogether if possible' or 'cache high contention data outside database (and serialise access & handle consistency)': e.g. maintain the stock count in a fast in-memory/cache layer with its own serialised decrement logic, only periodically or eventually reconciling it back to the database, rather than every single checkout transaction taking a row lock on the same shared counter. The slide's second strategy — reduce 'path length', the number of statements run while the lock is held — would also help even if the row lock is kept: do the minimum possible work (just the decrement) while holding that specific lock, moving anything else the checkout needs (payment, shipping details) outside the critical section. Making the transaction 2PC-compliant would not fix this on its own because 2PC governs how multiple participants agree to commit or abort together — it says nothing about how long any single participant holds its own local lock. A hot-spot row lock held for the full duration of a 2PC round trip (per the '2PC impacts' slide's 'at least 4 cross-network messages, from time lock taken till time commit outcome known and lock released') would make the contention on that single shared row worse, not better, since every checkout transaction would now serialise on that lock for even longer.",
    },
  ],
};

export const WEEK_4_PAPERS: ExamPaperSeed[] = [TUTORIAL_PAPER, LECTURE_PAPER];
