import type { ExamPaperSeed } from "../types";

const TUTORIAL_PAPER: ExamPaperSeed = {
  course: "COMP5348",
  week: 3,
  paperNumber: 1,
  title: "Week 3 Tutorial Practice Paper",
  topics: "ERD notation (entities, attributes, primary/foreign keys, cardinality indicators); UML class diagram relationships (association, directed association, multiplicity, aggregation vs composition, inheritance vs realization, dependency); mapping the bank ERD (TransactionRecord/Account/Customer) to a class diagram; the tutorial-3-student Spring Boot bank-transaction app (Account/TransactionRecord/Customer model, service, controller, repository, and DTO layers; the deliberately-incomplete Customer entity 'fix' exercise; InsufficientBalanceException/NegativeTransferAmountException; the performTransaction transfer/deposit flow)",
  sourceFiles: [
    "tutorial/COMP5348_Tutorial 3 Slides.pdf",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/model/Account.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/model/TransactionRecord.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/model/Customer.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/service/AccountService.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/service/TransactionRecordService.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/service/CustomerService.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/controller/AccountController.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/controller/CustomerController.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/controller/TransactionRecordController.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/dto/AccountDTO.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/dto/CustomerDTO.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/dto/TransactionRecordDTO.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/repository/AccountRepository.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/repository/TransactionRecordRepository.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/repository/CustomerRepository.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/errors/InsufficientBalanceException.java",
    "tutorial/tutorial-3-student/src/main/java/com/comp5348/banktransaction/errors/NegativeTransferAmountException.java",
  ],
  questions: [
    {
      type: "mcq",
      prompt: "Per the Week 3 tutorial slides, what is an ERD 'entity'?",
      options: ["A UML relationship connecting two or more classes", "A method exposed by a class's public interface", "A foreign key constraint linking two tables", "An object (e.g. book, account, student) tracked in the database"],
      correctIndex: 3,
      modelAnswer: "The tutorial slides define an entity as 'an object (book, account, student) tracked in the database' — the Student example box shown is one instance of this definition.",
    },
    {
      type: "mcq",
      prompt: "In the tutorial's Student entity table (student_id PK; mobileNum, firstName, lastName, dob, enrolled all marked NOT NULL), what does the 'PK' marking on student_id specifically indicate that the other NOT NULL columns don't have?",
      options: ["That student_id uniquely identifies each row and is the entity's primary key, not just a required (non-null) value", "That student_id is a foreign key referencing the primary key of a different table, the way Account.customer_id references Customer", "That student_id is a derived value recalculated automatically from mobileNum, firstName, and lastName whenever the row changes", "That student_id is an optional attribute that may be left blank on insert, unlike the other NOT NULL columns beside it"],
      correctIndex: 0,
      modelAnswer: "PK marks student_id as the primary key — the column that uniquely identifies each row — which is a stronger property than merely being NOT NULL; the other attributes are required values but don't uniquely identify a row on their own.",
    },
    {
      type: "mcq",
      prompt: "Per the tutorial's Cardinality indicator table, what is the difference between '0..*' and '1..*'?",
      options: ["'0..*' means exactly zero related instances are permitted, while '1..*' means exactly one related instance is required and no more", "'0..*' and '1..*' are simply two alternative notations that both express the exact same unbounded-to-many relationship", "'0..*' is the cardinality notation used only in ERDs, while '1..*' is the equivalent notation used only in UML class diagrams", "'0..*' means zero or more; '1..*' means one or more — the difference is whether zero instances is allowed"],
      correctIndex: 3,
      modelAnswer: "The Cardinality table lists 0..* as 'Zero or more' and 1..* as 'One or more' — the only difference is whether the relationship permits zero related instances or requires at least one.",
    },
    {
      type: "mcq",
      prompt: "In the tutorial's ERD, Transaction Record has two separate foreign keys, to_account_id and from_account_id, both referencing the same Account table. Why two FKs instead of one?",
      options: ["Because one foreign key is dedicated to read-only reporting queries against the Account table, while the other is reserved exclusively for the write path that updates the balance", "Because a single transaction record needs to distinguish which account money left from and which account it arrived at — a transfer inherently touches two different accounts in two different roles", "It's redundant data duplicated across two columns purely as a backup in case one foreign key value gets corrupted or accidentally deleted from the row", "Because Account is modelled as a many-to-many join table in this ERD, and join tables conventionally need two foreign keys pointing back to the same referenced table"],
      correctIndex: 1,
      modelAnswer: "A transfer moves money between two accounts, so the record needs to capture both ends of the movement in their distinct roles — source and destination — which requires two separate foreign keys into the same Account table rather than one shared reference.",
    },
    {
      type: "mcq",
      prompt: "The tutorial's class diagram slide shows a directed association with an arrow from Airplane to Passenger, versus a plain undirected line for Students–Tutorial. What does the arrow/direction specifically add over a plain association?",
      options: ["It means the relationship is only optional in the direction the arrow points, while the reverse direction remains a mandatory, required association", "It means Airplane inherits from Passenger, the same way a hollow-triangle arrow would show one class extending another's implementation", "It has no semantic difference from an undirected line — both simply denote that Airplane and Passenger are associated with each other", "It shows navigability — that Airplane has a reference to/knowledge of Passenger, without necessarily implying Passenger holds a reference back to Airplane"],
      correctIndex: 3,
      modelAnswer: "A directed association arrow shows navigability: the class at the tail (Airplane) knows about/references the class at the head (Passenger), without implying the reverse reference exists — unlike a plain undirected association line, which doesn't specify a direction of knowledge.",
    },
    {
      type: "mcq",
      prompt: "The tutorial slide shows Library —◇ Books as aggregation (open/hollow diamond) and Person —♦ Name as composition (filled diamond). What is the key difference between these two relationships?",
      options: ["In composition, the part (Name) cannot meaningfully exist independently of the whole (Person); in aggregation, the part (Books) can exist independently of the whole (Library)", "Composition can only be used for primitive-typed fields such as Name, whereas aggregation can only be used for object-typed fields such as the Books collection", "They represent exactly the same relationship, drawn with two different diamond styles purely as an alternative visual convention for readability", "Aggregation is the stronger of the two relationships, since it implies the diamond end owns and controls the lifetime of the other class"],
      correctIndex: 0,
      modelAnswer: "Composition (filled diamond) is the stronger 'owns and cannot exist without' relationship — a Person's Name has no independent existence — while aggregation (hollow diamond) is a weaker 'has-a' relationship where Books can exist (e.g. in another library, or on their own) independently of this particular Library.",
    },
    {
      type: "mcq",
      prompt: "The tutorial slide shows Corporate Account → Bank Account with a solid line and hollow triangle (inheritance), and Printer Setup → Printer with a dashed line and hollow triangle (realization). What distinguishes realization from inheritance here?",
      options: ["Realization (dashed line) shows a class implementing an interface's contract; inheritance (solid line) shows a class extending another concrete class's implementation", "The dashed line means the relationship between Printer Setup and Printer is optional and may not always be present at runtime, unlike the solid line", "Realization is a notation reserved for database tables implementing a schema, never applied to classes implementing an interface in a class diagram", "There is no meaningful difference between the two — both the solid line and the dashed line denote exactly the same inheritance relationship"],
      correctIndex: 0,
      modelAnswer: "Both use a hollow triangle, but the line style differs: a solid line (Corporate Account → Bank Account) is inheritance/extension of a concrete class, while a dashed line (Printer Setup → Printer) is realization — implementing an interface's contract without inheriting a concrete implementation.",
    },
    {
      type: "mcq",
      prompt: "The tutorial slide shows a dashed arrow (dependency) from LibraryMember to Book, distinct from the solid diamond relationships. What does a dependency arrow represent?",
      options: ["That the two classes, LibraryMember and Book, are actually the same underlying class simply given two different names for documentation purposes", "A weaker relationship than association — that one class uses another (e.g. as a parameter, return type, or local variable) without a persistent structural link between them", "That Book cannot be instantiated at all unless a LibraryMember instance already exists first, the way a composed part depends on its whole", "The strongest possible ownership relationship between two classes, stronger even than the filled-diamond composition shown elsewhere on the slide"],
      correctIndex: 1,
      modelAnswer: "Dependency is a weaker relationship than association: it shows that one class (LibraryMember) makes use of another (Book) — e.g. via a method signature — without holding a persistent structural reference to it the way an association's field would.",
    },
    {
      type: "mcq",
      prompt: "In the tutorial's Class Diagram Example, Order and OrderItem are connected by an aggregation (hollow diamond at the OrderItem end) with multiplicities '1' on the Order side and '1..n' on the OrderItem side. What does this specifically require?",
      options: ["Every Order must have exactly one OrderItem, never more", "Every Order must be composed of at least one OrderItem, and each OrderItem belongs to exactly one Order", "Every OrderItem must belong to at least one Order, but an Order can have zero OrderItems", "Order and OrderItem have no required relationship at all"],
      correctIndex: 1,
      modelAnswer: "The '1' on the Order end and '1..n' on the OrderItem end mean each OrderItem is aggregated by exactly one Order, and each Order must aggregate at least one (one-or-more) OrderItem — not zero, and not capped at exactly one.",
    },
    {
      type: "mcq",
      prompt: "The Week 3 tutorial exercise asks for a bank application that tracks account balances 'through both implicit transaction records and explicit account balances.' How does this connect to the Week 2 lecture's discussion of state types?",
      options: ["Week 2 said derived state should never be cached because a cached value always becomes stale the moment the underlying data changes, so keeping both TransactionRecord rows and a cached Account.balance side by side directly contradicts that guidance", "It mirrors Week 2's derived-vs-resource-state example: the balance is derivable ('implicit') by summing TransactionRecord rows, but is also kept as a cached running total ('explicit') on Account.balance for efficiency, exactly like Week 2's own bank-balance example", "It means the balance should only ever be stored implicitly — recomputed on demand by summing every TransactionRecord row for the account — and never cached explicitly on Account.balance, per Week 2's guidance on derived state", "It has no real connection at all — Week 2's discussion was specifically about concurrency control and locking strategies, whereas this tutorial's implicit/explicit balance design is purely a database schema decision"],
      correctIndex: 1,
      modelAnswer: "Week 2's lecture used the bank account balance as its own worked example of derived state — 'could be computed by summing all transactions' but kept as a cached running total for efficiency. This tutorial's design does exactly both: TransactionRecord rows are the implicit/derivable source of truth, while Account.balance is the explicit, cached total that Account.modifyBalance() maintains directly.",
    },
    {
      type: "mcq",
      prompt: "Account.java declares two separate @OneToMany collections — fromTransactionRecords (mappedBy = \"fromAccount\") and toTransactionRecords (mappedBy = \"toAccount\"). Why two collections instead of one combined list of an account's transactions?",
      options: ["Because Hibernate enforces a convention requiring exactly two @OneToMany collections on every entity that participates in more than one relationship type", "Because JPA has a read/write separation rule requiring one @OneToMany collection to be used only for querying and a second, separate collection to be used only for persisting new rows", "It's simply a leftover bug in the student starter code, with fromTransactionRecords and toTransactionRecords serving no distinct architectural purpose", "Because TransactionRecord itself has two distinct @ManyToOne fields (fromAccount and toAccount) in two different roles, so JPA needs a separate mapped collection for each role an Account can play in a transaction"],
      correctIndex: 3,
      modelAnswer: "TransactionRecord has two separate @ManyToOne relationships to Account — fromAccount and toAccount — reflecting the two roles an account can play in one transaction. Account's mappedBy attributes must match each of those role names individually, which is why it needs two separate @OneToMany collections rather than one.",
    },
    {
      type: "mcq",
      prompt: "What does Account.modifyBalance(Double amount) do?",
      options: ["Replaces the balance entirely with the given amount, discarding whatever the previous balance was, similar to a plain setter method", "Only allows positive amounts to be passed in, throwing an exception whenever a negative amount would decrease the balance", "Acquires a pessimistic database lock on the Account row before applying the change, then releases it once the update commits", "Adds amount to the current balance (this.balance = this.balance + amount), so a negative amount decreases the balance and a positive amount increases it"],
      correctIndex: 3,
      modelAnswer: "modifyBalance is a simple additive update: `this.balance = this.balance + amount;` — TransactionRecordService calls it with a negative amount to debit the fromAccount and a positive amount to credit the toAccount, with no locking performed inside the method itself.",
    },
    {
      type: "mcq",
      prompt: "Unlike Account's customer field (@JoinColumn(nullable = false)), TransactionRecord's toAccount and fromAccount fields have no nullable = false constraint. Why does this matter given how TransactionRecordService.performTransaction is written?",
      options: ["Because nullable = false only applies to primary-key columns, never to @ManyToOne/@JoinColumn foreign keys — a misconception, since @JoinColumn(nullable = false) constrains any foreign-key column regardless of whether it's a PK", "Because a deposit only populates toAccount (fromAccountId is null), so exactly one of the two ends must be allowed to be null for a single-sided transaction to be recorded", "Because TransactionRecord entities in this codebase are never actually persisted to the database, so a nullable = false constraint on either @ManyToOne field would simply never be enforced or matter at runtime", "It's an oversight in the student starter code — both toAccount and fromAccount should really be marked nullable = false, exactly like Account.customer already is"],
      correctIndex: 1,
      modelAnswer: "performTransaction only builds a fromAccount when fromAccountId is non-null, and only a toAccount when toAccountId is non-null — the deposit endpoint passes fromCustomerId/fromAccountId as null. If either @ManyToOne column were nullable = false, deposits (no fromAccount) would violate the database constraint and fail to save.",
    },
    {
      type: "mcq",
      prompt: "In TransactionRecordService.performTransaction, why is the `if (amount <= 0) throw new NegativeTransferAmountException();` check placed before either account is looked up or modified?",
      options: ["Because negative amounts are actually valid for triggering withdrawals in this design, so the check is unreachable dead code left over from an earlier, stricter version of the method", "It has no effect on observable behaviour either way and could be moved to any other line in the method without changing what performTransaction does", "Because JPA/Hibernate requires all argument validation to run before any @Autowired repository field is touched, or the persistence context throws at startup", "To reject an invalid request immediately, before doing any repository lookups or balance changes that would otherwise need to be undone"],
      correctIndex: 3,
      modelAnswer: "Validating the amount first is a fail-fast check: it rejects a clearly invalid request before spending effort on repository lookups (getReferenceById, findByIdAndCustomer) or mutating any account balance, avoiding the need to undo partial work.",
    },
    {
      type: "mcq",
      prompt: "InsufficientBalanceException is annotated @ResponseStatus(value = HttpStatus.PRECONDITION_FAILED, ...). What does this annotation achieve, compared to NegativeTransferAmountException's @ResponseStatus(value = HttpStatus.BAD_REQUEST, ...)?",
      options: ["Each exception is automatically translated into its own distinct HTTP status code by Spring when thrown, without the controller needing a try/catch block — 412 for insufficient balance vs 400 for a negative amount", "The annotation only affects what gets written to the server's log output when the exception is thrown, and has no effect on the actual HTTP status or body returned to the calling client", "Both exceptions always return the same generic 500 Internal Server Error to the client regardless of which @ResponseStatus value is written on the exception class", "@ResponseStatus only takes effect if the controller explicitly catches the exception in a try/catch block and manually rethrows it back up the call stack"],
      correctIndex: 0,
      modelAnswer: "@ResponseStatus lets Spring MVC map an uncaught exception directly to an HTTP status automatically — InsufficientBalanceException maps to 412 Precondition Failed and NegativeTransferAmountException maps to 400 Bad Request — so TransactionRecordController needs no explicit try/catch to return the correct status for each distinct failure.",
    },
    {
      type: "mcq",
      prompt: "AccountDTO has two constructors: AccountDTO(Account) which defaults includeRelatedEntities to false, and AccountDTO(Account, boolean). Why does TransactionRecordDTO's constructor call `new AccountDTO(toAccount)` (the single-argument form) instead of passing true?",
      options: ["Because the single-argument constructor skips a database round trip that the boolean overload would otherwise trigger, making it faster purely for performance reasons unrelated to payload shape", "Because TransactionRecordDTO never needs the nested account's name or balance fields at all, so includeRelatedEntities has nothing meaningful to include either way", "To avoid an overly heavy/circular payload — a TransactionRecordDTO embedding an AccountDTO that itself embeds that account's full transactionRecords set (including this very transaction) would recurse", "It's an arbitrary stylistic choice left over from an earlier draft, and could safely be changed to pass true instead without any effect on the resulting JSON payload"],
      correctIndex: 2,
      modelAnswer: "Passing true would make the nested AccountDTO include its own transactionRecords set (via AccountDTO's includeRelatedEntities branch), which would embed TransactionRecordDTOs pointing back to AccountDTOs, risking a much heavier or effectively circular payload — so nested accounts inside a TransactionRecordDTO stay 'shallow' (false), while the top-level AccountDTO returned directly by the controller passes true to include its full detail.",
    },
    {
      type: "mcq",
      prompt: "AccountRepository declares `Optional<Account> findByIdAndCustomer(long id, Customer customer);` with no method body. What SQL-equivalent condition does Spring Data JPA generate from this method name?",
      options: ["WHERE id = ? OR customer = ?", "It requires a corresponding @Query annotation to work at all — an empty method body alone will fail", "WHERE id = ? AND customer = ? (i.e. matching both the given id and the given Customer)", "It generates a query that ignores the customer parameter entirely"],
      correctIndex: 2,
      modelAnswer: "Spring Data JPA parses the method name 'findByIdAndCustomer' into a query joining the two conditions with AND — this is the same derived-query mechanism used elsewhere in the course (e.g. Week 1's findByTitleContaining) — no method body or @Query annotation is required.",
    },
    {
      type: "mcq",
      prompt: "The tutorial's starter Customer.java is deliberately left incomplete as part of the 'fixing Customer entity' exercise. Given the ERD (Customer: id, first_name, last_name) and that Account already declares `@ManyToOne @JoinColumn(nullable = false) private Customer customer;`, which annotation should the completed Customer entity use on its collection of accounts to mirror the existing bidirectional pattern already used between Account and TransactionRecord?",
      options: ["@ManyToMany private Collection<Account> accounts;", "@OneToOne private Account account;", "@ManyToOne(mappedBy = \"customer\") private Collection<Account> accounts;", "@OneToMany(mappedBy = \"customer\") private Collection<Account> accounts;"],
      correctIndex: 3,
      modelAnswer: "The same bidirectional pattern already used between Account and TransactionRecord (@OneToMany(mappedBy = ...) on the 'one' side, @ManyToOne on the 'many' side) applies here: since Account already holds the owning @ManyToOne Customer field, Customer's inverse side should be @OneToMany(mappedBy = \"customer\") over a Collection<Account>, exactly mirroring Account.fromTransactionRecords/toTransactionRecords being mappedBy their respective TransactionRecord fields.",
    },
    {
      type: "mcq",
      prompt: "The tutorial slides state ERD's focus is '___' while Class Diagram's focus is '___'.",
      options: ["database design; object-oriented structure design", "concurrency control; transaction management", "object-oriented structure design; database design", "network topology; UI layout"],
      correctIndex: 0,
      modelAnswer: "The slides state this explicitly: 'Entity Relationship Diagram (ERD) — Focus: database design' and 'Class Diagram — Focus: object-oriented structure design.'",
    },
    {
      type: "mcq",
      prompt: "CustomerController.createCustomer delegates entirely to customerService.createCustomer(request.firstName, request.lastName) and returns the resulting CustomerDTO. Per the layered architecture pattern this course has used since Week 1, what should the controller layer specifically NOT contain?",
      options: ["Any HTTP method verbs at all, such as @PostMapping, @GetMapping, or @PutMapping annotations on its handler methods", "Any reference to or import of a DTO class, since DTOs are meant to be constructed only inside the service layer, never returned from a controller", "Direct repository/database access or business logic (e.g. validation, persistence) — that belongs in the service and repository layers respectively", "Any @RequestMapping-style class-level annotation used to declare the controller's base request path"],
      correctIndex: 2,
      modelAnswer: "Consistent with Week 1's layering (controller = request/response handling, service = business logic, repository = persistence), CustomerController only translates the HTTP request into a service call and wraps the result in a ResponseEntity — it never touches CustomerRepository or constructs a Customer entity directly.",
    },
    {
      type: "mcq",
      prompt: "TransactionRecordRepository and CustomerRepository both simply extend JpaRepository<Entity, Long> with an empty body and no custom methods declared. What functionality do they still provide as a result?",
      options: ["No functionality at all — an empty interface body with no declared methods means Spring cannot generate a working implementation and the repository bean fails to start", "Only read operations such as findById and findAll; any write operation like save or deleteById still requires a custom method to be explicitly declared in the interface", "The same custom findByIdAndCustomer method that AccountRepository declares elsewhere in the package, inherited automatically by every other JpaRepository subinterface", "The standard CRUD operations (save, findById, findAll, delete, etc.) that JpaRepository provides out of the box, with no custom query methods needed for the tutorial's current use cases"],
      correctIndex: 3,
      modelAnswer: "Extending JpaRepository<Entity, Long> alone already provides the standard CRUD operations (save, findById, findAll, deleteById, etc.) via Spring Data JPA — an interface only needs additional method declarations when it requires a query beyond that standard set, which CustomerService and TransactionRecordRepository's current callers don't.",
    },
    {
      type: "mcq",
      prompt: "TransactionRecordController's deposit endpoint calls the same transactionRecordService.performTransaction(...) method as the transfer endpoint, but passes fromCustomerId and fromAccountId as null. What does this reuse rely on inside performTransaction?",
      options: ["The amount <= 0 validation check, which is what the method actually uses internally to tell a deposit request apart from an ordinary two-account transfer request", "The fromAccountId != null guard, which skips looking up/debiting a source account entirely when it's null, so the same method naturally handles a one-sided (deposit) transaction as well as a two-sided (transfer) one", "Nothing meaningful — this endpoint reuse is actually a latent bug, and deposit requests silently fail to persist any TransactionRecord row at all", "A separate, overloaded performTransaction method signature that only the deposit endpoint calls, distinct from the one the transfer endpoint uses"],
      correctIndex: 1,
      modelAnswer: "performTransaction guards both the fromAccountId and toAccountId branches with null checks (`if (fromAccountId != null) { ... }`), so passing null for the 'from' side simply skips the debit branch entirely — the same method handles transfers (both branches run) and deposits (only the credit branch runs) without needing a separate code path.",
    },
  ],
};

const LECTURE_PAPER: ExamPaperSeed = {
  course: "COMP5348",
  week: 3,
  paperNumber: 2,
  title: "Week 3 Lecture Practice Paper",
  topics: "Distributed computing's ideal vs its reality; motivations for distribution (autonomy/independence, load balancing, reliability via redundancy) and the historical arc from 1960s conceptual origins through 1970s networking and 1980s Ethernet commercialisation to RPC/CORBA/DCOM/EJB; the Eight Fallacies of Distributed Computing (Deutsch); local vs remote method calls, stubs/skeletons, marshalling/unmarshalling, request/response message structure, SOAP; distributed architectures (peer-to-peer vs multi-tier); transparency's limits (network latency, partial failures, coarse- vs fine-grained interfaces); interface evolution strategy; Java EE application model and tiers (client/web/business/EIS), Enterprise Java Beans (stateless session beans, remote interfaces, JNDI lookup), deployment descriptors, JEE glossary (JNDI/RMI/JMS/JTA/JTS/JDBC); Spring Boot layering mapped onto the same tiered model",
  sourceFiles: ["lecture/COMP5348_W3.pdf", "lecture/Week 03 - Enterprise-s2-low.transcript.md"],
  questions: [
    {
      type: "mcq",
      prompt: "Per Peter Deutsch's 'Eight Fallacies of Distributed Computing' as presented in the lecture, which of the following is NOT one of the eight fallacies?",
      options: ["Latency is zero", "The network is fast", "Bandwidth is infinite", "The network is homogeneous"],
      correctIndex: 1,
      modelAnswer: "The lecture's list of eight fallacies is: the network is reliable, latency is zero, bandwidth is infinite, the network is secure, topology doesn't change, there is one administrator, transport cost is zero, and the network is homogeneous. 'The network is fast' is not one of the eight — the closest listed fallacies are 'latency is zero' and 'bandwidth is infinite', which are more specific claims.",
    },
    {
      type: "mcq",
      prompt: "What does the fallacy 'There is one administrator' actually warn against, per the lecture's framing of the eight fallacies as false assumptions?",
      options: ["Assuming only one client process can call into a given remote service instance at any one time, so the container-managed server object never actually needs to handle concurrent requests from multiple callers", "Assuming that a distributed system spanning many machines only ever needs exactly one dedicated system administrator on staff, whose job is to keep every one of those machines running, patched, and monitored", "Assuming that whichever single person administers the shared network infrastructure connecting the machines is necessarily also the same person who administers the backend databases sitting behind those services", "Assuming a single person/organisation controls and can be trusted to coordinate the entire network path a distributed call travels over, when in reality it usually spans multiple independent administrative domains"],
      correctIndex: 3,
      modelAnswer: "The eight fallacies are false assumptions developers wrongly rely on. 'There is one administrator' warns against assuming a single administrative authority governs the whole network path a call traverses — in practice a distributed call between organisations crosses multiple independently-administered networks with no single point of control. The lecture's own post-class discussion made this concrete: a company integrating with a third-party partner deals with that partner's own separate IT team and administration, not one shared administrator spanning both sides — exactly the kind of case the fallacy warns against assuming away.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's description of local method calls, which of the following correctly describes what happens at the hardware/runtime level?",
      options: ["A hardware-level 'call' instruction branches to the method, saving the return address; arguments are passed via registers and/or a new stack frame; a 'return' instruction exits the method", "The runtime first performs a JNDI naming lookup to resolve the target method's physical location on disk before the hardware call instruction is ever actually issued", "A locally-generated stub instance is created first and silently intercepts the plain method call, forwarding it across the network to a remote object running elsewhere", "The call's arguments are marshalled into a request message and sent across the network to a skeleton object listening for connections on the target machine"],
      correctIndex: 0,
      modelAnswer: "The lecture's Local Method Calls slide describes the hardware-level 'call' instruction (branch + saved return address), argument passing via registers/stack frame, and a 'return' instruction to exit — the marshalling/stub/skeleton/JNDI machinery described afterwards is specific to remote calls, not local ones.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's Remote Method Call (client) slide, what does the client-side stub (proxy) do?",
      options: ["Determines up front, on the client side, whether the target server object is stateful or stateless before deciding which network route to send the outgoing call over", "Represents the target server object within the client system, takes the call arguments, marshals them plus related information into a message, and sends the request to the server machine", "Listens on an open network endpoint sitting on the server machine, and unmarshals each incoming call request message as it arrives from clients", "Executes the actual business logic belonging to the remote method directly inside the client's own process, entirely skipping any network call"],
      correctIndex: 1,
      modelAnswer: "The stub represents the remote (server) object locally on the client side — from the programmer's perspective it looks like the remote object itself. Using the lecture's own worked example, a call like getStockByBookId(bookId) looks like an ordinary local method call, but it is actually a call on the stub: the stub takes the method name and the bookId argument, marshals them plus related information into a message, and sends the request to the server machine. The corresponding server-side responsibilities (listening, unmarshalling, dispatching) belong to the skeleton instead.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's Remote Method Call (server) slide, what does the server-side skeleton do after a request message arrives?",
      options: ["Unmarshals the call request message, extracts the arguments, determines which method/instance to call (raising the stateful/stateless question), and then does a normal method call to the server code/object", "Caches the result of the call in memory so that any future identical request arriving from any client at all can skip the network round trip entirely and return instantly", "Marshals the client's arguments into a request message and sends it onward across the network, effectively repeating the same job the client-side stub already performed earlier in the call", "Compiles the service's published IDL or WSDL interface definition into a freshly generated client-side stub, done on demand each time a request arrives"],
      correctIndex: 0,
      modelAnswer: "The skeleton is the server-side counterpart to the client's stub: it listens on a network endpoint, unmarshals the incoming request, extracts arguments and determines the target method/instance (this is exactly where the lecture notes the 'stateful/stateless question' arises), then makes an ordinary local call into the server object.",
    },
    {
      type: "mcq",
      prompt: "The lecture notes a 'stateful/stateless question' arises specifically when the server-side skeleton determines which object instance should handle an incoming call. Using Week 2's stateful/stateless definitions, what is this question actually asking?",
      options: ["Whether the skeleton should marshal the outgoing response payload as plain XML text or instead as a more compact binary encoding before sending the reply message back", "Whether the responsibility for encrypting the call's contents belongs to the client-side stub that sends it or to the server-side skeleton that ultimately receives it", "Whether the skeleton must route the call to one specific instance tied to that client's session (stateful), or whether any pooled instance can service the call because state is discarded/reloaded per operation (stateless)", "Whether the underlying network connection carrying the call is established over a reliable TCP socket or an unreliable UDP datagram channel instead"],
      correctIndex: 2,
      modelAnswer: "Week 2 defined stateful code as holding state between operations and being tied to a client session, versus stateless code discarding state after each operation so any instance can serve any client. That's exactly the decision the skeleton faces: a stateful server object must be routed to specifically, while a stateless one can be served by any available pooled instance — this is the same design choice EJB's @Stateless annotation makes explicit.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's Remote Method Call (return path) slide, what is the correct order of steps once the remote method finishes executing?",
      options: ["The client stub re-executes the same method call locally as well, purely to double-check and verify that the server's returned answer was correct", "Method returns to the skeleton → skeleton marshals the return values into a message and sends it to the client stub → client stub unmarshals the reply and returns the values to the caller", "Client stub marshals the return values first → skeleton then sends the original request onward → only then does the method actually execute on the server", "The return values skip the skeleton's involvement entirely and are written directly from the server object back into the client caller's stack frame"],
      correctIndex: 1,
      modelAnswer: "The return path mirrors the request path in reverse: the method returns to the calling skeleton code, the skeleton marshals the results and sends them back to the client-side stub, and the stub unmarshals the reply and returns the extracted values to the original caller.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Stubs etc' slide, where do stubs and skeletons come from?",
      options: ["They must be written entirely by hand, one painstaking line at a time, for every single remote method a developer ever wants to expose, with no compiler or IDE tooling support available to help at all", "They're generated by compilers/development environments from the set of methods/interfaces (which need to be known to the client), typically produced from server method definitions or an interface definition language such as IDL or WSDL", "They are generated dynamically at call time by the network's DNS server, purely as an incidental side effect of resolving the target hostname into a routable IP address", "They come pre-installed as a fixed, unconfigurable part of the operating system kernel's networking stack, bundled together alongside its own built-in TCP/IP implementation"],
      correctIndex: 1,
      modelAnswer: "The slide states stubs/skeletons are generated by compilers/development environments, which need to know the methods and interfaces plus the runtime layout/calling conventions of the language — generated from server method definitions or an interface definition language like IDL or WSDL, sometimes copied by hand or looked up in a repository. As the lecture put it, the application programmer's real job is only to provide the interface — what methods are available, what parameters they take, what types they return — not to hand-write the stub/skeleton plumbing underneath.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's History slide, which of the following pairings is correct?",
      options: ["RPC (1980s, procedural languages) came before CORBA (1990s, integrating objects across OO languages, standardised by OMG)", "Web services/REST were the first distributed computing technology, predating RPC", "DCOM predates RPC by several decades", "CORBA (1980s, procedural languages) came before RPC (1990s, object integration standardised by OMG)"],
      correctIndex: 0,
      modelAnswer: "The History slide places RPC in the 1980s for procedural languages (still used 'under the covers' today, e.g. file/mail servers), followed by CORBA in the 1990s for integrating objects written in multiple OO languages under OMG standards, followed later by DCOM/Java/WCF (components) and then web services/REST/MQ.",
    },
    {
      type: "mcq",
      prompt: "The lecture's 'Distributed architectures' slide lists peer-to-peer computing (e.g. mail server to mail server, B2B partners, supply chains) separately from multi-tier applications (layered roles/deployment, specialisation of servers, sharing load). Based on the accompanying online-retail diagram's Client Tier / Business Tier / Data Tier structure, which architecture style does that diagram illustrate?",
      options: ["Peer-to-peer, because the diagram also shows external Suppliers and Shippers connected symmetrically alongside the retailer's own systems", "Neither architecture style — the online-retail diagram is illustrating a completely unrelated concept from earlier in the same lecture section", "Peer-to-peer — every component shown in the diagram talks directly and symmetrically to every other component in it, with no layering or tiering visible at all", "Multi-tier — the diagram shows layered roles (web pages/user apps, then business components like Order/Payment/Stock, then databases) deployed across specialised, distinguishable tiers"],
      correctIndex: 3,
      modelAnswer: "The online-retail diagram explicitly labels Client Tier, Business Tier, and Data Tier, with business components (Order, Customer, Payment, Goods/Stock, Delivery) specialised and layered between the client apps and the databases — this is the multi-tier pattern (layered roles, specialisation of servers), not peer-to-peer, even though the diagram also shows peer-style connections to external suppliers/shippers/banks around the edges.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Transparency?' slide, what specifically does a 'partial failure' mean in a distributed system?",
      options: ["Some parts of a distributed operation succeed while other parts fail, rather than the whole operation cleanly succeeding or cleanly failing together", "The entire network connection goes down completely, so that no messages of any kind can get through between client and server anymore", "Only the client application itself crashes outright while the server process it was talking to keeps running completely unaffected", "A given method call is observed to fail roughly half the time it is invoked, on average, across many repeated attempts"],
      correctIndex: 0,
      modelAnswer: "The slide lists 'partial failures — some bits working, some not' alongside broken links, lost messages, and delays as new failure possibilities introduced by real networks — the defining trait is that a distributed operation can fail in a way where some of its parts succeeded and others didn't, unlike a local call which either fully executes or doesn't.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Transparency?' slide, why are standard OO techniques like frequent getters/setters and fine-grained objects specifically bad for remote/distributed interfaces?",
      options: ["Fine-grained objects exposing many small getter/setter fields consume noticeably more heap memory at runtime than a comparable coarse-grained object with fewer, larger fields would", "Getters and setters exposed on a remote interface are inherently insecure by design and will always leak internal data straight to any attacker capable of reaching the network endpoint", "Each small call becomes a full network round trip carrying its own latency and marshalling overhead, so many small remote calls are far more expensive in aggregate than one coarse-grained call that returns everything needed at once", "JVMs are structurally unable to marshal primitive return types such as int or boolean across a remote call boundary at all, so every such value must first be boxed into an object"],
      correctIndex: 2,
      modelAnswer: "The slide's point is about round trips: standard OO patterns (getters/setters, frequent small method calls, assuming a shared address space) work fine locally but translate into poor performance once distributed, because each call now costs a network round trip. The lecture makes this concrete: an object with 10 fields exposed as 10 separate getter methods costs nothing extra locally, but calling all 10 remotely means paying for 10 separate marshal/send/unmarshal round trips — the lecture's fix is to 'design coarse-grained components which offer meaningful services' (e.g. one call that returns everything needed) instead of many fine-grained ones.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Evolution?' slide, which strategy does it recommend for evolving a distributed interface once client code is already deployed 'in the wild'?",
      options: ["Always change the existing interface in place immediately, and require every deployed client to update to the new version before it can call the service again", "Never add any new methods or parameters to the system under any circumstances, ever, even when genuinely new functionality is needed by clients", "Keep existing interfaces unchanged, and add new interfaces for new situations, rather than mutating an interface (which requires finding and changing every caller) or freezing it forever", "Delete the old interface immediately the moment a new, replacement interface is published, regardless of whether existing clients still depend on it"],
      correctIndex: 2,
      modelAnswer: "The slide weighs 'immutable interfaces, defined once and never changed' against 'change interfaces and find/change every caller', and lands on a third option: 'Keep existing interfaces, and add new ones for new situations!' — old clients keep working against the interface they already use, while new functionality is exposed through additional interfaces.",
    },
    {
      type: "mcq",
      prompt: "Per the lecture's 'Lessons Learned' slide, what does 'transparency' in distributed computing actually deliver, and what does it NOT deliver?",
      options: ["It guarantees genuinely zero latency for every remote call made through it, no matter how congested, saturated, or slow the underlying network conditions happen to be at any given time", "It fully and completely eliminates every practical difference there is between an ordinary local call and a fully remote one, so that no special design consideration is ever required by the programmer afterward", "It lets programmers keep structuring code in terms of familiar local procedures/objects ('as-if' local), hiding hardware/platform complexity — but it does not make the remote call actually local, so pitfalls must still be planned for with technological assistance", "It is a transparency property that only ever applied to older middleware technologies like CORBA and DCOM specifically, and simply does not extend to modern web services or REST-style APIs"],
      correctIndex: 2,
      modelAnswer: "The slide is explicit: transparency is 'mainly with regard to the programming paradigm' — programmers can keep thinking in procedures/objects, used 'as-if' they are local — 'but remember: they are not local!' Designing a reliable, fast distributed system still requires awareness of distributed computing's pitfalls, addressed with technological assistance like reliable messaging, distributed transactions, and redundancy.",
    },
    {
      type: "mcq",
      prompt: "In the lecture's 'Distributed Multitiered Applications' diagram, JSP Pages and Enterprise Beans are shown in two different tiers of the same Java EE Server. Which tier is each placed in?",
      options: ["JSP Pages are in the Web Tier; Enterprise Beans are in the Business Tier", "Both JSP Pages and Enterprise Beans are in the Client Tier", "Both JSP Pages and Enterprise Beans are in the EIS Tier", "JSP Pages are in the Business Tier; Enterprise Beans are in the Web Tier"],
      correctIndex: 0,
      modelAnswer: "The diagram places JSP Pages inside the Web Tier and Enterprise Beans inside the Business Tier, both sitting within the Java EE Server between the Client Tier (Application Client / Dynamic HTML Pages) and the EIS Tier (Database).",
    },
    {
      type: "mcq",
      prompt: "The lecture's Enterprise Java Beans example annotates CalculatorService with @Stateless. Using Week 2's stateful/stateless definitions, what does this annotation guarantee about how calls are handled?",
      options: ["Exactly one dedicated CalculatorService instance is permanently reserved and pinned to each individual client for the entire lifetime of that client's session", "No client-specific state is retained between calls, so the container can hand any incoming request to any pooled CalculatorService instance, matching Week 2's definition of stateless code discarding state after each operation", "The bean automatically persists all of its instance fields to the underlying database as a side effect after every single method call completes", "It has no real relationship to the stateful/stateless distinction at all — @Stateless is purely a scheduling hint that only affects the thread priority the container assigns to the bean"],
      correctIndex: 1,
      modelAnswer: "Week 2 defined stateless code as discarding state after an operation so instances can be shared across clients, versus stateful code being tied to one client's session. @Stateless session beans are exactly this: since add/subtract/multiply/divide hold no per-client data between calls, the EJB container can pool instances and hand any of them to any client's request.",
    },
    {
      type: "mcq",
      prompt: "The lecture's example shows CalculatorServiceRemote as a separate @Remote-annotated interface, implemented alongside a local interface by CalculatorService. What is the purpose of this separate remote interface?",
      options: ["It defines which specific database table columns the underlying CalculatorService bean is permitted to read from or modify at the persistence layer", "It only actually needs to exist as a separate interface in the specific case where the bean declares no corresponding @Local interface at all", "It simply duplicates the same method signatures already declared on the local interface purely for documentation purposes, with no effect on runtime behaviour", "It declares which methods are exposed for cross-JVM/network invocation, forming the contract the client-side stub is generated from — distinct from a local interface used for in-process calls within the same JVM"],
      correctIndex: 3,
      modelAnswer: "@Remote marks CalculatorServiceRemote as the contract for calls arriving from outside the JVM — this is the interface a client-side stub is generated against — separate from any @Local interface used for calls from within the same JVM/container, which don't need the marshalling overhead of a remote call.",
    },
    {
      type: "mcq",
      prompt: "The lecture's Java EE Server Communications example does `Context ctx = new InitialContext(env); CalculatorServiceRemote calculatorService = (CalculatorServiceRemote) ctx.lookup(\"calculatorApp/CalculatorService/remote\");` before calling add/subtract/multiply/divide. What is JNDI being used for here?",
      options: ["Load-balancing the client's incoming requests across several redundant database replicas sitting behind the deployed CalculatorService bean instance", "Dynamically compiling the CalculatorServiceRemote interface's own source code into freshly loadable bytecode at the exact moment the lookup call is made", "Encrypting the add/subtract/multiply/divide method arguments before the client-side stub marshals them into the outgoing request message for transport", "Locating/looking up the remote service's stub by a logical, published name, rather than the client hardcoding a network address — matching the JEE Glossary's 'Naming-and-Directory Service (JNDI)' entry"],
      correctIndex: 3,
      modelAnswer: "The JEE Glossary lists JNDI (Java Naming and Directory Interface) under 'Naming-and-Directory Service.' The lookup() call resolves a logical name ('calculatorApp/CalculatorService/remote') to the actual remote stub, so the client doesn't need to hardcode a server address — this is the naming/lookup step that happens before any add/subtract/multiply/divide call can be marshalled and sent.",
    },
    {
      type: "mcq",
      prompt: "The lecture's Deployment Descriptors slide shows an ejb-jar.xml with <session-type>Stateless</session-type>, <transaction-type>Container</transaction-type>, and a <container-transaction><trans-attribute>Required</trans-attribute> entry. Comparing this to Week 2's Spring @Transactional annotation, what do both mechanisms have in common?",
      options: ["The XML deployment descriptor and Spring's @Transactional annotation are both functionally identical in effect to writing raw SQL COMMIT statements directly inline in the middle of the application's business logic code", "Both mechanisms still require the developer to manually call UserTransaction.begin() and commit() explicitly somewhere inside the method body itself, just with some extra surrounding configuration wrapped around it", "Both are declarative transaction configurations — the transaction boundary is specified outside the business-logic code itself (XML descriptor here vs an annotation in Spring), rather than the code explicitly calling begin()/commit() as in JTA's explicit-transaction style", "Neither mechanism actually has anything to do with transactions at all — the deployment descriptor's <container-transaction> block only ever configures unrelated security roles and access permissions instead"],
      correctIndex: 2,
      modelAnswer: "The lecture states deployment descriptors 'separate business logic from infrastructure concerns (eg: transactions and security)' — <transaction-type>Container</transaction-type> with <trans-attribute>Required</trans-attribute> declares that the method should run inside a container-managed transaction, without any begin()/commit() code, exactly matching Week 2's declarative @Transactional pattern; both stand in contrast to Week 2's JTA explicit-transaction example, which requires the code to call begin() and commit() itself.",
    },
    {
      type: "mcq",
      prompt: "A developer looks up a remote EJB stub via JNDI once at application startup and caches the reference for the app's entire lifetime, reasoning 'it's a name lookup, so it will always resolve to a working instance.' Which fallacy of distributed computing does this reasoning ignore, and why can the cached stub eventually start failing?",
      options: ["'Bandwidth is infinite' — the reasoning wrongly assumes that caching a stub reference has no bandwidth cost, when the initial JNDI lookup itself already consumed bandwidth that should have been budgeted for elsewhere", "'Topology doesn't change' — the server or network path behind that logical name can change over time (e.g. redeployment, failover, a restarted instance), so a stub cached once can point at a no-longer-valid endpoint even though the lookup name itself never changed", "'The network is homogeneous' — the reasoning ignores that different machines in the path can use different byte orders and encodings, something a one-time cached lookup doesn't account for", "'Transport cost is zero' — the reasoning wrongly assumes that holding a cached stub incurs no ongoing monetary transport cost, when in reality that cost grows the longer the stub is kept alive"],
      correctIndex: 1,
      modelAnswer: "The eight fallacies include 'Topology doesn't change.' A JNDI name is a logical lookup, but what it resolves to (the actual server/endpoint behind that name) can change at any time — redeployments, failovers, restarts — so a stub resolved and cached once at startup can silently go stale, even though nothing about the lookup call itself changed.",
    },
    {
      type: "mcq",
      prompt: "Using the lecture's bookshop/warehouse example, 'local computing and data' gives autonomy & independence as one motivation for keeping systems distributed rather than centralised. What two further motivations does the lecture give for actively distributing the application across multiple systems?",
      options: ["Making every warehouse's component byte-code compatible with every other warehouse's, and guaranteeing effectively zero latency between whichever machines happen to be talking to each other", "Actively reducing the total number of physical machines the bookshop chain needs to operate, and eventually eliminating its reliance on a network between warehouses entirely", "Centralising all order and stock data into one single shared database, and forcing every warehouse to run the exact same catalogue component with no local variation", "Distributing load across systems via a load balancer, and reliability — if one warehouse's system goes down (e.g. a power outage), work can be routed to a different warehouse instead"],
      correctIndex: 3,
      modelAnswer: "The slide's own bullets are 'distributing load across many systems' and 'high reliability through autonomy'; the lecture gives them concrete voice with the bookshop/warehouse example: if thousands of users suddenly hit one machine it can't cope, so putting a load balancer in front of multiple warehouses/systems spreads the work, and if one warehouse's system goes down (e.g. a power outage), orders can still be routed to a different warehouse rather than the whole application failing.",
    },
    {
      type: "mcq",
      prompt: "Walking through the lecture's SOAP Request example live, the lecturer asked the class to identify which method was being called remotely and what parameter was being sent. Per the <soap:Body> shown (`<m:GetLastTradePrice ...><symbol>DIS</symbol></m:GetLastTradePrice>`), what are the correct answers?",
      options: ["Method: UsernameToken; parameter: Password = weYI3nXd8LjMNVksCKFV8t3rgHh3Rw==", "Method: wsa:Action; parameter: MessageID", "Method: GetLastTradePrice; parameter: symbol = DIS", "Method: soap:Envelope; parameter: xmlns:wsa"],
      correctIndex: 2,
      modelAnswer: "The lecturer's live walkthrough pointed to the <soap:Body> element as the actual remote call being made: the method is GetLastTradePrice and the parameter passed is symbol, with value DIS. The surrounding <soap:Header> block (UsernameToken/Password, wsa:Action, wsa:MessageID) is security/addressing plumbing the framework handles for you — as the lecture put it, 'you don't have to understand every line ... everything around just supports its distributed interaction,' with the actual application-programmer-visible content being the method call and its parameters.",
    },
    {
      type: "truefalse",
      prompt: "True or False: per the lecture, the conceptual goal of distributed computing was already being discussed as early as the 1960s — well before 1970s networking became commonplace and 1980s Ethernet commercialisation — with the RPC/CORBA/DCOM technologies on the lecture's History slide arriving only later, as ways of actually achieving that older goal.",
      options: ["True", "False"],
      correctIndex: 0,
      modelAnswer: "The lecture's verbal framing (not printed on the slides) traces this arc explicitly: people were already asking whether different things could run across different machines/locations back in the 1960s; networking became more and more common through the 1970s; Ethernet was becoming commercialised by the 1980s, at which point the slide's own History timeline picks up — RPC for procedural languages in the 1980s, then CORBA for object integration under OMG in the 1990s. The underlying motivation (autonomy/independence combined with the need to communicate and cooperate) predates any of the specific technologies that eventually delivered on it.",
    },
    {
      type: "short",
      prompt: "Using the lecture's own worked example of a client calling a remote getStockByBookId(bookId) method, trace the full round trip from the client's call to the value being returned — naming every component involved — and explain why the lecture stresses minimising the number of such round trips (e.g. its '10 fields, 10 remote getter calls' example) rather than just accepting that frameworks make remote calls 'look local'.",
      modelAnswer: "The client calls getStockByBookId(bookId) on what looks like a normal local object, but is actually the stub/proxy. The stub marshals the method identifier and the bookId parameter into a request message and sends it over the network to the server-side skeleton, which unmarshals the message, determines the target method/instance, and makes an ordinary local call into the real server object. The method executes and returns to the skeleton, which marshals the result into a response message and sends it back over the network; the client-side stub unmarshals the reply and hands the value back to the original caller — the full client → stub → network → skeleton → server, then server → skeleton → network → stub → client path. This machinery makes the call look local syntactically, but each round trip still costs real network latency (the lecture's own point: local calls are microseconds, remote calls are milliseconds). The lecture's example makes this concrete: an object with 10 fields exposed as 10 separate getter methods is fine to call locally, but calling all 10 remotely means paying for 10 separate marshal/send/unmarshal round trips instead of one — exactly why the lecture recommends combining such calls into one coarse-grained request that returns everything needed at once, rather than trusting the stub/skeleton illusion of locality to make many small remote calls free.",
    },
    {
      type: "scenario",
      prompt: "Your team's remote CatalogueService interface, including getStockByBookId(bookId), has already been deployed and is being called by several partner bookshops' client code 'out in the wild.' Product now wants getStockByBookId to also accept an optional promoCode parameter, so promotional stock can be filtered differently. Using the lecture's 'Evolution?' guidance, explain the tradeoffs of your options and recommend one.",
      modelAnswer: "The lecture frames this exact dilemma: an immutable, frozen interface means you'd have to publish a whole new interface and drop the old one, breaking every partner who hasn't migrated; changing the existing interface in place (e.g. adding a required promoCode parameter to getStockByBookId) means finding and updating every one of those already-deployed partner clients, which for external partners you don't control may not even be possible. The lecture's recommended middle path is to keep the existing interface unchanged — getStockByBookId(bookId) keeps working exactly as before for partners who haven't adopted promoCode — and add a new interface/method for the new situation (e.g. an overload or a new getStockByBookIdWithPromo(bookId, promoCode) method, or a new interface version). Existing partner integrations keep working untouched, while new or updated partners can opt into the richer method — avoiding both the 'break everyone today' cost of mutating the interface and the 'break everyone eventually' cost of an immutable interface that can never grow.",
    },
  ],
};

export const WEEK_3_PAPERS: ExamPaperSeed[] = [TUTORIAL_PAPER, LECTURE_PAPER];
