import type { ExamPaperSeed } from "../types";

const PAPER: ExamPaperSeed =
  {
    course: "COMP5348",
    week: 2,
    paperNumber: 1,
    title: "Week 2 Practice Paper",
    topics: "Types of state (local computation, session, resource, derived), lifetime/sharing/integrity of state, stateful vs stateless, persistent state and access layers; Concurrency and its dangers (interleaving, lost updates); Optimistic vs pessimistic concurrency control, locking, deadlocks, lock granularity; Transactions and ACID, explicit vs declarative (@Transactional) transactions; Spring Boot/JPA optimistic (@Version) and pessimistic (PESSIMISTIC_WRITE) locking in the bank transfer tutorial",
    sourceFiles: ["lecture/COMP5348_W2.pdf", "tutorial/COMP5348_Tutorial 2.pdf", "tutorial/tutorial-2-student/src/main/java/com/comp5348/bank/service/BankService.java", "tutorial/tutorial-2-student/src/main/java/com/comp5348/bank/controller/BankController.java", "tutorial/tutorial-2-student/src/main/java/com/comp5348/bank/model/Account.java", "tutorial/tutorial-2-student/src/main/java/com/comp5348/bank/repository/AccountRepository.java", "tutorial/tutorial-2-student/src/main/java/com/comp5348/bank/BankAccount.java"],
    questions: [
      {
        type: "mcq",
        prompt: "According to the lecture, which of the following is NOT one of the ways state 'varies' that were listed on the 'State' slide?",
        options: ["Varying lifetimes", "Varying visibility", "Varying encryption strength", "Varying 'sharedness'"],
        correctIndex: 2,
        modelAnswer: "The State slide lists varying lifetimes, varying visibility, varying 'sharedness', and varying 'criticality' — encryption strength is not one of the listed dimensions.",
      },
      {
        type: "mcq",
        prompt: "Which type of state does the lecture describe as 'local visibility only (private)', 'transient', and used for things like local variables in programs or parameters passed between components?",
        options: ["Resource state", "Session state", "Local computation state", "Derived state"],
        correctIndex: 2,
        modelAnswer: "Local computation state is defined as temporary data used while performing an 'operation', with local (private) visibility and a lifetime limited to that one operation — 'state but not very interesting... even though it's essential'.",
      },
      {
        type: "mcq",
        prompt: "Per the lecture's Session State slide, what does session state hold?",
        options: ["The persistent data underpinning the whole enterprise", "The state of the overall session, e.g. user identity, books ordered, allowable protocol messages", "Only temporary local variables inside a single operation", "The physical location of deployed hardware"],
        correctIndex: 1,
        modelAnswer: "Session state holds the state of the overall session — the slide's own examples are 'user identity, books ordered, allowable protocol messages' — and can be kept client-side, server-side, or both (e.g. via cookies).",
      },
      {
        type: "mcq",
        prompt: "The lecture gives the bank account balance as an example of what kind of state, since it 'could be computed by summing all transactions' but is instead kept as a running total for efficiency?",
        options: ["Session state", "Local computation state", "Derived state", "Transient state"],
        correctIndex: 2,
        modelAnswer: "Derived state is state that is inherently derivable from other state — the lecture's example is the account balance, derivable by summing transactions, but cached/kept as a running total for computational efficiency.",
      },
      {
        type: "truefalse",
        prompt: "True or False: The lecture states that resource state lasts from creation to explicit deletion and may be migrated over time as requirements change, while local computation state is inherently transient.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "The 'Lifetime of state' slide states exactly this: resource state lasts from creation to explicit deletion (through many sessions/applications, migrated as requirements change), while local computation state 'lasts during one operation' and is 'inherently transient'.",
      },
      {
        type: "mcq",
        prompt: "Which of the following best matches the lecture's description of 'stateful' vs 'stateless' code?",
        options: ["Stateful code discards state after every operation; stateless code holds state waiting for the next request", "Stateful code holds state between operations and is tied to a client session; stateless code discards state after an operation and can be shared across clients", "Stateful and stateless are two names for the same thing", "Stateless code cannot access a database at all"],
        correctIndex: 1,
        modelAnswer: "Stateful code holds state, waiting for the next operation request from the client, so the program instance is tied to that client session. Stateless code discards state after the operation completes and reloads it as needed, so instances can be shared across clients.",
      },
      {
        type: "mcq",
        prompt: "Per the 'Integrity of state' slide, which of the following is given as an example of an integrity constraint/invariant that application code must maintain?",
        options: ["Money taken from an account must always go somewhere else", "Every table must have exactly ten columns", "Session state must be encrypted at rest", "Local variables must be declared as final"],
        correctIndex: 0,
        modelAnswer: "The lecture's examples of integrity constraints/invariants include 'money taken from an account must always go somewhere else', 'seats are always booked, reserved or available', and 'cannot assign an employee to a non-existent department' (referential integrity).",
      },
      {
        type: "truefalse",
        prompt: "True or False: The lecture says concurrency is introduced as a solution to the performance/scale problem (fast response times at scale), but it introduces new problems such as interference between programs/operations over shared resources.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "The 'Performance, scaling and concurrency' slide frames concurrency as the solution to needing fast response times at scale, then immediately notes concurrency 'introduces new problems' — interference between programs/operations, e.g. 'can't sell the same seat twice; money lost in transit'.",
      },
      {
        type: "mcq",
        prompt: "In the lecture's 'lost update' example, T1 wants to increase x by 1 and T2 wants to increase x by 2, both starting from x=10, and T1 finishes last. What is the final value of x, and why?",
        options: ["x=13, because both updates are applied", "x=11, because T1's write overwrites T2's earlier write based on the stale value T1 originally read", "x=12, because updates are averaged", "x=10, because the writes cancel out"],
        correctIndex: 1,
        modelAnswer: "Both transactions read x=10 before either writes. T2 sets x=10+2=12, but T1 (having also read the stale x=10) then sets x=10+1=11, overwriting T2's update. The final state is increased by 1, not by 3 — T2's increment is lost.",
      },
      {
        type: "mcq",
        prompt: "According to the lecture's 'General rules' slide, when is a concurrency-control mechanism needed between two code segment instances?",
        options: ["Only when the two segments are literally different pieces of code", "Whenever they can interleave, access the same shared state item, and at least one modifies it — including two instances of the same code segment", "Only when running on different physical machines", "Only when using a NoSQL database"],
        correctIndex: 1,
        modelAnswer: "The rule: if instances of two code segments can interleave, both access the same item of shared state, and at least one modifies it, then a concurrency-control mechanism is needed — and the same rule applies to two instances of the same code segment. The lecture explicitly warns: 'do not try to reason out why some particular case is safe — just use proper concurrency control measures'.",
      },
      {
        type: "mcq",
        prompt: "What is the key difference between optimistic and pessimistic concurrency control, per the lecture?",
        options: ["Optimistic always uses database-level locks; pessimistic never does", "Optimistic allows access and detects/fixes damage afterward; pessimistic detects and prevents concurrent access up-front via locks", "They are identical except for their names", "Pessimistic control has no performance impact, while optimistic control always does"],
        correctIndex: 1,
        modelAnswer: "Optimistic concurrency control always allows access, then checks for damage and repairs/undoes if necessary — it can waste work but performs well at low contention. Pessimistic concurrency control detects and prevents potentially harmful concurrent access ahead of time, implemented through locks and locking, which can have severe performance impacts.",
      },
      {
        type: "mcq",
        prompt: "Per the lecture, how is optimistic concurrency control typically implemented?",
        options: ["By locking the whole database for every read", "By keeping a modification count in the object, remembering it on read, checking it hasn't changed before writing, and retrying if it has", "By disabling concurrency entirely", "By always running transactions serially with no interleaving allowed"],
        correctIndex: 1,
        modelAnswer: "Optimistic concurrency control is programmed into the application: keep a modification count in the object, remember it when read, check it hasn't changed when you later try to change the object, and retry the operation if it has changed.",
      },
      {
        type: "truefalse",
        prompt: "True or False: The lecture states that finer-grain locks (e.g. individual rows/objects) generally give better concurrency and performance but come with more overhead and more chance of deadlocks, compared to coarse-grain locks.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "The 'Granularity of locks' slide states exactly this trade-off: finer-grain locks can give better concurrency/performance but more overhead and more chance of deadlocks; coarse-grain locks are simpler, with less overhead and less chance of deadlock, but less parallelism.",
      },
      {
        type: "mcq",
        prompt: "In the lecture's deadlock example, T1 holds Lock A and wants Lock B, while T2 holds Lock B and wants Lock A. What technique does the lecture list to avoid this kind of deadlock?",
        options: ["Never use more than one lock in an application", "Imposing a 'canonical locking order' constraint", "Always retry immediately with no timeout", "Disabling locks entirely"],
        correctIndex: 1,
        modelAnswer: "The Deadlocks slide lists lock timeouts and deadlock cycle detection (leading to exceptions) as ways to recover from deadlock, and separately lists avoidance 'by imposing canonical locking order constraints' — i.e. always acquiring locks in the same global order so a cycle like T1(A→B)/T2(B→A) can't form.",
      },
      {
        type: "mcq",
        prompt: "Per the lecture's definition, what is a 'transaction'?",
        options: ["Any single line of application code", "A complete, indivisible business operation — a segment of code executed as a whole or not at all", "A network request that always succeeds", "A read-only database query"],
        correctIndex: 1,
        modelAnswer: "A transaction is defined as a complete, indivisible business operation: 'a segment of code that will be executed as a whole (or not at all)', so the system infrastructure can prevent problems from failure and concurrency. Examples given: book a seat, transfer money, withdraw cash, sell something, borrow a book.",
      },
      {
        type: "mcq",
        prompt: "In the ACID acronym as covered in the lecture, what does the 'I' (Isolated) guarantee?",
        options: ["That every transaction runs on its own dedicated server", "That every transaction 'thinks it is running all alone' — concurrent transactions do not interfere with each other, even though in reality they may be interleaved", "That transactions cannot be rolled back once started", "That data is never cached"],
        correctIndex: 1,
        modelAnswer: "Isolated means every transaction thinks it is running all alone — the reality of concurrency is hidden, transactions running together do not interfere with each other, and it looks (and sometimes literally is) as if transactions run serially. The lecture notes databases offer a choice of isolation level, and lower isolation levels trade correctness for performance.",
      },
      {
        type: "mcq",
        prompt: "Per the lecture, which ACID property is described as 'really an application program responsibility' — e.g. ensuring all money in a bank is accounted for somewhere and not 'lost'?",
        options: ["Atomic", "Consistent", "Isolated", "Durable"],
        correctIndex: 1,
        modelAnswer: "Consistent means the transaction moves the system from one consistent state to another — e.g. all money in the bank is accounted for and not lost — and the lecture notes this is 'really an application program responsibility', unlike atomicity/isolation/durability which the transaction infrastructure enforces.",
      },
      {
        type: "truefalse",
        prompt: "True or False: Per the ACID model, once a transaction's changes are committed, the Durable property guarantees they remain permanent even after a subsequent system failure and recovery.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "Durable: once changes are committed, they are permanent, even after failure and recovery — changes are written to storage and the transaction waits for the write to complete.",
      },
      {
        type: "mcq",
        prompt: "Which code snippet style does the lecture identify as an 'explicit transaction' using JTA (Java Transaction API)?",
        options: ["@Transactional public void methodName(...) { ... }", "UserTransaction t = ...; t.begin(); ...; t.commit();", "using (TransactionScope tScope = new TransactionScope()) { ... }", "SELECT * FROM accounts WHERE id = ?"],
        correctIndex: 1,
        modelAnswer: "The 'Explicit transactions' slide shows JTA's explicit begin()/commit() (or rollback()) API, contrasted with the 'Declarative transactions' slide's Spring Boot @Transactional annotation, which lets a method 'always run as a transaction' without explicit begin/commit calls.",
      },
      {
        type: "mcq",
        prompt: "In the tutorial's BankService.java, what annotation is used on performTransfer, createSimulationAccounts, and getBalance to make them run as declarative transactions?",
        options: ["@Autowired", "@RestController", "@Transactional", "@Entity"],
        correctIndex: 2,
        modelAnswer: "All three methods (performTransfer, createSimulationAccounts, getBalance) in BankService.java are annotated @Transactional, matching the lecture's declarative-transaction pattern — the framework wraps the whole method body in a single transaction.",
      },
      {
        type: "mcq",
        prompt: "In the tutorial's Account entity, what does the @Version field (private Long version;) implement?",
        options: ["Pessimistic locking, blocking all other readers", "The optimistic concurrency control pattern the lecture describes: a modification count checked on write, incrementing and causing a conflict/retry if another transaction updated the row first", "A schema migration version number for Hibernate DDL", "An audit log of every past balance"],
        correctIndex: 1,
        modelAnswer: "JPA's @Version field is exactly the lecture's optimistic concurrency control pattern implemented for you: a modification count stored in the object, checked and incremented on update, causing an OptimisticLockException/conflict if another transaction changed the row between read and write — matching 'findByIdWithOptimisticLock' in AccountRepository.",
      },
      {
        type: "mcq",
        prompt: "In AccountRepository.java, the method findByIdWithPessimisticUpdateLock is annotated @Lock(LockModeType.PESSIMISTIC_WRITE). Per the lecture's terms, what kind of concurrency control does this apply?",
        options: ["Optimistic concurrency control", "Pessimistic concurrency control — an exclusive lock is obtained on the row before access, and other concurrent tasks must wait for it", "No concurrency control at all", "Session-state locking"],
        correctIndex: 1,
        modelAnswer: "PESSIMISTIC_WRITE takes an exclusive database lock on the selected row at query time, matching the lecture's pessimistic concurrency control: 'tasks must obtain exclusive lock over shared data before access; concurrent tasks will wait for lock before continuing'.",
      },
      {
        type: "mcq",
        prompt: "In BankService.performTransfer, why does the code swap fromAccountId/toAccountId (and negate the amount) whenever fromAccountId > toAccountId, before acquiring any locks?",
        options: ["To make the SQL query shorter", "To always acquire locks on accounts in the same canonical (ascending id) order across all concurrent transfers, avoiding the crossed-lock deadlock the lecture describes", "To randomise which account is charged", "It has no effect on correctness or concurrency"],
        correctIndex: 1,
        modelAnswer: "This implements the lecture's 'canonical locking order' deadlock-avoidance technique: by always locking the lower-id account first regardless of transfer direction, two concurrent transfers between the same pair of accounts can never form the crossed T1(A→B)/T2(B→A) waiting cycle the Deadlocks slide illustrates.",
      },
      {
        type: "truefalse",
        prompt: "True or False: BankAccount.java's deposit method is declared 'public synchronized void deposit(int amount)', which is a Java-language locking mechanism, not a database transaction — it prevents two threads in the same JVM from interleaving the read-modify-write of the in-memory balance field.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "synchronized is Java's built-in mutual-exclusion lock on the object monitor; it stops two threads from interleaving the balance += amount read-modify-write inside the same running JVM process, which is a lower-level, non-database analogue of the pessimistic locking the lecture discusses for shared resource state.",
      },
      {
        type: "short",
        prompt: "Distinguish resource state, session state, and local computation state in your own words, using an example from the tutorial's bank application for each.",
        modelAnswer: "Resource state is the persistent, shared data modelling the real world — in the bank app, the Account rows (balance, version) and Customer rows stored in PostgreSQL. Session state holds the progress of one ongoing interaction — the tutorial app doesn't have an explicit user login session, but if it did, it would be things like 'which transfer form the user currently has open'. Local computation state is transient, private data used inside a single operation — e.g. the local `Account fromAccount` and `toAccount` variables inside performTransfer, or the swapped `temp` variable used to reorder the account ids, which disappear once the method returns.",
      },
      {
        type: "short",
        prompt: "Explain the 'lost update' concurrency problem in your own words and show how it could occur on the Account.balance field in the tutorial's bank app if performTransfer had no locking at all.",
        modelAnswer: "A lost update happens when two concurrent operations both read the same value before either writes back, so one operation's update overwrites the other's instead of both being applied. Concretely: two concurrent transfers both credit account A. Thread 1 reads balance=50, thread 2 also reads balance=50 before thread 1 writes back. Thread 2 computes 50+20=70 and writes it; thread 1 computes 50+10=60 and writes it after, overwriting thread 2's update — the account ends up at 60 instead of the correct 80, exactly mirroring the lecture's x=10, T1+1, T2+2 example.",
      },
      {
        type: "short",
        prompt: "Compare optimistic and pessimistic locking as implemented in the tutorial's AccountRepository (findByIdWithOptimisticLock vs findByIdWithPessimisticUpdateLock). When would you prefer one over the other, per the lecture's discussion of contention and performance?",
        modelAnswer: "findByIdWithOptimisticLock relies on the Account entity's @Version field: both transactions can read the row concurrently, but at commit time Hibernate checks the version hasn't changed, throwing a conflict if it has, forcing a retry — no database-level lock is held while the transaction runs. findByIdWithPessimisticUpdateLock takes an exclusive PESSIMISTIC_WRITE lock immediately on read, so a second concurrent transfer touching the same account simply blocks and waits. Per the lecture, optimistic control 'performs well at low contention' since it avoids blocking, but wastes work on retries when contention is high; pessimistic control avoids wasted work under high contention but 'could potentially have severe performance impacts' since it serialises access and risks deadlock.",
      },
      {
        type: "short",
        prompt: "Explain how the account-id swap in BankService.performTransfer (lines 27-33) prevents the deadlock scenario shown in the lecture's Deadlocks slide. What would you expect to happen if that swap were removed while using pessimistic locking?",
        modelAnswer: "The lecture's deadlock example has T1 lock A then want B, while T2 locks B then wants A, forming a cycle where each waits on the other forever. The tutorial code avoids this by always acquiring the pessimistic lock on the lower account id first, regardless of transfer direction — so a transfer from A→B and a concurrent transfer from B→A both lock the same account first, and the second transaction simply queues behind the first rather than each holding one lock and waiting on the other. If the swap/reordering were removed, two concurrent opposite-direction transfers between the same pair of accounts under pessimistic locking could each grab one account's lock and then block forever waiting for the other — a real deadlock, which the tutorial's Q6d step deliberately has students trigger by removing this exact code.",
      },
      {
        type: "short",
        prompt: "Using the tutorial's Tutorial 2 Q4 scenario (functionalities A: read S, read U, read V, write V; B: read S, read U, read V, write S; C: read S, read T, read U, write T, where S/T/U are resource state and V is session state), identify which pairs of functionalities have a potential concurrency problem when run concurrently *in different sessions* with no concurrency control, and on which variable(s).",
        modelAnswer: "The 'different sessions' qualifier matters: V is session state, and the lecture states session state is 'not shared across distinct sessions' — each session has its own independent V, so no pair of functionalities run in different sessions can ever conflict on V, even though A and B both touch it. That leaves only the shared resource-state variables S, T, U in play, using the rule that a conflict exists wherever one side writes a shared variable the other side also touches. A/A: only reads S and U, no writes to shared state → no conflict. A/B: A reads S, B writes S → conflict on S. A/C: both only read S and U → no conflict. B/B: two instances of B each read-then-write S → lost-update conflict on S. B/C: B writes S, C reads S → conflict on S. C/C: two instances of C each read-then-write T → conflict on T, matching the tutorial sheet's own worked example marking C/C with T.",
      },
      {
        type: "scenario",
        prompt: "A junior developer removes the @Version field from the Account entity and switches BankService.performTransfer to always use findByIdWithOptimisticLock, arguing 'optimistic locking doesn't need locks anyway, so it'll be fine without the version column.' Using the lecture's explanation of how optimistic concurrency control actually works, explain what will go wrong, and what will happen to the combined account balance invariant (staying at 70) from the tutorial's bank.zip exercise.",
        modelAnswer: "Optimistic concurrency control isn't 'no mechanism' — the lecture is explicit that it's implemented by keeping a modification count in the object, remembering it on read, and checking/retrying if it changed before you write. Without the @Version column, there is nothing to check: findByIdWithOptimisticLock's plain SELECT just returns the current row with no conflict detection, so Hibernate can no longer detect that another transaction modified the same account between this transaction's read and write. Two concurrent transfers touching the same account would both read the same starting balance, and the later write would silently overwrite the earlier one — the classic lost-update problem from the lecture's x=10/T1/T2 example. In the bank.zip exercise this means the combined balance of accounts A and B, which should stay at 70 after every completed transfer, would drift away from 70 under concurrent load, exactly the bug the tutorial asks students to fix.",
      },
      {
        type: "scenario",
        prompt: "Your team is deciding between optimistic and pessimistic locking for two different features: (1) a high-traffic 'like' counter on a social media post, updated thousands of times per second by different users, and (2) the bank transfer feature from this week's tutorial, where money must never be duplicated or lost between two specific accounts. Using the lecture's discussion of contention, performance, and correctness trade-offs, recommend a locking strategy for each and justify your choice.",
        modelAnswer: "For the like counter: prefer optimistic locking (or an even lighter approach like an atomic increment), because contention on any single post's counter, while frequent in aggregate, is spread across many posts and the cost of an occasional retry is cheap — the lecture notes optimistic control 'performs well' at typical contention levels, and pessimistic locking here would serialise a high-throughput operation and hurt performance ('could potentially have severe performance impacts'), which matters more than perfect precision on a vanity metric. For the bank transfer: prefer pessimistic locking (as the tutorial's PESSIMISTIC_WRITE path does), because money must never be lost or duplicated — a failed optimistic retry that silently succeeds on a second attempt is more dangerous to reason about under real money movement, and transfers between the same two accounts are exactly the kind of moderate-contention, high-consequence case where the lecture says pessimistic locking's cost (blocking, deadlock risk — mitigated here by canonical lock ordering) is worth paying for the stronger guarantee.",
      },
      {
        type: "scenario",
        prompt: "In a Week 8 unaided oral viva you're asked (1-2 minutes, no notes): 'Explain what a lost update is, and describe two different mechanisms that could prevent it, using this week's bank-transfer example.' Structure a spoken answer: one claim, 2-3 supporting points, one concrete example — the kind of concise, structured answer the Interactive Oral rubric rewards, not an essay.",
        modelAnswer: "Claim: a lost update happens when two concurrent operations both read a shared value before either writes it back, so one write silently overwrites the other. Point 1: it needs no error or crash to happen — both operations succeed individually, but the combined effect is wrong, e.g. two transfers each reading account A's balance as 50 before either commits. Point 2: pessimistic locking prevents it by taking an exclusive lock before either reader proceeds — in the tutorial, findByIdWithPessimisticUpdateLock forces the second transfer to wait until the first fully commits. Point 3: optimistic locking prevents it differently — it lets both reads proceed, but the @Version column means the second writer's commit is rejected because the version it remembers no longer matches, forcing a retry instead of a silent overwrite. Example: this is exactly why the tutorial's bank.zip exercise requires the combined balance of two accounts to stay at 70 after every transfer — without one of these two mechanisms, concurrent transfers between the same accounts drift away from 70.",
      },
      {
        type: "scenario",
        prompt: "Connect this week's material to Week 1: the Week 1 lecture described a layered architecture (Controller → Service/business layer → Repository/data-access layer) and the modifiability scenario of moving components to the cloud. In the tutorial's bank application, which layer(s) hold the concurrency-control logic (locking mode, transaction boundaries), and why does keeping that logic out of BankController matter if the team later needs to swap PostgreSQL for a different database or split the service across multiple servers?",
        modelAnswer: "The concurrency-control logic lives in the Service and Repository layers, not the Controller: @Transactional and the account-reordering deadlock-avoidance code sit in BankService.performTransfer, and the actual lock mode (PESSIMISTIC_WRITE vs the @Version-based optimistic check) is declared in AccountRepository's query methods; BankController only decides which TransferBalanceLockingMode to pass in and orchestrates the concurrent simulation via an ExecutorService. This matches Week 1's layering principle that each layer has one responsibility (controller = request/response, service = business/transaction logic, repository = persistence) with a clear interface between them. It matters for a future cloud/multi-server move because concurrency correctness in this design depends on the database's own locking primitives (row locks, @Version columns) — if the team scales out to multiple application server instances all talking to one shared PostgreSQL database, the existing locking still works unchanged, since it's enforced by the shared database, not by anything process-local like Java's `synchronized` in BankAccount.java, which would stop working correctly the moment more than one JVM process is involved.",
      },
      {
        type: "mcq",
        prompt: "Per the Week 2 lecture's 'Common questions' slide, what is allowed in the COMP5348 final exam?",
        options: ["Full open-book access to all lecture slides", "A one-page cheat sheet", "No materials of any kind", "Unlimited handwritten notes"],
        correctIndex: 1,
        modelAnswer: "The Common questions slide states: 'Final exam: one page cheat sheet will be allowed.'",
      },
      {
        type: "mcq",
        prompt: "Per the Week 2 lecture's 'Common questions' slide, what is the maximum group size for the group project (with 3 described as ideal)?",
        options: ["2", "3", "4", "5"],
        correctIndex: 2,
        modelAnswer: "The slide states: 'Group size: 3 is ideal, 4 is maximum.'",
      },
      {
        type: "truefalse",
        prompt: "True or False: Per the Week 2 lecture's 'Common questions' slide, missing a tutorial only ever costs you attendance marks — there is no bonus for attending.",
        options: ["True", "False"],
        correctIndex: 1,
        modelAnswer: "This is reversed. The slide states tutorial attendance is a 'bonus mark, no mark will lose' — attending earns bonus marks, but not attending does not deduct marks.",
      },
      {
        type: "short",
        prompt: "Explain the difference between the granularity choices available for locking (e.g. whole table vs individual row), and connect this to why the tutorial's AccountRepository locks individual Account rows (via a WHERE a.id = :id query) rather than locking the whole accounts table.",
        modelAnswer: "Lock granularity is the 'grain size' of what gets locked — whole database, whole table/class, or individual row/object. Finer-grain locks (like a single row) allow more concurrency, since unrelated rows stay unlocked and other transactions on different accounts aren't blocked, at the cost of more locking overhead and more chance of deadlock; coarse-grain locks (like a whole table) are simpler and have less deadlock risk, but serialise unrelated work unnecessarily. The tutorial's findByIdWithPessimisticUpdateLock query locks a single Account row by id, which is the right granularity here — concurrent transfers between different, unrelated account pairs can still proceed in parallel, while only transfers that actually touch the same account contend for its lock.",
      },
      {
        type: "short",
        prompt: "The Week 1 lecture said 'each application should have a comprehensible architecture defining structure, behaviour, and allocation.' Using this week's material, explain how a badly-designed concurrency strategy (e.g. no transactions, no locking) violates the 'behaviour' aspect of architecture even if the 'structure' (layering) is otherwise clean.",
        modelAnswer: "Week 1 defined behaviour as 'when and how components call one another' — i.e. the runtime dynamics of the system, not just its static decomposition into layers. A system can have a perfectly clean structure (controller/service/repository layers, well-defined interfaces) and still have undefined or incorrect behaviour under concurrency if operations aren't wrapped in transactions or protected by locking: two well-structured, individually correct service calls can still interleave in ways that violate the resource state's integrity constraints (e.g. the combined bank balance invariant), because nothing in the structure alone constrains the order or atomicity of operations across concurrent requests. This week's ACID/@Transactional material is exactly what fills in that missing behavioural specification — declaring which sequences of operations must execute as one indivisible, isolated unit.",
      },
      {
        type: "mcq",
        prompt: "In Tutorial 2 Q6, the bank.zip application creates two accounts with initial balances of 50 and 20 and performs concurrent transfers between them. What invariant must the current (buggy) implementation preserve but does not?",
        options: ["Each account's balance must always be a whole number", "The combined balance of both accounts must remain 70 after every completed transfer", "Account A's balance must always exceed account B's", "No account may ever have a balance of exactly 20"],
        correctIndex: 1,
        modelAnswer: "The tutorial states the combined balance should remain 70 (50+20) after every completed transfer, since a transfer only moves money between the two accounts, but 'the current implementation does not consistently preserve this invariant' — the bug students are asked to fix by correctly applying optimistic and pessimistic locking.",
      },
      {
        type: "mcq",
        prompt: "What does BankService.getBalance do with entityManager.refresh(account) after loading the account via accountRepository.findById?",
        options: ["It deletes the account from the database", "It forces JPA to re-read the entity's current state from the database, discarding any stale in-memory/cached values, before returning the balance", "It starts a new transaction", "It creates a duplicate account row"],
        correctIndex: 1,
        modelAnswer: "entityManager.refresh(account) forces Hibernate to reload the entity's fields from the database, overwriting any values already cached in the persistence context — this ensures getBalance reports the true current balance rather than a possibly-stale value from an earlier read within the same persistence context, which matters when checking the invariant after many concurrent transfers.",
      },
      {
        type: "truefalse",
        prompt: "True or False: In BankController's simulateConcurrentTransfers, a fixed thread pool of size 2 is used to run pairs of opposite-direction transfers (A→B and B→A) concurrently across the requested number of iterations, which is exactly the kind of interleaving scenario the lecture's 'Interleaving' slide illustrates.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "Executors.newFixedThreadPool(2) runs two Runnables (transferAToB and transferBToA) concurrently per iteration, submitting the pair of opposite-direction transfers to the executor — directly mirroring the lecture's C1/C2 interleaving diagram of two concurrent 'check balance / withdraw money' sequences.",
      },
      {
        type: "short",
        prompt: "The lecture's Summary slide says 'Performance, robustness, simplicity — choose two...' Using this week's optimistic vs pessimistic locking comparison, briefly justify why this trade-off triangle applies here.",
        modelAnswer: "Pessimistic locking favours robustness (strong correctness guarantees, no lost updates) and relative simplicity to reason about (lock, do work, unlock), but sacrifices performance under contention since concurrent transactions block and wait. Optimistic locking favours performance under low contention (no blocking, work proceeds in parallel) and robustness (still correctly detects conflicts via the version check), but adds implementation complexity — the application must handle retries and decide how many times to retry before giving up, and behaviour under high contention degrades as repeated retries waste work. Trying to get all three — maximum performance, maximum robustness, and minimum complexity — isn't available from either strategy alone, matching the lecture's closing claim.",
      },
      {
        type: "mcq",
        prompt: "The Account entity uses @ManyToOne(cascade = CascadeType.ALL) for its Customer field. Combined with this week's state concepts, which type of state does the Customer object represent once persisted?",
        options: ["Local computation state", "Session state", "Resource state", "Derived state"],
        correctIndex: 2,
        modelAnswer: "Once persisted via JPA/Hibernate into PostgreSQL, both Account and its associated Customer are resource state — data modelling a real-world entity (a bank customer), held in a specialised state store (the database) independent of any single running operation, and shared across whatever future sessions/operations query it.",
      },
    ],
  }

export const WEEK_2_PAPERS: ExamPaperSeed[] = [PAPER];
