import type { ExamPaperSeed } from "../types";

const PAPER: ExamPaperSeed = 
  {
    course: "INFO5990",
    week: 1,
    paperNumber: 1,
    title: "Week 1 Practice Paper",
    topics: "Course logistics, learning outcomes, weekly schedule, assessment structure, hurdle requirements; IT professional practice, technical vs professional judgement, organisational reality, communication and accountability; Real-world case studies (ASX, Victorian Government, Optus, CrowdStrike), role of IT in organisations, McKinsey/Andreessen interview",
    sourceFiles: ["lecture/INFO5990 2026-S2 Week 01 - Introduction (1).pdf", "lecture/Reading 1 - The McKinsey article.pdf"],
    questions: [
      {
        type: "mcq",
        prompt: "Per the Learning Outcomes slide, LO1 is about understanding issues relating to ethics and professional responsibility in the IT profession. Which learning outcome instead covers software testing, data security, data quality, and quality assurance, solved using IT project management?",
        options: ["LO2", "LO3", "LO4", "LO6"],
        correctIndex: 0,
        modelAnswer: "LO2 states: 'Understand issues related to software testing, data security, data quality, and quality assurance in the IT industry, and learn methods to solve those issues using IT project management.'",
      },
      {
        type: "mcq",
        prompt: "What percentage of the final mark comes from the Final Exam in INFO5990, and is it a hurdle requirement?",
        options: ["50%, and yes it is a hurdle requirement", "60%, and no it is not a hurdle requirement", "35%, and yes it is a hurdle requirement", "50%, and no it is not a hurdle requirement"],
        correctIndex: 0,
        modelAnswer: "The Assessments table lists the Final Exam at 50%, closed-book and supervised, marked as a hurdle requirement.",
      },
      {
        type: "mcq",
        prompt: "What is the weighting and nature of the Interactive Oral / Viva assessment?",
        options: ["5%, an open-book quiz held in Week 4", "10%, a secured oral assessment with no notes allowed, held in Week 8, must attend, and is a hurdle requirement", "35%, a group report due Week 12", "10%, an optional bonus assessment that can be skipped"],
        correctIndex: 1,
        modelAnswer: "The Assessments slides describe the Viva/Interactive Oral as 10%, a secured assessment (no notes allowed) covering Weeks 1-6, held in Week 8, that students must attend, and flagged HURDLE.",
      },
      {
        type: "truefalse",
        prompt: "True or False: The Group Assignment (35%) requires groups of 4-5 people, with submission in Week 12.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "The Assessments slide confirms: 'Group Assignment (35%) - Groups of 4-5 people - Submission in Week 12.'",
      },
      {
        type: "mcq",
        prompt: "According to the schedule slide, when is the INFO5990 lecture held, and from which week do tutorials start?",
        options: ["Monday 5-7pm; tutorials start Week 1", "Tuesday 7-9pm; tutorials start Week 2", "Thursday 5-7pm; tutorials start Week 2", "Wednesday 6-8pm; tutorials start Week 1"],
        correctIndex: 1,
        modelAnswer: "The Schedule slide states the lecture session is 'Every Tuesday 7 to 9 pm,' delivered face to face with a live Zoom option, and that 'Tutorials start from week 2.'",
      },
      {
        type: "mcq",
        prompt: "Per the Weekly Readings slide, what is expected of students regarding readings?",
        options: ["Readings are optional and only for extra credit", "Students should read the weekly readings and module materials before attending the lecture", "Readings are only assessed in the final exam, not the lectures", "Only postgraduate students need to complete the readings"],
        correctIndex: 1,
        modelAnswer: "The slide states it is expected that students read through the weekly readings and reading materials on the module before attending the lecture, to have a thorough understanding of the unit context.",
      },
      {
        type: "truefalse",
        prompt: "True or False: The Early Feedback Task (5%) is an out-of-class quiz held in Week 4, and it uses multiple choice questions covering Week 1 to Week 3 content.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "The Assessments table shows the Out-of-class quiz / Early Semester Feedback Task is 5%, individual and auto-graded with multiple choice questions, based on content from Week 1 to Week 3, due Week 04.",
      },
      {
        type: "mcq",
        prompt: "Which resource does the slide deck describe as 'The most important tool' for this unit?",
        options: ["Canvas", "Ed Forum", "The lecture recordings", "The reading list"],
        correctIndex: 1,
        modelAnswer: "The Resources slide lists Ed Forum with the note 'The most important tool' — used to communicate with the cohort, ask doubts to tutors/TAs/the professor, and receive announcements.",
      },
      {
        type: "short",
        prompt: "Summarise, in your own words, what LO5 and LO6 ask students to be able to do by the end of INFO5990.",
        modelAnswer: "LO5 asks students to demonstrate an ability to construct effective written and oral communication appropriate to IT practitioners, using skills including conflict resolution, contract negotiation, team formation, leadership, and team dynamics. LO6 asks students to apply investigative research methods, models, and tools to IT professional practice, identify and critique changing information in their area of interest, and interpret the potential validity of results.",
      },
      {
        type: "short",
        prompt: "List the four assessment items in INFO5990 with their weightings, and identify which ones are hurdle tasks.",
        modelAnswer: "Written exam / Final Exam - 50%, hurdle task. Interactive oral / Viva - 10%, hurdle task. Out-of-class quiz / Early Semester Feedback Task - 5%, not a hurdle task. Research analysis / Team Report (Group Assignment) - 35%, not a hurdle task. Two of the four items (the Final Exam and the Viva) are hurdle requirements.",
      },
      {
        type: "short",
        prompt: "Describe the expectations slide's guidance on study commitment and classroom conduct.",
        modelAnswer: "Students should attend scheduled classes and tutorials, devote about 6-9 hours per week to study apart from lectures/tutorials, read weekly readings before the lecture, participate constructively (respect for one another, be humble since 'none of us know everything, but everyone knows something'), check Canvas at least once a week, check Ed Forum at least once a day, and notify academics and team members honestly and promptly about any difficulties.",
      },
      {
        type: "short",
        prompt: "What use-of-AI restrictions apply to the Written Exam and Interactive Oral, versus the other two assessments?",
        modelAnswer: "Both the Written Exam and the Interactive Oral (both hurdle tasks) are marked 'AI prohibited.' The Out-of-class quiz / Early Semester Feedback Task and the Research analysis / Team Report are both marked 'AI allowed.'",
      },
      {
        type: "scenario",
        prompt: "You're in Week 3 and haven't yet started the weekly readings or checked Ed Forum. Based on the Expectations and Weekly Readings slides, what should you do before Week 4's lecture, and why does it matter that the Viva happens in Week 8 covering Weeks 1-6?",
        modelAnswer: "Catch up on the weekly readings before Week 4's lecture, since the slides say readings should ideally be done before attending so students have a thorough understanding of the unit context, and check Ed Forum (described as 'the most important tool') at least once a day per the Expectations slide. The Viva in Week 8 is a hurdle task covering Weeks 1-6 with no notes allowed, so falling behind early compounds: content from Week 1 onward has to be retained and orally recalled five to seven weeks later without written support, unlike the AI-allowed, open-book Early Feedback Task in Week 4.",
      },
      {
        type: "scenario",
        prompt: "Your group has formed for the 35% Group Assignment. One teammate wants to use an AI tool to write the entire final report the night before the Week 12 deadline. Using the Assessments table's 'Use of AI' column, explain whether this is allowed and what professional-practice concern this raises regardless of the AI policy.",
        modelAnswer: "The Research analysis / Team Report is marked 'AI allowed,' so using AI tools on this assessment is permitted by the unit's policy — unlike the Written Exam and Viva, which are 'AI prohibited.' However, this doesn't resolve the professional-practice concern: submitting AI-generated work the night before a deadline, without genuine engagement from the team, risks low-quality or unverified content going forward under the team's name, and undermines the team-formation, communication, and accountability skills (LO5) the unit is designed to build. The Expectations slide's call to 'notify your team members honestly and promptly about difficulties' points toward raising this concern with the team directly rather than letting a rushed AI-only submission stand in for real collaboration.",
      },
      {
        type: "mcq",
        prompt: "According to the lecture, what does IT professional practice focus on, in contrast to just building the technical solution?",
        options: ["Choosing the fastest programming language available", "What happens after the technical solution is proposed", "Writing the cleanest possible source code", "Minimising the number of team meetings"],
        correctIndex: 1,
        modelAnswer: "The 'IT Professional Practice' slide states: 'In practice, IT professional practice focuses on what happens after the technical solution is proposed.'",
      },
      {
        type: "mcq",
        prompt: "Per 'When Technical Excellence Is Assumed to Be Enough,' what does real IT work show about technical competence?",
        options: ["It is unnecessary for successful projects", "It is essential but not sufficient on its own", "It is the only thing that determines project success", "It matters only for small-scale projects"],
        correctIndex: 1,
        modelAnswer: "The slide states that although the assumption 'if the system works, if the design is sound, if the code is correct, then the outcome should be successful' makes sense, 'technical competence is essential but real IT work shows that it is not sufficient on its own.'",
      },
      {
        type: "mcq",
        prompt: "In the example of a system meeting all functional requirements but failing anyway, what two reasons does the lecture give?",
        options: ["The database was too slow and the UI colours were wrong", "Staff are not ready to change their workflows, or decision-makers lose confidence due to delays", "The code had too many comments and not enough tests", "The system was built using the wrong programming language"],
        correctIndex: 1,
        modelAnswer: "'When Strong Technology Still Leads to Poor Outcomes' gives the example where 'staff are not ready to change their workflows' or 'decision-makers lose confidence due to delays' — concluding 'the issue is rarely the code, it is how decisions were made around it.'",
      },
      {
        type: "truefalse",
        prompt: "True or False: 'IT Systems Do Not Exist in Isolation' argues that success is determined only by how well a system is built.",
        options: ["True", "False"],
        correctIndex: 1,
        modelAnswer: "False. The slide explicitly says the opposite: 'success is not determined only by how well a system is built, but by how well technology fits within organisational constraints and decision-making structures.'",
      },
      {
        type: "mcq",
        prompt: "In 'The Nature of Real IT Work,' which competing priorities are given as an example of different stakeholders valuing different outcomes?",
        options: ["Business prioritises speed and market impact; IT prioritises stability, maintainability, and scalability; Security prioritises risk reduction and compliance", "Marketing prioritises branding; Sales prioritises commissions; HR prioritises headcount", "Developers prioritise code style; Testers prioritise bug counts; Managers prioritise deadlines only", "Executives prioritise profit; Customers prioritise price; Regulators prioritise paperwork"],
        correctIndex: 0,
        modelAnswer: "The slide gives exactly this example: 'Business prioritises speed and market impact; IT prioritises stability, maintainability, and scalability; Security prioritises risk reduction and compliance.'",
      },
      {
        type: "mcq",
        prompt: "'From Technical Feasibility to Professional Judgement' contrasts technical questions with professional questions. Which of these is a professional question, per the lecture?",
        options: ["Can this system be built?", "Which architecture, platform, or tool should we use?", "Should we proceed now, delay, or change direction?", "What is the expected runtime complexity of this algorithm?"],
        correctIndex: 2,
        modelAnswer: "Professional questions focus on consequences: 'Should we proceed now, delay, or change direction? What risks are we accepting and on whose behalf? Who will be affected if this decision goes wrong?' — moving from 'can we do this?' to 'should we do this under these conditions?'",
      },
      {
        type: "truefalse",
        prompt: "True or False: 'Communication, Accountability, and Responsibility' states that many IT problems escalate because responsibility is spread so widely that no one owns it.",
        options: ["True", "False"],
        correctIndex: 0,
        modelAnswer: "True. The slide lists 'responsibility is spread so widely that no one owns it' alongside 'risks are known but poorly communicated' and 'assumptions remain implicit' as reasons many IT problems escalate.",
      },
      {
        type: "mcq",
        prompt: "Per 'When Technology and Professional Practice Work Together,' what typically explains why many IT initiatives succeed?",
        options: ["Because the technology used is always perfect", "Because professional practice is handled well, alongside realistic alignment, honest risk communication, and willingness to adjust scope", "Because the project has an unlimited budget", "Because the team avoided all stakeholder engagement"],
        correctIndex: 1,
        modelAnswer: "The slide states: 'many IT initiatives succeed, not because the technology is perfect, but because professional practice is handled well,' showing clear decision ownership, realistic alignment between technology and organisational readiness, early and honest risk communication, and willingness to adjust scope, timing, or approach.",
      },
      {
        type: "short",
        prompt: "Explain why the lecture argues the professional side of IT work 'must be learned' separately from technical knowledge.",
        modelAnswer: "Technical knowledge can often be developed through study and practice, but professional practice is different because it emerges in real organisational contexts, requires judgement under uncertainty and competing priorities, and involves decisions with broader consequences. In real IT work, professional judgement affects people, organisations, and trust, and mistakes are often visible and difficult to undo — so learning the professional side helps develop judgement before real consequences are at stake.",
      },
      {
        type: "short",
        prompt: "Describe the four bullet points the lecture lists under 'In this environment' (IT Systems Do Not Exist in Isolation) that shape organisational reality.",
        modelAnswer: "Decisions are shaped by hierarchies, authority, and influence; budgets and timelines are negotiated, constrained, and often fixed; policies, regulations, and legal obligations limit what can be done; and teams and stakeholders are driven by different goals, incentives, and pressures.",
      },
      {
        type: "short",
        prompt: "What common characteristics does 'When Professional Practice Breaks Down' identify, even when technology and teams are capable?",
        modelAnswer: "Early commitments made under pressure; risks known but not clearly escalated; and misalignment between technical readiness and organisational expectations. Even with capable technology and skilled teams, IT initiatives can struggle when professional practice does not keep pace with these dynamics.",
      },
      {
        type: "short",
        prompt: "Using the lecture's five bullet points under 'IT professional practice ... involves,' summarise what IT professional practice is about.",
        modelAnswer: "It involves making decisions when requirements, risks, and information are incomplete; balancing technical choices with organisational strategy, cost, time, and quality constraints; communicating risks, trade-offs, and uncertainty to technical and non-technical stakeholders; acting responsibly and ethically under delivery pressure and change; and taking accountability for decisions, outcomes, and professional judgement.",
      },
      {
        type: "scenario",
        prompt: "You're the technical lead on a project. The system is technically complete and passes all tests, but your team just learned that end users have not been trained and won't be ready to switch workflows for another month. The delivery date is next week. Using 'From Technical Feasibility to Professional Judgement,' describe the professional (not technical) questions you should be raising, and to whom.",
        modelAnswer: "Rather than technical questions like 'does the system work?' (already answered), the professional questions are: should we proceed with go-live now, delay, or phase the rollout? What risks are we accepting by launching before users are trained, and on whose behalf (e.g. the business, the end users, customers relying on the system)? Who will be affected if this decision goes wrong — the users forced into an unfamiliar workflow, or the business if the delay causes reputational or contractual issues? These should be raised early and honestly with decision-makers and stakeholders (per 'Communication, Accountability, and Responsibility') rather than left implicit, since escalating concerns early is exactly what the lecture identifies as the difference between IT problems that stay contained and ones that escalate.",
      },
      {
        type: "scenario",
        prompt: "A vendor proposes a new CRM system in a single 'big-bang' deployment to save time, versus a phased rollout that takes longer but is lower risk. Drawing on 'IT Systems Do Not Exist in Isolation' and the triple-priority example (Business/IT/Security), argue for one approach and identify which organisational constraints most influence your choice.",
        modelAnswer: "A phased rollout better reflects that IT systems do not exist in isolation from organisational reality: budgets and timelines are often fixed but so are legal/regulatory obligations, and teams have competing priorities — Business wants speed and market impact, IT wants stability/maintainability, and Security wants risk reduction and compliance. A big-bang deployment optimises for Business's speed priority at the expense of IT's stability priority and Security's risk-reduction priority, concentrating all deployment risk into a single cutover with no fallback. A phased approach makes trade-offs explicit and navigates the tension responsibly rather than optimising for only one stakeholder's priority, which is exactly what the lecture frames as the core of professional practice.",
      },
      {
        type: "mcq",
        prompt: "In Case 1 (ASX Technology Overhaul & Outages, 2024-2025), what does the lecture identify as the core issue, despite the technology being sophisticated?",
        options: ["The technology itself was outdated and unreliable", "The challenges were organisational, including governance, planning, risk management, and accountability across stakeholders", "ASX did not have enough engineers on staff", "The outage was caused by a natural disaster"],
        correctIndex: 1,
        modelAnswer: "The slide states: 'While the technology was sophisticated, the challenges were organisational, including governance, planning, risk management, and accountability across stakeholders.'",
      },
      {
        type: "mcq",
        prompt: "What triggered the major ASX outage referenced in the lecture, and when?",
        options: ["A cyberattack in June 2023", "A deployment related to a security upgrade, in December 2025", "A hardware failure during a routine backup, in March 2024", "A staff strike that halted operations in early 2025"],
        correctIndex: 1,
        modelAnswer: "The slide states: 'In December 2025, a deployment related to a security upgrade caused a major outage, halting trading for many companies and raising investor confidence concerns.'",
      },
      {
        type: "mcq",
        prompt: "In Case 2 (Victorian Government Digital Services), what was the core issue behind service disruptions on citizen-facing platforms like Services Victoria?",
        options: ["Immature technology that could not handle demand", "Organisational complexity, including cross-agency governance, risk escalation, and decision-making under public pressure", "A lack of any government funding for IT", "The platforms had never been tested before launch"],
        correctIndex: 1,
        modelAnswer: "The slide states: 'The challenges were not driven by immature technology, but by organisational complexity, including cross-agency governance, risk escalation, and decision-making under public pressure.'",
      },
      {
        type: "truefalse",
        prompt: "True or False: Case 3 (Optus Nationwide Network Outage, 2023) attributes the outage to experimental, unproven technology.",
        options: ["True", "False"],
        correctIndex: 1,
        modelAnswer: "False. The slide explicitly says: 'The outage was not caused by experimental technology, but by professional decisions related to system resilience, risk preparedness, and operational governance.'",
      },
      {
        type: "mcq",
        prompt: "According to the lecture's Optus case, what did post-incident reviews identify gaps in?",
        options: ["Marketing strategy and customer communications only", "Resilience planning, redundancy, and change management", "Employee salaries and staff retention", "Office building security"],
        correctIndex: 1,
        modelAnswer: "The slide states: 'Post-incident reviews identified gaps in resilience planning, redundancy, and change management.'",
      },
      {
        type: "mcq",
        prompt: "In the End of Lecture Questions case (CrowdStrike, July 2024), what made the global IT outage notable, given the update was 'intended to improve security'?",
        options: ["The software was obscure and rarely used", "The technology itself was industry-standard and widely used, and the outage affected airlines, banks, and hospitals", "It only affected a small number of home users", "It was immediately reversed with no impact"],
        correctIndex: 1,
        modelAnswer: "The slide states the update was from a trusted, widely deployed cybersecurity firm and 'the technology itself was industry-standard and widely used,' yet airlines grounded flights and banks, hospitals, and businesses were disrupted.",
      },
      {
        type: "mcq",
        prompt: "Per the 'Role of IT' slide, what three verbs describe how IT serves organisations?",
        options: ["Enable, Support, Transform", "Design, Build, Ship", "Plan, Execute, Review", "Buy, Install, Maintain"],
        correctIndex: 0,
        modelAnswer: "The slide states IT's role 'is to enable, support, and transform the way individuals, businesses, and governments store, process, communicate, and access information,' serving as 'the backbone of modern operations and innovation.'",
      },
      {
        type: "mcq",
        prompt: "In the McKinsey interview, what does Marc Andreessen say he would tell big companies about how to digitally transform?",
        options: ["Hire more Harvard MBAs to run the technology division", "Find the smartest technologist in the company and make them CEO", "Outsource all technology work to consultants", "Wait for a market downturn before investing in technology"],
        correctIndex: 1,
        modelAnswer: "Andreessen's answer to Tracy Francis's question about how big companies should digitally transform is: 'Find the smartest technologist in the company and make them CEO.'",
      },
      {
        type: "short",
        prompt: "Summarise the shared lesson across the ASX, Victorian Government, and Optus case studies, even though each involves a different organisation and incident type.",
        modelAnswer: "In all three cases, the technology itself was not the primary cause of failure — the ASX technology was sophisticated, the Victorian platforms weren't described as immature, and the Optus outage wasn't caused by experimental tech. Instead, each failure traces back to organisational and professional factors: governance, planning, risk management, and accountability (ASX); cross-agency governance, risk escalation, and decision-making under public pressure (Victorian Government); and resilience planning, redundancy, change management, and operational governance (Optus). The common lesson is that as systems scale and become more critical, professional judgement, coordination, and accountability become as important as technical capability.",
      },
      {
        type: "short",
        prompt: "According to the McKinsey interview, why does Andreessen say 'the best technology doesn't always win,' and what mistake does he say companies make when they draw the wrong lesson from that?",
        modelAnswer: "Andreessen cites business-school case studies like Betamax vs VHS, Qwerty vs Dvorak, and DOS vs Macintosh as examples where the best technology didn't win. But he argues a lot of companies and MBAs take this to mean 'we don't actually have to be good at technology, we can still win, we can market our way through' — which he says is the wrong lesson, since really good tech companies (like Tesla, which has never run a TV ad) build really good products and win by being genuinely good at technology, not by marketing around a weak product.",
      },
      {
        type: "short",
        prompt: "List the four 'core roles of IT' from the lecture slide, in addition to the two not asked about here (cybersecurity/risk management and technical support/troubleshooting).",
        modelAnswer: "Enabling communication and collaboration; data management and storage; process automation; system development and maintenance; and supporting innovation and digital transformation — these sit alongside cybersecurity and risk management, and technical support and troubleshooting, as the seven core roles of IT listed on the slide.",
      },
      {
        type: "short",
        prompt: "Explain Andreessen's answer to why big Fortune 500 companies struggle to compete with digital-native companies, in terms of where technologists sit in the organisation.",
        modelAnswer: "Andreessen argues that true technologists inside big companies are often not treated as first-class citizens — historically they sat in a segregated IT department, and later in a separate 'digital division' led by a VP of digital, but it's 'still a division, still a unit.' By contrast, at companies like Tesla, the engineers working on core technology (e.g. self-driving cars) are the most important people in the company and effectively lead it. Big companies are typically run by people with classical business training who are not inherently technologists, which he argues is the core disadvantage versus digital-native competitors run by technologists.",
      },
      {
        type: "scenario",
        prompt: "Using the CRM example from the 'Example' slide (a nation-wide real estate chain considering a CRM enterprise system), pick three of the listed questions and explain how you, as an IT professional, would investigate each one before recommending the system.",
        modelAnswer: "Example selection: 'What value can this provide?' - investigate by mapping the CRM's features against current pain points (e.g. lost leads, inconsistent follow-up) and quantifying potential impact (conversion rate, agent productivity). 'How might the CRM interoperate with the other systems?' - audit existing systems (listing platforms, accounting, marketing tools) for integration points, APIs, and data formats, and identify where manual reconciliation would otherwise be needed. 'What will be the security issues?' - assess what customer and transaction data the CRM will hold, who needs access across a nation-wide, multi-branch organisation, and what compliance obligations (e.g. privacy law) apply to that data. Each investigation should be documented and communicated to both technical and non-technical stakeholders, consistent with the professional-practice emphasis on making trade-offs and risks explicit.",
      },
      {
        type: "scenario",
        prompt: "Apply the lesson from the CrowdStrike case (industry-standard, trusted technology causing a global outage) to a hypothetical: your organisation is about to push a routine, low-risk-seeming security patch to all production systems overnight, with no staged rollout. Using the 'For You to Think' questions as a guide, explain what professional decisions you would want confirmed before approving the release.",
        modelAnswer: "Following the lecture's four framing questions: (1) 'At what point did this stop being a technical issue?' - recognise that even a 'routine' patch becomes a business-critical decision once it touches production, not just a technical deployment step. (2) 'Which professional decisions mattered most before the update was released?' - confirm whether the patch was tested against a representative subset of production configurations first, and whether a staged/canary rollout plan exists rather than a single global push. (3) 'Who should be accountable when a trusted update causes global impact?' - ensure there's a named decision-owner who explicitly approved skipping staged rollout, not an implicit assumption that 'routine' means 'no review needed.' (4) 'What would you have done differently?' - insist on a phased deployment with rollback capability and monitoring at each stage, treating trust in the vendor as a reason for confidence, not a reason to skip the organisation's own resilience and change-management practices — directly echoing the Optus case's lesson about gaps in resilience planning and change management.",
      },
    ],
  }

export const WEEK_1_PAPERS: ExamPaperSeed[] = [PAPER];
